### ISSUE TITLE
[css-variables] Relative URL resolution in var() references

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#757] opened 2016-11-24 07:17 UTC
Related discussions:
https://twitter.com/LeaVerou/status/801661659949371392
https://bugs.chromium.org/p/chromium/issues/detail?id=618165

Summary: Relative URL resolution in var() is underspecified and currently buggy in all browsers.
The main issue is, as @tabatkins pointed out in the second linked thread above is this:

```css
/* a.css */
--a: "a.png";

/* b.css */
--b: url(var(--a));

/* c.css */
background-image: var(--b); /* resolved according to a, b, or c? */
```

Since CSS Variables are uninterpreted token streams, it should be c (which is what @dbaron and I think), but some members (such as @FremyCompany in the first thread) argue that this may not be useful to authors.

**Comment by upsuper** [comment] 2016-11-24 23:24
It seems to me it makes no sense to resolving the url according to a, since a is just a string.

I guess Houdini's CSS Properties and Values API would make it possible to resolve according to b, as that may no longer be a token stream?

**Comment by FremyCompany** [comment] 2016-11-25 05:49
Yes, and we would like that not to be a behavior change from untyped variables. Typing should only get you transitionability and type checking, but should otherwise not change the behavior.

That is why the proposal was to remember the origin of the url() token so that you can always resolve based on that instead of the url of the document it was finally used on. This is not incompatible with what is currently specified but would require a clarification.

The issue of doing (c) is that we basically make it impossible to create variables to images if you own a theme.css but do no know on which site(s) your theme will be installed on (but you know the images will be in the same folder as your css file). This is very user-hostile.

I would not object clarifying (b) if that is what the group want to do, but this is in clear violation of our own specs where we argue authors should not use absolute urls (and yet those would be the only one working properly in this case).

**Comment by FremyCompany** [comment] 2016-11-25 05:50
Side note but url(var(...)) is parsed as url("var(...)") and therefore the variable does not work as far as I know so the (a) option does not seem possible to achieve in today's css

**Comment by upsuper** [comment] 2016-11-25 05:57
Hmmm, but `url("a.png")` is not a `<url-token>`, but a `<function-token>`, and we already have other CSS functions which also accept url string as parameter (e.g. `image`), and in those functions, variable is possible (e.g. `image("a.png", var(--fallback))`), so it could be hard to keep consistency in that way.

**Comment by FremyCompany** [comment] 2016-11-25 06:07
This can be solved by always using the origin of the function token (so the origin of image(...) in that case.

**Comment by upsuper** [comment] 2016-11-25 06:21
I cannot find any normative text about how value of custom properties should be parsed... Some notes in css-variables seem to indicate that a custom property cannot contain only half of a function token, so probably remembering the original url of function token is feasible...

**Comment by tabatkins** [comment] 2016-11-30 18:28
The spec is clear - it's parsed as a `<declaration-value>`, which is just any valid token (with a few restrictions). There's no further structure to parse them into, so you have to keep the parsed result around, raw and without any further meaning assigned to them (beyond the `var()` substitution defined by the spec).

One consequence of this, if you're following the Syntax spec, is that, yes, you can't have "half a function token" - the parsing algos never return function tokens, only function component values, which are whole functions that know what their arguments are.  You similarly can't have half a (), [], or {} block.

URL parsing is, unfortunately, fucked here.  `url("foo")` and `url('foo')` cause the `url(` part to parse as a function token, but anything else causes the whole shebang to parse as a url token, and the whole contents between the parens is a url.  As François says, `url(var(--foo))` is identical in meaning to `url("var(--foo)")` as a result.  We need to add a new, non-stupid function for urls to make this work better, such as `image()`.

---

So, back to the issue.  Nothing's underspecified here.  The value in `a.css` isn't a URL, it's a `<string-token>`.  The value in `b.css` isn't a URL, it's a `<url-token>` (uninterpreted!).  (And, as François notes, does *not* have the value you expect - it's not equivalent to `url("a.png")`.)  Only in `c.css` is the value finally in a context where it's given a meaning, and it finally becomes a URL, where it can be resolved into an absolute URL, and that's done relative to the location of `c.css`, like any other URL in the file would be.

I agree this isn't the friendliest behavior.  But it's the logical behavior of untyped custom properties, as they're meaningless by design.  The correct fix for this is to use a typed custom property, so we can actually parse the value in `b.css` and give it meaning.  Let's finish up the Houdini custom properties stuff, so we can make sure we're doing things right and then produce a simple declarative version - that way you can write `@custom-property --b { type: "<url>"; }` and everything works as expected.

**Comment by FremyCompany** [comment] 2016-12-09 18:29
Given @tabatkins isn't likely to attend next week's telcon, and given it is holiday period, I propose we move this issue out of the agenda for now, and we can probably address that during the Seattle F2F. I will write down a summary of my thoughts by then.

**Comment by dbaron** [comment] 2016-12-11 03:59
One other problem with doing this:

While [CSS 2 defined <code>url()</code> containing quoted urls as URI tokens](https://drafts.csswg.org/css2/syndata.html#tokenization), this has changed in css-syntax-3, which [defines <code>url()</code> containing quoted url as a function token plus the normally-tokenized arguments](https://drafts.csswg.org/css-syntax/#consume-ident-like-token).  I presume this change is to support the [&lt;url-modifier&gt; concept in css-values-3](https://drafts.csswg.org/css-values-3/#urls).

Given those definitions, only some <code>url()</code> functions are actually tokens.  So the underlying mechanism for describing this would need to be further from the way the spec works.  (Although maybe not further implementations, since Gecko and possibly other implementations of variables actually store strings rather than token streams, since a string can always be turned back into a token stream, and it's more compact.)

**Comment by LeaVerou** [comment] 2016-12-11 18:52
> Gecko and possibly other implementations of variables actually store strings rather than token streams, since a string can always be turned back into a token stream, and it's more compact.

Frankly, I've found the idea that variables are token streams rather hard to teach:

Me: So you cannot do `width: var(--number)em;` because variables are not strings, but token streams. Also you cannot animate them, because the browser doesn't know what type they are.
Audience: But didn't you say they are token streams? Then the browser *does* know what type they are, no?
Me: Ummm…

**Comment by upsuper** [comment] 2016-12-11 21:47
Token doesn't necessary have type, and even if they have, different properties may have different rules for animating a token, so...

**Comment by LeaVerou** [comment] 2016-12-11 22:07
> Token doesn't necessary have type, and even if they have, different properties may have different rules for animating a token, so...

I wasn't asking a question, I was referring to how it makes it more complicated to teach variables.

**Comment by FremyCompany** [comment] 2016-12-14 01:08
Looks like we are going to discuss this on the call tomorrow so here is the summary of my thoughts:

- Currently relative url() do not work in Edge and Chrome at all, because at the time we do the replacement we do not know how to resolve the url. In both our browsers this will require a fix, and it seems worth fixing this properly instead of fixing this the wrong way. It doesn't seem very difficult to me to keep track of url tokens and url functions and resolve based on their origin instead of where they are used

- Second, I think not resolving uri properly is a major issue has this prevents inline styles to work, generic wordpress themes, as well as componentized css like the sort of which we want web components to do. Variables moving from outside the component to inside it will not work as expected.

- Third, I think Tab's solution is not going to work. (3.1) You cannot define a property like "background" using the proposed level 1 of the Houdini spec, and that seems by design. Even worse, even if you could, that means that if a component did it to make things work, it would not be able to support new syntax for background that are not compatible with its micro-syntax. That seems terrible. (3.2) The kind of replacement Tab suggests would only work if you replace the computed value of property in, since urls are resolved at computation. I argue this is impossible, because length properties for instance would resolve "em" based on their current element and not based on where they would be used. Worse, what if you do "--custom-length: 1em; font: var(--custom-length);". If you argue only url-typed properties should resolve at computation time because they won't cause such conflict, then this doesn't solve complex properties like background either, so that doesn't get you anywhere. In addition to being super confusing, that is.

**Comment by astearns** [comment] 2016-12-14 17:28
We discussed again and decided not to change the current custom property behavior for this case, but to solve it in the future with typed custom properties and/or new URL function extensions that can specify origin intent

**Comment by LeaVerou** [comment] 2016-12-14 17:28
RESOLVED in today's call: Relative URLs resolve when they are substituted in an actual property, i.e. c.css in the first post's example. Typed Custom Properties will provide more flexibility on this in the future.

**Comment by SimonSapin** [comment] 2017-04-03 14:17
https://drafts.csswg.org/css-variables/ still needs to be edited to reflect this, doesn’t it?

**Comment by tabatkins** [comment] 2017-04-03 20:15
At most it needs a note clarifying that; the resolution is just what falls out of the "custom properties aren't typed" definition.

**Closed** 2021-07-28 21:32 UTC
Labels: Closed Accepted by CSSWG Resolution, Commenter Satisfied, Needs Edits, css-variables-1
