### ISSUE TITLE
[css-color-5] RCS channel keyword definitions are broken

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#8250] opened 2022-12-21 19:07 UTC
In https://github.com/w3c/csswg-drafts/commit/102f3c3a8c9a273d6ab7db046341a92b13d1307d Chris changed the definition of many of the channel keywords (like r, g, b in rgb(); s, l in hsl()) from being `<<percentage>>` to being "`<<number>>` or `<<percentage>>`".

This needs to be reverted; that definition isn't about allowed syntax, but rather about the value itself. The channel keywords *are* percentage values. They can't be either/or, as calc()s using them need to know which they are for validity.

**Comment by svgeesus** [comment] 2022-12-23 12:05
Some (like `a`, `b`, `x`, `y`) changed from being `<<number>>` to being "`<<number>>` or `<<percentage>>`".

I agree that what you get from a channel keyword needs to be unambiguous for calc() to work; you are correct that I was mixing up syntax changes with types in that commit.

**Comment by weinig** [comment] 2022-12-26 00:35
Dupe of https://github.com/w3c/csswg-drafts/issues/7876?

**Comment by svgeesus** [comment] 2022-12-26 13:10
Yes, it is. Thanks for spotting!

**Closed by svgeesus** 2022-12-26 13:10 UTC
Labels: Needs Edits, css-color-5
