### ISSUE TITLE
[css-variables-1] Expose pending substitution value?

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#11055] opened 2024-10-21 11:00 UTC
> [Pending-substitution values](https://drafts.csswg.org/css-variables/#pending-substitution-value) must be serialized as the empty string, if an API allows them to be observed.

https://drafts.csswg.org/css-variables/#substitution-in-shorthands

Authors do trip over this behavior sometimes (https://issues.chromium.org/issues/40804066), and it's not ideal for cases where round-tripping via text is crucial, like serializing to MHTML.

Can we somehow expose the pending-substitution value? E.g.:

```
border-width: shorthand(border, 1px var(--x) black);
```

**Comment by Loirooriol** [comment] 2024-10-21 17:51
Duplicate of #8055 ?

**Comment by tabatkins** [comment] 2024-10-21 19:13
Technically a separate request, but close enough to be worth deduping. I'll move the comment over to there.

**Closed** 2024-10-21 19:18 UTC
Labels: css-variables-1
