### ISSUE TITLE
[css-selectors-4] Selector for element with another element as ancestor

### ISSUE THREAD

**Issue by dpk** [w3c/csswg-drafts#9130] opened 2023-07-31 12:14 UTC
Rough proposal: a pseudo-class, such as `p:within(a)` selects `p` elements which have an `a` element anywhere in their ancestor tree.

E.g. it would select any of the `<p>` elements here:
```html
<div>
  <a href="http://example.org/">
    <p>I match
  </a>
</div>

<a href="http://example.org/">
  <div>
    <p>I match
  </div>
</a>
```

But not this one:

```html
<div>
  <p>I don’t match, <a href="http://example.org/">me neither</a>
</div>
```

While writing my first major design using CSS Nesting, this seemed like a missing feature, mainly for maintainability but also because truly accounting for all possible nesting situations to target the element wanted using regular selectors could be tricky within a complex nesting of selectors. A strong use case in particular (as implied above) is when elements might sometimes be inside links and sometimes not. This would allow them to be styled or restyled in a way more clearly indicating that they can be interacted with as links.

Link to spec: <https://www.w3.org/TR/selectors-4/>

**Comment by Loirooriol** [comment] 2023-08-01 17:54
Yeah I don't get the difference between `p:within(a)` and `a p`. See https://drafts.csswg.org/selectors-4/#descendant-combinators

If you just want to impose extra conditions, like `foo p:within(a)`, then use `foo p:is(a *)`

**Comment by tabatkins** [comment] 2023-08-01 21:46
Yup, `a p` is what you want, and you can use `:is()` as @Loirooriol said if you need to impose multiple ancestor conditions that aren't related to each other.

Note tho that your first example:

```
<div>
  <a href="http://example.org/">
    <p>I match
  </a>
</div>
```

won't match the selector because, due to the way HTML parsing is defined, inline elements are auto-closed by a `p` and then reopened inside of them. That is, the DOM structure produced by that markup is:

```
DIV
├ A href="http://example.org/"
└ P
  └ A href="http://example.org/"
    └#text: I match
```

(Your second example works as intended, because `div` does *not* have that special behavior. So it is able to nest inside the `a` without a problem, and then the `p` sees that it has a `div` parent and acts normally as well. HTML parsing has a lot of funky quirks that it's developed over the decades that HTML has been in use.)

This might be the source of your confusion!

**Closed by tabatkins** 2023-08-01 21:46 UTC

**Comment by Loirooriol** [comment] 2023-08-01 22:03
Actually, the HTML parser can place both `p` and `div` inside an `a`, but this doesn't happen if the end tag is missing like in the example. I think this is handled in https://html.spec.whatwg.org/multipage/parsing.html#adoption-agency-algorithm. So this works:

```html
<!DOCTYPE html>
<style>a p { border: solid green }</style>
<div>
  <a href="http://example.org/">
    <p>I match</p>
  </a>
</div>
```

**Comment by Loirooriol** [comment] 2023-08-02 11:30
Then you should use

```css
.aleph {
  /* ... styles for .aleph ... */
  & .beth {
     /* ... styles for .aleph .beth ... */
    & .gimel {
      /* ... styles for .aleph .beth .gimel ... */
      & .daleth {
        /* ... styles for .aleph .beth .gimel .daleth ... */
        a & { /* or `&:is(a *)` works too */
        /* special styles for .daleth when within a link, regardless of where the a
           is in the tree of .aleph .beth .gimel */
        } } } } }
```

Note that `a &` only requires `a` to be an ancestor of the element matched by the parent selector, basically it will behave like `a :is(.aleph .beth .gimel .daleth)`.

Unlike `a .aleph .beth .gimel .daleth`, `a &` doesn't require `a` to be an ancestor of `.aleph`.

**Comment by SebastianZ** [comment] 2023-08-02 19:26
> and, afaict, in the PostCSS plugin I’m using as a stopgap to support Firefox

As a side note, Firefox 117 will ship with nesting and without the punctuation symbol requirement.

Sebastian

**Comment by tabatkins** [comment] 2023-08-02 20:58
Yup, that restriction got dropped a while back and implementations will follow. We can't fix legacy implementations by adding new features, as by definition they're not being updated. ^_^
