### ISSUE TITLE
[css-text][css-sizing] When to/not to include preserved trailing spaces

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#3440] opened 2018-12-13 05:14 UTC
We found browsers are inconsistent on the topic on `pre-wrap`. `pre` always include trailing spaces.

Feature|Blink|Edge|Gecko|WebKit
---|---|---|---|---
`text-align: start`|Don't include|Don't include|Don't include|Don't include
`text-align: end / center`|Include|Include|Include|Don't include
`text-align: justify`|If !wrap|Do not justify|Do not justify|Do not justify
`min-content`|Don't include|Don't include|Include|Don't include
`max-content`|Include|Include|Include|Include

Can we define these? Are there more cases we should cover?

Note: table updated on June 2, 2019. `text-align: left` added, and some values updated. Changes maybe from inaccurate old tests, or browsers updated, not sure.

**Comment by upsuper** [comment] 2018-12-13 09:41
What do you mean by "Not include" vs. "Ignore justify" in the row of `text-align: justify`?

Conceptually, `min-content` should force trailing spaces to wrap if not !wrap, and in that case they should be counted as one space in size. Is that the behavior of "If !wrap" or "Include", or none of the browsers do this?

**Comment by kojiishi** [comment] 2018-12-13 13:58
Thank you for asking.

> What do you mean by "Not include" vs. "Ignore justify" in the row of text-align: justify?

"Not include" mean to ignore trailing spaces and flush the end of non-space character. "Ignore justify" means justification is not applied.

For `min-content`, !wrap (i.e., `pre`) is interoperable, all impls include trailing spaces. When wrap (`pre-wrap`), the desired behavior is not clear to me. We wrap at spaces, and such trailing spaces are not removed, but 3 impls do not include it when computing `min-content`.

**Comment by upsuper** [comment] 2018-12-16 00:47
If the trailing spaces are meant to be preserved, flushing the end of non-space character doesn't sound like the right thing to do? I'm not sure...

**Comment by fantasai** [comment] 2018-12-18 08:09
The spec currently specifies that trailing spaces are hung (like hanging-punctuation) if `pre-wrap` is specified. This is because UAs don't want to wrap the last word down just because there are spaces following it that overflow the containing block. (Spaces are not allowed to hang for `pre`; they are measured just like any other characters.)

Per spec, "hanging" the spaces means they are excluded from the line box--they can overflow it, and therefore are ignored when justifying or end-aligning the text, and are not considered in intrinsic sizing.

If a different behavior is wanted, then we'd have to spec something explicitly different.

**Comment by fantasai** [comment] 2019-01-23 17:10
@kojiishi @upsuper Did you want something different here or should I close the issue with no change?

**Comment by upsuper** [comment] 2019-01-28 02:07
I don't have strong opinion either way, since I don't really have any usecase in mind for this.

The general idea explained by @fantasai makes sense to me. I have one question, though. If the trailing spaces are allowed to hang (i.e. not always hang), then I think for `text-align` (when available width is enough) and `max-content`, the spaces should be included, and the only case where it should never be included when wrap is `min-content`.

If that understanding is correct, then WebKit would be wrong on both `text-align` items, and Blink would be wrong on `text-align: justify`, and Gecko would be wrong on `min-content`, but vast majority of impls still match the spec, and the spec has at least two correct impls for each behavior (Edge counts one for all items), which sounds like an encouraging situation.

**Comment by kojiishi** [comment] 2019-01-28 03:42
The way I read look different from the way @upsuper read, I think it means there's a room to improve the spec?

Also, IIRC at least some of Blink behaviors (e.g., text-align) are from bugs filed by authors. We will need to review those feedback carefully before making the changes. It'd be greater if spec can solve this issue in a way that developers can follow easier.

**Comment by fantasai** [comment] 2019-01-30 02:07
@upsuper So, let me see if I get this right.... You're suggesting that trailing spaces should be counted for max-content, but not for min-content. You're also suggesting that spaces should hang according to allow-end rules rather than force-end rules.

This makes sense to me. But did I get that right? :)

**Comment by fantasai** [comment] 2019-01-30 02:09
Hm, actually, I think that's not right. Space should hang... when there's a force-break after, but not when there's a soft-wrap after. Is that right?

**Comment by frivoal** [comment] 2019-01-30 03:31
>  Space should hang... when there's a force-break after, but not when there's a soft-wrap after. Is that right?

where did you get that from?

**Comment by upsuper** [comment] 2019-01-30 13:02
> @upsuper So, let me see if I get this right.... You're suggesting that trailing spaces should be counted for max-content, but not for min-content. You're also suggesting that spaces should hang according to allow-end rules rather than force-end rules.

Yeah, that seems to match my understanding.

**Comment by kojiishi** [comment] 2019-02-21 02:59
@fantasai thank you for discussing this. Can I ask one clarification on what allow-end means for justification? I'm not sure if I have a good understanding of what "allow-end" behavior is.

> Other suggestion was to define spaces hang according to allow-end rules. allow-end if it fits in the line it's not hanging. When you do right alignment it won't go outside. If it doesn't fit we allow it to fit on the line and in that case it's hanging

There are web pages that use pre-wrap+justify, so I wish to keep the current Blink behavior, but wondering what this means for justify.

**Comment by frivoal** [comment] 2019-02-21 05:20
> I'm not sure if I have a good understanding of what "allow-end" behavior is.

I means that the advance measure of any end-of-line preserved space that would fit the line if text-align was start need to be taken into account and continue to fit within the line with other alignments. those that don't fit the line don't count.
So
```
   |A_B____  |
```
gets right aligned as 
```
   |  A_B____|
```
not
```
   |      A_B|____
```
and 
```
   |A_B______|___
```
gets right aligned as 
```
   |A_B______|___
```
not 
```
   |      A_B|_________
```
or
```
A_B|_________|
```


For justification specifically, I believe the same logic would apply, so 

So
```
|A_B____  |
```
would get justified as something like
```
|A_ B ____|
```
not
```
|A   _   B|____
```

However, currently, it seems to me that browsers just don't justify at all when white-space is pre-wrap, which I believe used to be required by CSS2.1 but no longer is.

**Comment by kojiishi** [comment] 2019-02-21 05:36
> However, currently, it seems to me that browsers just don't justify at all...

See the table at the original comment, Blink and WebKit does justify. There were bugs filed against us when we included trailing spaces in pre-wrap+justify, because the reporter used pre-wrap+justify for the whole content (probably to make double-spacing at the end of sentence easier.)

Can we special case justify, because including trailing spaces does not look reasonable result if browsers chose to justify pre-wrap?

**Comment by frivoal** [comment] 2019-02-21 06:33
I'm not opposed, but am a little confused at to what the use case is for using pre-wrap and using justify at the same time, so I don't really know what authors would expect.

**Comment by frivoal** [comment] 2019-02-21 06:35
> probably to make double-spacing at the end of sentence easier

Is that the only use case we know of, or are there others?

**Comment by kojiishi** [comment] 2019-02-21 06:49
Hm, how is pre-wrap different from normal? When authors don't need whitespace collapsing, pre-wrap looks reasonable choice for normal documents. For example, [this page](https://rome.ro/news/2018/12/10/reflections-on-dooms-development) uses `pre-wrap` for the all paragraphs. The contenteditable might also want to use pre-wrap too.

BTW, forgot to say thank you for making pictures that are very easy to understand. That helped me a lot to understand what "allow-end" means in this context.

**Comment by frivoal** [comment] 2019-02-21 07:46
Other than the effect on line-breaks and tabs in the source, pre-wrap will also preserve the (single) space between each word at the end of the line, which normal won't do. That can already be observed if you underline the text. With normal, the end of line space is gone, so it is not underlined, but with pre-wrap it is there, so it is underlined.

This sort of things makes me think that using pre-wrap for long form text is probably not ideal.

pre-wrap on editable areas does make sense, but these are rarely justified, I think?

Anyway, I am not strongly opposed, but the argument that line start and line end should be symetrical, and that we should be consistent with other types of alignments also makes sense to me. Since this is more about an exception to the general rule than disagreement about the general rule, I think we should probably open a new issue.

**Comment by upsuper** [comment] 2019-03-10 05:15
> <heycam> koji: I think that makes sense
> <heycam> ... if other browsers are willing to match, I think we can try to match
> <heycam> ... is Gecko happy with it? I think xidorn wanted to include trailing spaces
> <heycam> ... for right and center
> <heycam> heycam: we can resolve and ping xidorn to get his opinion

As I mentioned before that I don't have strong opinion either way. I was just trying to figure out the general rule from the discussion before which seems to make sense, and matches majority of implementations. If there are usecases suggest otherwise, I'm fine with that as well.

So it seems the resolution was to have spaces force-end for alignment when it's a soft wrap, but allow-end otherwise? That sounds reasonable to me.

**Comment by frivoal** [comment] 2019-03-12 01:39
> So it seems the resolution was to have spaces force-end for alignment when it's a soft wrap,

Yes

> but allow-end otherwise? 

I think we were saying not to hang at all in that case.

**Comment by upsuper** [comment] 2019-03-12 10:56
> I think we were saying not to hang at all in that case.

How would you handle cases like
```
|a____________|_____
```
then?

**Comment by kojiishi** [comment] 2019-03-12 17:17
> How would you handle cases like...

I think it's an overflow, not hanging. Maybe a minor terminology problem though.

**Comment by frivoal** [comment] 2019-03-12 23:51
If you try the same example with something other than spaces, we still overflow to the right even if `text-align:right`. So either way, it would still render as:
```
     |a____________|_____
```
and not
```
a____|_____________|
```

**Comment by upsuper** [comment] 2019-03-16 06:31
Being an overflow means it is supposed to have line wrap but just has no wrap opportunity? Then what about something like
```
|a__b______|_____
```

Is this overflow or hanging? If it's overflow, why is wrapping not triggered?

**Comment by kojiishi** [comment] 2019-03-18 04:48
Such line should wrap before "b", right? And if the 2nd line is longer than available width, it will overflow.

Maybe we have different mental model and that terminologies are confusing?

**Comment by frivoal** [comment] 2019-04-23 07:07
I've made a pull request to apply this change: https://github.com/w3c/csswg-drafts/pull/3868

However, while I think force-hanging the end-of-line pre-wrap preserved spaces, I unsure about not doing so for end-of-line pre-wrap preserved spaces that come before a forced break:
* I don't undertand what the use case is for that distinction
* it would change where lines wrap compared to today, including causing some previously non wrapping elements to start wrapping. (example: https://jsbin.com/leqanut/edit?html,css,output)

Are we sure that we don't want simply force-hang for all end-of-line pre-wrap preserved spaces, regardless of being followed by a soft wrap vs forced break?

**Comment by frivoal** [comment] 2019-04-23 07:15
Also, Safari, Chrome (and Edge), but not Gecko also ignore all end-of-line pre-wrap preserved spaces (regardless of forced break vs soft wrap) for min-content sizing purposes, while Gecko includes them (also regardless of forced break vs soft wrap). (example: https://jsbin.com/wonefeq/edit?html,css,output)

**Comment by fantasai** [comment] 2019-05-01 23:03
Well, we definitely don't want to force-hang the preserved spaces before a forced break when calculating the max-content size; otherwise max-content won't leave room for the spaces, and I think we do expect that.

**Comment by frivoal** [comment] 2019-05-01 23:26
I agree with including these spaces in max-content calculations, but they shouldn't be included in min-content, or to cause additional wrapping, so I don't think that means they need not to hang. Force-hanging **punctuation** should also be included in max-content calculations, so the way I'd deal with that is to say that end-of-line spaces (with pre-wrap) always hang, regardless of forced break vs soft wrap, but also clarify the definition of hanging to make sure it does the right thing for max-content.

**Comment by fantasai** [comment] 2019-05-01 23:30
I don't think force-hanging punctuation should be included in max-content calculations. Hanging punctuation generally means you expect the padding to provide space for it and don't want extra space to be generated for it.

**Comment by frivoal** [comment] 2019-05-02 00:13
Personally, I think that justifying pre-wrap text is weird, and that we should not optimize for that case. If we give up on that, we can go back to hanging only the spaces that overflow, which means:
* count the preserved spaces for max content
* don't count the preserved spaces for min content
* don't ignore the preserved spaces when center/right/justify aligning.
That does make justification a bit odd, but again, I don't think the use case is strong, and having consistency on the rest seems more useful.

If we do want to solve it for justification as well, a more complete but also more complicated answer could be that we allow-hang (i.e. only hang the spaces that would overflow) the pre-wrap spaces in general, but force-hang (i.e. hang all of them) when justifying. Since justification already has the distinction between the last and non-last lines, `text-align: justify` would force-hang on all lines but the last, and allow-hang on the last line, while `text-align: justify-all` would force-hang on all lines.

**Comment by kojiishi** [comment] 2019-05-07 04:18
The different opinions might come from whether to see `pre-wrap` as 1) a variation of `pre` that allows wrapping, or as 2) a variation of `normal` that does not collapse spaces. It looks like you are the former and want to handle preserved spaces in the same way for `pre` and `pre-wrap`. I agree the former cases exist, but I think the latter is more common.

**Comment by kojiishi** [comment] 2019-06-01 16:23
One new data: we've got a report saying that LayoutNG shows horizontal scrollbar for the following CSS:
```css
white-space: pre-wrap;
overflow-x: scroll;
```
I think we need to think about `text-align: left` (or `start` to be more accurate) too. I'm updating the existing behavior table in the top of this thread.

**Comment by kojiishi** [comment] 2019-06-02 16:47
and [crbug.com/453830](https://crbug.com/453830) is when Blink matched to Gecko. @fantasai's proposal seems to work for this reported case.

**Comment by frivoal** [comment] 2019-07-09 13:19
I've made two possible pull requests to close this bug:
* https://github.com/w3c/csswg-drafts/pull/3868 which strictly applies the resolution we took.
* https://github.com/w3c/csswg-drafts/pull/4095 which implements a variant: instead of requiring end-of-line preserved spaces to hang on lines with no forced breaks, and forbidding hanging to on lines with forced breaks, it requires end-of-line preserved spaces to hang on lines with no forced breaks, but allows (not forces) handing forbidding them to on lines with forced breaks.

In many cases, the result will be the same, but there are some subtle (and useful) differences:
* In https://github.com/w3c/csswg-drafts/pull/3868's example 6, the text is wrapped onto 3 lines. Current browsers don't do that. The equivalent situation shown in example 8 in https://github.com/w3c/csswg-drafts/pull/4095 keeps the text on two lines, matching what browsers have implemented.
* If https://github.com/w3c/csswg-drafts/pull/3868's example 6 was made editable, and the user placed the caret after the last space, and inserted an x, the rendering would change from
    ```
    |0_0|_
    |0_ |
    |0_ |
    ```
    to
    ```
    |0_0|_
    |0_0|_
    |x  |
    ```
    If instead we used the rules of https://github.com/w3c/csswg-drafts/pull/4095, we go from
    ```
    |0_0|_
    |0_0|_
    ```
    to
    ```
    |0_0|_
    |0_0|_
    |x  |
    ```
    which seems much preferable.

I'd like @fantasai and @kojiishi feedback on this.

**Comment by frivoal** [comment] 2019-07-09 13:23
Agenda+ to draw attention to it (or to resolve if people have sufficiently looked at it in advance).

**Comment by kojiishi** [comment] 2019-07-24 17:19
> #4095 which implements a variant: instead of...

IIUC the difference is that you want to allow both hanging and not-hanging for end-of-spaces with forced breaks? I'm ok as long as the spec allows not-hanging behavior. I'm personally a fan of hanging behavior regardless of soft-/forced breaks, but when all impls do not hang them for `pre`, that is probably not easy to change.

**Comment by frivoal** [comment] 2019-07-26 14:53
> all impls do not hang them for pre

We're keeping that. This change only affects `pre-wrap`. For `pre`, nothing changes: we do not hang.

> you want to allow both hanging and not-hanging for end-of-spaces with forced breaks?

Kind of, but the choice is not up to the UA, it depends on what fits the line or not.

The key point here is that:

1. Before unforced breaks, we require hanging in all cases (same as "force-end" for punctuation). (same in #3868 and #4095)

2. For #4095, before forced breaks, we require "conditional hanging", which is the type of hanging used by "allow-end" for punctuation: hang if it wouldn't fit, don't hang if it does. #3868 was different, and never hangs it before forced break, even if it doesn't fit.

It will give the behavior you wanted when using pre-wrap on a paragraph with two spaces after period: the end-of-line space for spaces in the middle of the paragraph will hang, and therefore justification will work properly.

It also means, that if you have a single line, with a forced break at the end, and preserved spaces at the start and end, both the start spaces and the end spaces are taken into account for alignment. See example 6.
![Screen Shot 2019-07-20 at 09 42 43](https://user-images.githubusercontent.com/113268/61575907-d088ef80-aad2-11e9-8b8e-8c82723e6ad5.png)

This will give the correct result in https://bugs.chromium.org/p/chromium/issues/detail?id=453830 

All that is the same in #3868 a #4095. But here is the difference:
If there are more spaces than can fit the line before a forced break, those than don't fit hang. For example, if we have `<div>a_b__</div>` with `white-space:pre-wrap` and a line length that will fit only 4 characters, #3868 will result in
```
|a_  |
|b__ |
```
but #4095 will result in
```
|a_b_|_
```

That seems better because:
* #4095 is more web compatible: #3868 would result in content that currently fits in one line to start taking two some times
* If you consider editing, and you add a "c" at the end of the example above, both #3868 and #4095 will result in:
    ```
    |a_b_|_
    |c   |
    ```
   For #4095, that's not surprising for the user, as the previous text doesn't change, but for #3868, it is surprising, as the wrapping of the previous text changes.

**Comment by kojiishi** [comment] 2019-07-26 20:46
Are you proposing to change to hang out overflow? And that rule will apply to when text-align: right too?

**Comment by frivoal** [comment] 2019-07-26 20:53
> Are you proposing to change to hang out overflow?

Before forced breaks, yes.

> And that rule will apply to when text-align: right too?

Yes. See example 7 (especially the second figure in it) for details:
![Screen Shot 2019-07-20 at 09 42 36](https://user-images.githubusercontent.com/113268/61575908-d41c7680-aad2-11e9-9011-dbc292d174af.png)

**Comment by kojiishi** [comment] 2019-07-26 22:13
If you want to fix the case, I mildly prefer using `text-align`. I think explicit control is more intuitive for authors, and we can make sure that the new behavior is compatible for `text-align: right`, even when the line overflows.

So, do not hang if `text-align` is `end`, `center`, or physical value that is equivalent to `end`. Does this work for you?

**Comment by frivoal** [comment] 2019-07-27 12:02
I don't see how that's relevant. How the updated proposal interacts with alignment is the same as the old one from fantasai, on which we had resolved with your approval, and reconfirmed in with you Toronto.

Again, the difference between the standing resolution (#3868) and my proposed tweak on it ( #4095) is limited to what happens to spaces before a forced break when they don't fit the line. Everything else is the same.

If we have `<div>a_b__</div>` with `white-space:pre-wrap` and a line length that will fit only 4 characters, the previous resolution results in:
```
|a_  |
|b__ |
```
My proposed change will result in:
```
|a_b_|_
```

That seems better because:
* it is more web compatible: the existing resolution would result in content that currently fits in one line to start taking two some times.
* If you consider editing, and you add a "c" at the end of the example above, both the existing resolution and my proposal will result in:
    ```
    |a_b_|_
    |c   |
    ```
   For my proposal, that's not surprising for the user, as the wrapping of the text before the inserted character doesn't change, but for the existing resolution, it is surprising, as the wrapping of the previous text would change.

**Comment by kojiishi** [comment] 2019-07-29 03:43
Your proposal improves the case you presented, but has an undesired side-effect when `text-align: right`. Given this behavior was desired when `text-align` is `center` or `end`, the trade-off does not seem very attractive to me.

If there's a way to improve the case without the trade-off, I'm happy to discuss more.

**Comment by frivoal** [comment] 2019-07-30 12:31
Please explain what you find undesirable. As far as I can tell, the behavior for text align is unchanged compared to the resolution we previously took.

**Comment by kojiishi** [comment] 2019-07-30 13:30
> Please explain what you find undesirable.

Oh, sorry, I thought I did, but apparently didn't.

Imagine you have "0" in `width: 3ch` block. Adding a space after the "0" moves it to left by one space. This is what authors expect AFAIU. Adding another space moves it to left by one more space. Still good.

Adding another space, however, moves "0" back to the right edge, and adding more doesn't move any longer. I think this isn't desired.

Does this explain?

**Comment by fantasai** [comment] 2019-07-30 23:19
@kojiishi No, that's not how allow-end hanging works! That wouldn't work very nicely for hanging-punctuation either. :) Whatever part doesn't fit hangs, that's all.

**Comment by frivoal** [comment] 2019-07-30 23:51
> Adding another space, however, moves "0" back to the right edge, and adding more doesn't move any longer. I think this isn't desired.

As Elika said, that's not what happens. What would happen at the various steps of the insertion is:
```
|  0|
```
```
| 0_|
```
```
|0__|
```
```
|0__|_
```

That is identical to the previous resolution. The difference is that if, instead of inserting spaces after 0 in a 3ch line, you insert spaces after "0 0" on a 5ch lines. You'd get this:
```
|  0_0|
```
```
| 0_0_|
```
```
|0_0__|
```
```
|0_0__|_
```

With the previous resolution, you would have had (this is only different at the last step):
```
|  0_0|
```
```
| 0_0_|
```
```
|0_0__|
```
```
|0_   |
|0___ |
```

**Comment by kojiishi** [comment] 2019-07-31 00:27
For the last example, I think the previous resolution is preferrable for authors. Is that where you and I prefer different option?

Understood there were some misunderstanding, sorry about that, but my point is that adding spaces should change something, at least for `center` and `end`. I personally like WebKit behavior, but we once chose to not to hang on `center` and `end`. If we chose that, I think we should make sure it works all the time.

**Comment by kojiishi** [comment] 2019-07-31 03:06
...now I feel less sure how much we want to try the new spec, because by doing so, we have to regress either the case @frivoal presented or the case I presented, for the behavior 3 browsers are interoperable today, correct? Any chance to reconsider the resolution?

**Comment by frivoal** [comment] 2019-08-01 15:34
> the behavior 3 browsers are interoperable today, correct?

No, it is not. Chrome and Firefox are similar, but Safari is different.

None of the existing implementations solve both the alignment/justification use case you brought up when opening this issue and cases like https://crbug.com/453830.

#4095 and #3868 do solve both.

> we once chose to not to hang on center and end

If "we" means the CSSWG, I don't believe we did. At least, the spec as it exists today is not like that, and the resolution in this issue is not like that either.

> I personally like WebKit behavior

Both #4095 (my proposal) and #3868 (the standing resolution) are closer to the Webkit behavior than the current spec text. They both do the same thing as Safari[1] in for spaces at **unforced** breaks. The difference is only about the handling of spaces before **forced** break, which is necessary to handle cases like the one you reported with https://crbug.com/453830. Both #4095 and #3868 solve that case (but current Safari behavior does not).

I think a good way to describe the behavior of my proposal (#4095) would be:
* same as Safari[1] today for spaces before **unforced** breaks
* same as Chrome and Firefox today for spaces before **forced** breaks.

The original resolution (#3868) would be:
* same as Safari[1] today for spaces before **unforced** breaks
* new behavior (no hanging at all) for spaces before **forced** breaks. That's different from all implementations today (web compat concern) and is a worse behavior when editing.

> my point is that adding spaces should change something

I agree. What it changes is a little bit different in different situations, but it changes something:
* If you are adding spaces before a **forced** break (which includes at the end of an element), **and** the spaces fit the line, this will affect alignment
* if you are adding spaces either at before an **unforced** break (whether they fit the line or not), or before a forced break if they don't fit the line, the spaces are inserted[1] (so the caret moves further each time you insert a spce, they affect scrollbars, you can underline them or put a background on them...), but they hang, so they don't affect alignment.

----
[1] Note: When I say "like Safari", I mean with regards to hanging and to alignment. In addition to hanging the spaces, Safari also collapses the advance width of these spaces, so that they're not visible. This is allowed, but not required (and I would recommend not doing that) by the specification. Nobody is proposing to change that particular point.

**Comment by kojiishi** [comment] 2019-08-05 04:47
I think I understood you correctly, but not sure if you understood me correctly, so allow me to rephase in simple text. Sorry if this looks rude or offensive, that's not my intention, just want to avoid misleading.

I understood you pointed out a regression in the previous resolution, and your new proposal can solve it. This is great, thank you.

In the proposal, when it says:
> If you are adding spaces before a **forced** break (which includes at the end of an element), **and** the spaces fit the line, this will affect alignment

The "and the..." clause doesn't look great to me, it regresses when the space doesn't fit, and it's getting more complex. Given you found a regression, I prefer revisiting the previous resolution instead of adding new fixes on top of it.

...do I still look not understanding you correctly?

**Comment by fantasai** [comment] 2019-08-13 22:09
@kojiishi In general, if there is overflow, text-alignment doesn't happen. So I think it's OK in this case, if there is extra spaces in the line that don't fit, that they're not considered for alignment.

Overall I think @frivoal's proposed adjustment to the CSSWG resolution is a good fix, it addresses some unforseen problems in the original resolution but otherwise preserves its spirit and, in nearly all cases, its behavior. And it does so by taking advantage of existing definitions we already have for `hanging-punctuation`, so I think it's a clean solution.

**Comment by kojiishi** [comment] 2019-08-14 03:38
Not sure my previous point was understood, I'm not against @frivoal's proposal, I'm asking to revisit the previous resolution thanks to @frivoal's finding of the regression.

I don't think I want to accept the other regression in the new proposal, but I do agree that the regression @frivoal found is a very good one and we should try to fix it.

**Comment by faceless2** [comment] 2019-09-06 11:39
@frivoal I've put your "0's and 1's" test, above, at https://jsbin.com/fanatifawi. I hope I've understood your intention correctly.

This test is working properly in Chrome/Firefox, not in Safari. However it's contradicting the behaviour required by these tests:

http://w3c-test.org/css/css-text/white-space/pre-wrap-012.html
http://w3c-test.org/css/css-text/white-space/pre-wrap-013.html
http://w3c-test.org/css/css-text/white-space/pre-wrap-014.html
http://w3c-test.org/css/css-text/white-space/white-space-pre-wrap-trailing-spaces-001.html
http://w3c-test.org/css/css-text/white-space/white-space-pre-wrap-trailing-spaces-002.html

All of which work in Safari, but not in Chrome/Firefox.

Perhaps this is contributing to the confusion?

**Comment by frivoal** [comment] 2019-09-10 06:21
@faceless2 Nice test, thank you.

Your tests correctly captures what #4095 proposes to do for lines ending in forced breaks, which does indeed match Chrome and Firefox. The behavior specified in #3868 is different: it'd be the same on your "0" lines, but it would be different on the "1 1" lines.

The test does not cover what happens to lines ending in a soft wrap. The two proposals are identical about that, and match the behavior of Safari in that case.

(and yes, the WPT tests need to be updated, but we need to decide how we are going to resolve this before I do that update).

**Comment by fantasai** [comment] 2019-09-10 06:32
I updated the testcase to include the line-wrapping case here: https://jsbin.com/luxarox/1/edit?html,css,output I hope this makes things clear.

Thanks @faceless2 for such a nice test!

**Comment by frivoal** [comment] 2019-09-10 06:50
Screenshot of @fantasai 's edited version of @faceless2 's test:

| Firefox / Chrome | Safari |
|-|-|
|![firefox-screenshot](https://user-images.githubusercontent.com/113268/64590492-a244d380-d3e2-11e9-9ffa-e8fafce517b2.png)|![safari-screenshot](https://user-images.githubusercontent.com/113268/64590459-83ded800-d3e2-11e9-94dc-bc34c45290b7.png)|

**Comment by fantasai** [comment] 2019-09-12 07:30
@fantasai and @kojiishi trying to clarify the definition of the terminologies together.

Given the definition:
* allow-hang means 1) line breaker allows spaces to hang, and 2) alignment treats spaces same as any other characters.
* forced-hang means 1) same as allow-hang for line breaker, and 2) alignment ignores trailing spaces.

Then "Include" in the original table is exactly the same as "allow-hang" and "Don't include" is "forced-hang".

Feature|Blink|Edge|Gecko|WebKit
---|---|---|---|---
`text-align: start`|hang|hang|hang|hang
`text-align: end / center`|allow-hang|allow-hang|allow-hang|forced-hang
`text-align: justify`|forced-hang|Do not justify|Do not justify|Do not justify


For `text-align: start`, allow-hang and forced-hang is indistiguishable.

Latest WG resolution (and @frivoal's proposal) is to match WebKit for lines that end in a soft wrap.
Lates WG resolution was to not hang at all for lines that end in a forced break; @frivoal's proposal is to allow-hang for such lines.

**Closed** 2019-09-17 08:15 UTC
Labels: Agenda+ F2F, Closed Accepted by CSSWG Resolution, Needs Edits, Needs Testcase (WPT), Tracked in DoC, css-text-3
