### ISSUE TITLE
[css-values] Allow division of same types in calc()

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#545] opened 2016-09-28 16:18 UTC
The reason that division by a `<length>` was originally not allowed was that in some cases there was no way of knowing whether that was a division by 0, and before Variables there was no such concept as _invalid in computed value time_. Now that there is, perhaps we can revisit this issue for [Values 4](https://drafts.csswg.org/css-values).

This is especially useful in conjunction with CSS Variables, as currently one can convert from a `<number>` to a `<length>` (or `<angle>` etc) but there is **no way to convert a `<length>` to a `<number>`**! Also, calculating the ratio of two lengths is often very useful, e.g. what percentage of the viewport width is `500px`? `calc(500px / 100vw)`! Not to mention that this would be a more consistent, less surprising design.

**Comment by LeaVerou** [comment] 2016-10-04 17:39
@jpamental and I just found another use case: Variable fonts that smoothly change width and/or weight as the viewport is resized.

**Comment by jpamental** [comment] 2016-10-13 16:20
Seems like @tabatkins is talking about similar math issues here: https://github.com/w3c/csswg-drafts/issues/581

**Comment by fantasai** [comment] 2017-01-12 17:12
Yeah, this was in the plans for Level 4 (since it was deferred out of L3).

CSSWG just resolved to add it back to L4, so just needs edits at this point.

**Comment by tabatkins** [comment] 2018-05-08 00:54
Fixed in ea66912c7 and f791dfa76.

Agenda+ for review by the WG.

**Comment by dbaron** [comment] 2018-05-24 22:44
For the record, one place (out of possibly more than one) where the group resolved to add unit algebra to `calc()` was [the 2014-04-23 teleconference](https://lists.w3.org/Archives/Public/www-style/2014Apr/0373.html).

**Comment by dbaron** [comment] 2018-05-24 22:51
I think my only review comments, after reviewing [8.1.2. Type Checking](https://drafts.csswg.org/css-values-4/#calc-type-checking) are:
* the definition of division seems a little bit on the informal side -- "negate" / "negated" isn't formally defined, and I suppose it's not completely clear what it would mean for the percent hint on a type.  (Can the type in a `calc()` ever have a percent hint?)
* it's not clear what determines whether the result is `<number>` or `<integer>`, though I suspect that's a pre-existing issue.
* I'm worried that the clamping behavior (for infinities) is also underdefined.

**Comment by AmeliaBR** [comment] 2018-05-30 18:22
I agree with @dbaron that "negating" types is confusing wording.

> it's not clear what determines whether the result is `<number>` or `<integer>`, though I suspect that's a pre-existing issue.

Based on the decision in #2337, there is no longer any need to keep track of the distinction between numbers and integers: the calculation can happen as full numbers, and integer clamping happen on the final value.

More comments on @tabatkins' edits:

- Which is likely to go to CR first, Values 4 or CSS Typed OM 1?  Maybe it would be better to move the full type checking definitions here, and then reference/overwrite them from Typed OM.

- Regardless of whether or not you continue to link to Typed OM, it would be helpful if you actually define the type map concept in this spec before using it in the list of rules. Suggested wording:

  > Operators form sub-expressions, which can have complex types created by combining the types of their arguments. These complex types are represented as map of base types to integers representing a power.
  > 
  > [example]
  > The complex type «[ "length" → 1 ]» is a simple length (to the power 1).
  >
  > The complex type «[ "length" → 2 ]» is a length squared (to the power 2), which could represent an area measurement such as cm<sup>2</sup> (although area measurements aren't currently used in CSS).
  >
  > The complex type «[ "length" → 1, "time"→ -1 ]» is length over time (length to the power 1, time to the power negative 1), which could represent speed such as <sup>cm</sup>/<sub>s</sub> (again, not a type currently used in CSS properties, but still valid as an intermediary type in a calculation).
  >
  > The complex type  «[ "length" → 0 ]» is the same as  «[  ]» (an empty type map), and is equivalent to a unitless number.

- The "In previous versions..." sentence should be pulled out as an informative note.

- Then, in the rule list, move the list of simple types up to be the first point in the list, as it provides an understandable example of what this means.

- Since that bullet point already handles converting percentages to their "hint" types, I think it just confuses matters to link to the Houdini "add the types" algorithm for the "+" operator. In this simplified case, the algorithm is:
  
  > At a `+` or `-` sub-expression, determine simplified type maps for both the left and right arguments, by calculating a complex type map for that argument and then removing any types with a power of 0.
  > If the resulting type maps for both arguments are not identical, then the entire math function is invalid.
  > Otherwise, the sub-expression's type map is the result of removing any types with a power of 0 from the complex type map of one of its arguments.

- For multiplication: again, the linked Houdini algorithm includes complications about percent hints which don't apply here.  Notably, with percent hints already resolved to other base types, there is no way for the type checking to fail in a multiplication operation.  After removing percent hints from the algorithm, and converting some of the pseudocode to prose, it would look something like:

  > At a `*` sub-expression, generate a new complex type map, _finalType_, that is a copy of the complex type map for the left-hand argument to the expression.
  > Then, for each base type in the complex type map of the right-hand argument:
  >  - if _finalType_ already has an entry for that base type, increment its power by the amount of the power from the right-hand type map;
  > - otherwise, add a new entry for that base type to _finalType_, with a power equal to the power from the right-hand type map.
  > 
  > The sub-expression’s type is _finalType_.

- For division: 

  > At a `/` sub-expression, invert the type of the right-hand argument by multiplying ever power in the complex type map by -1.
  > The sub-expression's type is the result of multiplying the left-hand argument by this inverted type.

- If the decision is that this spec should stand alone, without reference to Typed OM, then the paragraph about resolving the math expression to a final type also needs to be re-written. But even if you continue to link to Typed OM, there might need to be some clarification here given that percentage types have already been resolved to other base types when possible. (The rules in Typed OM _do not_ define mutually exclusive types, since they allow a `«[ "percent" → 1 ]»` type to match percent, length-percent, angle-percent, etc.)

- Per the decision in https://github.com/w3c/css-houdini-drafts/issues/734#issuecomment-389592303, the "anything else" bullet point will need to be updated (although it might be best to keep that as a separate commit).

- The note about percentages and numbers not being combine-able needs to be updated, so that it doesn't reference division by other types being disallowed.

**Comment by tabatkins** [comment] 2018-05-31 23:49
> the definition of division seems a little bit on the informal side -- "negate" / "negated" isn't formally defined, and I suppose it's not completely clear what it would mean for the percent hint on a type. (Can the type in a calc() ever have a percent hint?)

Sigh, I knew that would be problematic, but hoped it was okay to be short with it. I added an "invert a type" algo to TypedOM and am using it directly now.

> it's not clear what determines whether the result is <number> or <integer>, though I suspect that's a pre-existing issue.

As Amelia said, that distinction is no longer necessary.

> I'm worried that the clamping behavior (for infinities) is also underdefined.

Interesting, what problems do you foresee? It should be identical to the existing clamping behavior for very-large-but-finite values; I can't imagine anything that would distinguish it from that case.

-----

> Which is likely to go to CR first, Values 4 or CSS Typed OM 1? Maybe it would be better to move the full type checking definitions here, and then reference/overwrite them from Typed OM.

I don't particularly care; if it becomes a publication issue I'll move things, but otherwise I'll just leave them where they are.

> Regardless of whether or not you continue to link to Typed OM, it would be helpful if you actually define the type map concept in this spec before using it in the list of rules.

I think that would be a distraction from the spec text. Even in Typed OM, the algorithms for types are off in their own subsection, separated from the actual operations that use them, because the details aren't particularly relevant for understanding things.  The fact that following the definitions jumps to another document instead of a same-document separate section isn't a particularly relevant difference here.

> The "In previous versions..." sentence should be pulled out as an informative note.

Good catch, done.

> Then, in the rule list, move the list of simple types up to be the first point in the list, as it provides an understandable example of what this means.

I see the value of this, but I'm currently relying on it being last so I can say "anything else".  For consistency I'd also have to move the final bullet point up, and I think it reads best put at the end.

> Since that bullet point already handles converting percentages to their "hint" types, I think it just confuses matters to link to the Houdini "add the types" algorithm for the "+" operator. 

Sure, it's some indirection, but it's identical to the type-determining line of the `.add()` algorithm in TypedOM, and that sort of parallel construction helps highlight that there's nothing surprising.  Rewriting it to be more explicit and reproducing the "add two types" algo makes this less obvious.

I'm similarly against trying to inline the algorithms for multiplication and division.

> Notably, with percent hints already resolved to other base types, there is no way for the type checking to fail in a multiplication operation.

Ah, this is true. I'll simplify.

> (The rules in Typed OM do not define mutually exclusive types, since they allow a «[ "percent" → 1 ]» type to match percent, length-percent, angle-percent, etc.)

They *do* define mutually-exclusive types *among the types that I listed*.  I didn't say that it can resolve to the `<*-percentage>` productions on purpose.

> Per the decision in w3c/css-houdini-drafts#734 (comment), the "anything else" bullet point will need to be updated (although it might be best to keep that as a separate commit).

I don't understand what needs to be updated - I wrote the spec text with the assumption that the issue would be resolved in the way I wanted, so it already defines how to handle `<flex>`.

> The note about percentages and numbers not being combine-able needs to be updated, so that it doesn't reference division by other types being disallowed.

Updated from future to present tense. ^_^

**Comment by dbaron** [comment] 2018-06-01 00:01
So for clamping of infinities, a few things (though maybe not what I was thinking at the time):
* the allowed range doesn't seem to be defined
* since some `calc()`s are resolved at computed value time, I think some clamping needs to happen then, or else you need to figure out how to represent infinite computed values
* do the IEEE-754 semantics depend on the order of operations in places where the order of operations isn't defined by CSS?  (I'm not sure.)
* within what scope does an implementation need to track distinctions like +0 and -0?  A single `calc()` expression?  When `calc()` is nested inside of `calc()`, is that treated as just syntactic sugar for parentheses, or a separate expression that triggers clamping?  (I'd hope the former.)  Likewise for "If a math function would resolve to NaN, it instead resolves to positive infinity." which I would hope refers to the entire toplevel function, not pieces of it -- though that should be clear.
* is it defined how `min()` and `max()` handle NaNs?

**Comment by tabatkins** [comment] 2018-06-02 01:13
> the allowed range doesn't seem to be defined

It wasn't previously defined either, that's up to individual properties and/or user-agent choice.  Again, you could *always* define an arbitrarily large value in calc(); infinity is just slightly larger than that. ^_^

> since some calc()s are resolved at computed value time, I think some clamping needs to happen then, or else you need to figure out how to represent infinite computed values

Ah, I didn't mean to restrict it to used-values only. Fixed.

> do the IEEE-754 semantics depend on the order of operations in places where the order of operations isn't defined by CSS? (I'm not sure.)

I dunno either.

> within what scope does an implementation need to track distinctions like +0 and -0?

I rewrote it to be more specific, specifying exactly which operations produce infinities or NaNs, and how infinities or NaNs affect operations they show up in. I defined "top-level calculations" to be any of the expression arguments to min()/max()/clamp(), or a non-nested calc(); these censor NaN by turning it into positive infinity, while non-top-level calculations are still allowed to produce NaN.  (So in particular, `calc(-1 * calc(0/0))` will produce positive infinity, not negative infinity, because the inner calc() resolves to a NaN, so the outer calc() resolves to a NaN, and gets censored into positive infinity.)

I went ahead and dropped negative-zero tracking, tho I'm not sure if I should. There are only two ways to produce a negative zero in 754 semantics: explicitly negate a zero (or an expression resulting in zero), or divide a finite number by negative infinity.  calc() can't negate things, only subtract them, and subtraction will never result in -0 unless one of the arguments is -0 already.  So we're left with dividing by negative infinity. Unless there's some difficulty with implementations having semantics differenting from 754, I'd rather just pretend that particular case doesn't exist. But if it does become a problem, I'm fine with explicitly specifying how it works, too.

**Comment by tabatkins** [comment] 2018-06-04 19:43
Agenda+ to ask about whether I should keep negative-zero tracking within an expression.  (The distinction will disappear when it exits a top-level calculation, at the same time as NaNs disappear.)

Specifically, should `calc(1 / calc(1/(-1/0)))` produce positive infinity or negative infinity?  If negative-zero is tracked, the the inner calc produces negative zero, and the outer calc then produces negative infinity. If it's not, then the inner calc just produces zero, and the outer calc produces positive infinity.

**Comment by FremyCompany** [comment] 2018-06-06 21:54
Mmmmm, I have the impression dividing by zero is currently disallowed by all browsers. 
Did we have a resolution to change this?

If yes, no opinion, since there isn't an implementation of this yet.

**Comment by FremyCompany** [comment] 2018-06-06 22:29
https://wptest.center/#/lr3dp8 (testcase in case someone else want to try this before the call)

**Comment by tabatkins** [comment] 2018-06-06 23:04
Yes, we changed that (because we *have* to - you can't tell at parse time if `1 / (16px - 1em)` will be a division by zero).  That's not an issue at hand. ^_^

**Closed** 2018-06-14 23:01 UTC
Labels: css-values-4
