### ISSUE TITLE
[css-values-4] Visual viewport units

### ISSUE THREAD

**Issue by devongovett** [w3c/csswg-drafts#7194] opened 2022-04-01 21:24 UTC
The new [viewport relative units](https://www.w3.org/TR/css-values-4/#viewport-relative-lengths) introduced recently are a great step forward. However, none of them correspond with the [VisualViewport](https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport) API in JavaScript. Specifically, when the software keyboard is visible, the `visualViewport.height` property changes accordingly, but e.g. `100dvh` does not.

This behavior is problematic when trying to build interfaces that are positioned above the on-screen keyboard, or resize so that they are always visible while the keyboard is open. Examples include chat UIs, commenting UIs, trays/sheets, modals containing forms, floating toolbars, etc.

I would like to propose another unit that corresponds exactly to what the VisualViewport API returns, but without requiring JavaScript. It is possible to accomplish this by setting a custom property from JS when the VisualViewport resize event occurs, but this approach has some drawbacks:

* It requires JavaScript. This seems like a common enough UI pattern to warrant a CSS-only solution.
* It does not adjust smoothly during keyboard open/exit animations. The VisualViewport API typically only fires a single resize event at the end of the transition. This can lead to janky user experience where UI components are incorrectly positioned or sized temporarily while the keyboard is opening or closing. I think the UA would need to be in charge of doing this animation for performance reasons, rather than dispatching a JS event every frame.

Possible names:

* `vvh` - i.e. visual viewport height
* `vvw`
* `vvmin` / `vvmax`

Has something like this been discussed in the past?

**Comment by Loirooriol** [comment] 2022-04-01 22:30
> when the software keyboard is visible, the `visualViewport.height` property changes accordingly, but e.g. `100dvh` does not.

I'm not much familiar with that, but I think `dvh` should change accordingly. Wasn't that the entire point of adding that unit?

**Comment by devongovett** [comment] 2022-04-01 22:49
The current spec for dynamic viewport units is clear:

> Additionally, UAs may have some dynamically-shown interfaces that intentionally overlay content and do not cause any shifts in layout—and therefore have no effect on any of the [viewport-percentage lengths](https://www.w3.org/TR/css-values-4/#viewport-percentage-lengths). (Typically on-screen keyboards will fit into this category.)

That's why I think we need a new unit.

**Comment by bfgeek** [comment] 2022-04-05 17:08
I believe based on https://bokand.github.io/demo/urlbarsize.html (and inserting a <textarea> or <input> in the DOM to trigger the keyboard behaviour) that Blink will adjust the dvh/lvh unit based on whether the keyboard is showing. @devongovett - Does Chrome Canary on Android (with chrome://flags/#enable-experimental-web-platform-features enabled) match your expected behaviour?

**Comment by devongovett** [comment] 2022-04-05 19:47
I believe Chrome on Android has always resized the viewport when the keyboard appears, even with regular `vh` units. iOS does not do this though - the keyboard covers the content instead. The spec as quoted above seems to allow this, which is why I think either the spec should be changed, or a new unit is needed.

**Comment by tabatkins** [comment] 2022-04-14 20:52
> It does not adjust smoothly during keyboard open/exit animations. 

Note that this would still be true of a new viewport unit. dvh explicitly says UAs are *not* required to animate the unit while stuff is showing/hiding, just that they have to be correct when the animation is finished. We'd have a similar clause for any other unit in this space.

**Comment by bokand** [comment] 2022-06-16 02:00
> This behavior is problematic when trying to build interfaces that are positioned above the on-screen keyboard, or resize so that they are always visible while the keyboard is open. Examples include chat UIs, commenting UIs, trays/sheets, modals containing forms, floating toolbars, etc.

A challenge with using a visual viewport unit to achieve these use cases is that the visual viewport also resizes (and offsets) as a result of pinch-zoom. If you're positioning a floating toolbar based just on the visual viewport height, it'll be wrong as soon as some pinch-zoom (and non-0 `visualViewport.offsetTop`) is introduced (and browsers perform automatic zoom onto a focused input element in some cases).

IMHO, something like [position: device-fixed](https://www.quirksmode.org/blog/archives/2010/12/the_fifth_posit.html#:~:text=the%20user%20interaction.-,position%3A%20device%2Dfixed,-Which%20of%20these) seems more natural for these use cases since it'd let you position things in the coordinate space of the visual viewport.

**Comment by devongovett** [comment] 2022-06-16 04:08
That might work for fixed size floating toolbars, but I need to both position _and size_ content to fit above the keyboard though. When the user scrolls while the keyboard is open, content shouldn't be behind the keyboard, only above it.

**Comment by bramus** [comment] 2022-06-21 09:15
> (@bfgeek) I believe based on https://bokand.github.io/demo/urlbarsize.html (and inserting a <textarea> or in the DOM to trigger the keyboard behaviour)

A forked version that includes this can be found at https://urlbarsize.netlify.app/urlbarsize-allowresize.html
It also contains an extra option to toggle the behavior of the Virtual Keyboard _(if supported by the browser)_.

> (@devongovett) I believe Chrome on Android has always resized the viewport when the keyboard appears, even with regular vh units.

Correct. It's the only platform that does this, and we'll be looking into that as part of https://github.com/web-platform-tests/interop-2022/issues/41

> (@bokand) A challenge with using a visual viewport unit to achieve these use cases is that the visual viewport also resizes (and offsets) as a result of pinch-zoom.

What if the zoom level was also exposed? Then an author would be able to reconstruct the “Unzoomed Visual Viewport” values from that:

- Unzoomed `vvh` = `calc(100vvh * 100vvz)`;
- Unzoomed `vvw` = `calc(100vvw * 100vvz)`;

_(`vvz` to be bikeshed, but you get the point)_

Alternatively `uvvh` and `uvvz` could be exposed, but that would – again – be extra units for the author to remember/use.

> (@bokand) IMHO, something like [position: device-fixed](https://www.quirksmode.org/blog/archives/2010/12/the_fifth_posit.html#:~:text=the%20user%20interaction.-,position%3A%20device%2Dfixed,-Which%20of%20these) seems more natural for these use cases

Also a fan of it :)

**Comment by bramus** [comment] 2022-07-01 11:15
The proposed Visual Viewport Units do not form a closing solution for the stated use-case of positioning above the Virtual/On-Screen Keyboard (OSK). Take this snippet that _should_ achieve the desired effect.

```css
#target {
  position: fixed;
  height: 2em;
  width: 100vvw;

  top: 100vvh;
  transform: translateY(-100%);
}
```

The code above only works when the top edges of the Layout Viewport and Visual Viewport line up. This, however, is not always the case. When scrolling down with the OSK shown, the Layout Viewport will initially stay where it is, and the user is merely moving the Visual Viewport down. Because the Visual Viewport always matches the device, the net result is that the Layout Viewport will “shoot up”. 

See illustration below where the FixedPos Element _(orange)_ appear to be floating in the middle of the Visual Viewport _(orange dotted line)_ once you scroll down, because it is laid out against the top edge of the Visual Viewport _(blue dotted line)_.

<img width="745" alt="image" src="https://user-images.githubusercontent.com/213073/176884020-b2d6ddec-2866-4cb9-8592-725df9250e2f.png">

To work properly one would also need the distance between the top edges of both viewports mentioned, which would introduce even more extra units.

The already mentioned [`position: device-fixed;`](https://www.quirksmode.org/blog/archives/2010/12/the_fifth_posit.html#:~:text=the%20user%20interaction.-,position%3A%20device%2Dfixed,-Which%20of%20these) would form a more closing solution, as that would really keep items in place – even when the Visual Viewport moves or gets resized.

**Comment by flackr** [comment] 2022-08-02 18:04
I started #7475 to discuss a particular proposal to allow content to stay visible when the keyboard is shown. It has an interactive demo that can be viewed on desktop. This seems highly related.

**Comment by fantasai** [comment] 2022-10-10 19:46
Closing out since we definitely won't be adding visual viewport units, but discussion on addressing the use case should continue in https://github.com/w3c/csswg-drafts/issues/7475 (or other issues).

**Closed by fantasai** 2022-10-10 19:46 UTC
Labels: css-values-4
