### ISSUE TITLE
[css-view-transitions-1] Clarify rendering constraints for elements participating in a transition

### ISSUE THREAD

**Issue by jakearchibald** [w3c/csswg-drafts#8139] opened 2022-11-28 16:25 UTC
Right now, if an element is to be captured for a view transition, we require the developer to set either layout or paint containment. There's no longer a technical reason for this, but it may still catch some unexpected behaviour.

For example, take this sidebar.

```css
.sidebar {
  view-transition-name: sidebar;
  position: absolute;
  inset: 0 auto 0 0;
}
```

Imagine, due to some hacky layout, a logo overlay was within the sidebar:

```css
.sidebar > .logo {
  position: fixed;
  right: 0;
  top: 0;
}
```

In CSS terms, the sidebar and the logo are independently positioned, since the logos containing block is some ancestor of the sidebar.

However, with view transitions, if we create a transition where the sidebar moves horizontally, we'll also be moving the logo, since it's part of the same capture. If the sidebar transitions to left by 100px, the old view of the logo (as part of the sidebar view) will slide to the left by 100px and fade out, and the new view of the logo will slide in from the right by 100px and fade in.

`contain: layout` ensures children of the sidebar will not use a parent as a containing block. It won't 'fix' the issue above, but it will make it obvious that it won't work, before the transition starts.

My thoughts on this:

- Helping developers identify issues early is good. But how common is the above gotcha?
- Even as someone involved in the spec, I frequently forget to add `contain: paint` and my transition fails. I then roll my eyes & add `contain: paint`. This might be a net negative on developer experience.
- Adding `contain: paint` has never saved me from the gotcha above, but my demos have been simple, so they're unlikely to have weird layouts like above.
- Removing the `contain: paint` requirement is a backwards compatible change, so we can do it later.

**Comment by fantasai** [comment] 2022-12-06 04:59
I would lean towards not requiring `contain`. It's not really helping the developer to require it: if there's something that doesn't get captured as they expect, then they can fix that. But requiring it really makes view transitions unnecessarily complicated to use.

And more importantly, requiring it invites errors in the form of accidentally overwriting `contain: somethingelse` when you add a view transition because you added `contain: paint`.

**Comment by jakearchibald** [comment] 2022-12-06 10:58
@fantasai does this need to be aired in a CSSWG meeting? (assuming consensus here is to remove the `contain` requirement)

**Comment by khushalsagar** [comment] 2023-01-03 16:07
+1 from me as well to remove the contain requirement. But one side effect of contain: layout (or paint) is that the element becomes a stacking context. And we do need this to capture the element as an atomic image.

The spec could say that if an element has a non-none computed value for `view-transition-name` then it becomes a stacking context but I want to avoid unexpected side-effects from applying this property. Especially if a developer adds this property only for the duration of the transition and the layout changes in unexpected ways.

So could we require that developers explicitly ensure that named elements create a stacking context? It could be from an effect (like `opacity`) or by adding `isolation: isolate` to the element.

**Comment by vmpstr** [comment] 2023-01-16 19:36
To add to this, I think elements participating in a view transition should have `trasform-style: flat`, because we will be moving the paint of this element elsewhere so it makes sense to flatten it, not to mention that this also avoids a large implementation complexity.

both `opacity < 1` and `isolation: isolate` are [grouping property values](https://w3c.github.io/csswg-drafts/css-transforms-2/#grouping-property-values) so this would work.

I want to consider that `view-transition-name` should imply one of the grouping properties, like `isolation: isolate`, without the need for there to be an ongoing transition. IOW, the presence of the property should be enough to put `isolation: isolate` on it to ensure that the effect imposed by the property is not ephemeral.

As a side note, `view-transition-name` and in general elements participating in a view transition should have `isolation: isolate` on its own due to the fact that the blending of captured pixels would be different in a non-normal `mix-blend-mode`

**Comment by khushalsagar** [comment] 2023-01-17 00:02
+1 to requiring elements participating in a transition to have `transform-style: flat`. My read on the discussion so far is that there is agreement to require isolation, as described by `isolation: isolate`, but we don't need layout containment.

I don't have a strong preference on whether isolation should be implicitly applied based on `view-transition-name` or explicitly require developers to add it. I'm in agreement though that if its implicit, it shouldn't be limited to the duration of the transition. Summarizing the 2 options:

1. If an element has a non-none computed value for `view-transition-name`, then `isolation` computed to `isolate`. Less annoying for developers to have to add it but the side-effect on `isolation` could be unexpected. At least it'll be easily observable to devs since the change will be in computed value (not used).
2. If an element has a non-none computed value for `view-transition-name`, the author must ensure it also has isolation for the duration of ViewTransition. Failing to do so causes the transition to abort. This is the pattern being used for layout containment currently.

@fantasai @tabatkins do you have a suggestion on which pattern is better based on best CSS practices.

**Comment by vmpstr** [comment] 2023-01-17 01:18
Layout containment aside, I'm still not convinced that we don't want the shared element to be a containing block for positioned descendants. As Jake described it initially, the effect you would get looks strange. Although I agree that the case may be rare, I think having the shared element be a containing block up front _seems_ better and more helpful to help the developer fix their page

**Comment by khushalsagar** [comment] 2023-01-17 02:55
The case Jake described is the reason I'm advocating against forcing the shared element to be a containing block for positioned descendants. For the layout issue mentioned in the first comment, where the nested element moves with the shared element as a part of its snapshot, developers can easily workaround this by making the descendant a shared element.

Here is a concrete example which simulates what will happen if the ancestor shared element is not a containing block for a fixed position descendant:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width">
  <title>JS Bin</title>
</head>
  <style>
    .inner {
      position: absolute;
      width: 100px;
      height: 100px;
      background: blue;
    }
    
    .outer {
      position: fixed;
      width: 200px;
      height: 200px;
      background: red;
      view-transition-name: foo;
      contain: layout;
    }
    
    .outer_old {
      top: 0px;
      left: 0px;
    }
    .outer_new {
      top: 50px;
      left: 50px;
    }
    
    .inner_old {
      top: 10px;
      left: 10px;
    }
    .inner_new {
      top: -40px;
      left: -40px;
    }
    
    button {
      position: fixed;
      top: 250px;
    }
  </style>
  <script>
    function doTransition() {
      document.startViewTransition(() => {
        outer.classList.toggle("outer_old");
        outer.classList.toggle("outer_new");
        
        // Change position to simulate pos: fixed.
        inner.classList.toggle("inner_old");
        inner.classList.toggle("inner_new");
      });
    }
  </script>
<body>
<div class="outer outer_old" id="outer">
  <div class="inner inner_old" id="inner"></div>
</div>
<button onclick="doTransition()">Animate</>
</body>
</html>
```

The start/end viewport positions of `inner` will be based on its containing block in author DOM, which is the ICB. The animation definitely looks awkward because of the way `inner` fades out and then fades in at the same location. But if `inner` is also made a shared element, there is no issue.

On the other hand if we force shared elements to become containing blocks, authors will have no choice but to change the DOM topology if there are positioned descendants. This can be fairly complicated. Also want to point that this is not a theoretical case, we have seen partner use-cases like this.

**Comment by jakearchibald** [comment] 2023-01-17 14:00
I'm not against `view-transition-name` causing an element to become a stacking context. I think developers are pretty used to that given the number of other properties that result in the same behaviour.

@khushalsagar 

> 1. If an element has a non-none computed value for `view-transition-name`, then `isolation` computed to `isolate`.

I don't know if you meant this literally, but I don't think it should work literally like this. That isn't how it works with `opacity` etc https://jsbin.com/xuyekeh/edit?css,js,console,output

@vmpstr 

> To add to this, I think elements participating in a view transition should have `trasform-style: flat`

I don't fully get the reasons for this, but I don't mind that being a restriction. It's something we can revisit later if needed.

**Comment by khushalsagar** [comment] 2023-01-17 19:12
Summarizing an offline discussion. TLDR, no opposition to the following requirements on a shared element:

- Must force a stacking context.
- Must flatten all descendants into the coordinate space of the shared element. Or make `view-transition-name` a [grouping property](https://w3c.github.io/csswg-drafts/css-transforms-2/#grouping-property-values).

Both can be done with the proposal above to use `isolation: isolate` for these elements.

But with respect to whether the shared element needs to be a containing block, there's good points for both options:

- Force it to be a containing block for all positioned descendants.
   - This means all descendants transform with the shared element, which is what will happen when the descendants move as a part of the snapshot anyway (unless they are also shared elements).
   - Also avoids surprised where an element's snapshot is expanded significantly because a pos: fixed descendant is far off in the shared element's layout overflow.
   - Follows the pattern of `transform` which [forces a containing block](https://w3c.github.io/csswg-drafts/css-transforms-2/#transform-functions:~:text=while%20all%20other%20values%20(including%20%E2%80%9Cidentity%E2%80%9D%20transforms%20like%20translate%3A%200px)%20create%20a%20stacking%20context%20and%20containing%20block%20for%20all%20descendants%2C%20per%20usual%20for%20transforms.).

- Don't force it to be a containing block. You get the weird animation in the comment [above](https://github.com/w3c/csswg-drafts/issues/8139#issuecomment-1384771727), but:
   - Developers can fix it trivially by making the descendant a shared element.
   - They can also explicitly force the shared element to be a containing block (with `contain: layout` or `transform: translate: 0px`) if that's the desired behaviour. Instead of the browser forcing this behaviour that the developer can not change.

This needs more input from developers.

**Comment by khushalsagar** [comment] 2023-01-18 16:04
> This won't literally use isolation: isolate in any observable way.

Depends on how we want to spec it:

1. A non-none computed value of `view-transition-name` causes the element to generate a stacking context and is a [grouping property value](https://w3c.github.io/csswg-drafts/css-transforms-2/#grouping-property-values).
2. A non-none computed value of `view-transition-name` causes the element's used value for `isolation` to be `isolate`. If the change is in computed value of `isolation`, instead of used, then it will be observable to developers.

Since `isolation` already conceptually maps to what we want, could build on that concept.

> I think there will be cases where the developer really doesn't want a containing block here.

+1. That's why I'm leaning towards no containing block by default, with guidance on how developers can detect and fix common errors (by manually adding `contain: layout` for example).

**Comment by jakearchibald** [comment] 2023-01-18 16:14
> Depends on how we want to spec it:

I vote for 1, since that's how the other [grouping properties](https://w3c.github.io/csswg-drafts/css-transforms-2/#grouping-property-values) behave. Or is this behaving differently to other grouping properties?

**Comment by ydaniv** [comment] 2023-01-18 17:15
From this:

> Summarizing an offline discussion. TLDR, no opposition to the following requirements on a shared element:
> - Must force a stacking context.
> - Must flatten all descendants into the coordinate space of the shared element. Or make view-transition-name a [grouping property](https://w3c.github.io/csswg-drafts/css-transforms-2/#grouping-property-values).

Follows that `view-transition-name` should be a grouping property, then, AFAICT looks like 1 it is.

**Comment by ydaniv** [comment] 2023-01-19 13:01
Damn, we just hit that after several hours of debugging 🙈 
So another +1 to @fantasai's suggestion.

**Comment by khushalsagar** [comment] 2023-01-19 19:57
Sorry @ydaniv, this is getting fixed soon. :)

I missed another restriction we need, the named element needs to be the [backdrop root](https://drafts.fxtf.org/filter-effects-2/#backdrop-root) for descendants with a backdrop filter. Given that this element's painting will be rendered via the pseudo-element, it doesn't make sense for an ancestor to readback the named element's painting. @mfreed7 FYI.

So the constraints required on a named element, implicitly applied if it has a non-none computed value for view-transition-name, are:

- Generate a stacking context.
- Be a grouping property.
- Be the backdrop filter root for all descendants.

Still undecided on whether it needs to be a containing block.

**Comment by jakearchibald** [comment] 2023-01-25 16:26
One decision remaining on this, is how we should handle:

- **named-element** has a `view-transition-name`
- **child**, is a child of **named-element**, is fix-pos, and uses a containing block that's parent to **named-element**

```html
<style>
  .named-element,
  .child {
    width: 150px;
    height: 150px;
    background: green;
  }

  .named-element {
    view-transition-name: named-element;
    margin: 120px;
  }
  
  .child {
    background: blue;
    position: fixed;
    top: 0;
    left: 0;
  }
</style>
<div class="named-element">
  named-element
  <div class="child">child</div>
</div>
```

Which looks like this:

![Screenshot 2023-01-25 at 15 58 18 copy](https://user-images.githubusercontent.com/93594/214612855-0ec4653e-8769-49e2-86cd-b34c3e965fe0.png)

How should the view-transition work, considering changes to `named-element`, such as position and background color?

## Option 1: Capture as-is

Capture `named-element` and all its content. The size of the image is the border box of `named-element`.

Here's how the background color and position transitions would look:

https://user-images.githubusercontent.com/93594/214614069-f1f6e456-9914-4aff-93de-a0bc8e154094.mp4

The background color animation looks good. However, the position transition doesn't look 'right', since the captures move with the bounding box of `named-element`, yet the child has remained fixed.

If this isn't what the developer wants, they can make the child part of the transition too:

```css
.child {
  view-transition-name: child;
}
```

And the result:

https://user-images.githubusercontent.com/93594/214615591-1001be16-7457-4431-b60f-132eb94b4e7b.mp4

## Option 2: Exclude the child from the capture

`named-element` is captured excluding the child, because it uses a containing block that's an ancestor of `named-element`. The child is instead captured with the view-transition part that's closest (as in `el.closest()`) to the child's containing block, which is the root in this case.

Here's how that would look:

https://user-images.githubusercontent.com/93594/214616580-5e09507e-c1c2-44bc-aac8-fec90536f3c1.mp4

This doesn't look quite right, as the `named-element` appears over the child during the transition, since the child is now painted onto the root.

The fix is the same as before, which is to make the child part of the transition.

## Option 3: Force a containing block

Adding a non-`none` `view-transition-name` to an element causes it to be a containing block, similar to `opacity` values less than `1`, and transforms.

When the developer does this, their layout will break, which should be easy to spot.

The best fix for this would be for the developer to change the DOM so the fix-pos element is no longer within `named-element`.

This is already the case if the developer wants to animate a transform.

**Comment by flackr** [comment] 2023-01-25 16:36
Note regarding option 3, we may be able to say that `view-transition-name` is only a forced container for elements which do not also have a `view-transition-name`, allowing the same ability for developers to keep them separate the same way as the first two.

**Comment by khushalsagar** [comment] 2023-01-25 18:05
Thanks for the excellent summary @jakearchibald and @flackr for thinking through the options. We've been weighing these options against 3 parameters: developer expectations (does the behaviour during the transition align with what developers would expect given a layout), developer ease of use (how easy is to for developers to get the behaviour they want, if the default doesn't work for them) and ease of implementation for the engine.

Here's my take for the 3 options:

- Option 1
   - Developer expectation: Doesn't line up with developer expectations since child is not positioned relative to its containing block during the transition. But works for any case where the named ancestor doesn't have a position animation.
   - Developer ease of use: Can make the child a named element to move it independently. Some desired behaviour can not be achieved, for example in the case where where a node between the named element and child has opacity. The opacity won't apply since named elements don't get ancestor effects in their snapshots.
   [Nested transition groups](https://github.com/WICG/view-transitions/blob/main/explainer.md#nested-transition-groups) will eventually fix this.
   
   - Implementation Complexity: Easy to implement (speaking from Blink's perspective). Since `opacity` forces a stacking context but not a containing block, there is precedent to paint a DOM element as an atomic unit with descendants that don't use this DOM element as a containing block.
   We did notice that element() in Gecko skips fixed positioned descendants so maybe there is implementation complexity there ([demo](https://jsbin.com/nuwukob/edit?html,css,output)). @emilio @dholbert for feedback.
   
- Option 2
   - Developer expectation: Doesn't line up with developer expectations since child paints into a different stacking context than it normally would. 
      This means the child wouldn't have effects like opacity from an ancestor which is between the named element and child in the hierarchy. But this is already possible if the child is a named element, since its snapshot excludes ancestor effects by design.
      The paint order would also change (as shown in the example). But this is also already possible. If there are 3 sibling elements with a paint order of a, b, c and b becomes a named element, then a and c get squashed into their ancestor's snapshot while b draws on top (as an independent snapshot).
   - Developer ease of use: Same as option 1.
   - Implementation Complexity: Harder to implement than option 1. There isn't an existing pattern to change the stacking context hierarchy this way.

- Option 3
   - Developer expectation: Lines up with developer expectations, child moves with the named ancestor since its forced to be its containing block.
   - Developer ease of use: Must change the DOM topology if there is a child which shouldn't use a named ancestor as its containing block.
   - Implementation Complexity: None. Its a subset of the constraints that come with layout containment.

- Option 4
   This is from flackr's last comment, the named element is a containing block for all descendants except other named elements.
  - Developer expectation: Unsure. It would be a new pattern for developers to learn, since view-transition-name can now selectively change the containing block for some elements.
  - Developer ease of use: Similar to option 1/2. The downside I see is that developers could be forced to make a child a named element even if its not needed, for example in the background color animation case in Jake's summary of option 1. Each named element has a memory cost to be rendered into an independent snapshot.
  - Implementation Complexity: Minimal.

My preference order would be option 1 followed by option 4. Option 2 trades one set of unexpected behaviour from option 1 with a different set of unexpected behaviour and adds implementation complexity. Option 3 seems too restrictive for developers. I'd err on the option which is better for developer expectation/ease of use so would help to hear developer feedback on this. @mirisuzanne FYI.

**Comment by jakearchibald** [comment] 2023-01-26 12:45
I really want to keep this simple rule for developers: When you give an element a `view-transition-name`, it, and its descendants, are captured separately as an image.

Given that, I'm not convinced that option 1 breaks developer expectations. Or, if it isn't initially what they expect, a quick look at the `old` and `new` images should make it clear.

Even with forcing a containment block, you can achieve the same effect by counter-transforming the child element (it's how [the demo was made](https://static-misc-3.glitch.me/vt-containment-demos/allow.html)). It looks weird, sure, but it's following the rule of capturing the element as an image, which seems easy to understand.

Option 2 is a smart workaround, but it breaks the simple rule. The rule becomes: When you give an element a `view-transition-name`, it, and its descendants that use a containing block that is not an ancestor of element, are captured separately as an image.

I think that's much harder to understand, and lead to more unexpected behaviour. Also, when developers encounter this unexpected behaviour, I don't think they're going to easily figure out what's happening.

Option 3 maintains the simple rule, but adds an additional rule: `view-transition-name` causes a containing block. Although, this is a rule that also comes with setting transforms, so maybe it isn't a big deal.

Option 4 lefts the restrictions of option 3, but it seems like a new bit of layout to learn.

My preference is option 1. It does what it says, without introducing new rules to learn. If it creates an effect the developer doesn't want, it's easy to figure out and resolve.

**Comment by mirisuzanne** [comment] 2023-01-26 18:05
I agree with @jakearchibald on this – I'd vote for option 1. When option 1 'fails' (by not providing a perfect default transition) - that failure is clear to see, understand, and address without any changes to the DOM or other aspects of the layout. The solution is contained to the view-transition. The other options try to magically enforce a perfect default, but end up introducing less obvious side-effects.

**Comment by jakearchibald** [comment] 2023-02-08 13:29
Summary for the CSSWG meeting:

In our early implementation, paint containment was required for captured elements.

```css
.header {
  view-transition-name: header;
  contain: paint;
}
```

This requirement was lifted, but we still required layout containment, to ensure captured elements were containing blocks.

```css
.header {
  view-transition-name: header;
  contain: layout;
}
```

This turned out to be frustrating, because it was easy to forget about, the transition would fail, you'd see the warning in dev tools, then add `contain: layout`. It felt like this happened every time. I experienced this myself, and heard the same from other developers.

Resolution 1 of 2: Remove the requirement to set `contain: layout`, and instead apply any requirements to elements that have a `view-transition-name`. Similar to how elements with a `transform` become containing blocks, without that being set explicitly.

Assuming resolution 1 is passed, a non-`none` `view-transition-name` will cause the element to:

- generate a stacking context
- be a grouping property (forces flat preserve-3d)
- be a backdrop root

…which is the same set of behaviours that comes with `opacity` less than 1.

The remaining question is: how should we handle elements within the captured element, that use a containing block that's outside the element? We've seen this in the wild, with one of our partners testing the API - they had a pos-fixed close button inside an element with a `view-transition-name`.

If the element moves position (and the pos-fixed element naturally doesn't), you can end up with a transition which looks like this:

https://user-images.githubusercontent.com/93594/214614069-f1f6e456-9914-4aff-93de-a0bc8e154094.mp4

…where the pos-fixed element moves when it shouldn't.

We considered forcing a containing block to prevent this effect, requiring the developer to move the fixed-pos element out of the captured element if they want the same layout.

We also considered more complex solutions that allowed for the fix-pos element to be excluded from the capture, and instead be captured along with the group associated with its containing block.

However, we concluded that:

- Forcing a containing block requires the developer to alter their DOM, which feels like it will hurt adoption - again we've seen this in real-world cases.
- We'd like to keep a simple rule: When an element as a `view-transition-name`, it, and its descendants, are captured separately as an image. The more complex solutions we thought of break that rule.
- Cases where this results in an animation the developer didn't expect are clear to see, understand, and address without any changes to the DOM or other aspects of the layout (thanks @mirisuzanne for that summary). The fix is usually to give the fix-pos element its own `view-transition-name`.

So resolution 2 of 2: Don't require or force a containing block. Capture the element and all its descendants as-is, even if they're positioned to a parent containing block.

**Comment by flackr** [comment] 2023-02-08 15:24
Given that opacity has established that we can paint the content independently without containment, I think technically option 1 should work.

My main concern is that non-contained descendants will result in the capture being much larger than the developer realizes (e.g. bounding box of the capture element to the current position of the descendants), however perhaps #8282 will help with this and make it less of an issue.

I was also concerned that the inconsistency between this behavior (which effectively allows animating transform without containment) where normally any non-none transform forces containment would be confusing for developers. I can understand how forcing containment can be surprising to developers, but it is the way that [transforms work](https://www.w3.org/TR/css-transforms-1/#containing-block-for-all-descendants) which developers already likely have to deal with. I'm not sure what lead to transforms doing this, and if that rationale is applicable here. Perhaps opacity behaving differently is a good reason we don't need this.

**Comment by khushalsagar** [comment] 2023-02-08 15:41
> I was also concerned that the inconsistency between this behavior (which effectively allows animating transform without containment) where normally any non-none transform forces containment would be confusing for developers. I can understand how forcing containment can be surprising to developers, but it is the way that [transforms work](https://www.w3.org/TR/css-transforms-1/#containing-block-for-all-descendants) which developers already likely have to deal with. I'm not sure what lead to transforms doing this, and if that rationale is applicable here. Perhaps opacity behaving differently is a good reason we don't need this.

[#913](https://github.com/w3c/csswg-drafts/issues/913) has history behind why transforms force a containing block. The short answer is implementation complexity across all engines, effects like `filter` cause the same. A lot of developers have expressed frustration with this decision on the issue. That tells me that if browsers can support this, most developers would prefer option 1. From Blink's perspective, implementation complexity is not a concern because `opacity` establishes a similar pattern.

**Comment by jakearchibald** [comment] 2023-02-09 10:14
@fantasai @tabatkins I need a bit of advice for speccing this. It seems like there isn't consistency when it comes to _where_ to define this. The choices are:

- Option 1: Along with the `view-transition-name` definition (eg "setting this make the element a stacking context")
- Option 2: Along with the layout concept (eg "the following properties are grouping property values… `view-transition-name`)

Taking `opacity` as an example:

- Stacking context: [option 1](https://w3c.github.io/csswg-drafts/css-color/#ref-for-TermStackingContext)
- Grouping element: [option 2](https://w3c.github.io/csswg-drafts/css-transforms-2/#ref-for-propdef-opacity)
- Backdrop root: [option 2](https://drafts.fxtf.org/filter-effects-2/#backdrop-root)

Or, should I just do the same as opacity here, and do both options depending on the effect? In cases I do option 2, I'll add a note to the view transitions spec.

**Comment by jakearchibald** [comment] 2023-03-07 12:06
I'm going to go for option 1 for all three. It can be changed later if needed.

**Closed** 2023-04-19 10:17 UTC
Labels: Needs Edits, css-view-transitions-1
