### ISSUE TITLE
[css-transitions]/[css-animations] Have auto be a valid value for transitions and animations

### ISSUE THREAD

**Issue by SetTrend** [w3c/csswg-drafts#5076] opened 2020-05-17 00:28 UTC
Currently, transitions and animations don't work when either the start or the end value is `auto` (see sample below and [JSFiddle sample](https://jsfiddle.net/0r8o9k1z/2/) for steps to reproduce). But `auto` is a value often required for standard layout.

I propose to have CSS Transitions and Animations explicitly accept `auto` as a valid value for transitions and animation key frames.

Applications are supposed to utilize the _computed value_ of a property declared as `auto` for transitioning and animation.

<hr/>

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Transition-Test</title>

  <style type="text/css">
    body
    {
      font: 12px sans-serif;
      color: #334;
    }

    h1
    {
      font-size: 130%;
    }

    div
    {
      border: 2px solid #caa;
      background-color: antiquewhite;
      padding: 1em;
      margin: 2em auto;
      width: 80%;

      transition: height 1s;
    }

    div:hover
    {
      height: 2em !important;
    }

    div.manual
    {
      height: 1.2em;
    }
  </style>
</head>

<body>
  <h1>Use the mouse pointer to hover over any of the two DIVs below to see the transition effect:</h1>
  <div class="auto">CSS height value: auto</div>
  <div class="manual">CSS height value explicitly set</div>
</body>

</html>
```

**Comment by birtles** [comment] 2020-05-18 03:51
Thank you for filing this. I'm closing it as a duplicate of #626 but please re-open if you disagree.

**Closed by birtles** 2020-05-18 03:51 UTC
