### ISSUE TITLE
[css-contain-3] Container Queries and DOM-APIs like querySelector

### ISSUE THREAD

**Issue by nuxodin** [w3c/csswg-drafts#6215] opened 2021-04-15 15:29 UTC
With the current Syntax, its not possible to query Elements using apis like querySelector.

I might like to use this:
```js
.querySelector(' .card:container(min-width: 450px) ');
```

But the current Syntac does not allow this.   
Or it would look a little unconventional:
```js
.querySelector(' @container (min-width: 450px) {  .card ')
```

**Comment by SebastianZ** [comment] 2021-04-15 20:47
I am wondering what you want to achieve. Selecting an element that is a container isn't different from one that is not a container.
Taking your example you'd just write this to select the first element with the class `card`:

``` js
.querySelector('.card');
```

I guess what you actually want is an API like `Window.matchMedia()` but for containers. This is already covered by #6205.

Sebastian

**Comment by nuxodin** [comment] 2021-04-16 00:25
I want to select not only an element that is a container, but an element with a container that has a minimum width of 450px at the moment.

With a possible `matchConntainer` method, it would be something like:
```js
.querySelector(' .card ').filter( el => el.matchContainer('(min-width: 450px)') );
```

Also, if I understand correctly, nested container queries or container queries on a spezific parent are not feasible.
I just think it would be nicer if the condition were part of the selector.
But it is quite possible that this is not possible because it generates things like loops.

I just wanted to express my thoughts before the syntax is set in stone.

**Comment by bkardell** [comment] 2021-04-30 15:14
I'm not sure about `querySelector` and I don't know if co-opting this issue is worse than opening another (happy to do if anyone agrees), but it does seem worth thinking about what an author of a component might reasonably desire from a scripting standpoint and about how well any proposed solutions matches similar things in the platform. In fact, I was just having some similar thoughts yesterday...

For example, should there be any equivalent to `MediaQueryList` that one could utlize that reported on changes to whatever the applicable container of the element is?  Is there any method one can use to access or determine what the applicable container is at the time of execution ("computedStyle-like")?   etc..

**Comment by lilles** [comment] 2021-04-30 18:44
Making querySelector dependent on layout means it will synchronously need to make layout up-to-date like getBoundingClientRect, offsetWidth, etc. That can be a performance foot-gun of the type that was the reason for introducing APIs like IntersectionObserver and ResizeObserver. If matchContainer() or similar would solve your problem, I think that would be a better way.

**Comment by mirisuzanne** [comment] 2021-06-22 19:50
I'm going to close this as a duplicate of #6205, since it sounds like that's more the direction we'd want to take.

**Closed by mirisuzanne** 2021-06-22 19:50 UTC
Labels: css-contain-3
