### ISSUE TITLE
[css-images-4] Gradients need more than piecewise-linear interpolation

### ISSUE THREAD

**Issue by svgeesus** [w3c/csswg-drafts#4754] opened 2020-02-07 05:50 UTC
@jrus [wrote](https://github.com/w3c/csswg-drafts/issues/4703#issuecomment-582695022):

> If you really want to make a more capable gradient capability, the most useful addition in terms of raw power/flexibility isn’t changing the color space where interpolation happens, but instead adding some facility for non-linear interpolation on each segment. For instance, allowing arbitrary cubic (or even just quadratic) polynomial segments would give the tool dramatically more flexibility for a given number of specified colors, comparable to the difference between polylines vs. Bézier splines for specifying 2D shapes.

**Comment by SelenIT** [comment] 2020-02-07 10:46
Isn't this the same as #1332 (or am I missing something)?

**Comment by tabatkins** [comment] 2020-02-08 00:56
Yeah, closing as a dupe of #1332.

**Closed by tabatkins** 2020-02-08 00:56 UTC
Labels: css-images-4
