### ISSUE TITLE
Deployment of drafts broken?

### ISSUE THREAD

**Issue by Schweinepriester** [w3c/csswg-drafts#7275] opened 2022-05-13 09:36 UTC
Apologies if this is the wrong place or a duplicate (I tried searching, I swear!), but:
Is the deployment of drafts currently broken?

Tried looking up https://drafts.csswg.org/css-color/ but I currently get the index:

![image](https://user-images.githubusercontent.com/2644614/168255450-468d144f-b0e9-4e92-b0d1-278d40f01e22.png)

Even went to [the archive](https://web.archive.org/web/*/https://drafts.csswg.org/css-color/), looks like it was like that on 2022-05-07
https://web.archive.org/web/20220507061245/https://drafts.csswg.org/css-color/
but on 2022-05-05 it was fine
https://web.archive.org/web/20220505175340/https://drafts.csswg.org/css-color/

Additionally the [index of all specifications](https://drafts.csswg.org/) linked in this repos README appears to be empty:
![image](https://user-images.githubusercontent.com/2644614/168256063-90309b90-04e5-4d04-99b1-a4be006554b7.png)

**Comment by SebastianZ** [comment] 2022-05-13 10:44
This is indeed a duplicate of #6528. And unfortunately, it's not the first time this happens.

Sebastian

**Closed** 2022-05-13 10:44 UTC
