### ISSUE TITLE
[css-anchor] Interaction between `anchor-scroll` and `position: sticky` is not well defined

### ISSUE THREAD

**Issue by xiaochengh** [w3c/csswg-drafts#8448] opened 2023-02-13 20:06 UTC
The current spec takes a [snapshotted scroll offset](https://drafts4.csswg.org/css-anchor-1/#snapshotted-scroll-offset) of the anchor element.

When the anchor has `position:sticky` and is stuck, this offset no longer matches the actual offset of the anchor element. Then both `position-fallback` and `anchor-scroll` fail.

Test case (by @jh3y): https://codepen.io/web-dot-dev/pen/dyqbqjE/8b6fc20f812f33ba4920620bb9af3604

---

Edit: there's another case when we have an anchor-scrolled container with sticky positioned content

Test case: https://jsfiddle.net/p7nfqyzw/

The tooltip should be stuck when hitting the top of the viewport, but currently it doesn't.

**Comment by kizu** [comment] 2023-06-01 20:43
Moving a (reworded) part of my comment regarding sticky positioning from https://github.com/w3c/csswg-drafts/issues/8584 here:

Right now, the positions for the anchors do not take into account `position: sticky` when something is in a stuck position.

In practice, there were cases in my experiments where I wanted to use it: the adjusted position of an element with the `position: sticky` for things that should be shown for the stuck element.

Use cases:
- A stuck toolbar/header with items having tooltips/dropdowns attached to buttons inside of it
- Sticky sidebars that could also have things inside that cause anchored popovers to appear.

**Comment by tabatkins** [comment] 2023-06-06 17:12
This should be considered an impl bug, I think. We track the position of relpos things, and stickypos is just a magical relpos, so it should work the same.

**Comment by wangxianzhu** [comment] 2024-02-29 21:30
Chrome CL to support anchor position adjustment with position:sticky has landed: https://chromium-review.googlesource.com/c/chromium/src/+/5297007.

There may also be issues with position:sticky under anchor position, but I haven't created a test case broken on Chrome.

**Comment by tabatkins** [comment] 2024-04-08 22:30
(Closing as a dupe of #9071, which is more general.)

**Closed by tabatkins** 2024-04-08 22:30 UTC
Labels: css-anchor-position-1
