### ISSUE TITLE
[css-shadow-parts] consider moving part-mapping to style rules

### ISSUE THREAD

**Issue by fergald** [w3c/csswg-drafts#2904] opened 2018-07-11 05:17 UTC
This came up in a meeting with Salesforce. It seems reasonable to consider this option.

The current [spec](https://drafts.csswg.org/css-shadow-parts-1/#partmap-attr) provides the partmap attribute to allow a part inside a sub-component to be stylable from outside the containing component. This means that forwarding rules are spread across many elements, e.g.

```
<x-bar>
  # shadow
  <x-foo partmap="inner outer">...</x-foo>
  <x-foo partmap="inner outer">...</x-foo>
  <x-buz partmap="buz-part">...</x-foo>
</x-bar>
```

An possible alternative to that would be to include the part-mapping information in the style rules. There are several ways we could do this e.g.

```
<x-bar>
  # shadow
  <style>
    /* this causes x-bar::part(outer) to match elements inside x-foo */
    x-foo::part(inner) { @outer-name(outer) } 
    /* expose buz-part without renaming */
    x-buz::part(buz-part) { @outer-name() } 
  </style>
  <x-foo>...</x-foo>
  <x-foo>...</x-foo>
</x-bar>
```

Alternative ways of expressing this could be e.g.

```
@partmap myMap::x-foo {
	inner => outer; 
}

x-foo {
    @partmap(inner, outer);
}

x-foo::part(inner) { outer-name: outer } 
```

Good points:
- all mappings are centralized
  - although they may be spread through multiple style elements inside the shadow root, so not necessarily centralized
  - exposing the part name map via IDL is something we want, no matter how it expressed and anyone who wants to reason about the mapping should use that
- can compress many repetitive partmaps into a single CSS rule
- makes it even easier to emulate ::theme using ::part, each shadow tree can just do `::part(theme-name) { @outer-name()}` to expose all the theme-name parts
- could also be used to add part names to elements, e.g. `.some-class { @outer-name(some-part) }` would be the same as adding `part="some-part"` to all of the elements of class "some-class"

Possible objections:
- all mappings are centralized
- these are not style rules, so should not be in the style sheet
- unclear if there are implementation problems with this

This is a fairly radical departure from the current spec and if people think this is a great/terrible idea, I'd like to hear that quickly. I think there's no difference in what can be expressed in either case, the main points are:
- the ability to expressing mappings for many elements in a compact form
- centralized vs distributed

[ Edited by @dbaron to change a file: URL to the https: URL for the spec. ]

**Comment by dbaron** [comment] 2018-07-11 05:32
My initial (and not particularly carefully considered) reaction is that it feels rather complex; it's a good bit of additional syntax both for implementors to implement and for developers to learn.  If the value it provides is worth the complexity, then it seems worth considering, but it's not clear to me whether it is.

**Comment by upsuper** [comment] 2018-07-11 06:08
This seems like proposing to make selector matching depend on cascading result... It's unclear to me whether this setup is going to work.

**Comment by fergald** [comment] 2018-07-11 06:31
@dbaron I think you actually have less custom syntax in some versions of this because it's just selectors and a pseudo-property "outer-name". You've gotten rid of the comma-separated partmap attribute entirely. However you do have some new and maybe unexpected semantics to deal with.

**Comment by idoros** [comment] 2018-07-11 10:20
Hey, we are developing a pre-processor called [Stylable](https://stylable.io), which extends the idea of scoping stylesheets with the ability to expose a "style API" for inner parts & states. Providing a static language server that provides completions and warnings for this kind of style API.

This topic is interesting to me, because although Stylable currently implements scoping by namespacing the output CSS in build time, it could potentially provide the same developer experience for styling Web-Components. and hopefully output CSS that is more similar to the source CSS.

So currently Stylable treats any CSS class as a potential custom pseudo-element (similar to `::part()`):
```css
/* btn.st.css */
.label { color:red; }
```
```css
/* panel.st.css */
:import {
    -st-from: './btn.st.css';
    -st-default: Btn
}
.okBtn {
    -st-extends: Btn; /* give okBtn a Btn interface */
}
.okBtn::label { color:green; } /* access the label */
```
> Notice: Stylable source file contain custom syntax that is transpiled away (like `:import`, `-st-extends` and the access to the custom pseudo-element `::label`).

Which will be transpiled into:
```css
.btn__label { color:red; }
.panel__okBtn .btn__label { color:green; }
```

If css shadow parts will allow defining parts through CSS definition, it would help tools such as Stylable to provide tooling to enhance web components authoring. For example we could output the previous CSS for web components (with the `.some-class { @outer-name(some-part) }` suggestion):

```css
/* btn.st.css */
.label { @outer-name(label) }
```
```css
/* panel.st.css */
.okBtn::part(label) { color:green; }
```

**Comment by caridy** [comment] 2018-07-11 19:19
thanks @fergald for creating the issue. There are few more things from the meeting yesterday that I want to highlight to give more context on why are we proposing this thing:

* ergonomics: creating a new IDL for the `remap` attribute seems very limiting, and also suffered from some of the issues mentioned above, e.g.: users will have to learn that new syntax no matter what.
* perf: it you move the remap info into a CSS, it is probably easier to cache the remapping (speculating here). At least you don't have to worry about the remap attribute reflection and mutation.
* extensibility: in the CSS we have more room for experimentation with the rules (we have quotes, line breaks, etc).
* equivalence: ultimately, users who want to have the remap in the place where they use the element can use the `style` attribute with the remap rules on it. (e.g.: `<x-foo style="::part(inner) { @outer-name(outer) }">...</x-foo>`

Yes, there are some cons:

* you need at least one style blob to do any remapping (I don't think this is a big deal).
* decentralization since the style blob might reference things that are not longer in use by the markup (counter argument is the usage of the `style` attribute)

**Comment by fergald** [comment] 2018-07-17 01:31
@caridy I think your example in 'equivalence" is not correct, style= shouldn't be a selector-declaration pair, it should just be the inside of the declaration. So, it would have to be `<x-foo style="@other-name(outer)">` which is not remapping, it's just naming, so equivalent to `<x-foo part="outer">`. To be able to do the remapping in-place you would need to go with the version where the inner and outer names are included inside the declaration, `<x-foo style="@partmap(inner, outer)">` and when you use it in a stylesheet you select the host element without using ::part(inner).

**Comment by fergald** [comment] 2018-07-17 01:38
If there is ever any future pure-HTML use case for and API like part, for exposing bits of shadow trees in a controlled way, then we should leave it as a purely HTML feature and not bring style sheets into it it.

**Comment by sorvell** [comment] 2018-07-25 00:21
This seems like a pretty powerful alternative to the current spec. It seems like it could be the exclusive way to describe parts. Consider:

```
// Defining Parts
// in x-foo
<style>
  .thumb.active {
    @part(thumb-active);
  }
</style>

// Forwarding Parts
// in x-host that contains an x-foo
<style>
  x-foo::part(thumb-active) {
    @part(x-foo-thumb-active);
  }
</style>
```

This would make it pretty easy to define parts that match complex selectors. For example, this would make it easier to expose parts for the "red" and "black" squares on a checkerboard.

If this is at all feasible to implement it seems worth exploring, at least briefly.

**Comment by fergald** [comment] 2018-08-02 13:54
I'm not sure why this makes IDL expensive, the map is in the stylesheet,
so you mutate it as you would any other rule in the stylesheet. There
wouldn't be a partmap attribute or equivalent IDL.

The implementation is the biggest concern for me. At least in blink it
seems fairly implementable since Blink goes element by element. For each
element it moves up the tree, so as we enter a new scope we would run these
rules first to find out what the current element is named in this scope. It
doesn't seem very hard but it definitely is special, that said you have
have something doing roughly the same thing to apply the partmap as you
move up through scopes. Whether you base it on an explicit map or on
something like this.

**Comment by rniwa** [comment] 2018-08-02 16:06
Manipulating rules is decidedly worse than exposing `part` or `partmap` IDL attribute for developer ergonomics.

This proposal is definitely a lot harder to implement in WebKit than the DOM-based alternative, and it would be quite a bit slower to run.

**Comment by sorvell** [comment] 2018-08-02 17:04
The ergonomics is debatable but I do think the selector based version is more powerful.

However, I also think the attribute based version (which is obviously much father along) makes sense and is workable.

**Comment by justinfagnani** [comment] 2018-08-02 17:33
I'm unsure of implementation costs, but after thinking about it a bit, defining parts in CSS is definitely more powerful, especially with pseudo-classes and elements because you can abstract away the pseudo-class from the outside.

Some examples I thought of:

Defining parts of a checkerboard:

```css
.cell:nth-child(odd) {
  @outer-name(odd-cell);
}
.cell:nth-child(even) {
  @outer-name(even-cell);
}
```

Disabling arbitrary elements and inputs:

```css
:disabled, [disabled] {
  @outer-name(disabled);
}
```

Adding part names for light children and shadow children via ::slotted():

```css
::slotted(.item), .item {
  @outer-name(item);
}
```
(Think of this when combined with display: contents on the host to treat light and shadow children as siblings for flex and grid layouts. It be nice to give a single part name rather than have the outside select the parts and children separately.)


Exposing a pseudo-element like ::before
```css
li::before {
  @outer-name(marker);
  content: counter(li);
}
```

I'm sure there's some other cases where a component wants hover, active, etc states abstracted or styled the same as some other parts.

**Comment by rniwa** [comment] 2018-08-03 09:58
The problem is that the power comes with a cost. Being able to change the presence of a part based on :hover, etc... would mean that we'd have to invent a new mechanism to implement in browser engines. Style invalidation would be a nightmare because now we'd need to first resolve part selectors to see if any part names have changed, then schedule a secondary path to actually invalidate elements, etc...

**Comment by idoros** [comment] 2018-08-03 11:19
What about simplifying it to work only for classes or ids?

**Comment by rniwa** [comment] 2018-08-03 22:18
If we did that, what's the point of doing this in CSS? Also, we'd still have to keep matching those IDs & classes to find out if any given element defines a part or not.

Here's another problem. If we did this in CSS, I bet my money on someone coming around and asking for a DOM event whenever the presence of a part changes (i.e. appears / disappears). We won't be able to implement that because it would basically involve browser engines constantly evaluating CSS selectors which define parts to decide whether any given DOM mutation should result in the firing of such an event.

**Comment by idoros** [comment] 2018-08-05 09:30
> what's the point of doing this in CSS?

I wrote my case above. Not having the ability to define the parts in CSS, means that my users will have to maintain a more complicated source, or compromise on custom run-time code in order to support web components.

> we'd still have to keep matching those IDs & classes to find out if any given element defines a part or not.

I agree, this is another level of abstraction between CSS an DOM.

> Here's another problem. If we did this in CSS, I bet my money on someone coming around and asking for a DOM event whenever the presence of a part changes (i.e. appears / disappears).

I don't know the implementation internals that you are, obviously, aware of, but I think that there are lots of use cases where allowing the developer to hook into changes in the CSS with JavaScript will improve the way we build web applications today. 

also:
 - Wouldn't such a request might already be raised for components wanting to know when a composed component changed it's parts?
 - Isn't this already the case with `animationstart` and `transitionstart `? 

-----

That being said, I accept that you have more knowledge of the implementation risks. And if this is an implementation / performance issue, then it's beyond my current understanding. However, API-wise, I still think having the parts definitions as part of the style, which is also the context in which a developer targets these parts, is better.

**Comment by tabatkins** [comment] 2018-08-06 19:14
We're generally fine with dropping this idea. Vast majority of part mappings will be static and thus easily inlineable in the first place; the tiny fraction that aren't can be done with mutation observers or some other state-tracking.  On the other hand, Ryosuke's speed concerns are definitely legitimate, plus weirdness like making slot-ness depend on a `:hover` rule or something.

So, closing.

**Closed by tabatkins** 2018-08-06 19:14 UTC
Labels: css-shadow-parts-1, topic: shadow
