### ISSUE TITLE
[css-color] gray(<number>) or gray(<percent>)

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#872] opened 2017-01-09 12:47 UTC
The [spec](https://drafts.csswg.org/css-color-4/#grays) defines `gray()` as taking a number argument, but the prose around it shows it being used with a percentage.

**Comment by Crissov** [comment] 2017-01-09 16:36
Duplicate of #635.

**Closed** 2017-01-10 08:10 UTC
Labels: css-color-4
