### ISSUE TITLE
[css-conditional-4] Specific font families?

### ISSUE THREAD

**Issue by ShaneHudson** [w3c/csswg-drafts#2139] opened 2017-12-27 20:45 UTC
Would it be feasible to add the ability to use `@supports` for checking if particular font-families available?

For instance something like:

```
@supports (font-family: georgia) {
    body {
        font-size: 1.1em;
    }
}
```
The main use-case for this would be improving (and indeed testing, by misspelling) typography for fallbacks. This is especially useful for fonts that have very different sizes by default, in which changing the font could make the layout look odd. This could also be useful if the fallback font is showing while a webfont is being loaded.

**Comment by upsuper** [comment] 2017-12-27 23:16
1. You cannot reuse `font-family: georgia` like that, because that has been defined as doing only parsing. You may need function syntax, e.g. `font-family(georgia)` or something like that, which is currently reserved for future extension.
2. I don't think we can add this, because it would become an easy fingerprinting vector. I'm not sure whether it is any worse than current situation, e.g. via canvas, though.

For the use-case that fonts may have different sizes, you can probably try [`font-size-adjust` property](https://developer.mozilla.org/en-US/docs/Web/CSS/font-size-adjust) which was designed to address this issue.

**Comment by Nadya678** [comment] 2017-12-28 07:58
Yes, it is big impact for privacy of users. Please do not add it.
But: 
still there may be in hidden `<div/>` set "font-family:georgia, self-defined font" and with JavaScript readed height of content/element and thus impact for privacy for fingerprint the browser. but... only with enabled JS. It means: also selectors like `@element div and (max-height:40px)` shall be forbidden if will be proposed.

**Comment by svgeesus** [comment] 2021-12-03 18:25
This is related to https://github.com/w3c/csswg-drafts/issues/4497

See also the [Privacy section in CSS Fonts 4](https://drafts.csswg.org/css-fonts-4/#sp201):

> An attacker may obtain fingerprinting information by querying the Installed Fonts. In contrast to older technologies (notably Adobe Flash, which provided a complete list of Installed Fonts and sent this information in HTTP headers) such probing must be done one font at a time, providing the font family name and then checking (either via script, or by using unicode-range to selectively download webfonts depending on whether the user has a font by a certain name that supports a certain character) whether the font was loaded. This takes time, and checking for more than a few hundred fonts introduces a noticeable delay in page rendering.

**Comment by svgeesus** [comment] 2021-12-03 18:27
Closing because adding a fast, Flash-like way to test for thousands of installed fonts as a fingerprinting vector is the last thing we want to do.

**Comment by svgeesus** [comment] 2021-12-03 18:28
(Adding privacy tracker just so PING know we won't be doing this)

**Closed by svgeesus** 2021-12-03 18:27 UTC
Labels: Closed Rejected as Wontfix by Editor Discretion, css-conditional-4
