### ISSUE TITLE
[css-flexbox] Should fully inflexible item have definite height even with min-height: auto?

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#4305] opened 2019-09-13 17:55 UTC
https://drafts.csswg.org/css-flexbox/#definite-sizes says:
> Note: The main size of a fully inflexible item with a definite flex basis is, by definition, definite.

However, with min-height: auto, such an item may well require layout to determine its size (in a column flexbox where the item has `height: auto; flex: 0 0 100px;`). Should its size still be considered definite?

cc @dholbert  @fantasai  @tabatkins

**Comment by tabatkins** [comment] 2021-06-10 18:54
Test case demonstrating the behavior: http://software.hixie.ch/utilities/js/live-dom-viewer/saved/9405

```html
<!DOCTYPE html>
<div style="display: flex; flex-flow: column; border: thick dotted; height: 150px;">
  <span style="border: thick solid; flex: 0 0 1em;">
   <div style="float: right; height: 50%; background: orange;">foo</div>
   foo<br>foo<br>foo<br>foo<br>foo<br>foo
  </span>
</div>
```

The % on the float does resolve against the height of the flex item, despite that height being boosted by the min-height:auto specifically.

**Comment by davidsgrogan** [comment] 2021-06-10 22:27
Not cbiesinger, but still confused :)

1. Blink has a bug where it doesn't respect the normative text [fantasai quoted above](https://github.com/w3c/csswg-drafts/issues/4305#issuecomment-858905404) in a [case](http://software.hixie.ch/utilities/js/live-dom-viewer/?saved=9407) similar to Tab's, where the flexbox's height is auto instead of 150px. Blink makes the orange float's % height behave as auto, but the normative text says the % must be resolved. Firefox does the right thing. (I'm not making a point here just FYI if anyone has come across this case.)

2. I don't see where the behavior described in the [Note above](https://github.com/w3c/csswg-drafts/issues/4305#issue-493448057) is implied by normative text. In the case below, the row flexbox qualifies for the Note, which claims the row flexbox's height is definite. But where does that definiteness come from? The definiteness matters apart from resolving percentages because it decides if the inner flexbox's children qualify for [9.8.1](https://drafts.csswg.org/css-flexbox/#definite-sizes).

```html
<!DOCTYPE html>
<div style="display: flex; flex-flow: column; border: thick dotted;">
  <div style="display: flex; flex: 0 0 10px; border: 2px dotted blue;" id=should-my-children-stretch-to-my-definite-height>
    <...some flex items...>
  </div>
</div>
```

**Comment by tabatkins** [comment] 2021-08-12 18:21
Closing since #4311 was closed, and is a dupe of this issue.

**Closed** 2021-08-12 18:20 UTC
Labels: css-flexbox-1, Commenter Response Pending, Closed as Question Answered

**Comment by cbiesinger** [comment] 2021-08-12 22:33
Not technically a dupe but that resolution does resolve this one, thanks
