### ISSUE TITLE
[css-fonts] font-feature-settings property should be reset by font shorthand

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1349] opened 2017-05-11 07:26 UTC
Given that subproperties of `font-variant` are all reset by `font` shorthand, I think it's pretty apparently `font-feature-settings` should be as well. It makes no sense to apply the same set of settings when the font is changed.

**Comment by upsuper** [comment] 2017-05-11 07:27
(I tried to do the edit myself for this and #1032 but I failed... I don't know how to generate `Fonts.html` from `Fonts.src.html`. It seems `bikeshed` doesn't work very well...)

**Comment by dbaron** [comment] 2017-05-13 18:19
I believe the fonts spec is still generated using Bert's preprocessor because bikeshed doesn't understand descriptors vs. properties with the same name.

It's also worth noting that Gecko has [always implemented](https://hg.mozilla.org/mozilla-central/rev/0f7bc3357bc3d24d1f325c945a8d7b929c0a9b53) it this way -- `font-feature-settings` has been a subproperty of `font`.

**Comment by svgeesus** [comment] 2017-05-13 18:46
Yes, Fonts 3 uses the old pre-bikeshed processor (I think only this spec and CSS 2.2 or whatever wer are calling it this week still use the old preprocessor).
Fonts 4 uses bikeshed, and seems to have both descriptors and properties, in many cases with the same names.
https://drafts.csswg.org/css-fonts-4/#property-index
https://drafts.csswg.org/css-fonts-4/#font-face-descriptor-table

I agree that font-feature-settings should be reset by the font shorthand.

**Comment by xfq** [comment] 2017-05-14 02:37
Just FYI - the conversion of css-fonts-3 is tracked in #234.

**Comment by upsuper** [comment] 2017-05-24 03:19
Also the new property "font-variation-settings" in CSS Fonts 4 should be reset by font shorthand as well, I believe.

**Comment by litherum** [comment] 2017-07-09 00:47
If we're going to do `font-feature-settings`, we should also do `font-variation-settings`.

**Comment by litherum** [comment] 2017-07-21 22:43
According to https://github.com/w3c/csswg-drafts/issues/1636#issuecomment-317127312, Gecko is the only engine on macOS which sets this. If someone has access to a Windows machine, data about Edge would be appreciated. (There is an .html test file attached to that issue.)

**Comment by litherum** [comment] 2017-08-03 09:01
Adding to F2F [agenda](https://wiki.csswg.org/planning/paris-2017?&#topics), so removing Agenda+

**Comment by tabatkins** [comment] 2017-08-03 12:53
> I believe the fonts spec is still generated using Bert's preprocessor because bikeshed doesn't understand descriptors vs. properties with the same name.

No, it understands them just fine.  You do have to be more explicit about autolinking, so it knows whether you're referring to the property or the descriptor.

(The old preprocessor doesn't complain, it just silently links all of them to a single arbitrarily-chosen definition. In other words, it's wrong for a lot of the links.)

**Comment by litherum** [comment] 2017-08-03 14:09
Duplicate of https://github.com/w3c/csswg-drafts/issues/1636

**Closed by litherum** 2017-08-03 14:09 UTC
Labels: Agenda+, css-fonts-3, css-fonts-4, Needs Edits
