### ISSUE TITLE
[css-nesting-1] Yet another nesting proposal (Option 5)

### ISSUE THREAD

**Issue by plinss** [w3c/csswg-drafts#7970] opened 2022-10-27 19:51 UTC
The fundamental problem with allowing nested style rules is disambiguating properties from nested rules.

So far, every proposal has focused on taking a regular style rule and creating a syntax to identify selectors within it. What if we turned that around?

My proposal is to have an at-rule that has a selector, and contains nothing but style rules (and other at-rules), whose selectors are relative to the at-rule. We can then have a special block within the at-rule to hold properties that apply to the nesting root,

E.g.
```
@nest foo {
    & { color: blue; }
    bar { color: red; }
}
```
would be equivalent to:
```
foo { color: blue; }
foo bar { color: red; }
```

You could also, of course nest the at-rules:
```
@nest foo {
    & { color: blue; }
    @nest bar {
        & { color: red; }
        baz { color: green; }
    }
}
```
would be equivalent to:
```
foo { color: blue; }
foo bar { color: red; }
foo bar baz { color: green; }
```

It may also be possible to omit the `&` and just use a bare `{}` block within the at-rule to hold properties.

This requires no changes to existing parsing, OM, or behavioral rules and has a straightforward OM for the new at-rule.

**Comment by Loirooriol** [comment] 2022-10-27 20:19
I like the cleanness of this proposal, but I think it can be a bit annoying when you start styling an element

```css
foo {
  color: blue;
}
```

And then realize you also want to style the descendants, so you have to refactor it all. With other proposals the change is simpler:


<table>
<tr>
<th>
This
</th>
<th>
Proposals 1 & 3
</th>
<th>
Proposal 4
</th>
</tr>

<tr>
<td>

```diff
-foo {
-  color: blue;
-}
+@nest foo {
+  & {
+    color: blue;
+  }
+  & bar {
+    color: red;
+  }
+}
```

</td>
<td>

```diff
 foo {
   color: blue;
+  & bar {
+    color: red;
+  }
 }
```

</td>
<td>

```diff
 foo {
   color: blue;
+} {
+  & bar {
+    color: red;
+  }
 }
```

</td>
</tr>
</table>

**Comment by plinss** [comment] 2022-10-27 20:31
I think the refactoring is fairly minimal, you're just prepending `@nest` to the original selector and wrapping the exiting properties in `{}`s. The diff is making the changes appear to be more than they are.

I do have to note that your example is slightly wrong:
It's not:
```diff
+@nest foo {
+  & {
+    color: blue;
+  }
+  & bar {
+    color: red;
+  }
+}
```
but:
```diff
+@nest foo {
+  & {
+    color: blue;
+  }
+  bar {
+    color: red;
+  }
+}
```
(note no `&` on the nested rule).

The basic gist is that instead of a style rule that expects properties, we're minting a new kind of style rule that expects nested selectors. And then providing a carve-out for properties.

**Comment by Loirooriol** [comment] 2022-10-27 20:49
Just noting it's still a less local change, since probably the cursor is at the end of the declarations, and then you have to go back to the selector, select all the declarations to indent them, etc. Not a big problem but it's an annoyance for me.

> note no `&` on the nested rule

Even if optional, I hope `&` is still allowed?

**Comment by plinss** [comment] 2022-10-27 21:06
> Even if optional, I hope & is still allowed?

No, not on a nested rule. The `&` in this proposal indicates that the following block is a collection of style properties that apply to the selector on the at-rule (and we could do this without the `&` entirely, in which case I wouldn't allow it as optional even there).

As I said, by default, everything inside a `@nest` is a style rule relative to the selector on the rule itself.

My original thought was to not even allow properties inside at all, e.g.:
```
foo {
  color: blue;
}
@nest foo {
  bar { color: red; }
}
```
but having to repeat the first selector seemed an unnecessary redundancy. 

The main issue with all the other proposals is that style rules expect properties, and the syntax for properties has way too many collisions with selectors, so a carve-out for allowing selectors gets cumbersome. 

This proposal makes a new kind of style rule that expects nested style rules, the carve-out is to allow properties within a limited scope.

Another detail that I didn't mention originally, by default there's an ancestor combinator between the `@nest` selector and nested selectors. There's no reason that the `@nest` selector couldn't end with a combinator, or the nested rules could start with a combinator (probably not both tho).

E.g.:
```
@nest foo > {
   bar { ... }
   baz { ... }
}
```
would be equivalent to:
```
foo > bar { ... }
foo > baz { ... }
```
and
```
@nest foo {
  > bar { ... }
  + baz { ... }
}
```
would be equivalent to:
```
foo > bar { ... }
foo + baz { ... }
```

**Comment by Loirooriol** [comment] 2022-10-27 21:12
Why disallow `&` to express complex relationships? I want to be able to use these:

```css
@nest foo {
    &:hover { color: blue; }
    bar + & { color: red }
    & + & { color: green }
}
```

**Comment by tabatkins** [comment] 2022-10-27 21:15
> the syntax for properties has way too many collisions with selectors, so a carve-out for allowing selectors gets cumbersome.

Note: it has *one* collision with selectors. The carve-out to avoid the ambiguity is rather simple, as Option 3 has shown.

> No, [& is not allowed] on a nested rule. 

It must be allowed, to hit a number of important use-cases, namely the `&:hover` and `.parent &` ones. Making it purely a suffix to the parent with a combinator between them is too limited.

----

But yeah, generally I agree with Oriol. This is a relatively invasive change to add nesting to an existing style rule. It continues to require non-local edits in deeper nesting, too, going from:

```css
@nest foo {
  bar {color: red;}
}
```

to 

```css
@nest foo {
 @nest bar {
   & { color: red; }
   baz { color: green; }
  }
}
```

**Comment by plinss** [comment] 2022-11-26 20:31
Ok, in my original thinking `&` in this proposal would only be used to denote a rule matching the selector in the `@nest` rule, but I can see the use cases for allowing it in other nested rules, especially for the pseudo-element usage.

So we can allow the `&` to appear (zero or one times) in any nested rule. If not present, it defaults to being at the front with a space combinator.

I disagree with the added indenting being a problem however, all modern code editors can indent and un-indent blocks with a single keystroke, and any decent diff tool will also clearly show changes as being whitespace-only. I don't see this a burden on developers (in fact, showing that something is now the root of a nesting context in a diff may actually be useful). I still think this proposal deserves consideration as it neatly side-steps all the other issues with the other nesting proposals.

**Comment by romainmenke** [comment] 2022-11-30 19:11
>  do we have a path forward to organize non-biased survey

I think the bigger issue is author preconception.
The last survey result was basically : "we want what we have in Sass or as close to that as possible" The option that best fit that description was option 1 in that survey.

@LeaVerou's Twitter polls again confirmed that authors want nesting to be as terse and relaxed as possible.

If the concern is to pick the right syntax for the future regardless of what preprocessors have done in the past then I don't think another author survey will be helpful. Authors will pick proposal 3. I don't think it is possible to design a survey for todays authors that will have a different outcome.

----

I personally would be fine with proposal 1, 3 or even 5.
But I am part of the minority that likes to read/write `&` and `@nest`.

**Comment by mirisuzanne** [comment] 2022-11-30 21:02
I think @romainmenke is very likely right about predicting the poll result. But I guess we'll see. 

I very much appreciate having various alternative proposals to consider, and have backed several of them at this point. But I disagree with the premise mentioned a few times that some proposals are more 'programmer focused' while others are more appropriate for a broad CSS audience. So far all the seriously-considered proposals have been designed around CSS syntax, and they have all involved awkward tradeoffs that authors will need to get used to. This isn't a philosophical debate about the soul of CSS, it's a practical debate about how to make nesting work around some inconvenient parsing limitations.

Anyway, I want to follow-up a little on my mention of `@scope` on the call. I said I wasn't sure if that's a pro or a con for this proposal, but I don't think that's actually the right framing. More important than that, it brings into clearer focus how these features overlap, and where they differ. That's a pro for the discussion, no matter where we land.

## The overlap between `@scope` and `@nest` (version 5)

Like I said, the outline of this proposal (v5!) has a nearly identical footprint to the `@scope` feature as specified. These would select exactly the same elements:

```css
@nest foo {
    & { color: blue; }
    bar { color: red; }
}

@scope (foo) {
    & { color: blue; }
    bar { color: red; }
}
```

## The differences

There's only one difference between the selectors above, and that's _scope proximity_ - which gives some cascade priority to scoped selectors that have a 'closer' scope root. It's not clear at this point _how much_ of a difference that creates, because the spec is currently indecisive on _how much priority_ scope proximity should have (@fantasai and I drafted the spec, and we disagree on that point). From my perspective a _weak scope proximity_ (weaker than specificity in the cascade) would be a _desirable_ addition to nesting. The difference is subtle, but meaningful to authors. If we went that rout, the two features have a very large overlap.

But it's not a complete overlap, as we can see by looking at one of the other demos in the original post. The `@scope` rule _only targets elements that are inside the scope root_ (inclusive of the root element itself). So any nested rules that aren't truly nested may be an issue:

```css
@nest foo {
  + baz { /* sibling selector should work here, and match foo + baz */ }
}

@scope (foo) {
  + baz { /* since baz is a sibling of the scope root, it is outside the scope and not matched */ }
}
```

That's a pretty big distinction.

## Can we disentangle these features?

It seems to me like:

- In most (all?) cases where you want to select a truly nested element, `@scope` might be the better alternative. That's exactly what it's designed for.
- Most (but sadly not all) of the problematic edge cases for other nesting proposals fall into that category.

These problem cases for proposal 3 can all be represented in `@scope` without issues - because they target elements that are in scope:

```css
foo {
  baz { /*…*/ }
  html & { /*…*/ }
  baz + & { /*…*/ }
}

@scope (foo) {
  baz { /*…*/ }
  html & { /*…*/ }
  baz + & { /*…*/ }
}
```

My thesis here is roughly that `@scope` would help _limit the frequency_ of problematic use-cases. And it will do that in a way that matches this proposal pretty closely. 

Sadly for my thesis, it's not quite _all_ the problematic cases. These can't be converted to scope, because the targets are not nested:

```css
foo {
  baz:has(&) { /*…*/ }
  baz > & + bing { /*…*/ }
}
```

I don't feel like that's a conclusive argument. But, I think the main takeaway here is that we need to keep thinking of these features as intertwined. Specifically, the implementation of scope might change what people need or want from nesting.

**Comment by plinss** [comment] 2022-11-30 21:29
One other advantage to this proposal, `@nest` is something that authors can enter into a search engine when they encounter it in the wild for the first time. (It also provides context to figure it out on their own.)

An author seeing:
```css
foo {
  color: red;
  & bar { color: blue; }
}
```
or
```css
foo {
  color: red:
} {
  bar { color: blue; }
}
```
has no keywords any search engine is going to provide reasonable results for (and no obvious indication that nesting is happening, either could be interpreted as typos).

**Comment by LeaVerou** [comment] 2022-12-01 00:34
As an author, I would be strongly against something that requires me to create a whole separate rule like that. Part of the benefit of nesting is organizing my code into portable "chunks", so I can copy a rule and have all the CSS needed for a "component". It seems that option 5 breaks this, unless I'm missing how exactly it's supposed to be used.

**Comment by LeaVerou** [comment] 2022-12-01 00:36
> One other advantage to this proposal, `@nest` is something that authors can enter into a search engine when they encounter it in the wild for the first time. (It also provides context to figure it out on their own.)
> 
> An author seeing:
> [snip]
> has no keywords any search engine is going to provide reasonable results for (and no obvious indication that nesting is happening, either could be interpreted as typos).

CSS is full of symbols that have the same issue: `#id`, `.class`, `[foo]` etc
Also, googling "ampersand css" would probably work fine (as evidenced by the [current results](https://www.google.com/search?q=ampersand+css) which are about nesting in preprocessors).

**Comment by plinss** [comment] 2022-12-01 01:42
> As an author, I would be strongly against something that requires me to create a whole separate rule like that. Part of the benefit of nesting is organizing my code into portable "chunks", so I can copy a rule and have all the CSS needed for a "component". It seems that option 5 breaks this, unless I'm missing how exactly it's supposed to be used.

I don't understand your point here at all. All the CSS for a "component" is within the @nest rule and it can be copied as a whole. If anything, by not requiring `&` everywhere you're making your CSS more copyable and usable in other contexts. Can you give an example of what you';re concerned about? (and how that would be different from the other proposals)

**Comment by plinss** [comment] 2022-12-01 01:46
> CSS is full of symbols that have the same issue: #id, .class, [foo] etc

Doesn't mean we're doing people any favors by adding more... (in fact, there's even a TAG [design principle](https://w3ctag.github.io/design-principles/#leave-the-web-better) about this  :-)

Another point, how would proposals 3 & 4 be [feature detectable](https://w3ctag.github.io/design-principles/#feature-detect)? (I accept it can likely be done, but in an obvious way?)

**Comment by LeaVerou** [comment] 2022-12-01 01:49
> > CSS is full of symbols that have the same issue: #id, .class, [foo] etc
> 
> Doesn't mean we're doing people any favors by adding more... (in fact, there's even a TAG [design principle](https://w3ctag.github.io/design-principles/#leave-the-web-better) about this :-)

My point wasn't "there is precedent for this bad thing and thus it's fine", it was "CSS already does this and authors don't seem to have any trouble googling things". So I don't think the TAG principle you linked applies here. Learnability is one component of usability, efficiency is another, equally important one. For commonly typed things, brevity becomes more important than learnability.

> Another point, how would proposals 3 & 4 be [feature detectable](https://w3ctag.github.io/design-principles/#feature-detect)? (I accept it can likely be done, but in an obvious way?)

`@supports selector(&)`?

**Comment by plinss** [comment] 2022-12-01 02:36
> My point wasn't "there is precedent for this bad thing and thus it's fine", it was "CSS already does this and authors don't seem to have any trouble googling things". So I don't think the TAG principle you linked applies here. Learnability is one component of usability, efficiency is another, equally important one. For commonly typed things, brevity becomes more important than learnability.

CSS has rejected other uses of sigils in the past for precisely the searchability issue, and it's not necessarily obvious to an author to search for 'ampersand' instead of `&`. Brevity can be taken too far (see YAML), it is a tradeoff, but not an obvious one. And given that `@nest` mostly doesn't require the `&` it can easily result in less typing if there are enough nested rules, so proposal 3 doesn't necessarily win on brevity.

> @supports selector(&)?

Maybe, but seems fragile, what if there are other places `&` can be used? (and is it *really* a selector?)

**Comment by LeaVerou** [comment] 2022-12-01 04:02
> CSS has rejected other uses of sigils in the past for precisely the searchability issue, and it's not necessarily obvious to an author to search for 'ampersand' instead of `&`. Brevity can be taken too far (see YAML), it is a tradeoff, but not an obvious one. And given that `@nest` mostly doesn't require the `&` it can easily result in less typing if there are enough nested rules, so proposal 3 doesn't necessarily win on brevity.

Yes, because to use a symbol, the feature needs to be needed frequently enough that brevity is important. This is not true for every feature, but it certainly is for nesting.

> > @supports selector(&)?
> 
> Maybe, but seems fragile, what if there are other places `&` can be used?

Other places …in a selector?

> (and is it _really_ a selector?)

Yes, it is. Really.

**Comment by plinss** [comment] 2022-12-01 05:04
> Yes, because to use a symbol, the feature needs to be needed frequently enough that brevity is important. This is not true for every feature, but it certainly is for nesting.

And in this proposal, even the `&` is not going to be needed that often (zero characters wins for brevity every time). The enclosing `@nest` will likely not get repeated enough to justify its removal/replacement.

> Other places …in a selector?

Yes, in principle it could be used in a selector in some context that isn't nesting. We have a limited number of ascii-friendly sigils to use and may need to repurpose it at some point. If the need is to detect the feature of nesting (or the other theoretical usage), it may not be enough to disambiguate. Being able to detect an actual at-rule is more specific, and more obvious.

You also still never explained your initial objection about having to create a "whole separate rule" and the perceived componentization issue.

**Comment by bramus** [comment] 2022-12-01 06:28
Below is a slightly altered version of [this example from the spec](https://drafts.csswg.org/css-nesting-1/#example-df188c81) _(the difference being `table.colortable td .c` instead of `table.colortable td.c`)_:

```css
table.colortable td {
  text-align:center;
}
table.colortable td .c {
  text-transform:uppercase;
}
table.colortable td:first-child, table.colortable td:first-child+td {
  border:1px solid black;
}
table.colortable th {
  text-align:center;
  background:black;
  color:white;
}
```

Converted to syntax 5 it –if I’m interpreting things correctly here– becomes this:

```css
@nest table.colortable {
    @nest td {
        & {
            text-align: center;
        }
        .c {
            text-transform: uppercase;
        }
        &:first-child,
        &:first-child + td {
            border: 1px solid black;
        }
    }
    @nest th {
        & {
            text-align: center;
            background: black;
            color: white;
        }
    }
}
```

Actions that were needed:
- I need to prepend `@nest` to parent selectors to enable nesting upon adding a nested selector. This moves my focus away from the original code I pasted in.
- In the existing ruleset, I need to take the existing declarations and wrap them inside a `& { }` upon adding a nested selector.
- To add components to the parent selector, I need to prepend `&`

While doing this:
- I found myself jumping around the code quite  a bit, which is not something I liked.
- I didn’t find this to be highly copy-paste friendly. When I copy a ruleset from somewhere else in my stylesheet to target a child element of `table.colortable  td .c`, I need to make the first two of the three changes listed above:

  ```css
  @nest table.colortable {
      @nest td {
          & {
              text-align: center;
          }
          @nest .c {
             & {
                text-transform: uppercase;
             }
             span {
                color: hotpink;
             }
          }
          &:first-child,
          &:first-child + td {
              border: 1px solid black;
          }
      }
      @nest th {
          & {
              text-align: center;
              background: black;
              color: white;
          }
      }
  }
  ```

Furthermore, with this fifth proposal, I noticed:
- Declarations are sometimes in a `& { }` block and sometimes not. This is not consistent.
- Selectors are sometimes prefixed with `@nest` and sometimes not. This feels redundant, as the intent to nest was already there when I pasted in the nested ruleset.

Comparing this to proposal 3:
- There I can paste it my copied content, and _maybe_ need to add an `& `, depending on the selector.
    - Furthermore: as there’s no harm in always adding the `& `, I don’t really need to worry about this _maybe_ and can simply always add it if I wanted.
- Declarations are consistent, as long as they come first.

```css
table.colortable {
    & td {
        text-align: center;
        .c {
            text-transform: uppercase;
            & span {
              color: hotpink;
           }
        }
        &:first-child,
        &:first-child + td {
            border: 1px solid black;
        }
    }
    & th {
        text-align: center;
        background: black;
        color: white;
    }
}
```

This last code example –using proposal 3– is imo much more consistent than the proposal 5 version.

**Comment by plinss** [comment] 2022-12-01 06:57
A few corrections:
1) all of the `&`s in your example except for `&:first-child` are unnecessary, legal, but they are the default behavior.
2) the last `@nest th { {` is also legal, but completely unnecessary. That could simply be `th { text-align: ...}

Remember, in this proposal `@nest` the the thing that contains nested rules, not a nested rule itself (unless it's a second level of nesting).

So it's actually:
```css
@nest table.colortable {
    @nest td {
        {
            text-align: center;
        }
        .c {
            text-transform: uppercase;
        }
        &:first-child,
        &:first-child + td {
            border: 1px solid black;
        }
    }
    th {
        text-align: center;
        background: black;
        color: white;
    }
}```

**Comment by bramus** [comment] 2022-12-01 11:29
> A few corrections

Thanks for clarifyin. Updated the code to remove the unnecessary `@nest`. Kept the `& { }` though, but added a note that the `&` itself can be removed.

**Comment by LeaVerou** [comment] 2022-12-01 19:39
> > Yes, because to use a symbol, the feature needs to be needed frequently enough that brevity is important. This is not true for every feature, but it certainly is for nesting.
> 
> And in this proposal, even the `&` is not going to be needed that often (zero characters wins for brevity every time). The enclosing `@nest` will likely not get repeated enough to justify its removal/replacement.

In option 3, which is the current state of the spec, `&` will still be needed pretty often. It's common to style descendant element selectors.

> > Other places …in a selector?
> 
> Yes, in principle it could be used in a selector in some context that isn't nesting. We have a limited number of ascii-friendly sigils to use and may need to repurpose it at some point. If the need is to detect the feature of nesting (or the other theoretical usage), it may not be enough to disambiguate. Being able to detect an actual at-rule is more specific, and more obvious.

I still don't understand what problem you are seeing. You think browsers will implement `&` in selectors, *without* implementing Nesting, and we need a way to distinguish the two?

> You also still never explained your initial objection about having to create a "whole separate rule" and the perceived componentization issue.

Copying two rules (two sets of `{...}`) is more error-prone than copying one and feels more scattered.

**Comment by astearns** [comment] 2022-12-05 05:21
I think option 5 has an issue with progressive enhancement. 

With options 3 and 4 I can write rules for the nesting root, then add on a nesting block. Then, for browsers that do not support nesting I have to repeat the nesting block in an `@supports not ???` rule (where ??? is whatever syntax we choose for detecting nesting). 

But with option 5 I have to repeat both the nesting root and the nesting block in my `@supports not ???` rule, because older browsers will ignore the `@nest` rule entirely.

Not a big issue long-term, but annoying for the transition.

**Comment by plinss** [comment] 2022-12-05 05:59
Yes, you'd have to repeat the outer rule.

But, the point of nesting is to make the stylesheet smaller and more maintainable. It completely defeats the purpose to have an `@supports` block in the same stylesheet to also include non-nested versions. With any of the proposals, the best way to support older browsers is to write your stylesheet with nesting, and then use a pre-processor to generate a non-nested version, then use the `@supports` mechanism to import either the more modern or the older (and larger) stylesheet when necessary.

**Comment by vrubleg** [comment] 2022-12-05 18:12
Instead of `@nest selector { ... }`, a bit shorter `selector {{ ... }}` could be used for the same purpose.

**Comment by plinss** [comment] 2022-12-05 18:51
Unfortunately that would require arbitrary lookahead during parsing.

It also gets weird when one of the legal contents is a style rule without a selector, so you'd get:
```css
selector {{{ color: red; } selector { color: blue; }}}
```
Not sure that helps readability, maintainability, or searchabilty.

**Comment by vrubleg** [comment] 2022-12-05 19:35
> Unfortunately that would require arbitrary lookahead during parsing.

If a parser encountered `{{`, it means that it is a nested block. `{{{` should be illegal.

```
selector {{
    & { /* properties */ }
    /* nested rules */
}}
```
This should be used instead if required.

**Comment by plinss** [comment] 2022-12-05 20:43
> {{ and }} shouldn't allow spaces inside double braces. If a parser encountered {{, it means that it is a nested block.

1) That doesn't remove the lookahead, the parser can't tell if it's parsing a regular style rule or a nesting container until it finds the `{{`. They are completely different objects in the OM so the parser needs to know ASAP. The selector can be arbitrarily long (and even have multiple selectors separated by `,`s), current CSS parsers don't require more than a handful of token lookaheads and we try to not add more, especially an arbitrary amount.
2) That effectively introduces `{{` and `}}` as new sigils, either through a parsing change or a one-off rule.

> {{{ should not be allowed.

Why not? The `&` is optional, requiring a space after the opening `{{` is arbitrary. We generally don't require specific formatting in CSS. This is just introducing more arbitrary rules that authors will have to learn. One of the main points of this proposal is to remove those as found in the other proposals. Another is to avoid parser changes. Yet another is to make the feature obvious and searchable.

You're adding a bunch of complexity and author pain to save 4 characters.

**Comment by sesse** [comment] 2022-12-06 09:19
> One other advantage to this proposal, `@nest` is something that authors can enter into a search engine when they encounter it in the wild for the first time.

If you search for “& css”, the first top hits are about CSS nesting (in SASS).

**Comment by sesse** [comment] 2022-12-06 09:43
> 1. That doesn't remove the lookahead, the parser can't tell if it's parsing a regular style rule or a nesting container until it finds the `{{`. They are completely different objects in the OM so the parser needs to know ASAP.

FWIW, despite everything that I don't like about this proposal, lookahead wouldn't be a problem for Blink here from what I can see. We know we're parsing a selector, so we don't have to backtrack when we see the `{{` (we just have to use the selector for “something else” instead of a regular style rule).

**Comment by fantasai** [comment] 2023-01-10 19:23
Closing as WONTFIX by CSSWG resolution [see minutes](https://lists.w3.org/Archives/Public/www-style/2022Dec/0015.html)

**Closed by fantasai** 2023-01-10 19:23 UTC
Labels: css-nesting-1
