### ISSUE TITLE
[css-sizing-4] Should we mention aspect-ratio in margin collapsing?

### ISSUE THREAD

**Issue by BorisChiou** [w3c/csswg-drafts#5328] opened 2020-07-15 23:31 UTC
Based on the [spec definition of margin-collasping](https://drafts.csswg.org/css2/#collapsing-margins), there are at least two items which mention `auto` computed `height`:

> Two margins are adjoining if and only if:
> ...
> both belong to vertically-adjacent box edges, i.e. form one of the following pairs: 
>* top margin of a box and top margin of its first in-flow child
>* bottom margin of box and top margin of its next in-flow following sibling 
>* bottom margin of a last in-flow child and bottom margin of its parent if the parent has `auto` computed `height`
>* top and bottom margins of a box that does not establish a new block formatting context and that has `zero` computed `min-height`, zero or `auto` computed `height`, and no in-flow children

If `height` is the ratio-dependent axis, should we also take [aspect-ratio](https://drafts.csswg.org/css-sizing-4/#aspect-ratio) into account for these cases?

For example:
```
#parent {
  margin: 0px;
  width: 100px;
}
#child {
  margin-top: 50px;
  margin-bottom: 200px;
  width: 100px;
  aspect-ratio: 1/1;
}
<div id='parent'>
  <div id='child'></div>
</div>
```
Based on the current spec words, the computed height of `parent` is `auto`, so we merge the bottom margins of `parent` and `child`, and so the final bottom margin of `parent` is 200px (i.e. `std::max(0px, 200px)`).
And `child` is not empty (because of `aspect-ratio`), so we don't merge the top and bottom margins of `child` (and `parent`). Therefore, the final top margin is 50px (i.e. `std::max(0px, 50px)`). Is this correct?

Another case
```
#parent {
  margin: 0px;
  width: 100px;
  aspect-ratio: 1/1;
}
#child {
  margin-top: 50px;
  margin-bottom: 200px;
  width: 100px;
}
<div id='parent'>
  <div id='child'></div>
</div>
```
The `child` is content empty, so we merge the margins of the `child` as 200px (i.e. `std::max(50px, 200px)`).
The `parent` has aspect-ratio, so it has the block context (and its used height is 100px), right?
So the final top margin of `parent` is 200px (which is carried out from `child`), and the final bottom margin of `parent` is 200px (which is also carried out from `child`, because the computed height of `parent` is `auto`)? I may be wrong.
I'm confused about this case actually. It seems the final bottom margin is 0px in Chrome now (note: I guess it treats the `aspect-ratio:1/1` as a non-auto height?).

cc @fantasai @cbiesinger @bfgeek

**Comment by BorisChiou** [comment] 2020-07-15 23:33
and cc @emilio.

**Comment by BorisChiou** [comment] 2020-07-16 00:25
Not sure what are the expected behaviors. In my opinion, I think we should treat "non-auto width & aspect-ratio" as a "non-auto height" for these cases.

**Comment by bfgeek** [comment] 2020-07-19 03:43
@BorisChiou Right - this should be treated as a non-empty block, and therefore margins don't "collapse through". However all the other standard margin collapsing rules apply.

For the 1st case it should be no different if the "child" had an explicit height of "100px" e.g. the parent gets a "top" margin of "50px", and a "bottom" margin of "200px".

For the 2nd case it should be no different if the "parent" had an explicit height of "100px" e.g. the parent gets a top margin of "200px" (due to collapsing through), and a bottom margin of "0px".

Do you disagree at all with above description?

Ian

**Comment by BorisChiou** [comment] 2020-07-19 19:00
I agree with your answer. Treat aspect-ratio as a non-empty block, so it should be no different if the block had an explicit "height". Thanks for this clarification.

**Comment by bfgeek** [comment] 2020-07-20 17:46
There is one case where it should be considered empty is if you have something like:
```
#parent {
  margin: 0px;
  width: 100px;
}
#child {
  margin-top: 50px;
  margin-bottom: 200px;
  width: 0px; /* FUN */
  aspect-ratio: 1/1;
}
<div id='parent'>
  <div id='child'></div>
</div>
```

I.e. the "top" margin will be `200px`. This is the same if `#child` had an explicit height of `0px`.

**Comment by BorisChiou** [comment] 2020-07-20 18:09
OK. This makes sense for margin through on `#child` because of "zero or auto computed height". The basic rule is just to replace the `auto` computed height with the calculated height (from aspect-ratio and width). Then it's pretty easy to map it into the spec rules.

**Comment by emilio** [comment] 2020-07-27 21:20
@bfgeek do we actually need to make `inline-size: 0` work?

It'd be nice not to add more special cases to margin collapsing, I'd prefer to consider any finite ratio as not empty for margin collapsing purposes, but...

**Comment by bfgeek** [comment] 2020-07-30 21:36
> It'd be nice not to add more special cases to margin collapsing, I'd prefer to consider any finite ratio as not empty for margin collapsing purposes, but...

@emilio I'd sort of see *not* making the `inline-size: 0` work a special case. :)

FWIW we basically did no work to get aspect-ratio + margin-collapsing to work, instead of relying on all of the existing rules.

**Comment by tabatkins** [comment] 2020-08-04 21:38
@fantasai and I are inclined to go with "if aspect-ratio gives it a non-zero height, that non-zero height inhibits collapse-thru", so in the `inline-size: 0` case, it would continue to collapse thru, exactly as if you'd put `block-size: 0` on it.

**Comment by fantasai** [comment] 2020-08-04 21:45
CSS2 specifies in https://www.w3.org/TR/CSS2/box.html#collapsing-margins the following condition for top & bottom adjoining margins:
> top and bottom margins of a box that does not establish a new block formatting context and that has zero computed 'min-height', zero or 'auto' computed 'height', and no in-flow children  

In the case of applying aspect ratio, the *computed* height is clearly not zero, or else we would be ignoring the aspect ratio. Only the used height is.

That said, CSS2 has no way to distinguish the above condition vs the same condition with s/computed/used/.

So the question now becomes, should margin collapsing be checking for a zero *used* height instead?

CC @dbaron

**Comment by emilio** [comment] 2020-08-05 10:44
I think ideally margin-collapsing would not depend on used values, fwiw. It seems useful to know whether a margin collapses without having laid out the box yet.

**Comment by bfgeek** [comment] 2020-08-05 23:47
> I think ideally margin-collapsing would not depend on used values, fwiw. It seems useful to know whether a margin collapses without having laid out the box yet.

But you need to layout, or at least walk the sub-tree to determine if it has any content?

**Comment by tabatkins** [comment] 2020-10-06 00:13
So for now we've committed the following:
    
> For the purpose of margin collapsing ([[css2#collapsing-margins]]),
> if the [=block axis=] is the [=ratio-dependent axis=],
> it is not considered to have a [=computed value|computed=] 'block-size' of ''height/auto''.

This communicates that a non-zero height caused by aspect-ratio definitely inhibits margin-collapse (as per the resolution above), but it also implies that aspect-ratio inhibits margin-collapse in all cases, even if the resulting height ends up being zero. This matches Firefox, but doesn't match Chrome currently. (Don't know about WebKit.)  It seems like adjusting Chrome to pay attention to aspect-ratio is a smaller task than adjusting Firefox to care about used values when doing margin-collapsing, so hopefully this is ok? Overall this is a corner-case anyway; the only time an ar-having box would get a zero height is if either the a-r is 0/X (weird) or is zero-width (rare).

There's a follow-up CSS2 issue about non-interop on collapsing margins at https://github.com/w3c/csswg-drafts/issues/5571

Let us know if this seems adequate to close the issue, or if further edits are wanted.

**Comment by cbiesinger** [comment] 2020-10-06 14:35
@bfgeek knows our margin collapsing code better but that seems easy enough to implement, though a bit weird. still, agree that this is a corner case and it doesn't matter too much what we decide.

**Closed** 2021-03-11 22:08 UTC
Labels: CSS2, Closed Accepted by CSSWG Resolution, css-sizing-4
