### ISSUE TITLE
[css-transforms-1] Browsers do not implement transform attribute syntax as described by w3c

### ISSUE THREAD

**Issue by longsonr** [w3c/csswg-drafts#2623] opened 2018-04-28 20:57 UTC
Per https://www.w3.org/TR/css-transforms-1/#svg-functional-notation or the earlier https://www.w3.org/TR/SVG11/coords.html#TransformAttribute
All transform arguments need to be separated by whitespace and/or a comma, however no browser implements this restriction. All browsers (tested Edge, Firefox, Chrome and Safari) parse transform arguments like path values i.e. 5-5 is valid and parsed as 5, -5

Firefox thought about fixing this in https://bugzilla.mozilla.org/show_bug.cgi?id=1449075 but we've chickened out. Chrome has https://bugs.chromium.org/p/chromium/issues/detail?id=577219 but doesn't seem to have done anything with it.

I'm prepared to reland the Firefox fix if there's going to be a concerted effort to fix all browsers, otherwise shouldn't the spec simply reflect reality here.

**Comment by fsoder** [comment] 2018-04-28 21:03
FWIW, I'd be willing to try to land a fix in Blink (Chromium bug mentioned), if consensus is built for that option.

**Comment by AmeliaBR** [comment] 2018-04-28 22:00
Given that we already have special parsing rules for the transform attribute (as compared to the property), it seems reasonable to match reality.

That said: as it is currently spec'd, browsers are supposed to accept either the CSS or SVG syntax in attributes. I don't think anyone actually implements it, but if we want the too, adding fast & loose whitespace handling isn't going to make it any easier.

A decision should therefore consider whether we want to shift the attribute to being more consistent with CSS parsing, or leave the attribute as a purely legacy feature.  (It may be worth mentioning that, elsewhere in SVG, we have switched to using CSS parsing rules in many attributes.)

**Comment by dirkschulze** [comment] 2018-04-29 09:15
The issue is that making transform a presentation attribute means that CSS tokenization rules apply. Though browsers may support the relaxed SVG syntax today, it just makes it harder for them to comply to CSS rules tomorrow. CC @tabatkins 

@AmeliaBR in webkit I did experiment with using the CSS parser and legacy parsing rules for many properties (like cx, cry and so on). Even for the transform attribute. Though i know that the code for geometry properties landed, I can’t remember if I ever landed the patch for transforms. Do you have a simple test case that demonstrates that units and/or “pure” CSS transform functions do not apply?

**Comment by AmeliaBR** [comment] 2018-04-29 15:55
@dirkschulze [Test case](https://codepen.io/AmeliaBR/pen/694fec3a2cd9397b0d28f50cba5f1bf2?editors=1100)

Using units in `translate` or the new `translateX` function (with or without units) in the the `transform` attribute does not move the green squares in any browser I tested (Note: I haven't tested the new Edge 17 implementation of CSS transforms for SVG elements). Using negative numbers without separator characters does move the red square.

**Comment by tabatkins** [comment] 2018-04-29 19:07
If you use the CSS parser, but impose the optional-comma rule from SVG, and don't then take special care to *require* whitespace between tokens, then something like `translate(5-5)` will indeed work just fine - the `5-5` part is tokenized into two `<number-token>`s.

(That is to say, if you just parse it as if the CSS grammar is `translate(<number> ,? <number>)`, you'll get this result.  Note that `translate(5px-5px)` will *not* parse correctly - this results in a single `<dimension-token>` with a value of `5` and a unit of `px-5px`.)

If you want to disallow this, you need to impose a manual restriction requiring whitespace between the numeric tokens, similar to what `calc()` requires around its `+` and `-` operators.

**Comment by AmeliaBR** [comment] 2018-04-30 16:37
@tabatkins Oh, that's a nice result.  I think it's reasonably to only accept the legacy whitespace parsing behavior with the legacy no-units syntax.

I would be happy to go further and say that the complete attribute has to either be strictly in the modern syntax or strictly in the legacy syntax: but it would be nice if both syntaxes were supported!

Would it be possible to define the syntax of the attribute as `<transform-list>|<legacy-transform-list>`
and then build it up from there as a full CSS parsing syntax? Or would other differences (like whitespace between the keyword and the parenthesis) make that fall apart?

**Comment by AmeliaBR** [comment] 2018-05-01 01:35
> (Note: I haven't tested the new Edge 17 implementation of CSS transforms for SVG elements)

Now tested, same result as other browsers.

**Comment by dirkschulze** [comment] 2018-05-01 05:14
@AmeliaBR do you propose the legacy parsing behavior to only apply on the presentation attribute but not any CSS property definition?

**Comment by dirkschulze** [comment] 2018-05-02 05:54
@longsonr @AmeliaBR @tabatkins There are actually a couple of more differences between the parsing rules for SVG transform attribute and the CSS transform property. My hope was that they do not matter to much and we could add more restrictions.

One example is:
```xml
<rect transform="translate   (20, 20)"/>
```

This is allowed according to SVG parsing rules but isn't in CSS.

I checked the implementation of MS Edge and it seems like it goes the same route as WebKit and later Blink and Firefox are going. (I have to admit that this is probably my fault as I implemented it this way in WebKit. :( ):

Example: https://codepen.io/krit/pen/LmyjVE

In the example there are 2 rectangles. Both set the `transform` attribute. Former uses the CSS syntax, latter uses the SVG syntax to translate a rectangle by 40px, 40px from the top left.

As you can see in all browsers, the one with the CSS syntax does not get transformed. That is because implementations still only accept the SVG syntax exclusively on the `transform` attribute. All browsers still support things like `translate   (`. None supports the new CSS transform functions like `translateX()` on the attribute.

Now, given that we want to get to a PR eventually and that all browsers comply, it would make sense to allow the old SVG syntax on the attribute as well. However, this may make it harder to support the actual CSS syntax in addition to the SVG syntax later.

Couple of options:
* We ask implementations to remove as many parts of the SVG syntax as possible up to the point where the SVG syntax is compatible to "legacy mode" of CSS (the parsing that @tabatkins suggested)
    * We could set a different requirement for the SVG transform attribute: Must support all transform functions supported in SVG 1.1 and may support additional transform functions from CSS Transforms.
    * Still require all transform functions, which could delay level 1 further.
* We could require the SVG syntax for `transform` **attribute**
    * Add new transform functions to the _SVG syntax_ in the next level or put them in level 1 but implementations _may_ support the new transform functions.

This broadens the scope of this issue a bit. However, we should clarify our priorities rather sooner than later.

**Comment by AmeliaBR** [comment] 2018-05-02 14:44
The attribute needs to support any syntax that was valid & supported for SVG 1.1, and preferably also any syntax that was technically invalid per spec but was widely supported.

I would *like* to eventually make it a deprecated syntax & recommend authors use the CSS syntax, but we can't do that until browsers actually support the CSS syntax in the attribute.  There is currently no "hybrid" syntax that works in either case.

If defining the legacy syntax in CSS parsing grammar makes this second situation more likely, that would be a route forward. But I am in no way suggesting that we should remove currently well-supported syntax structures.  So yes, that would mean defining a new syntax that looks something like `<legacy-translate-function> = [translate (|translate(]<number>[,? <number]?)` (with two options for the function, one as a single token and one as two tokens separated by whitespace).

**Comment by tabatkins** [comment] 2018-05-02 17:15
> Small correction: It is not only translate ( but translate <wsp>* (. @tabatkins could you confirm that this is or is not possible with the CSS tokeniser and parser?

`translate (` gets tokenized as `IDENT(translate) OPEN-PAREN`; `translate(` gets tokenized as `FUNCTION(translate)`.  I'm not sure what the rest of your question is asking about. ^_^

**Comment by longsonr** [comment] 2018-05-02 19:32
It would be simple to implement.

What about transform="translate(10,10),,,,,,,,,,scale(2)"

Firefox & SVG 1.1 spec says OK, Safari&Chrome say no.

**Comment by dirkschulze** [comment] 2018-05-02 20:32
@longsonr You are right, SVG BNF does allow it. Here an example: https://codepen.io/krit/pen/deRoXz
* Firefox renders as if there would just be spaces between the 2 transform functions for the attribute.
* WebKit, Blink ignore the transform because it is invalid for the attribute.
* Edge applies just the first transform functions for the attribute.
* CSS does **not** allow commas as separator at all.

**All** browsers do allow at least one comma between the transform functions on the transform attribute. As far as I can see, it would be possible to define a syntax that would allow one comma or wsp+ but it would be difficult.

Do you see any other incompatible difference that I missed?

**Comment by longsonr** [comment] 2018-05-03 02:29
Nothing else obviously weird from looking at the code. [Here it is](https://dxr.mozilla.org/mozilla-central/source/dom/svg/SVGTransformListParser.cpp) should you wish to do so.

**Comment by dirkschulze** [comment] 2018-05-10 09:41
Here a more detailed test: https://codepen.io/krit/pen/rvdOQX

It confirms that **all** browsers support `number comma-wsp? number` for all transform functions with more than one number value on the `transform` attribute.

However, there are a couple of items from SVG 1.1 that are not supported by all browsers. According to SVG 1.1 the following is valid:
* `translate(1. 1.)` only supported by Edge and not compatible to CSS
* `translate(1 1) ,,, translate(1 1)` only supported by Firefox and not compatible to CSS

The error handling is not consistent across browsers either.
`translate(1 1) error translate(1 1)`
* Edge applies the first transform function but nothing after a syntax error.
* All other browsers ignore the entire transform.

Edge probably tries to follow [SVG 1.1 Error processing](https://www.w3.org/TR/SVG/implnote.html#ErrorProcessing):
> When an element has an attribute or property value which is not permissible according to this specification

* **No browser** supports new CSS Transform functions on the `transform` attribute
* **No browser** supports units for `<length>` or `<angle>` values on the `transform` attribute.

As much as I liked to have the property and attribute to get aligned: I'd suggest that we follow one of @AmeliaBR's proposals in https://github.com/w3c/csswg-drafts/issues/2623#issuecomment-385208372 and leave the `transform` attribute as a legacy feature. At the same time, we align the specification to the implementation behavior of browsers. There would still be open questions where browsers do not align:
* `digital-sequence "."` as defined by SVG 1.1 - _suggest to follow SVG 1.1_
* `transform comma-wsp+ transforms` as defined by SVG 1.1 - _suggest to follow SVG 1.1_
* Error handling on syntax errors. - _suggest to ignore the `transform` attribute on syntax errors_

**Comment by longsonr** [comment] 2018-05-10 18:10
Since only Firefox supports comma-wsp+ I'm happy to change it to 

transform comma-wsp? transforms

Presumably we should document that somewhere in the SVG 2 spec though.

**Comment by dirkschulze** [comment] 2018-05-10 18:25
@longsonr It would probably go into CSS transforms: [transform list](https://drafts.csswg.org/css-transforms/#svg-transform-list) which. Note: The wording currently is incorrect and would allow no comma or wsp. Will fix it together with the other proposed changes when we get to a resolution to keep the SVG syntax on the `transform` attribute.

**Comment by dirkschulze** [comment] 2018-05-16 19:12
The same rules for the patternTransfom and gradientTransform attributes apply as for the transform attribute.

When working on the spec text, I’ll also write examples to check the behavior of transitions from/to a transform attribute value to/from a transform property value in CSS.

**Comment by dirkschulze** [comment] 2018-05-23 17:33
@longsonr I changed the section about the SVG `transform`, `patternTransform` and `gradientTransform` attributes.
https://drafts.csswg.org/css-transforms/#svg-transform

Couple of changes to SVG syntax:
* There is only one comma allowed between 2 transform functions
* No comma or whitespace required between numbers as implemented by all checked UAs.
* Use CSS number notation for now until we got a resolution on https://github.com/w3c/svgwg/issues/442

Please comment if that addresses your requests or is acceptable for Firefox at least.

**Comment by dirkschulze** [comment] 2018-06-01 17:22
I am closing this issue as resolved. Please open this or a new issue if there is more to discuss.

**Closed by dirkschulze** 2018-06-01 17:22 UTC
Labels: Commenter Timed Out (Assumed Satisfied), SVG, css-transforms-1
