### ISSUE TITLE
[css-counter-styles-3] Custom counters and list-style ambiguity

### ISSUE THREAD

**Issue by faceless2** [w3c/csswg-drafts#2724] opened 2018-05-31 10:54 UTC
```
@counter-style inside {
   ...
}

@counter-style outside {
    ...
}

ul { list-style: inside outside }
```

Can I suggest that "inside" and "outside" are added to the list of proscribed values for custom counter names? Otherwise, we need to define how to resolve this one.

**Comment by emilio** [comment] 2018-05-31 12:05
Dupe of #2624. Firefox handles this fine afaict, but would require the change in that issue.

Please reopen if you think it's a different issue.

**Closed by emilio** 2018-05-31 12:05 UTC
