### ISSUE TITLE
[css-grid][css-align] How items with synthesized baseline affect the size of intrinsic tracks

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-drafts#1365] opened 2017-05-12 11:37 UTC
Let's try to explain an issue we're hitting while trying to implement baseline alignment on CSS Grid Layout.

The example is a bit complex, so let's go step by step:
```html
<div style="display: grid; width: 200px; height: 200px;
            grid: auto 50px / 100px 100px; border: solid thick;
            align-items: baseline;">
  <div style="font: 25px/1 Monospace; background: magenta;">
    First<br>item
  </div>
  <div style="writing-mode: vertical-lr;
              font: 25px/1 Ahem; background: cyan;">
    XX X X X X X
  </div>
  <div style="grid-column: span 2; align-self: stretch;
              background: rgba(255, 255, 0, 0.5);">
  </div>
</div>
```

Columns have a fixed size, so we don't need to care about them.

Regarding rows, on the first run of the grid track sizing algorithm, to calculate the size of the first row it checks the heights of the items inside:
* 1st item (magenta) has a 50px height.
* 2nd item (cyan) is vertical, so its height has a range between 50px (the min-content size) and 300px (the max-content size).

As the 2nd row has 50px and the grid container has a fixed height of 200px, the 1st row ends up being 150px tall.

![Status of the grid after the first pass](https://cloud.githubusercontent.com/assets/11602/25994215/56ef8340-370d-11e7-94e2-3e6d87497a00.png)

Until here everything seems pretty clear. Let's move to the funny part.

Now we calculate the baselines to apply the alignment to the items in the first row.
* 1st item (magenta) baseline is 25px (height of the first line).
* 2nd item (cyan) as is vertical we use the [synthesized baseline](https://drafts.csswg.org/css-align/#synthesize-baselines), so the bottom of the element 150px.

We take the biggest one 150px baseline and calculate the baseline offsets:
* 1st item (magenta) 150px - 25px = 125px. We add [a kind of 125px margin](https://drafts.csswg.org/css-align/#baseline-self-alignment) to the item.
* 2nd item (cyan) 150px - 150px = 0px. No changes here.

![Status of the grid when we apply baseline alignment](https://cloud.githubusercontent.com/assets/11602/25994223/61544320-370d-11e7-9b56-4105952e8cd9.png)

Here the [min-content contribution of the first item has changed](https://drafts.csswg.org/css-grid/#algo-overview), before it was 50px, and now it's 175px = 125px (the baseline offset) + 50px (its height). So we've to do a new run of the algorithm.

In this second run to compute the size of the first row we do:
* 1st item (magenta) has a 175px "height" now (it's not really its height but its min-content contribution due to the baseline alignment).
* 2nd item (cyan) has a range between 50px and 300px.

The first row has to be now 175px height, the 2nd row is fixed so it has 50px height and it overflows the container (not a big deal as that's what happens in similar cases without baseline alignment).

Problem comes now, what should we do at this point?

### Option 1)

Following the approach above, we'd recompute the baselines offests:
* 1st item (magenta) the baseline is 150px = 125px (from the previous run) + 25x (height of the first line).
* 2nd item (cyan) this item has now a height of 175px, so 175px.

The biggest baseline is 175px so we calculate the offsets again:
* 1st item (magenta) 175px - 150px = 25px. We move the item down 25px more.
* 2nd item (cyan) 175px - 175px = 0px. We don't do any change.

Then we'd stop, as the algorithm just ask to repeat it only once.
The result would be:
* 1st row: 175px.
* 2nd row: 50px, overflowing the grid container.
* 1st item (magenta): 50px height (with a 150px baseline offset), overflowing the 2nd row.
* 2nd item (cyan): 175px height, no oveflow.

![Status of the grid following option 1](https://cloud.githubusercontent.com/assets/11602/25994178/29ebc5e8-370d-11e7-80c4-08a2d24f665f.png)

### Option 2)

We avoid to recompute the baselines and reuse the biggest one from the previous run, which was 150px.

Then we calculate the new offsets:
* 1st item (magenta) 150px - 150px (current "height") = 0px. We don't move it further.
* 2nd item (cyan) 150px - 175px (current height) = -25px. We move it up 25px.

Again, this is the 2nd run so we stop at this point.
The result would be:
* 1st row: 175px.
* 2nd row: 50px (overflowing the grid container).
* 1st item (magenta): 50px height (with a 125px baseline offset), not overflowing the 2nd row.
* 2nd item (cyan): 175px height (with a -25px baseline offset), overflowing the 1st row on the top and not reaching the bottom of the row.

![Status of the grid following option 2](https://cloud.githubusercontent.com/assets/11602/25994478/43991f12-370e-11e7-89e2-c5cc06a8a36e.png)

### Option 3)

As a last resort we could think on a different approach that would be to ignore the items with synthesized baseline. So in this case both items will be on the top of the first row and have a height of 50px and 150px (so the row would be 150px). But probably we don't want this.

What do you think?

**Comment by tabatkins** [comment] 2017-06-21 23:08
I'm thinking that, since this is a bad situation in any case (trying to baseline-align orthogonal flows), I'm okay with the result that we currently get from the spec (option 1). Option 2 looks at *least* as bad, and would involve some changes I'm not confident about, and option 3 goes against the entire reasoning for having synthesized baselines.

The result isn't pretty, but it's both (a) rare, and (b) well-defined already, so I'm okay with it as it is.

**Comment by javifernandez** [comment] 2017-06-27 13:13
> I'm thinking that, since this is a bad situation in any case (trying to baseline-align orthogonal flows), I'm okay with the result that we currently get from the spec (option 1). 

I'm ok with this decision. I didn't have any preference and current behavior is as good as any other option. The only issue worth discussing would be the fact that Baseline Alignment alters box's intrinsic size. If we end up removing that behavior, implementation would be considerably simpler.

**Comment by tabatkins** [comment] 2017-07-20 19:25
The problem is that the cyan box is allowed to grow into the new space cleared out below it by aligning to the baseline of the pink box.  If we can prevent that growth from happening, then the cyan's baseline will stay the same in both rounds, and the layout stabilizes in the second round.

Suggestion, then: when we do self-baseline-alignment, we add pretend-margin to *both* sides of the boxes, so that all the aligned boxes have *identical* margin-box sizes.

In this example, then, the first round would give the pink box 125px of top margin, and the cyan box 25px of bottom margin (so both have a margin-box height of 175px). Then, when we go into the second round, both boxes already exactly fit into the new 175px row height. The cyan box's synthesized baseline is still at 150px, so the pink box is already aligned with it, and layout is finished.  The yellow box still overflows the grid container by 25px, but otherwise things fit together nicely.

What this means is that, if there are larger items in the row, the cyan item will not resize to fit the row. And we haven't solved that there will be some overflow in this case even though it's theoretically not necessary.  But at least its size should be stabilized across cycles.

Thoughts?  We're not sure at the moment whether this is only needed for self-alignment, or whether it would apply to the pretend-padding of content alignment too.

**Comment by tabatkins** [comment] 2017-10-17 18:58
Our current proposal is to simply detect when there's a circularity in sizing for baseline-aligned things (that is, when an item depends on the size of the track), and disable their baseline alignment so that they fall back to start/end alignment.  In the first example in this thread, then, the first image is also the final one, because the teal item is no longer baseline-aligning (and becomes start-aligned instead) and the magenta item now has nothing else to baseline-align to (and so start-aligns as much as possible).

We considered just ignoring the circular items for sizing purposes (the step added in #1039) but still allowing it to baseline-align at the end of layout like normal, but in the common case this will cause the item to overflow upwards, and we can't come up with a single use-case where this seems desired in the first place. (Hence the changes added/reverted above.)

Thoughts?

**Comment by javifernandez** [comment] 2017-10-30 14:01
I think this simplification makes sense. I agree it will solve these and many other cases, related to baseline regular and orthogonal items. 

Shouldn't we add something regarding ignoring the circular items for baseline-alignment purposes ? Perhaps we can add something here:

https://drafts.csswg.org/css-align-3/#baseline-values

We could state there that items with a size dependent on its content area (in the appropriated axis) don't share the baseline alignment context.

**Comment by fantasai** [comment] 2017-11-27 20:15
Edits checked in! Please let us know if it needs further clarification.

**Closed** 2017-11-27 20:14 UTC
Labels: Closed Accepted by CSSWG Resolution, css-align-3, css-grid-1, Needs Edits

**Comment by javifernandez** [comment] 2017-11-30 09:30
Sorry for the delay, I'm still implementing a prototype of the new algorithm to play with some orthogonal cases. As I said before, I think the new text addresses the problems identified in this issue, but I think we may have to add some minor changes to the current text to deal properly with some orthogonal cases. 

I'll provide the required examples soon and will define the WPT when I started the actual implementation.

**Comment by mrego** [comment] 2017-11-30 20:45
Just as a summary I'm attaching an image showing the behavior of the example from the first comment on the different browsers and how it'd work with the new proposal.

![Status of this issue on the different browsers](https://user-images.githubusercontent.com/11602/33453875-7b04db1e-d617-11e7-81aa-39606b05610f.png)

The situation is:
* Chromium: Needs changes.
* Firefox: It's fine because it doesn't apply baseline to orthogonal flows.
* Edge: Needs changes.
* Safari: It's not implementing baseline yet, so I'm not even adding a screenshot for it.

**Comment by javifernandez** [comment] 2017-11-30 23:00
The new text added states the following: 

https://drafts.csswg.org/css-grid/#algo-baseline-shims
> Since grid items whose own size depends on the size of an intrinsically-sized track do not participate in baseline alignment, they are not shimmed.

Perhaps I'm understanding it wrong, but I've got the impression that it implies that such items are excluded of participating on baseline alignment **on any axis** I don't think that's necessary, nor desirable, since the only way of defining baseline alignment along the column axis is using orthogonal items. 

I'd like the new text to allow baseline in both dimensions, like this:

![2-dimension-baseline](https://user-images.githubusercontent.com/2230241/33459392-12b8ceea-d62a-11e7-9dd9-a03328cc9669.png)

What do you think about being more specific about which baseline axis the item doesn't participate on ?

**Comment by tabatkins** [comment] 2017-12-01 19:21
@mrego Correct.

@javifernandez 
> Perhaps I'm understanding it wrong, but I've got the impression that it implies that such items are excluded of participating on baseline alignment on any axis I don't think that's necessary, nor desirable, since the only way of defining baseline alignment along the column axis is using orthogonal items.

Notes are not normative, they're just reminders! If you follow the link to the actual normative text in chapters 10.3 and 10.4, it's clear that the "doesn't baseline-align" is per-axis.

**Comment by javifernandez** [comment] 2017-12-01 21:47
Yes, it's indeed clear, thanks.

**Comment by mrego** [comment] 2019-11-22 08:29
Test case has been merged: https://github.com/web-platform-tests/wpt/pull/8580
