### ISSUE TITLE
[css-color-adjust-1] more granular overriding of forced colors mode than per-element

### ISSUE THREAD

**Issue by melanierichards** [w3c/csswg-drafts#4178] opened 2019-08-06 22:16 UTC
Somewhat combinatorial between specs, but css-color-adjust-1, [Forced Color Schemes](https://www.w3.org/TR/css-color-adjust-1/#forced) might be the best place to put this.

It would be ideal if an author could override a [property value affected by forced colors](https://www.w3.org/TR/css-color-adjust-1/#forced-colors-properties) without requiring the author to set `forced-color-adjust` to `none` on the element.

In some cases, authors will want to fully manage how an element is styled in forced color modes, which is an appropriate use of `forced-color-adjust`. But in other cases, they may just want to change a singular property value without interfering with other UA forced color styles, e.g.:

```
@media (forced-colors: active) {
  [aria-disabled="true"] {
     color: GrayText;
  }
}
```

We should perhaps tweak cascade expectation in [Forced Color Schemes](https://www.w3.org/TR/css-color-adjust-1/#forced) such that cascaded values outside of the `forced-colors` media query are unset, but origin override rules apply when additional styles are set within a `forced-colors` media query block. Essentially want to ensure that point 4 of the [Cascade Order in the initial High Contrast explainer](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/master/Accessibility/HighContrast/explainer.md#cascade-order) is true in standard implementations of forced color modes.

**Comment by FremyCompany** [comment] 2019-08-07 21:15
I personally disagree with this.

**Comment by emilio** [comment] 2019-08-08 12:01
Yeah, I think making rules apply or not whether they're in a media query block is pretty confusing.

**Comment by atanassov** [comment] 2020-02-04 16:31
@emilio can you expand why you believe such declarations are confusing? 

The intent of the request is to allow declarations to work as expected inside a media query block, including `forced-colors`. The use of `forced-colors-adjust` is a pretty heavy hammer that is intended to put the author in charge of the element and all its descendants. In contrast, honoring the declarations inside `forced-colors` media query allows individual properties to be set just like you would inside `prefers-colors-scheme` for example.

**Comment by AmeliaBR** [comment] 2020-02-05 03:44
>  they may just want to change a singular property value without interfering with other UA forced color styles

This seems like a dangerous thing to do, anyway. If an author changes foreground but not background colors (or vice versa) based on what they _expect_ a "high contrast" mode to do, it could break very badly in a different forced colors mode.

The specific case of being able to indicate grayed text, using system colors, is valid, but is it really that much harder to also set the `forced-colors-adjust: none` and the matching background color (buttonFace or field)?

There's also nothing stopping a UA stylesheet from selecting on ARIA attributes when applying the forced color mode, if you're seeing this problem (ARIA semantics being lost in high contrast) a lot in the wild.

**Comment by atanassov** [comment] 2020-02-07 18:36
The ergonomics of setting `forced-colors-adjust: none` are pretty bad if an author wants to adjust a single, targeted property. We heard strong author feedback on the issue from framework developers and looking further into it I agree it doesn't make sense to penalize them in these cases. 

In the case of components where an author wants to opt-out and have complete control over it (ex. maps widget rendered in Canvas) the property makes complete sense.

**Comment by fantasai** [comment] 2020-03-06 03:37
I agree that rules inside an MQ should be special. In particular, it's hard to know what rules are inside an MQ -- entire style sheets can be imported via several levels of @import indirection through a mediaquery-filtered link.

One possible way around this could be the author specifying which properties to except, e.g. `forced-color-except: border stroke`. Otherwise we're looking at a lot of magic in the cascade, I think.

**Comment by tabatkins** [comment] 2020-03-18 18:10
I assume you mean "shouldn't be special", @fantasai ^_^

But yeah, we've avoided giving special meaning to things inside of MQs for a long time for several reasons, and I think we should continue avoiding that.

**Comment by lilles** [comment] 2020-03-25 11:56
I agree with not making rules inside MQ special. Either something like forced-color-except like fantasai proposes, or could a priority on the declaration be an alternative?

**Comment by fantasai** [comment] 2020-03-25 16:10
@tabatkins Uh, yeah. :) Fixed.

**Comment by AmeliaBR** [comment] 2020-04-02 00:03
The more I think of this, the more I like Fantasai's suggestion of explicitly listing the properties you want to ignore, as the values of a property which cascades normally.

Maybe make it `forced-color-ignore: all | <property-name>+`, where `forced-color-ignore: all` replaces the currently spec'd `forced-color-adjust: none`.

The one downside to this is that, like all properties that take a list of values (`transition-property`, `will-change`, etc.), you can't add values to that list by separate selectors, you need to set them all at once.

**Comment by tabatkins** [comment] 2020-04-02 00:31
Summary of the discussion is that dbaron argued that we've historically considered "property A which influences how property B works" as a bad idea; a notable example is 'box-sizing' which is generally considered a legacy mistake. Several people agreed with this.

Instead, some sort of addition to the value space of the properties was preferred. I suggested that we finally use the ! space that Syntax allows, as it gives us an unambiguous way to add to flags to values without worrying about syntax collisions; this would look something like `color: blue !override-forced-color;`.  (Post-call correction: I actually simplified Syntax to *just* look for !important at some point, and not have a general mechanism. But it's still totally possible to re-open that with some trivial fixes.) This wouldn't conflict with the existing !important; you should still be able to say `color: blue !important override-forced-color;` if you wanted to.

This received general approval, but there was a split in how it should be interpreted. The broadly accepted possibilities were:

1. The !-ident would kick the declaration into a mega-important cascade origin, overriding the UA-important origin that the forced-colors declarations live in. (This means that in `.foo { color: red !override-forced-color; } #bar { color: blue; }`, the red would win in all cases over the blue, despite blue having a higher specificity.)

2. The forced-colors-mode declarations, rather than living in a high origin, instead magically override the cascade winner. If the cascade winner has the !-ident, it doesn't get overridden. (So in the above example, the blue would win the cascade as normal, and then get overridden by a forced color.)

3. Like 1, but the declaration gets moved into the special origin *only* if forced colors are active. (So blue would win normally, but red would win if forced-colors-mode was active.)

Rossen didn't want to discard (3), but Florian and I didn't like it, because it would mean a significant behavior change in forced-colors-mode that is likely to not really be tested.

-----

Also, given <https://github.com/w3c/csswg-drafts/issues/4175#issuecomment-603965581>, forced colors mode **can't** be just literally applying rules in a high origin based on a MQ. It's gonna have to do something magical for at least *some* properties, to preserve the alpha component of the author's cascade-winning color, so it doesn't feel like there's much value in preserving the fiction that it's just a line in the UA sheet; instead I think we should go whole-hog in the "it's a magical adjustment" direction.

**Comment by astearns** [comment] 2020-04-02 00:32
@emilio @FremyCompany @melanierichards please take a look at the above and weigh in

**Comment by AmeliaBR** [comment] 2020-04-02 22:16
OK, building on Tab's three options for interpreting a `!override-forced-colors`, one thing to think about is how they interact with the media query:

- In (1), if you used the override outside of a `(forced-colors: active)` media query, it would behave as a `!super-important` when the browser isn't in forced colors mode.

  This seems like a potential for misuse, throw it on when you need to override a 3rd-party library's `!important` style, without testing for what it actually does in forced color mode.

- In (3), the media query would become completely optional unless you also wanted to adjust other properties, as the `!override-f-c` would act as a declaration-scoped media query condition itself.

  E.g., the following would always have a red border, but the text color would be purple in normal mode (because of regular positional cascade) and the `highlightText` color in forced color mode (because of forced color mode triggering the super important behavior):

  ```css
  .selector {
    border: thick solid red !override-forced-colors;
    color: highlightText !override-forced-colors;
    color: purple;
  }
  ```

- In (2), the media query would be optional if you wanted to force your normal style to stay the same in forced-color mode, but it would be required if you want to define your own color overrides.  Which seems like a nice compromise to me.

  The previous example would become:

  ```css
  .selector {
    border: thick solid red !override-forced-colors;
    color: purple;
  }
  @media (forced-colors: active) {
    .selector {
      color: highlightText !override-forced-colors;
    }
  }
  ```  

  The only downside is one that is shared with all media queries: the MQ doesn't add any specificity or importance to the declaration, so authors still need to make sure that the MQ rules override the basic rules when the MQ is active.

In all of these cases, if you do use the media query, you'd probably need a big long line of `!override-f-c` modifiers on every declaration inside the MQ block.

In contrast, the way the original `-ms-` prefixed media query worked is that by the nature of being contained inside that MQ block, declarations had special importance given to them. I'm not sure of how that special importance worked in its interactions with the rest of the cascade, but it's worth considering whether it would be possible to recreate some of that simplicity.

Maybe a media query that is activated by forced colors mode could implicitly get the `!override-f-c` behavior for all of its declarations. Or maybe there could be a new syntax way of setting a `!` modifier on a media query block as a whole.

**Comment by fantasai** [comment] 2020-04-02 22:17
I don't like the proposal.

Wrt #1, “overriding the UA-important origin that the forced-colors“, that's not actually how the mechanism works, because we resolved in https://github.com/w3c/csswg-drafts/issues/4020 to rewrite the author rules instead.

Wrt all of them, they violate the principle that the UA !important rules always win. Always. And user !important rules override author rules. Always. Author rules should not be moving outside their cascade origin.

**Comment by tabatkins** [comment] 2020-04-03 17:36
> Wrt all of them, they violate the principle that the UA !important rules always win. Always. And user !important rules override author rules. Always. Author rules should not be moving outside their cascade origin.

I'm confused why you're implying this is true for "all of them" - one of the solutions is just "normal cascade, and if the cascade-winner has !foo, it doesn't get overridden by forced-colors".

The other ones do talk about a new higher origin, but I assume it's still meant to be an author-level origin, and thus will get overridden by UA and user !important things.

**Comment by FremyCompany** [comment] 2020-04-30 16:33
Not sure if this will come up in today's discussion on custom origins, but in case it does, here are my thoughts on this.

## Background
Forced colors mode mostly does two things:
- Remap colors to valid known defaults (appropriate system colors)
- Ensure text readability when drawn over unknown backgrounds

I am only aware of two ways one would want to adjust the forced-colors mode:
- Either you are building a graphic or chart, or more generally work in a fully controlled canvas and are already enforcing contrast one way or another, and need to avoid the remapping and backplating to screw it up; you therefore disable forced-colors intervention, and eventually use your own styles to address this somehow. This use case is already addressed properly at this point.
- The color-remapping and backplate do work for you globally. In one particular case, though, you know of some state that should affect the color remapping but isn't possible to convey in a way the browser heuristics would understand. You therefore want to specify one particular remapping yourself, while leaving the rest untouched. This doesn't seem very convenient to address today.

## Thoughts on proposals
While custom origins and !overrides would definitely enable to solve the second use case, I think they give more power than is actually required to solve the problem at hand here (including unfortunate footguns).

Aiming for more simplicity, I rather propose to add a third value to `forced-color-adjust` instead of adding a more generic complexity. I have two options in mind for the form this third value would take, and I would be interested to know what people at Microsoft who reviewed the use cases think of them.

**Option 1:** `forced-color-adjust: out-of-palette-only`
Under this proposal, the colors of an element are still adjusted to fit the palette accepted by the mode, but if the computed value of a color property happens to be in that system palette already, no modification is made to that color.

I believe this should cover the case presented above in this discussion without modification to cascade rules whatsoever.

**Option 2:** `forced-color-adjust: auto <foreground-color>? <background-color>?`
Under this more strict proposal, the forced-coloring is still applied, but instead of following heuristics, colors are mapped to `<foreground-color>` (color, border, ...) or `<background-color>` otherwise. Disabling the heuristics for that element (and its inheriting descendant unless explicitly respecified otherwise) makes the authors in control.

To avoid being painful, forms and replaced elements would have `forced-color-adjust: auto` speficied in the User-Agent stylesheet, so that they don't inherit a foreground-background combination aimed at a section of text instead (but authors can of course specify `forced-color-adjust: inherit` on them if that was intended.

This second proposal is more strict than the first one, but slighly more powerful in some cases if we don't restrict `<foreground-color>` and `<background-color>` to be in the palette (we could, though, in which cases it is more strict that option 1 and never more powerful).

**Are there known use cases that wouldn't be solved by either proposal?** (If not, my recommendation is to add this third value, and not fiddle with cascade rules in this scenario)

**Comment by FremyCompany** [comment] 2020-04-30 19:28
**Option 1 addendum**: `color(..., system-color)`
Last but not least, I would like to note that with a tiny update to `color()` behavior, we can make the life of developers super easy! The proposed change here would be that, in forced-colors mode, if the fallback color of the `color()` function is a system color, this system color is always returned irrespective of whether the colors specified on the left would otherwise be recognized as valid.

With this addition, developers don't need to write this:

```css
.disabled-button {
    color: rgb(128 128 128);
}
@media(forced-colors: active) {
    .disabled-button {
        border-color: GrayText;
        forced-color-adjust: out-of-palette-only;
    }
}
```
They could write this instead: (and abstract this in a custom property variable if frequent)
```css
.disabled-button { 
    color: color(rgb 128 128 128, GrayText); 
    forced-color-adjust: out-of-palette-only;
}
```

**Comment by tabatkins** [comment] 2020-05-19 18:39
Okay, so on review, Elika and I like the "out of palette only" suggestion the best here. It seems to hit the use-case well while still respecting forced colors as much as possible. In fact, we think this should be the "auto" behavior; if we do still want the original auto behavior (do we?) we can add this as a stricter keyword.

François' idea about auto-triggering color() fallback to a system color if possible is also pretty good, we think. Essentially, in forced-color mode we pretend that *all* the colorspaces aren't loaded, except for one capable of expressing the dozen-ish system colors.

**Comment by atanassov** [comment] 2020-06-24 17:00
Perhaps the motivational test case mislead the direction of this issue a bit. The main use case for the capability is intended to allow authors to supply arbitrary color values for a specific property override.

Consider the following use case where the author's intent is to change the text color to dark gray in the case of `forced-colors:black-white`  

```
@media (forced-colors: active) {
   @media (prefers-color-scheme: dark) {
      [aria-disabled="true"] {
         color: #767676;
      }
   }
}
``` 

Per our previous discussions my understanding was that our intent is to enable this by adding the `!forced-override` _(name tbd of course)_ to any selector. That same example is then enabled as follows

```
 @media (prefers-color-scheme: dark) {
    [aria-disabled="true"] {
       color: #767676 !foced-override;
    }
 }
```

**Comment by tabatkins** [comment] 2020-07-10 20:22
I suppose my question now is: *why* is this different from the example in the OP? What is the justification for using colors other than what the user explicitly indicated they want to exclusively see?

Note in particular that `forced-colors` gives *zero* indication of what those colors are; all the author knows is that the page will be shifted into exclusively using the system colors. (And possibly that it's roughly a darkish or lightish theme.)

In particular, there is no guarantee in your example that `#767676` isn't *already* the text or background color (or close to it), rendering the text either invisible or indistinguishable from normal. Or even if neither of these are true, the other disabled text on the platform is probably *not* in `#767676`, so this'll look different for no apparent reason. Whereas using `graytext` would make it look exactly like all the other disabled text on the platform automatically, *whatever* color that was.

I'd like to see some examples that need a *specific* color and couldn't be served by a system color.

**Comment by alisonmaher** [comment] 2020-07-15 01:09
@tabatkins I combed through the list of bugs reported in Microsoft Edge that are related to this issue, and the majority could be resolved by the most recent proposal (ie. don't override system color in forced colors mode).

There were a few example sites that I came across that would require specific colors other than system colors.
1. Bing Maps, for example, requires non-system colors to ensure the map is still readable in forced colors mode. However, because the entire map is being adjusted by the author, `forced-color-adjust: none` already works great in this case.
2. The map on the right of [this Wikipedia article](https://en.wikipedia.org/wiki/Pacific_swift) has a legend that becomes unreadable in forced colors mode. In this case, using system colors would be insufficient.
3. Color options for products (ex. choosing a [color for a laptop](https://www.microsoft.com/en-us/store/configure/Surface-Laptop-3/8VFGGH1R94TM?crosssellid=drawer2&selectedColor=CBB1A0&preview=&previewModes=)) can become unusable in forced colors mode and would require non-system colors.

Although these examples would require non-system colors to maintain usability, I could easily see applying `forced-color-adjust: none` as a resolution in these specific cases. Perhaps @atanassov knows of additional examples, though, where this wouldn't be the case?

**Comment by FremyCompany** [comment] 2020-07-15 12:24
Thanks @alisonmaher for the analysis, it certainly took some time to dig through these issues!

I agree that sometimes preserving raw colors is needed when the color itself is part of the information (like 2 and 3) or when the color scheme requires a level of granularity not available to system colors (like 1). I also agree that this is why `forced-color-adjust: none` exists; all the use cases above fit that use case very well.

I am not personally aware of cases where `forced-color-adjust: none` is not desirable but arbitrary colors would be.

**Comment by tabatkins** [comment] 2020-07-17 22:17
@alisonmaher Yes, thank you, that's an excellent list.

And I agree that all three cases should work just fine with `color-adjust: none`: maps will be entirely color-controlled anyway, and the other two options are color swatches which don't need any special per-property granularity, since they're just showing off a background color.

Do we want to conclude, then, that per-property granularity isn't needed, beyond the ability to choose precisely which system color is used? At least for now; we can revisit in the future if necessary.

**Comment by alisonmaher** [comment] 2020-07-17 23:00
Based on the examples I have seen, I would be okay with resolving to this for now and re-addressing as necessary.

**Comment by tabatkins** [comment] 2020-07-18 00:26
@melanierichards As the original reporter, could you confirm that you're okay with this resolution?

**Comment by melanierichards** [comment] 2020-07-18 01:03
First, apologies for going quiet on this issue; didn't want to speak for folks still working on the forced colors implementation while I was on other projects. :)

Am I correct in understanding that the current resolution is "won't fix"? That's probably ok, this was more about developer ergonomics (folks complaining / not understanding why they'd need to set `forced-colors-adjust: none` just for one simple override) than authors being explicitly blocked.

@tabatkins

**Comment by alisonmaher** [comment] 2020-07-20 16:45
@tabatkins is the resolution here "Won't Fix" or that we should add to the spec that we will not revert system colors set by the author in Forced Colors Mode?

**Comment by tabatkins** [comment] 2020-07-21 01:15
Ah, sorry, yes, proposal is to reject Melanie's proposal from their original post, but still add the "any system colors you use will be respected in forced-colors mode, even if they're not the colors that would normally be chosen" bit.

**Comment by melanierichards** [comment] 2020-07-21 01:34
SGTM, thanks!

**Comment by tabatkins** [comment] 2020-08-19 16:23
From Francois' comments in the call, want to be clear that the earlier suggestion about having `color()` be valid and respected if it falls back to a system color is intended to be part of this as well.

**Comment by tabatkins** [comment] 2020-08-20 16:49
I've made the edits to color-adjust, I think minimally. Can I get a review? In particular, @fantasai, can you give it a look-over, since you wrote most of the text I was changing?

**Comment by fantasai** [comment] 2020-09-29 06:32
Pushed a revision of your edits, @tabatkins. There remain some interesting questions:

- Is the result of forcing a computed or used value? Mapping out-of-gamut colors is a used-value time operation, which I thought is what we were doing here, but your edits indicate changes to the computed value.
- Previous text reverted colors to match the UA+user style sheets. I've restored this requirement as a SHOULD, but that's also up for discussion.
- These rules will override any explicit values in the UA or user style sheet. Are we sure that's what we want?

**Closed** 2020-11-09 20:46 UTC
Labels: Closed Accepted by CSSWG Resolution, Needs Testcase (WPT), css-color-adjust-1
