### ISSUE TITLE
[css-text] cursive shaping breaks needs better scoping

### ISSUE THREAD

**Issue by r12a** [w3c/csswg-drafts#698] opened 2016-11-09 11:46 UTC
8.3. Shaping Across Element Boundaries
https://drafts.csswg.org/css-text/#boundary-shaping

previous discussion on this topic can be found at:
http://www.w3.org/Mail/flatten/index?subject=Arabic+letters+connecting+between+elements+with+display%3A+inline&list=www-style

> Text shaping should not be broken across inline box boundaries otherwise, if it is reasonable and possible for that case given the limitations of the font technology.

I think this is too broad.  I created a set of tests for arabic script text at
https://w3c.github.io/i18n-tests/results/css-text-shaping (click on the link in the left column to see the test run)

The results show that no browser tested maintains the joining behaviour where font-weight and font-style and font-size are different. (Red appears because the spec currently implies that those shouldn't break the cursive shaping.) Those should probably be added to the list of styles that break the text shaping.  Either that, or it may be simpler to list styling that should _not_ break shaping.

Note also that a border doesn't break the joining behaviour in Firefox and Edge.  This perhaps seems like reasonable behaviour for highlighting items, and i wonder whether we should drop that from the list of things that break shaping? I suppose the argument (as for margins and padding) is that this might have been a block element that has been added inline.  It seems a pity, however, that such a possibility would rule out the ability to put a border around one character in a cursive sequence using inline markup when wanted.

**Comment by fantasai** [comment] 2017-04-19 15:46
Are you arguing that shaping shouldn't, on principle, be applied across changes in font weight/style/size, or that because this is not implemented it should be considered a spec bug and not an implementation bug?

We definitely should be maintaining shaping across font family changes, fwiw, simply because that's a font fallback issue.

**Comment by r12a** [comment] 2017-04-19 18:39
Trying to remember what i was thinking back then.  Coming to it fresh, i also wonder why i suggested that changes in font weight/style/size should break the shaping.  

I'm now thinking that we should probably call out at least the more obvious things we believe should **not** break the shaping, to improve consistency across browsers. And i guess i'd include font weight/style/size in that list, as well as non-zero width borders and font-family.

**Comment by behnam** [comment] 2017-04-26 16:48
From https://drafts.csswg.org/css-text-3/#boundary-shaping
> Text shaping should not be broken across inline box boundaries otherwise, if it is reasonable and possible for that case given the limitations of the font technology.

Although it's a good start, but the "if it is **reasonable and possible** for that case given the limitations of the font technology" part apparently makes it a matter of choice again and leaves a lot of room for inconsistency between implementations, and eventually, as a result of the inconsistencies, users not being able to rely on it.

Regarding "joining context" of elements, has it been discussed to allow user to control it for `inline` elements, with options to *isolate* the element regarding joining or *absorb* context from surrounding?

Why I think explicit method is better than implicit is that there exist cases that the element can have a margin/border/padding **and** also a non-`baseline` vertical alignment, and still the *joining context* should be preserved, for example, "drop caps" for Arabic.

Here's an example of a drop caps being applied without proper *joining context* for either the first letter or the rest of the word:

![image](https://cloud.githubusercontent.com/assets/37169/25446075/f93acc9e-2a75-11e7-862b-b4e02d36741c.png)

Example is from this discussion: https://groups.google.com/forum/#!topic/persian-computing/W-Upl6DAEcg

**Comment by behdad** [comment] 2017-04-26 21:14
I agree it would be good to call out property changes that MUST NOT break shaping.  For the rest (font change), I like to still suggest the correct behavior, even if no implementation does it currently.  FWIW, the layout-ng rewrite effort in Chrome is going to fix that.  That has been one of the design goals.

**Comment by r12a** [comment] 2017-04-27 11:57
@behnam, just to be sure i'm clear, i think you saying that the paragraphs should start with

![screen shot 2017-04-27 at 12 54 22](https://cloud.githubusercontent.com/assets/4839211/25482234/c7ec3ac8-2b48-11e7-9ed8-55558b7765ec.png)


rather than what is shown in your picture. Is that right?

**Comment by behnam** [comment] 2017-04-27 18:17
That's correct, @r12a. For both cases.

**Comment by fantasai** [comment] 2018-03-05 09:10
Filed https://github.com/w3c/csswg-drafts/issues/2399 about drop-caps.

Fwiw, the current text is the result of discussions in https://lists.w3.org/Archives/Public/www-style/2014Aug/0217.html I agree that there's no excuse to break Arabic joining in #2; I would find that unreasonable, and therefore a spec violation, but I suppose we can make it more explicit. :)

**Comment by fantasai** [comment] 2018-03-05 09:25
Possible edits: add the following note

> Note: The correct choice of joining forms in Arabic (initial, medial, final, isolated) is always reasonable and possible; even given no support in the text rendering back-end, the UA can always pass in strings marked up with U+200D Zero Width Joiner.

Open to suggestions/comments, but only from people who have read the thread linked above. ;)

**Comment by r12a** [comment] 2018-04-30 17:16
alreq TF notified

**Comment by r12a** [comment] 2018-05-09 16:46
Here's an easier to read version of the thread mentioned by @fantasai 
https://www.w3.org/Mail/flatten/index?subject=Shaping+Isolation+and+Layout+Separation+of+Inlines&list=+www-style

**Comment by r12a** [comment] 2018-05-09 17:28
Based on the classification in the thread @fantasai pointed to, here's a first proposal:

1. (must not break shaping) includes: change to colour, border, font-weight, font-style, text-decoration, first-letter styling
2. (should not break, if possible) includes: font-size, font-family
3. (must break) includes: one of margin/padding are non-zero, baseline change, isolation boundary

**Comment by palemieux** [comment] 2018-06-14 03:02
Is this related to https://bugs.webkit.org/show_bug.cgi?id=6148 ?

**Comment by fantasai** [comment] 2018-07-24 23:51
@r12a Font changes should all be handled as a single category, and same with margin/border/padding.

**Comment by frivoal** [comment] 2018-10-02 01:55
@atanassov The minutes say:
> Rossen: I'll get our fonts people to look and comment and ideally we can resolve on github and put on agenda for resolution.

Any update?

**Comment by ntounsi** [comment] 2018-10-07 22:08
@r12a 
>     1. (must not break shaping) includes: change to colour, border, font-weight, font-style, text-decoration, first-letter styling

You may add "link" (element `<a>`) to the list above.

In Arabic, some prepositions are two or three characters: من MIN (from), في FI (in), إلى ILA (for/to) etc., and are a separate word.

But some other prepositions are one character:   ب BI (with), ل LI (for/to), and they join with the word which follow them. So they shape like : لـ , بـ .

When the following word (or phrase) is a link, the joining must still apply. Here are two examples among others (each in English and then Arabic) :

1) Verify your site with [i18n validator](https://validator.w3.org/i18n-checker/).

حقق موقعكك ب[محقق التدويل](https://validator.w3.org/i18n-checker/).

2) To [lead the Web to its full potential](https://www.w3.org/).

ل[قيادة الويب إلى إمكانيته الكاملة](https://www.w3.org/).

Currently, only Firefox and Edge do the right shaping

Don't know in other languages if part of a written word can be a text link.

**Comment by svgeesus** [comment] 2018-10-08 11:16
> (should not break, if possible) includes: font-size, font-family

I would expand that to font-size, font face (within a family) and font-family.

I heard there was discussion at ATypI 2018 about how changing the face (either a slightly different weight, or a change from one subsetted font to another with a different subset, but again in the same family) was breaking shaping.

**Comment by kojiishi** [comment] 2018-10-08 15:40
@ntounsi 
> You may add "link" (element `<a>`) to the list above.

`<a>` is an inline box boundaries, and normally it has different color and text-decoration, so I think they're covered.

> Currently, only Firefox and Edge do the right shaping

Chrome with new engine enabled (enable "LayoutNG" in chrome://flags) do the right shaping too, as far as I understand. Your double check would be appreciated.

**Comment by ntounsi** [comment] 2018-10-08 16:35
@kojiishi 
> Chrome with new engine enabled (enable "LayoutNG" in chrome://flags) do the right shaping too

You're right. "LayoutNG" enabled in Chrome. Both examples are OK now. Thank you.

**Comment by fantasai** [comment] 2018-10-15 05:53
@svgeesus I believe your concerns are already handled by the current spec: https://www.w3.org/TR/css-text-3/#boundary-shaping

@r12a: Afaict, your list differs from the one in the spec in these respects:
    
    * don't break across borders (but do across margins/padding)
    * don't break due to changes in text-decoration
    * don't break due to first-letter styling
   * don't break due to font color, style, weight, etc.
   
The first case, I disagree with. Borders and padding must be treated the same way. If you want to draw a box around a character without affecting anything, use 'outline' instead.

The second case, we should clarify. Done in https://github.com/w3c/csswg-drafts/commit/5b26dfb9655b7963b9809854b96d2028954fed63 .

The third case, :first-letter should be treated the same as any other inline box, and should already be covered by this statement: "Text shaping must not be broken across inline box boundaries when there is no change in formatting.". If your'e talking about an element with 'initial-letter' formatting, that's covered in the spec for 'initial-letter', see https://drafts.csswg.org/css-inline-3/#initial-letter-shaping

The fourth case really needs to be limited by the font technology. A color change partway through a ligature is not likely to work out. Switching font styles ends the text run, and if the platform doesn't offer an API to pass in context (like Harfbuzz was recently updated to do), then trying to get contextual shaping to do will not be possible and trying to hack it by clipping rendered text that includes the context would be crazy. Arabic shaping is a much simpler sort of contextual shaping in the sense that we can easily force the renderer to give us initial/medial/final/isolated forms as required, but in more calligraphic fonts we won't be able to maintain the shaping across font changes in any reasonable way.

So afaict the only thing that should change here is clarifying text decoration, and maybe giving some examples of what's reasonable vs. not.

Let me know if that's acceptable.

**Comment by r12a** [comment] 2018-11-12 16:29
> If you want to draw a box around a character without affecting anything, use 'outline' instead.

i was unaware of the outline property (!). Ok then.

> A color change partway through a ligature is not likely to work out....

Sure, there are things that are more difficult, and content authors are not likely to try that, if it doesn't. But highlighting signs as shown here for devanagari is not an extraordinary ask, and should continue to be feasible, given an appropriate font:

![screen shot 2018-11-12 at 16 25 02](https://user-images.githubusercontent.com/4839211/48360618-888a1100-e697-11e8-973b-7f01e42ae63a.png)

![screen shot 2018-11-12 at 16 26 39](https://user-images.githubusercontent.com/4839211/48360745-cbe47f80-e697-11e8-9695-3b669cd2be4e.png)

> The third case, :first-letter should be treated the same as any other inline box, and should already be covered by this statement: "Text shaping must not be broken across inline box boundaries when there is no change in formatting."

I begin to wonder what is the meaning of 'change in formatting' if first-letter styling doesn't result in any??  What would be the point in using first-letter unless it changed the formatting?  Can you make that clearer?

**Comment by r12a** [comment] 2018-11-14 06:08
Sure, i understand that, but the example you give is not a particularly useful thing to do.  I suspect that much of the time one will apply first-letter in order to change the formatting (see the image at https://github.com/w3c/csswg-drafts/issues/698#issuecomment-297472304).

We have https://drafts.csswg.org/css-inline-3/#initial-letter-shaping saying that 

> When initial-letters is not normal, shaping should still occur across an inline initial letter box’s boundaries. ... For example, if the first letter of the Farsi word “پس” were styled with initial-letters: 2 1, both letters would be styled in their joined forms, with initial-form “ﭘ” as the initial letter, followed by the normally-styled final-form “ﺲ”. **Note that the two letters might not always graphically connect, even when shaped in their joining forms.**  (my emphasis)

But we have https://drafts.csswg.org/css-text/#boundary-shaping saying that

> Text shaping must be broken at inline box boundaries when any of the following are true for any box whose boundary separates the two typographic character units: Any of margin/border/padding separating the two typographic character units in the inline axis is non-zero. ...

The two things seem to be contradictory, or at least to warrant some additional explanation.

**Comment by fantasai** [comment] 2018-12-04 23:49
@r12a 
> Sure, i understand that, but the example you give is not a particularly useful thing to do. I suspect that much of the time one will apply first-letter in order to change the formatting

Well, yes. But we still have to define what happens in all cases. This is a Web Platform spec after all. :)

Wrt `initial-letter` vs regular inlines, were were made aware that the specific requirements around initial letter formatting that requires shaping across that boundary, so that's explicitly specced. Initial letter formatting is a specialized form of layout, and is different form inline layout. (I also want to point out that initial letter styling and :first-letter styling are not the same thing. Initial letter styling can be applied to spans, and :first-letter elements are just like spans and not like initial letters unless they're explicitly styled as initial letters.)

Agenda+ to ask the WG if we should have margins/borders/padding _not_ affect shaping in regular inlines, as Firefox now appears to do. @jfkthame Any opinions? [testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?%3C!DOCTYPE%20html%3E%0A%3Cspan%20style%3D%22margin%3A%201em%22%3E%D9%86%D9%88%D8%B4%3C%2Fspan%3E%D8%AA%D9%86)

**Comment by jfkthame** [comment] 2018-12-05 02:13
The WG [decided](http://www.w3.org/2014/09/08-css-irc#T08-02-24) several years ago that non-zero margins/borders/padding *should* interrupt shaping at inline boundaries; the fact that Firefox currently applies shaping across these is simply a [Gecko bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1064172) and we should fix it. (I thought I had an experimental patch for this somewhere, even; maybe I can resurrect it.)

**Comment by fantasai** [comment] 2018-12-05 08:03
@jfkthame Right, but @r12a seems to be challenging that decision so wanted to ask your opinion.

**Comment by jfkthame** [comment] 2018-12-05 12:22
> @jfkthame Right, but @r12a seems to be challenging that decision so wanted to ask your opinion.

IIUC, this was mostly about font-related properties (size, weight, etc); he then mentioned border as well:

> Note also that a border doesn't break the joining behaviour in Firefox and Edge. This perhaps seems like reasonable behaviour for highlighting items, and i wonder whether we should drop that from the list of things that break shaping? I suppose the argument (as for margins and padding) is that this might have been a block element that has been added inline. It seems a pity, however, that such a possibility would rule out the ability to put a border around one character in a cursive sequence using inline markup when wanted.

but the hypothetical use-case suggested here would be better served by outline, IMO.

I think the properties that introduce visual separation between the adjacent elements (so any of margin/border/padding at the relevant side) *should* indeed interrupt shaping, and I've seen sites where the current Firefox behavior of shaping across such gaps results in broken rendering. People do things like navigation or menu bars across a page:

    <div class="nav"><a>home</a><a>away</a></div>

and apply margins to the `<a>` elements to spread them across the line, and when Firefox applies shaping across the resulting gaps, the result looks terrible. (I don't have a bug number to hand but we've had real-world reports of this.)

**Comment by jfkthame** [comment] 2018-12-05 12:35
> Sure, i understand that, but the example you give is not a particularly useful thing to do. I suspect that much of the time one will apply first-letter in order to change the formatting (see the image at [#698 (comment)](https://github.com/w3c/csswg-drafts/issues/698#issuecomment-297472304)).
> 
> We have https://drafts.csswg.org/css-inline-3/#initial-letter-shaping saying that
> 
> > When initial-letters is not normal, shaping should still occur across an inline initial letter box’s boundaries. ... For example, if the first letter of the Farsi word “پس” were styled with initial-letters: 2 1, both letters would be styled in their joined forms, with initial-form “ﭘ” as the initial letter, followed by the normally-styled final-form “ﺲ”. **Note that the two letters might not always graphically connect, even when shaped in their joining forms.**  (my emphasis)
> 
> But we have https://drafts.csswg.org/css-text/#boundary-shaping saying that
> 
> > Text shaping must be broken at inline box boundaries when any of the following are true for any box whose boundary separates the two typographic character units: Any of margin/border/padding separating the two typographic character units in the inline axis is non-zero. ...
> 
> The two things seem to be contradictory, or at least to warrant some additional explanation.

If the first letter is styled with a different font-size, font-family, etc it's entirely possible it won't actually connect to the next letter even when the appropriate contextual forms are used; I think that's what the emphasized sentence above is pointing out.

Adding margin or border around the letter, OTOH, would be a cause for *not* shaping between the initial letter and following text.

Raised caps are an interesting edge case, where I guess it's reasonable to maintain joining as the baseline isn't changed and no horizontal separation is being introduced (though it seems an unlikely thing for someone to really want to do in such a script).

The few examples I've seen of traditional practice (see https://github.com/w3c/csswg-drafts/issues/698#issuecomment-297472304 and the linked discussion) don't appear to support shaping across more general drop-cap-like formatting: the large dropped, boxed initial in https://upload.wikimedia.org/wikipedia/commons/6/6a/Hafezeshamlu02.jpg, for example, is *not* shaped in an initial form.

**Comment by fantasai** [comment] 2018-12-06 01:16
Closing out as a mix of Editorial and Wontfix per https://github.com/w3c/csswg-drafts/issues/698#issuecomment-429716817 and WG resolution supporting @jfkthame's position that margin/border/padding should break shaping across boundaries.

Wrt https://github.com/w3c/csswg-drafts/issues/698#issuecomment-444470317 about shaping initial letters, re-opening https://github.com/w3c/csswg-drafts/issues/2399 and copying over @jfkthame's comment.

@r12a If you want something changed here or would like to object to the resolution, please open a new issue. This one has turned into issue salad.

**Comment by r12a** [comment] 2018-12-06 15:11
> @jfkthame Right, but @r12a seems to be challenging that decision so wanted to ask your opinion.

Not correct. @jfkthame said earlier

> The WG decided several years ago that **non-zero** margins/borders/padding should interrupt shaping at inline boundaries;

(my emphasis) which is fine by me.  I was only suggesting that **zero** m/b/p should not interrupt, but i think i'm fine breaking for any m/b/p – particularly now that i know that the outline property can be used for drawing around things. (see above)

The i18n WG will keep our tracker issue open until we've seen the edited text.  Btw, it would be nice if you could briefly summarise the conclusions reached (preferably before closing the issue), wrt the other aspects.

PS: Please don't open another issue to continue this discussion. Apart from a small but mostly relevant digression into first-letter, i don't see any salad. The really useful thing about github issue threads is that you don't have to go chasing all over the place to find the discussion about a particular topic/request.

**Comment by fantasai** [comment] 2018-12-07 00:37
>  I was only suggesting that zero m/b/p should not interrupt, but i think i'm fine breaking for any m/b/p

Unfortunately, due to some historical decisions made back in the 90s, we can't distinguish between zero m/b/p and no m/b/p, so indeed zero m/b/p will not interrupt because it's the default case. :P

>  i don't see any salad

Heh. Here, I'll sort it into piles for you so you can see how many different issues have been raised in this thread:

<h4>1. font-weight / font-style / font-size changes should break shaping</h4>

@r12a raised this request in the OP, but later retracted in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-295383826 and confirmed in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-387814460

<h4>2. Borders should not break shaping</h4>

@r12a raised this in the OP, reiterated in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-295383826 and https://github.com/w3c/csswg-drafts/issues/698#issuecomment-387814460
fantasai objects to borders being handled differently than margins and padding in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-407588131 and https://github.com/w3c/csswg-drafts/issues/698#issuecomment-429716817
CSSWG had resolved that non-zero margins/borders/padding must break shaping in http://www.w3.org/2014/09/08-css-irc#T08-02-24. CSSWG re-resolves that non-zero margins/borders/padding break shaping in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-444700062 backed by Jonathan Kew's arguments in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-444467145
@r12a accepts that the 'outline' property is a sufficient substitute for his use cases for border in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-437944436 and verifies acceptance of the CSSWG decision in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-444904200

<h4>3. Spec should lock down when shaping occurs</h4>

@behnam asserts the spec is too lenient in not requiring shaping in all cases where it would make sense in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-297472304
@behdad requests in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-297543175 that the spec call out changes which must not break shaping; the spec already tries to do this to the extent it can without listing all CSS properties which would be an extremely long and increasingly incomplete list. @bedad also requests that in other cases the correct behavior is suggested; the spec also does this already.
@fantasai points out that “shaping” is a much broader topic than the choice of isolated/initial/medial/final forms in Arabic and that the current spec text is the result of discussions in thread at https://lists.w3.org/Archives/Public/www-style/2014Aug/0217.html (consolidated view at https://www.w3.org/Mail/flatten/index?subject=Shaping+Isolation+and+Layout+Separation+of+Inlines&list=+www-style )
@r12a proposes list at https://github.com/w3c/csswg-drafts/issues/698#issuecomment-387814460
@fantasai points out that all font changes need to be handled the same way in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-407588131 @svgeesus concurs in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-427797013
@fantasai reiterates the limitations of what shaping can do across font changes in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-427797013 and points out that breaking Arabic shaping would be a spec violation even under the current intentionally-not-entirely-deterministic text. Adds examples to the spec in https://github.com/w3c/csswg-drafts/commit/dfa85aadd56d7743341c2f3acf5d4a7fd65bb4f3#diff-2eb05d513690e5c4031fdea92fa32604
Current state of the spec text, fwiw, is https://www.w3.org/TR/css-text-3/#boundary-shaping

<h4>4. Allow explicit control over shaping isolation</h4>

@behnam requests explicit control over shaping isolation in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-297472304
This point was missed in the replies, but the answer there is that `unicode-bidi: isolate` can already enforce isolation (usually the desire for shaping isolation will coincide with the desire for bidi isolation). So far we haven't see any strong use cases for either a) an independent switch to trigger isolation b) a switch to enforce joining across a boundary where we're currently requiring a break. Hence, my conclusion is no change to the specs for this point.

<h4>5. Initial letters should join to adjacent content</h4>

@behnam raised this in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-297472304
@r12a requests clarification in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-297693106
@beham confirms in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-297796468
@fantasai files https://github.com/w3c/csswg-drafts/issues/2399 to track this issue
@r12a complains that inline margin/border/padding is handled differently than initial letter margin/border/padding in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-438549364
@jfkthame requests the opposite behavior (that initial letters *not* join to adjacent content) in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-444470317
@fantasai copies @jfkthame's comment into https://github.com/w3c/csswg-drafts/issues/2399

<h4>6. Text decoration should not break shaping</h4>

@r12a proposes that the spec explicitly say that text decoration not break shaping
@fantasai accepts in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-387814460 and commits changeset https://github.com/w3c/csswg-drafts/commit/5b26dfb9655b7963b9809854b96d2028954fed63

<h4>7. Color changes within grapheme clusters</h4>

Side discussion on color changes within clusters (for various definitions of clusters) starts in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-429716817, continues in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-437944436, and gets pushed out to https://github.com/w3c/csswg-drafts/issues/699

<h4>8. :first-letter should not break shaping</h4>

(Note that :first-letter styling is not synonymous with initial letter formatting. :first-letter styling is the styling of an inline box (similar to a span) which is automatically generated around the first letter of a paragraph. Initial letter styling is a type of special formatting--effectively a different `display` type--that is sometimes but not exclusively applied to :first-letter pseudo-elements.)

@r12a asserts that :first-letter should not break shaping in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-387814460
@fantasai points out that whether :first-letter breaks or does not break shaping depends on the style rules applied to the :first-letter, and that this behavior is already defined since it is (per spec) identical to the requirements applied to any other inline element (such as a SPAN), see https://github.com/w3c/csswg-drafts/issues/698#issuecomment-429716817
@r12a seems confused about this point in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-437944436 @frivoal attempts to clarify in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-438541355 This thread continues in https://github.com/w3c/csswg-drafts/issues/698#issuecomment-438549364 and https://github.com/w3c/csswg-drafts/issues/698#issuecomment-444303748

Essentially this sub-issue is invalid. I suppose I can add a “Closed as Invalid” tag to the soup here.

<hr>

As we can see here, there are at least 8 separate sub-issues discussed in this issue. I think I'm thoroughly justified in calling it an issue salad. :)

**Comment by r12a** [comment] 2018-12-11 16:45
I guess it depends on the vantage-point of the reader.  For me, those are all just facets of the discussion that addresses the original comment, where i was asking, essentially "what things should or shouldn't break cursive joining behaviour". It wasn't just about border.

So the summary appears to be that which is currently stated in the spec as of https://www.w3.org/TR/2018/WD-css-text-3-20181206/#boundary-shaping. Good.

**Comment by fantasai** [comment] 2018-12-12 01:00
And a salad is just a single dish, but the chef still has to prep each ingredient independently. ;) OK, then, closing out as Commenter Satisfied!

Initial letter discussion continues in https://github.com/w3c/csswg-drafts/issues/2399 Note: Current status of that issue is that @behnam and @jfkthame are arguing for opposite behavior, so we're going to need some help sorting it out. :)

**Closed by fantasai** 2018-12-12 01:00 UTC
Labels: Closed Accepted as Editorial, Closed Rejected as Invalid, Closed Rejected as Wontfix by CSSWG Resolution, Commenter Satisfied, Tracked in DoC, css-text-3, i18n-alreq, i18n-comment
