### ISSUE TITLE
[css-fonts-4] font-stretch valid values.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2591] opened 2018-04-17 15:20 UTC
https://drafts.csswg.org/css-fonts-4/#font-stretch-prop says:

> Values less than 0% are not allowed and are treated as parse errors.

However Safari and Chrome at least treat `0%` as invalid:

> CSS.supports('font-stretch', '0%') -> false
> CSS.supports('font-stretch', '10%') -> true

What's the expected thing here? Is it a typo in the spec, or should 0% really be allowed, and thus a bug in WebKit / Blink?

cc @litherum

**Comment by jfkthame** [comment] 2018-04-17 15:25
Interestingly, in Chrome i get true for

    CSS.supports('font-stretch', '0.000000000000000000000000000000000000000000001%')

even though such a tiny value appears to compute to 0%.

**Comment by jfkthame** [comment] 2018-04-17 21:30
I checked MSEdge, and confirmed that `CSS.supports('font-stretch', '0%')` returns `true`, as per spec. (And correctly returns `false` for negative values.)

**Comment by drott** [comment] 2018-04-18 09:30
Yes, if we the spec stays unchanged, it's a bug in Chrome, [we reject for <= 0, should be easy to fix by changing the parse-time check](https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/css/properties/css_parsing_utils.cc?type=cs&sq=package:chromium&l=1567). It's a different discussion how much sense is in 0% as a stretch value.

**Comment by tabatkins** [comment] 2018-04-18 17:34
Doesn't matter whether it makes sense or not; percentages are floats, and so disallowing 0% would make the valid syntax an open range, which is disallowed as a general spec-design rule.  (For example, it makes it unclear what value `font-stretch: calc(-10%)` should clamp to.) 

Given that this is just a factor in the font-selection, not something used directly, there's nothing wrong with 0%; it just means you'll select the narrowest available font.

**Comment by tabatkins** [comment] 2018-04-18 17:35
Closing because the spec is clear, Chrome just has a bug.

**Closed by tabatkins** 2018-04-18 17:35 UTC
Labels: Closed Rejected as Invalid, css-fonts-4

**Comment by drott** [comment] 2018-04-19 09:37
> [...] and so disallowing 0% would make the valid syntax an open range, which is disallowed as a general spec-design rule. (For example, it makes it unclear what value font-stretch: calc(-10%) should clamp to.)

Thanks for the clarification, makes sense.
