### ISSUE TITLE
[cssom] [css-cascade] Legacy shorthands never appearing on cssText has unfortunate effects when variable references are involved.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#3332] opened 2018-11-17 09:56 UTC
https://drafts.csswg.org/css-cascade-4/#legacy-shorthand means that for:

```html
<div style="page-break-after: var(--a)"></div>
```

The following happens:

```js
div.style.cssText == "break-after:;"
```

It's a bit unfortunate, but maybe it's ok, given this is a more general issue (#2515), and these shorthands are supposed to be legacy anyway. We could fix legacy shorthands by special-casing them and saying that they serialize in this case, but that's not necessarily great, and certainly propagates the weirdness a bit more in the implementation.

**Comment by upsuper** [comment] 2018-11-18 09:39
It's probably more a duplicate of #2515 since they are both about shorthand serialization. But legacy shorthand might be easier to resolve than #2515 if we want to special-case it... It just doesn't seem to be worth it as you said.

**Comment by tabatkins** [comment] 2021-01-13 20:16
This does indeed appear to just be a duplicate of #2515, so we'll go ahead and close this one.

**Closed by tabatkins** 2021-01-13 20:16 UTC
Labels: css-cascade-4, cssom-1
