### ISSUE TITLE
[css-writing-modes] Orthogonal Flow Constraint: viewport vs scroller

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#1391] opened 2017-05-18 00:17 UTC
Was going through old action items and found [this one](https://lists.w3.org/Archives/Public/www-style/2014Dec/0301.html):

> ACTION fantasai: Put IE's nearest-scrollable-box behavior into orthogonal flows spec

Specifically

>  Rossen: What we do, basically the obvious pitfall is we say it's shrink to fit, assuming you do layout for shrink to fit.  If you, let's assume you have one long line of text. You don't want shrink to fit that's one long line of text.
> Rossen: I believe there's text in writing modes that spec if you have no height in the orthogonal switch you cap that to the viewport. We do nearest scrollable box of viewport.
>  Rossen: We discovered with orthogonal flow, the cases are mostly having some kind of webpage where you scroll down and find an example of vertical text. The idea is you want to be able to see that in your screen. You don't want to have to scroll both ways. In our implementation we cap the size of the vertical orthogonal content to be the min of your nearest scrolling ancestor and your viewport.
>  Rossen: With that in mind you can go and compute your min and max size. You need to define that. Max size can be the layout that you would produce when you cap content at the min.
> Rossen: The min of the content would be the cap size, the viewport or nearest scrolling.
>  Rossen: That's a fairly good result in almost all practical cases. I'm pretty sure you're looking to avoid where you have the min and max to be one line height.

Testcase: data:text/html;charset=utf-8;base64,PCFET0NUWVBFIGh0bWw%2BDQo8c3R5bGU%2BDQogIGRpdiB7IGJvcmRlcjogc29saWQ7IGhlaWdodDogMTAwcHg7IG92ZXJmbG93OiBzY3JvbGw7IH0NCiAgcCB7IHdyaXRpbmctbW9kZTogdmVydGljYWwtcmw7IH0NCjwvc3R5bGU%2BDQoNCjxkaXY%2BDQogIDxwPkEgQiBDIEQgRSBGIEcgSCBJIEogSyBMIE0gTiBPIFANCjwvZGl2Pg%3D%3D

The spec says to use the initial containing block size.
Firefox and Chrome apparently use the nearest scroller size.
It sounds like Edge does something a bit more complex, more like min(scroller, viewport).

In any case, I agree with Rossen that referencing the nearest scroller is better than just using the initial containing block size, and since we have two implementations of that, we should fix the spec.

We can also, in the future, look into intersecting that size with intervening scrollers as described in those minutes, but I'm a bit less convinced of that (since it's less predictable for the author what's happening).

Agenda+ for WG approval to update the spec to match implementations and use the nearest scroller instead of the ICB.

**Comment by atanassov** [comment] 2017-05-24 16:20
The CSS Working Group just discussed [css-writing-modes] Orthogonal Flow Constraint: viewport vs scroller, and agreed to the following resolutions:
RESOLVED: shrink-to-fit formula for auto-sized orthogonal flows uses nearest scrollable ancestor, not necessarily viewport
The full IRC log of that discussion
<zcorpan> Topic: [css-writing-modes] Orthogonal Flow Constraint: viewport vs scroller
<Rossen_> https://github.com/w3c/csswg-drafts/issues/1391
<zcorpan> fantasai: Realized that I hadn't done ???
<Rossen_> Github issue: https://github.com/w3c/csswg-drafts/issues/1391
<zcorpan> fantasai: we have 2 impl and a test that i need to check in
<zcorpan> fantasai: the issue is about when you have orthogonal flows and a scroller
<zcorpan> fantasai: normally when htere's no constraint of the child... the height is determined by a shink-to-fit formula
<zcorpan> fantasai: better to use the hight of the nearest ancestor
<zcorpan> Rossen_: I recall discussing this
<fantasai> s/nearest ancestor/nearest scrollable ancestor/
<zcorpan> Rossen_: we already agreed to do this for the reasons you outline
<zcorpan> Rossen_: are there any other opinions or alternative proposals?
<zcorpan> Rossen_: if not we can just resolve
<zcorpan> Rossen_: I will take that as a no
<fantasai> RESOLVED: shrink-to-fit formula for auto-sized orthogonal flows uses nearest scrollable ancestor, not necessarily viewport
<zcorpan> Rossen_: Does that change go to Level 1?
<fantasai> s/1/3/
<zcorpan> Rossen_: any other knobs or switches ?
<zcorpan> fantasai: we have the change, the WG resolution, test case and implementations
<zcorpan> Rossen_: ok great
<Rossen_> Github topic: https://github.com/w3c/csswg-drafts/issues/708

**Comment by dbaron** [comment] 2017-05-24 16:20
The CSS Working Group just discussed `[css-writing-modes] Orthogonal Flow Constraint: viewport vs scroller`, and agreed to the following resolutions:

* `RESOLVED: shrink-to-fit formula for auto-sized orthogonal flows uses nearest scrollable ancestor, not necessarily viewport`

<details><summary>The full IRC log of that discussion</summary>
&lt;zcorpan> Topic: [css-writing-modes] Orthogonal Flow Constraint: viewport vs scroller<br>
&lt;Rossen_> https://github.com/w3c/csswg-drafts/issues/1391<br>
&lt;zcorpan> fantasai: Realized that I hadn't done ???<br>
&lt;Rossen_> Github issue: https://github.com/w3c/csswg-drafts/issues/1391<br>
&lt;zcorpan> fantasai: we have 2 impl and a test that i need to check in<br>
&lt;zcorpan> fantasai: the issue is about when you have orthogonal flows and a scroller<br>
&lt;zcorpan> fantasai: normally when htere's no constraint of the child... the height is determined by a shink-to-fit formula<br>
&lt;zcorpan> fantasai: better to use the hight of the nearest ancestor<br>
&lt;zcorpan> Rossen_: I recall discussing this<br>
&lt;fantasai> s/nearest ancestor/nearest scrollable ancestor/<br>
&lt;zcorpan> Rossen_: we already agreed to do this for the reasons you outline<br>
&lt;zcorpan> Rossen_: are there any other opinions or alternative proposals?<br>
&lt;zcorpan> Rossen_: if not we can just resolve<br>
&lt;zcorpan> Rossen_: I will take that as a no<br>
&lt;fantasai> RESOLVED: shrink-to-fit formula for auto-sized orthogonal flows uses nearest scrollable ancestor, not necessarily viewport<br>
&lt;zcorpan> Rossen_: Does that change go to Level 1?<br>
&lt;fantasai> s/1/3/<br>
&lt;zcorpan> Rossen_: any other knobs or switches ?<br>
&lt;zcorpan> fantasai: we have the change, the WG resolution, test case and implementations<br>
&lt;zcorpan> Rossen_: ok great<br>
&lt;Rossen_> Github topic: https://github.com/w3c/csswg-drafts/issues/708<br>
</details>

**Comment by fantasai** [comment] 2017-07-19 02:23
Official minutes at https://lists.w3.org/Archives/Public/www-style/2017May/0057.html
This has now been edited.

**Comment by fantasai** [comment] 2017-07-19 21:53
Reopening because dbaron points out that the nearest scroll container could be an auto-height element, and further testing reveals we have no interop on this.

**Comment by frivoal** [comment] 2017-09-20 00:45
This may not necessarily change our conclusion, but I've found something that wasn't discussed as far as I remember, and doesn't show in the minutes.

Some current implementations go further than what we suggested, and do clamp at non-fixed sized scrollers as well, at least in some cases:

In this example, which has a non fixed sized scrolled with a max-height:
http://jsbin.com/gekebob/edit?html,css,output

* Firefox / Edge do what we said, and reach for the ICB
* Chrome sizes to the scroller at max height
* Safari almost sizes to the scroller at max height, but misses because it forgets to take the child's border into account.

So, are we happy with the resolution as is, or do we want to add "non-fixed height scrollers with a fixed max-height" as well to the list of things you clamp to?

**Comment by fantasai** [comment] 2017-09-20 17:02
I wouldn't add it to the list, but I think switching to "nearest ancestor scroll container with fixed height or max-height" would be fine.

**Comment by frivoal** [comment] 2017-09-20 17:12
That would work for me. Also, if we write the test without borders, we have two passing implementations (Chrome and Safari).

**Comment by frivoal** [comment] 2018-01-28 13:42
Spec change and Test cases merged. Closing.

**Closed by frivoal** 2018-01-28 13:42 UTC
Labels: Closed Accepted by CSSWG Resolution, Commenter Satisfied, css-writing-modes-3, css-writing-modes-4
