### ISSUE TITLE
[css-scoping-1] Drop :host-context

### ISSUE THREAD

**Issue by rniwa** [w3c/csswg-drafts#3699] opened 2019-03-01 22:25 UTC
Splitting the discussion from https://github.com/w3c/csswg-drafts/issues/1915, as we've repeatedly said in the past, we don't think changing the style of an element based on where it appears is a good practice to design a re-usable element in general, and this particular feature poses a significant implementation complexity & cost as pointed out by @emilio in https://github.com/w3c/csswg-drafts/issues/1915#issuecomment-467590316.

We propose to drop this feature from the specification as we've previously requested.

**Comment by rniwa** [comment] 2019-03-01 22:25
@hober @smfr @litherum

**Comment by emilio** [comment] 2019-03-01 23:40
Dupe of https://github.com/w3c/csswg-drafts/issues/1914?

**Comment by tabatkins** [comment] 2019-03-01 23:49
Yeah, dupe.

Note @emilio's comment in #1914; we'll put in usage counters to see if it's easily droppable or if it should be reviewed more closely.  I filed <https://bugs.chromium.org/p/chromium/issues/detail?id=936225> to track it.

**Closed by tabatkins** 2019-03-01 23:49 UTC
