### ISSUE TITLE
https://drafts.csswg.org/ broken

### ISSUE THREAD

**Issue by sideshowbarker** [w3c/csswg-drafts#6528] opened 2021-08-19 17:26 UTC
2022-09-10 Update: https://w3c.github.io/csswg-drafts/ now exists as an alternative (thanks to @tabatkins and based on @andreubotella’s system from https://github.com/andreubotella/csswg-auto-build/).

So if you can’t access a CSS spec at a particular drafts.csswg.org URL, replace `drafts.csswg.org` in the URL with `w3c.github.io/csswg-drafts` and you’ll have what you need.

**Comment by plinss** [comment] 2021-08-19 17:55
Should be back up momentarily

**Comment by SebastianSimon** [comment] 2021-09-03 21:34
<https://drafts.csswg.org/> still (or again) says _“No specification drafts in the repository.”_.

**Comment by tabatkins** [comment] 2021-09-03 21:38
It's "again" - the server was hanging on a drafts update. I've kicked it, should be fixed in a bit. (In the meantime, the individual drafts do work.)

**Comment by Crissov** [comment] 2021-09-07 07:40
Again

**Comment by Elchi3** [comment] 2022-02-10 14:14
Broken again

**Comment by sideshowbarker** [comment] 2022-02-11 23:36
Down still (or again)

**Comment by faceless2** [comment] 2022-02-15 11:57
Broken again

**Comment by svgeesus** [comment] 2022-02-15 15:27
[Still broken](https://drafts.csswg.org/)

**Comment by svgeesus** [comment] 2022-02-15 16:36
Seems to be working now

**Comment by faceless2** [comment] 2022-02-25 17:20
Sorry to report, dead again: https://drafts.csswg.org/css-page-3/

**Comment by faceless2** [comment] 2022-02-25 17:59
Seems fixed, thanks!

**Comment by faceless2** [comment] 2022-03-01 16:36
Broken again

**Comment by sideshowbarker** [comment] 2022-03-08 09:03
Broken again

**Comment by sideshowbarker** [comment] 2022-03-10 09:02
Broken again

**Comment by upsuper** [comment] 2022-05-07 10:09
Broken again

**Comment by SebastianZ** [comment] 2022-05-13 10:43
Broken again, unfortunately.

**Comment by sideshowbarker** [comment] 2022-05-17 07:11
> WARNING: mysqli_connect(): (HY000/1135): Can't create a new thread (errno 11 "Resource temporarily unavailable"); if you are not out of available memory, you can consult the manual for a possible OS-dependent bug

**Comment by Schweinepriester** [comment] 2022-05-20 18:23
Broken again…
https://drafts.csswg.org/css-images-4/#the-object-view-box
![image](https://user-images.githubusercontent.com/2644614/169589723-25b8e57b-c454-467c-997c-c686e4a72266.png)

**Comment by astearns** [comment] 2022-05-24 14:42
Broken again. please leave this pinned so we can find it easily (until we get this recurring issue fixed)

**Comment by sideshowbarker** [comment] 2022-05-27 01:22
again

**Comment by sideshowbarker** [comment] 2022-05-27 11:39
again

**Comment by SebastianZ** [comment] 2022-06-11 21:32
Broken again, unfortunately.

Sebastian

**Comment by rik** [comment] 2022-06-13 09:52
Seems broken again. https://drafts.csswg.org is empty and https://drafts.csswg.org/css-images-4 lists a directory.

**Comment by bramus** [comment] 2022-06-13 13:46
Fixed again.

**Comment by SebastianZ** [comment] 2022-06-14 10:57
And again.

**Comment by SebastianZ** [comment] 2022-06-16 09:40
Again...

**Comment by svgeesus** [comment] 2022-06-16 10:25
![image](https://user-images.githubusercontent.com/2506926/174050724-20e90e9b-30b8-413d-a18f-b1eedb847d91.png)

**Comment by plinss** [comment] 2022-06-17 06:32
@bramus the best help would be funding. I can do the work, I just can't take unpaid time off from my day job to do it (and probably can't afford the amount of time it would take to onboard someone new either). Unfortunately there's a lot more to do than some simple PHP coding, most of the back end is in Python2, which needs to be ported to 3, the OS needs to be upgraded, multiple apps need to be tested newer versions of PHP, the API back end should be ported from PHP to Python, etc. Then there's the changes to support static builds to reduce DB loads. The list goes on. The server hasn't had any real love in many years. The work has been mapped out, there's nothing to design, it just needs the time to do it.

There's been a lot of talk about funding, just no $$ appearing anywhere.

**Comment by svgeesus** [comment] 2022-06-21 09:28
again

**Comment by svgeesus** [comment] 2022-06-21 14:08
healed

**Comment by sideshowbarker** [comment] 2022-06-21 22:10
again

**Comment by plinss** [comment] 2022-06-21 23:04
Looks fine to me.

> **Note**: The server sometimes becomes unresponsive under heavy load. This is a known issue and it will resolve on its own (and go away once we can do the server upgrades).

Let's please reserve this issue for when the server needs human attention. e.g.:
* You're seeing a 'No specifications in the repository' message
* You're seeing a message like 'unable to contact the database server'
* The server has been unresponsive for a long time (over an hour)

When issues like those happen, either the database server fell over, or DB connection exhaustion caused a background process to fail (requiring it to be manually restarted), or the server is under a long-term 'DDOS' attack (usually a lot of crawlers more than a genuine attack) and firewall rules need to be tweaked.

**Comment by svgeesus** [comment] 2022-06-22 12:21
Down again while link-checking just now for publication.

**Comment by faceless2** [comment] 2022-06-25 22:50
again - https://drafts.csswg.org/css-pseudo-4/

**Comment by svgeesus** [comment] 2022-06-27 15:52
again

**Comment by faceless2** [comment] 2022-06-28 08:32
again

**Comment by faceless2** [comment] 2022-06-28 08:36
healed

**Comment by devongovett** [comment] 2022-07-11 18:10
again

**Comment by r12a** [comment] 2022-07-12 11:14
seem broken again now

**Comment by romainmenke** [comment] 2022-07-13 18:19
still broken or broken again.
Got a directory listing first and 500 after a long time.

**Comment by plinss** [comment] 2022-07-14 18:09
@NiedziolkaMichal the purpose of this issue is *not* to note the fact that the draft server goes down sometimes, but to notify those that can fix it when it needs attention.

The root cause is well understood and we've all been aware of the problem for a long time, we're not oblivious. 

&lt;rant>This has all been said before, but apparently needs to be said again. Fixing the server requires about a person-month of engineering effort. The issue has been that the person maintaining this server (me) is not sponsored to do **any** work for W3C. So in addition to the ~1 day per week I spend on CSSWG and TAG work I do on my own time, paying for this server out of my own pocket, and paying all my own travel expenses for F2F meetings, asking me to take a month of additional unpaid time off to fix the server is going a bit too far. No one else has stepped up to do the work, and only one person so far has offered to fund the engineering work. That funding effort is under way and once it's in place the server will get properly fixed.

Until then, re-raising complaints about the lack of reliability of a service that's completely free to you, but costs **me** time _and_ money, that have already been made ad-infinitum, is not helpful.&lt;/rant>

**Comment by sideshowbarker** [comment] 2022-07-15 02:10
Given the state of things here, I’ve raised https://github.com/w3c/csswg-drafts/issues/7500 with a specific concrete proposal that we consider replacing the current https://drafts.csswg.org/ backend with the backend from https://andreubotella.com/csswg-auto-build/.

But but more broadly, I’ve framed that issue as a detailed problem description, with a suggestion that we use it to discuss what our actual user requirements are for the site, and how we could best address those user needs.

**Comment by svgeesus** [comment] 2022-07-15 09:20
Down again just now

**Comment by svgeesus** [comment] 2022-07-15 09:57
Is back up

**Comment by binyamin** [comment] 2022-08-05 14:59
FYI, it's down again

**Comment by mitchellevan** [comment] 2022-08-11 12:23
Only a directory listing is appearing at https://drafts.csswg.org/css-nav-1/

**Comment by bramus** [comment] 2022-08-12 22:35
Down again.

**Comment by bramus** [comment] 2022-08-13 21:32
Down.

**Comment by plinss** [comment] 2022-08-13 21:33
Up for me.

**Comment by bramus** [comment] 2022-08-16 09:06
Down.

**Comment by upsuper** [comment] 2022-08-18 06:03
I think it's down again.

**Comment by plinss** [comment] 2022-08-18 06:04
Kicked, should be back in a few minutes

**Comment by upsuper** [comment] 2022-08-18 06:09
Yeah, it's back now. I just realized I didn't reopen it, so no need to close it either :D

**Comment by queengooborg** [comment] 2022-08-18 19:59
Aaaaaand it's down again... ;P

**Comment by plinss** [comment] 2022-08-18 20:29
up again

**Comment by queengooborg** [comment] 2022-08-20 03:31
May I recommend that this issue remain open until the core problem is resolved?  I don’t think this should be closed when the site temporarily comes back up, and I think that closing the issue gives off the wrong idea that the issue is permanently resolved.

**Comment by plinss** [comment] 2022-08-20 04:48
No, because as stated previously, the purpose of this issue is to notify the site maintainers when the site needs attention. There's no point in tracking the fact that the issue isn't yet permanently resolved when we all already know that.

FWIW, the paperwork for the funding to fix the server is just about done and work should start next week or so.

**Comment by SebastianZ** [comment] 2022-08-20 10:15
@plinss Is there a way to keep track of your progress fixing the server?

Sebastian

**Comment by plinss** [comment] 2022-08-20 18:06
I'll be giving updates to the WG as progress is made

**Comment by bramus** [comment] 2022-08-22 09:39
Down.

**Comment by svgeesus** [comment] 2022-08-23 10:38
Down

**Comment by hua03** [comment] 2022-08-25 07:32
down again

**Comment by svgeesus** [comment] 2022-08-26 10:11
down again

**Comment by bramus** [comment] 2022-08-31 14:33
Down.

**Comment by plinss** [comment] 2022-08-31 15:23
Kicked, should be back momentarily

**Comment by upsuper** [comment] 2022-09-02 05:47
Seems to be broken again.

**Comment by plinss** [comment] 2022-09-02 06:13
Kicked, should be back shortly

**Comment by marcoscaceres** [comment] 2022-09-02 06:22
This is breaking almost every day :( Can we PLEASE start moving drafts to /TR/? It doesn't make any sense that CSS WG doesn't just publish snapshots straight to TR like every other working group at the W3C. Alternatively, please just use GitHub pages.

**Comment by plinss** [comment] 2022-09-02 06:25
The funding to fix the server is in place, work will be starting shortly.

As was said before, the draft server does a lot more than just a simple build to GH pages would.

**Comment by sideshowbarker** [comment] 2022-09-08 06:31
As noted here previously, there’s a related proposal in #7500.

But it’s occurred to me that this doesn’t need to be an either-or — we can, if we choose to, start auto-publishing all the CSS specs to https://w3c.github.io/csswg-drafts URLs in parallel with continuing to publish them to drafts.csswg.org URLs.

However, since I titled and framed #7500 as _“Replace the https://drafts.csswg.org/ backend”_, it seems better to discuss the specific topic of parallel publishing to https://w3c.github.io/csswg-drafts URLs separately.

So I’ve opened https://github.com/w3c/csswg-drafts/issues/7712 for that.

**Comment by svgeesus** [comment] 2022-09-08 11:48
down again

**Comment by svgeesus** [comment] 2022-09-08 12:42
up again

**Comment by svgeesus** [comment] 2022-09-09 10:12
down again

**Comment by svgeesus** [comment] 2022-09-12 17:51
down again

**Comment by bramus** [comment] 2022-09-13 12:30
Down again

**Comment by SebastianZ** [comment] 2022-09-14 06:41
Down.

**Comment by plinss** [comment] 2022-09-14 10:51
Kicked, will be up in a few

**Comment by bramus** [comment] 2022-09-14 15:47
Down again.

**Comment by Loirooriol** [comment] 2022-09-17 23:59
Broken again. Can we get a redirection to w3c.github.io/csswg-drafts instead of the table with the files in the directory? #7760

**Comment by plinss** [comment] 2022-09-18 00:37
kicked, will be up in a few

**Comment by bramus** [comment] 2022-09-30 16:23
Down again.

**Comment by plinss** [comment] 2022-09-30 23:31
kicked, will be up shortly

**Comment by bramus** [comment] 2022-10-03 14:37
Down.

**Comment by svgeesus** [comment] 2022-10-03 15:46
Down again

**Comment by svgeesus** [comment] 2022-10-03 15:47
> Broken again. Can we get a redirection to w3c.github.io/csswg-drafts instead of the table with the files in the directory? https://github.com/w3c/csswg-drafts/issues/7760

That would certainly be preferable, until the server is reliably stable.

**Comment by Loirooriol** [comment] 2022-10-08 00:06
Now it's a 500 Internal Server Error instead of the typical table.

**Comment by Genz-Ghub** [comment] 2022-10-08 03:52
> 
[dumpstate-stats.txt](https://github.com/w3c/csswg-drafts/files/9738360/dumpstate-stats.txt)

**Comment by Loirooriol** [comment] 2022-10-11 14:39
> Broken again. Can we get a redirection to w3c.github.io/csswg-drafts instead of the table with the files in the directory? https://github.com/w3c/csswg-drafts/issues/7760

I have written this addon that does that: https://addons.mozilla.org/ca/firefox/addon/css-specs-mirror/

**Comment by plinss** [comment] 2022-10-11 19:43
Note there will be some planned downtime this afternoon (US/Pacific).

**Comment by svgeesus** [comment] 2022-11-01 20:50
Down again

**Comment by plinss** [comment] 2022-11-01 21:01
Not down. Likely a traffic burst due to scrapers.

**Comment by svgeesus** [comment] 2023-02-07 23:30
Down just now

**Comment by plinss** [comment] 2023-02-07 23:44
Should be back up momentarily

**Comment by svgeesus** [comment] 2023-02-22 16:39
Re-opening as specs are not being rebuilt; as [reported here](https://github.com/w3c/csswg-drafts/issues/8485#issue-1594753866) a commenter was unable to see changes from two days ago, so again I had to direct them to the more reliable (in uptime and in update regularity) https://w3c.github.io/csswg-drafts/.

**Comment by plinss** [comment] 2023-02-22 17:12
All drafts are updated now

**Comment by Loirooriol** [comment] 2023-03-03 21:39
I just get "No information available for the repository."

**Comment by plinss** [comment] 2023-03-03 23:00
Fixed

**Comment by svgeesus** [comment] 2023-03-06 14:43
> 504 Gateway Time-out
> nginx/1.23.3

**Comment by plinss** [comment] 2023-03-06 17:09
Kicked

**Comment by svgeesus** [comment] 2023-03-06 17:32
Thanks.

![image](https://user-images.githubusercontent.com/2506926/223186629-9061c145-97f9-4eed-a396-49cdb2f52eb9.png)

**Comment by svgeesus** [comment] 2023-08-27 13:04
Drafts redirected to the wiki just now; and the wiki is also down.

![image](https://github.com/w3c/csswg-drafts/assets/2506926/f5f954e5-1857-48db-b438-94bb132b3b09)

![image](https://github.com/w3c/csswg-drafts/assets/2506926/fc57bfe1-7f59-46b8-9889-45b0981d8929)

**Comment by plinss** [comment] 2023-08-27 18:25
The wiki has been fixed (the server got upgraded to PHP8.2 and there was an incompatibility in the auth code).

I can't reproduce the redirect issue, DNS glitch?

**Closed by plinss** 2023-08-27 18:25 UTC
Labels: meta
