### ISSUE TITLE
[cssom] [cssom-view] Use mixins in IDL definitions

### ISSUE THREAD

**Issue by TimothyGu** [w3c/csswg-drafts#1928] opened 2017-11-02 16:34 UTC
- https://drafts.csswg.org/cssom-1/
- https://drafts.csswg.org/cssom-view-1/
- Any other text defining interfaces with Web IDL

[Mixins](https://heycam.github.io/webidl/#idl-interface-mixins) have been added to Web IDL to replace the [[NoInterfaceObject](https://heycam.github.io/webidl/#NoInterfaceObject)] extended attribute + `implements` statement.

See https://github.com/heycam/webidl/pull/433.

/cc @tobie

**Comment by tobie** [comment] 2017-11-03 15:04
Please close as duplicate of #1932 and #1931 which are automatically generated and can be tracked. (Sorry for the hassle and the noise).

**Closed** 2017-11-03 15:08 UTC
Labels: cssom-1, cssom-view-1
