### ISSUE TITLE
"Applies to" and SVG

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#6481] opened 2021-07-28 20:31 UTC
As pointed out @dirkschulze in #3412, our "Applies to" line should for some properties list svg elements, but so far we haven't taken that into consideration.

I don't think we should start sprinkling SVG related information in some specs but not all, so we should discuss if we want to do this at all, and if so how. Should SVG information be part of the regular "Applies to" line? Should we have a dedicated SVG "Applies to" line? Should SVG be indexing the properties that apply to it on their end? How do we want to integrate the SVG and CSS specs here?

**Comment by AmeliaBR** [comment] 2021-08-06 00:19
Closing as duplicate of #3414

But yes, work still needs to be done to review all specs to identify these gap & then find sensible categories that can be used.

**Closed by AmeliaBR** 2021-08-06 00:19 UTC
Labels: SVG, meta
