### ISSUE TITLE
[css-text-3] Computed value of `text-align-last: match-parent`

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#9499] opened 2023-10-19 17:15 UTC
For the [`text-align-all` property](https://drafts.csswg.org/css-text-3/#text-align-all-property), the spec calls out the special behavior of `match-parent` in the computed value:

> *Computed value:* keyword as specified, except for `match-parent` which computes as defined above

where "as defined above" refers back to the description under the `text-align` shorthand of how `match-parent` computes an inherited `start` or `end` to a physical `left` or `right` depending on the parent's direction.

However, for [`text-align-last`](https://drafts.csswg.org/css-text-3/#text-align-last-property) this is missing; it simply says:

> *Computed value:* specified keyword

which would leave `match-parent` untouched.

I'm assuming this is just an oversight, and the spec should define the computed value of `text-align-last` in the same way as `text-align-all`, so that `match-parent` computes logical `start`/`end` to physical `left`/`right` here as well.

@fantasai / @kojiishi / @frivoal is this simply an editorial fix, or does it require any kind of discussion?

**Comment by Loirooriol** [comment] 2023-10-19 18:23
Duplicate of #7331?

**Closed** 2023-10-20 07:41 UTC
Labels: css-text-3, Closed as Duplicate
