### ISSUE TITLE
[css-sizing-4] Should aspect-ratio affect the intrinsic size?

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#5032] opened 2020-04-30 18:45 UTC
https://drafts.csswg.org/css-sizing-4/#aspect-ratio

If an aspect-ratio is used, should it also affect the intrinsic size of a box? That is, should:

`<div style="height: 100px; width: fit-content; aspect-ratio: 1/1;"></div>`

be 0px wide or 100px?

@bfgeek @tabatkins @fantasai

**Comment by AmeliaBR** [comment] 2020-04-30 19:14
For SVG, it's the intrinsic aspect ratio is defined as distinct from the intrinsic width and height. An element can have an intrinsic height, an intrinsic aspect ratio, and still no intrinsic width:

https://svgwg.org/svg2-draft/coords.html#SizingSVGInCSS

However, in that case, the CSS [default sizing algorithm](https://www.w3.org/TR/css-images-3/#concrete-size-resolution) kicks in to calculate the size of the other dimension. But different sizing algorithms can apply in other contexts (e.g., flexbox).

Also see this HTML issue about how browsers don't currently expose intrinsic / “natural” sizes consistently for images: https://github.com/whatwg/html/issues/3510

**Comment by cbiesinger** [comment] 2020-04-30 21:48
Looks like images don't let the aspect ratio affect the intrinsic size, so aspect-ratio probably shouldn't either:
http://plexode.com/eval3/#s=aekVQXANJVQMbAx1KTkgBVFNEHj2PVVVRVBsQEFdKQg9RTUJERklQTUVGUw9EUE4QEhYRngGDHrwRAXidA05CWQ6CGwFOSk8Ot09VRtSeHwNeAA==

**Comment by fantasai** [comment] 2020-05-01 18:31
It should be 100px wide. Both the `min-content` and `max-content` size of an image with one fixed dimension and an aspect ratio are calculated from those two measures. See https://www.w3.org/TR/CSS2/visudet.html#inline-replaced-width and https://drafts.csswg.org/css-sizing-3/#intrinsic-sizes

**Comment by fantasai** [comment] 2020-05-01 18:33
The fact that the image is wider than its max-content size when shrinkwrapped proves that the max-content size currently returned in layout is wrong. A shrinkwrapped box should never be wider than its max-content size, that is the maximum size of the formula.

**Comment by AmeliaBR** [comment] 2020-05-01 18:52
I agree that the definition of “intrinsic sizes” in https://drafts.csswg.org/css-sizing-3/#intrinsic-sizes is rather confusing, because we've got a bit of circular logic:

- First it says “ min-content size and max-content size are collectively referred to as the intrinsic sizes”
- Then it gives instructions for how to calculate max-content size for an element that doesn't have a defined intrinsic size.

It might be better to rewrite so the initial definitions is the “intrinsic max-content size” (which would be independent of aspect ratio), and then say the actual min/max content size is that value if it is a definite value, or the result of the algorithm otherwise.

That would also re-align the definition of “intrinsic size” for layout with the one from CSS images & SVG.

**Comment by fantasai** [comment] 2020-06-05 22:01
@AmeliaBR I think your comment is https://github.com/w3c/csswg-drafts/issues/4961

**Comment by tabatkins** [comment] 2020-06-05 22:42
Thinking about this and having off-list discussions with some implementors, @fantasai and I have come to some conclusions that we'd like to get WG review on.

First, some design constraints:
    * Intention of 'stretch' and 'fit-content' was to replicate the fill-container and shrink-to-fit behavior of CSS2.
    * 'min-content' and 'max-content' were defined to be the minimum and maximum range of 'fit-content', respectively.
    * From authoring perspective, barring any overriding sizing constraints, having 'width: min-content' yield the same size as sizing under a min-content constraint makes sense.
    * 'aspect-ratio' + 'min-size: initial' on a replaced element should replicate the current behavior of replaced elements with that intrinsic aspect ratio

Additionally, we want 'aspect-ratio' + 'min-size: auto' to have 'auto' resolve to the content height of a non-replaced element per #3268 (see [minutes](https://lists.w3.org/Archives/Public/www-style/2019May/0009.html)), so that the used height/width can violate the specified aspect-ratio if needed to prevent overflow.

However, current implementations treat 'min-content' and 'max-content' as the natural size of an image, which is not consistent with the design constraints above: 
```html
<!DOCTYPE html>
<img class=float src="https://placehold.it/50x50">
<img class=min-content src="https://placehold.it/50x50">
<style>
body { width: 1px; }
.float { height: 100px; float: left; }
.min-content { height: 100px; width: min-content; }
```
An image with a naturalWidth of 50px, a 1:1 ratio, and "height: 100px" has, in implementations, a different width when floated in a zero-width container vs when it's assigned "width: min-content", which is wrong per the principles above, and not the behavior we'd want for non-replaced elements with 'aspect-ratio'.

Implementors we discussed with from Blink and Gecko are optimistic that this behavior could be changed: replaced elements relying on an explicit non-prefixed 'min-content' or 'max-content' should be rare-to-nonexistent, since these relatively-obscure keywords grant no new abilities to replaced elements. So first, we want to verify with the CSSWG that this behavior can be changed, and that the spec is fine as-is.

----

Assuming the existing definitions are acceptable, we are missing the ability to explicitly restrain one axis of a non-replaced element with an aspect-ratio to its widest atomic inline (min) or longest line of unforced content (max) or, more significantly, its content-based block size. We have defined 'min-height/width: auto' to have this functionality (see earlier remarks about #3268), but it has additional magic such as resolving to zero on scroll containers, so some additional keyword is still needed if we want to represent this behavior unconditionally.

If we agree that such keywords would be useful for authors, we propose 'min-intrinsic' and 'max-intrinsic' for these keywords. These would match the concept already named “intrinsic” in 'contain-intrinsic-size' as well (since it is also prior to applying aspect-ratio). Either way, we can adopt such distinct terminology in the specs at least, to resolve #4961.

**Comment by bfgeek** [comment] 2020-06-13 01:06
What does:
```html
<div id="target" style="min-width: max-content; height: 100px; overflow: hidden; aspect-ratio: 1/1;">
  <div style="width: 150px;"></div>
</div>
```

... `target` resolve to above? `150px` or 100px` ?

**Comment by bfgeek** [comment] 2020-06-13 01:19
(above is conditioned on):
```html
<div style="
    min-width: max-content;
    height: 100px;
    aspect-ratio: 1/1;">
  <div style="width: 150px;"></div>
</div>
```

Resolving to `150px`.

**Comment by fantasai** [comment] 2020-06-15 18:19
`overflow` does not change the interpretation of `max-content`, so the two of them are necessarily the same.

Going from the notes in https://github.com/w3c/csswg-drafts/issues/5032#issuecomment-639874263 ...

If we had `width: max-content; height: 100px; aspect-ratio: 1/1`, `max-content` would resolve to 100px, because `max-content` is the upper bound of the shrink-to-fit (fit-content) width, and setting the `width` value aside because we're calculating it, the width range of shrink-to-fit is 100px to 100px here. So `min-width: max-content; height: 100px; aspect-ratio: 1/1` would have to be the same: both the `width` (which is `auto`) and the `min-width` (which is `max-content`) resolve based on the aspect ratio.

I think that's the correct logic? We can consider some other logic, but, afaict that's what's outlined in https://github.com/w3c/csswg-drafts/issues/5032#issuecomment-639874263

**Comment by cbiesinger** [comment] 2020-06-15 18:28
(I think the `overflow` comment was in regards to https://drafts.csswg.org/css-sizing-4/#aspect-ratio-minimum)

**Comment by bfgeek** [comment] 2020-06-16 03:59
So there are two different potential models `min-content`, and `max-content` sizes, currently both definitions resolve to the same thing (I believe) but will different when considering aspect ratio.
1) An element with `width: min-content` is the same size the element under a min-content constraint.
2) The *value* of `min-content` is the same size as the element under a min-content constraint.

```html
<!-- Case A -->
<div style="height: 100px; aspect-ratio: 1 / 1; width: max-content;">
  <div style="display: inline-block; width: 150px;"></div>
  <div style="display: inline-block; width: 150px;"></div>
</div>

<!-- Case B -->
<div style="height: 100px; aspect-ratio: 1 / 1; width: max-content; min-width: 0;">
  <div style="display: inline-block; width: 150px;"></div>
  <div style="display: inline-block; width: 150px;"></div>
</div>

<!-- Case C -->
<div style="height: 100px; aspect-ratio: 1 / 1; min-width: max-content;">
  <div style="display: inline-block; width: 150px;"></div>
  <div style="display: inline-block; width: 150px;"></div>
</div>

<!-- Case D -->
<div style="height: 100px; aspect-ratio: 1 / 1; min-width: max-content;">
  <div style="display: inline-block; width: 75px;"></div>
</div>
```

### Option 1 ###
`min-content` and `max-content` just consider the aspect-ratio (not their children) in this case.

For this to work the current definition of the [aspect-ratio-minimum](https://drafts.csswg.org/css-sizing-4/#aspect-ratio-minimum) is incorrect it likely wants to refer to the `min-intrinsic` size instead (described above).

Things like flexbox etc, will also potentially need to refer to the `min-intrinsic` size instead? E.g. [here](https://drafts.csswg.org/css-flexbox-1/#content-size-suggestion)?

| | `max-content` | `width` | `min-width` | final size |
|-|-|-|-|-|
| Case A | `100px` | `100px` | `150px` | `150px` |
| Case B | `100px` | `100px` | `0px` | `100px` |
| Case C | `100px` | `100px` | `100px` | `100px` |
| Case D | `100px` | `100px` | `75px` | `100px` |

### Option 2 ###
`min-content` and `max-content` consider both the aspect-ratio *and* their children if the aspect-ratio-minimum applies.

E.g. if there is an aspect-ratio present, the `min-content`, and `max-content` sizes are the resolved size from the aspect-ratio, then apply the content sizes.

| | `max-content` | `width` | `min-width` | final size |
|-|-|-|-|-|
| Case A | `300px` | `300px` | `150px` | `300px` |
| Case B | `300px` | `300px` | `0px` | `300px` |
| Case C | `300px` | `100px` | `300px` | `300px` |
| Case D | `75px` | `100px` | `75px` | `100px` |

The aspect-ratio-minimum can still use the min-content definition here, (and likely other places like flex?)

(I might update this in the morning, some things might be wrong).

**Comment by cbiesinger** [comment] 2020-06-24 22:38
And another question: Should min-content be affected by the aspect-ratio even if there is an explicit size in that axis? E.g.:

```html
<div style="width: 100px; height: 100px; aspect-ratio: 1/1; min-width: min-content;">
  <div style="width: 200px;"></div>
</div>
```

Should the width be 100px (from the aspect-ratio), or 200px (from the contents)?

**Comment by fantasai** [comment] 2020-06-29 22:27
@cbiesinger In [that example](https://github.com/w3c/csswg-drafts/issues/5032#issuecomment-649109809) if we go with the logic in https://github.com/w3c/csswg-drafts/issues/5032#issuecomment-639874263 then `min-width: min-content` will resolve as the size under min-content constraint, which considers `height: 100px` and the aspect ratio to yield `min-width: 100px`. The final width would then be 100px. (If we decide instead that `min-content` always takes the content’s size, then it would be 200px.)

I think one principle we need to make more explicit here is that resolving keyword sizes in a given axis requires ignoring all sizing properties in that axis, but might take into account sizing properties in the other axis due to an interdependency caused by layout rules or aspect-ratio. (The min/max clamps are applied after all sizing properties in that axis are resolved to a length.)

**Comment by fantasai** [comment] 2020-06-29 23:17
@bfgeek So wrt Option 2... if we take the natural size of an image as analogous to the content size of a non-replaced element *and* maintain the correspondendance of min-content/max-content to the min/max extremes of shrink-to-fit, then Option 2 would break the current handling of floating images. Assuming we want to maintain the shrink-to-fit correspondence, we could take your interpretation only if we decide to break the content-size=natural-size analogy. Which is an interesting possibility! So, if I'm understanding correctly, option 2 could be:
    * min-content/max-content/fit-content on replaced elements defers to the aspect ratio rather than maxxing with natural size, to maintain consistency with current shrink-to-fit behavior.
    * min-content/max-content/fit-content on non-replaced elements takes the larger of the aspect-ratio-derived size (if applicable) and the content-based size

But the problem with this is that it would give unexpected results for shrink-to-fit boxes. Consider your cases A-D as a float. The min-content size of the float would be 150px: if we put the float in a narrow box, it would not shrink below 150px, the size of its largest unbreakable content. This is fine, and probably what an author would expect. But if we place the float into a large container, it takes its max-content size, which would be 300px. This is not what an author would expect: they would expect the float to be its aspect-ratio-constrained width (floored by the min-content width if necessary), but no larger than that.

This suggests that either (a) both min-content and max-content work off the min-content size and AR (probably confusing?) or (b) we give up and go back to Option 1, where the shrink-to-fit size of a non-replaced ratio-having element is solely determined by its ratio and the size in the other dimension (tho still floored by the 'min-width: auto', giving a width of 150px in this case) or (c) max-content no longer represents the max extreme of shrink-to-fit/fit-content, but is something else entirely??

[In both of (a) and (b) the behavior of min-content and max-content are identical to each other for any element with an aspect-ratio, but we can't figure out a way to make them different without falling to the unintuitive behavior outlined above.]

Fwiw, our current inclination is to stick with [Option 1](https://github.com/w3c/csswg-drafts/issues/5032#issuecomment-644517090) / https://github.com/w3c/csswg-drafts/issues/5032#issuecomment-639874263  Further thoughts?

~@fantasai and @tabatkins

**Comment by bfgeek** [comment] 2020-07-08 17:09
@fantasai @tabatkins 

> But if we place the float into a large container, it takes its max-content size, which would be 300px. This is not what an author would expect: they would expect the float to be its aspect-ratio-constrained width (floored by the min-content width if necessary), but no larger than that.

So the difference with "Option 2" is that we aren't actually using STF sizing in the float case. If we have a `width: auto`, with an aspect-ratio, and a definite height, STF doesn't apply. I.e.
1) `width: auto` (which wouldn't be STF as it has an aspect ratio with a definite height) would resolve to `100px`.
2) `min-width: auto` would be `150px` (applying the minimum automatic size rule).

Thoughts?

**Comment by fantasai** [comment] 2020-07-20 18:40
@bfgeek Right; the idea of `width: fit-content` is that it gives the same results as `width: auto` on a float. And `width: auto` on the float, as you note, should be exactly aspect-ratio x height in this case. If `min-content` and `max-content` are to represent the extremes of `fit-content`’s size range, they can't be based on the content sizes, since the `fit-content` range is a single point equal to aspect-ratio x height (which may well even be outside the range of the minimum/maximum content-based sizes, as they are in this case).

**Closed** 2020-10-05 23:30 UTC
Labels: Closed Accepted by CSSWG Resolution, Needs Testcase (WPT), css-sizing-4

**Comment by fantasai** [comment] 2022-01-31 20:15
@tabatkins and I think some of the confusion here comes from missing a small nuance in this paragraph:

> The content-based minimum size of a flex item is the smaller of its specified size suggestion and its content size suggestion if its specified size suggestion exists; otherwise, the smaller of its transferred size suggestion and its content size suggestion **if the element is replaced** and its transferred size suggestion exists; otherwise its content size suggestion.

The flex item in question does not have a specified size suggestion, and is not replaced, and therefore it falls through to the final clause and uses its content size suggestion which is its min-content size in the main axis (100px). Therefore Firefox's behavior here is correct.

@aethanyc mentioned

> However, the current spec implies that the specified size suggestion is the item’s preferred main size, which can be computed via aspect-ratio + definite cross-size. @dholbert pointed to me that the definition was changed after the edit in 0c1a35d, and this seems changing the behavior.

0c1a35d was definitely not meant to change behavior, but I can see how switching the emphasis from the “computed value” would change how automatic sizes are interpreted. We need to clarify that we're only considering non-automatic definite sizes:

```diff
diff --git a/css-flexbox-1/Overview.bs b/css-flexbox-1/Overview.bs
index 2c3418beb..358740409 100644
--- a/css-flexbox-1/Overview.bs
+++ b/css-flexbox-1/Overview.bs
@@ -1001,7 +1001,7 @@ Grid doesn't have similarly meaningful shrinkability, so it doesn't need to care
 	<dl>
 		<dt><dfn>specified size suggestion</dfn>
 		<dd>
-			If the item’s [=preferred size|preferred=] [=main size=] is <a>definite</a>,
+			If the item’s [=preferred size|preferred=] [=main size=] is <a>definite</a> and not [=automatic size|automatic=],
 			then the <a>specified size suggestion</a> is that size.
 			It is otherwise undefined.
```
Committed in ca4dc9e0a .

**Comment by fantasai** [comment] 2022-01-31 20:33
Oops, wrong issue. Gonna delete and repost...
