### ISSUE TITLE
[css-cascade-6] A way for <style> elements to scope to their parent element

### ISSUE THREAD

**Issue by dfabulich** [w3c/csswg-drafts#6606] opened 2021-09-13 16:17 UTC
https://drafts.csswg.org/css-cascade-6/#scoped-styles

The [explainer](https://css.oddbird.net/scope/explainer/#references--acknowledgements) references this issue: [Please bring back scoped styles](https://github.com/w3c/csswg-drafts/issues/3547).

Either there's something missing from the spec or I'm missing it, which is a way to have a `<style>` element that gets scoped to its own parent element.

```html
<div>
  <style scoped>p { color: red; }</style>
  <p>red</p>
</div>
```

`<style scoped>` would guarantee that the color only applied to children of the parent div.

I could do it by adding a unique ID or attribute:

```html
<div id="foo">
  <style>#foo p { color: red; }</style>
  <p>red</p>
</div>
```

… this is basically what Vue does at build time. But I want the same effect without a build step!

I think we'd want something like `@scope(:style-parent)`.

```html
<div>
  <style>@scope(:style-parent) { p { color: red; } }</style>
  <p>red</p>
</div>
```

Otherwise, even with `@scope` back in play, I'd still have to use a build tool (or something) to generate an ID for the upper bound of the scope.

**Comment by mirisuzanne** [comment] 2021-09-13 16:35
If I understand this right, the new feature required for this is a `:style-parent` pseudo-class (`:style-root`? `:style-host`?) which:

- For stylesheets in the document `<head>` refers to the document root.
- For nested stylesheets, refers to their parent element.

I don't see any particular reason it should be restricted to use in `@scope` if we add it. Could also be used for basic child/descendant selectors, or the `:in()` pseudo-class. I'm not sure if that's feasible from an implementation perspective, but it's an interesting idea.

**Comment by dfabulich** [comment] 2021-09-13 17:06
As is typical for spec bugs, I think I've got two ideas piled into one:

1. I've got a problem: I want to be able to refer to the nested `<style>` element's parent.
2. I suggest a solution: A new pseudo-class `:style-parent` (or `:style-root` or `:style-host`, yeah) that would refer to the parent element of a nested `<style>`. (As you point out, that would not be meaningful for stylesheets in the `<head>`, so presumably in that case we'd want it to refer to `:root`.)

If `:style-parent` isn't feasible for some reason, I'd still wish for _some_ solution to the problem. I guess I could try to invent a handful of other solutions…? (The `scoped` attribute `<style scoped>` could literally be another alternative, for example.)

**Comment by mirisuzanne** [comment] 2021-09-13 20:47
Right. But I think one of the issues with `<style scoped>` is that it has backwards-compatibility problems. Browsers that don't understand the `scoped` attribute will continue to apply those styles globally (the [current behavior](https://codepen.io/miriamsuzanne/pen/oNwebYq)) — which is not the ideal fallback here. 

I like the pseudo-class idea because it avoids that issue, while building on top of the more flexible CSS-selector driven approach to `@scope`.

**Comment by bitdivine** [comment] 2021-11-01 08:27
Regarding the backwards compatibility issue, would it be possible to define a CSS selector that refers to the current location of a style tag?  If the browser does not recognize it, the CSS selector would match nothing, rather than everything.  

That way we could have:
```
<some-parent>
  <style>
    @here button {some css}
  </style>
  <button>CSS APPLIES HERE</button>
</some-parent>
```

**Comment by bitdivine** [comment] 2021-11-01 08:35
Regarding the issue of not wanting CSS to apply to all child elements, or "toroidal css", is that not a separate issue from local scoping?  It feels as if it should be possible to define selectors indicating "style this element but not its children" (non-inherited styles) or "style this element like its parent" (explicit inheritance of normally non-inherited styles) but that trying to combine inheritance constraints with local scoping makes things complicated.

**Comment by mirisuzanne** [comment] 2021-11-01 18:32
@bitdivine The current scope proposal (and this thread) do not have any impact on inheritance. The donut scope applies to selector targeting only. 

I do like the approach of a syntax for pointing to style location, whatever form that might take.

@Malvoz The problem is not for authors that want to use the new feature, but for legacy sites that already have nested style tags which apply globally. Authors can recreate a scoped attr using a polyfill, but any browser support for that would break legacy styles, and that's not an option. There's no way to polyfill opting-out all legacy sites from a new feature.

**Comment by mirisuzanne** [comment] 2022-09-21 17:24
I think this should be resolved by a combination of:

- #7348 [add a `scope()` to the `@import` syntax](https://github.com/w3c/csswg-drafts/issues/7348#issuecomment-1248646574).
- #7349  [`@scope` without root selector scopes to the parent of the owner node, or the containing tree if there's no owner node](https://github.com/w3c/csswg-drafts/issues/7349#issuecomment-1248666611).

The first one there allows scoped imports using `@import` (which we could propose to the WHATWG as an attribute, similar to the proposed `layer` attribute). The second means you can get the desired behavior by using the `@scope` rule in the nested style sheet, without waiting for an HTML attribute:

```css
<div>
  <style>
    /* scoped to the div, since no scope root selector is given */
    @scope { p { color: red; } }
  </style>
  <p>red</p>
</div>
```

Closing this issue as accepted by those resolutions. If we want to work on an additional `scope` attribute for HTML, that will need to happen in the WHATWG rather than the CSSWG.

**Closed by mirisuzanne** 2022-09-21 17:24 UTC
Labels: Closed Accepted by CSSWG Resolution, css-cascade-6

**Comment by yisibl** [comment] 2022-10-27 14:39
@andruud As far as I know, this is not currently implemented in Chrome, can you implement the new behavior in Chrome?

> Finally, we could allow `@scope` without any selector clauses, which would scope the styles to the parent of the stylesheet's owner node (or the containing tree for constructable stylesheets with no owner node).
> https://github.com/oddbird/css-sandbox/pull/22/files#diff-959903105b7abdfb2fa2540f104fdd8d7f347e6f339814fdf5e57f7e65f235e9

```html
<div>
  <style>
    @scope {
      p { color: red; }
    }
  </style>
  <p>this is red</p>
</div>
<p>not red</p>
```

That would be equivalent to:

```html
<div id="foo">
  <style>
    @scope (#foo) {
      p { color: red; }
    }
  </style>
  <p>this is red</p>
</div>
<p>not red</p>
```

**Comment by andruud** [comment] 2022-10-31 14:35
@yisibl Right, yes, the current Chrome prototype predates the resolution add that kind of scoping. It will be added eventually. I filed [crbug.com/1379844](https://bugs.chromium.org/p/chromium/issues/detail?id=1379844) if you want to follow that for updates.

**Comment by yisibl** [comment] 2022-10-31 15:21
@andruud Thanks! I am very much looking forward to the implementation of this feature.
