### ISSUE TITLE
[css-counter-styles] Mark <image> in <symbol> at risk?

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#1991] opened 2017-11-16 00:45 UTC
I didn't implement that in Gecko, and I'm not motivated to do so anytime soonish. Also it doesn't seem there is impl interest from other vendor yet. Having some feature which is not implemented and not going to be implemented in any browser in foreseeable future in a CR is probably not a good idea?

Also, given that some of the usecases of `<image>` are now covered by emoji, I guess `<image>` as `<symbol>` isn't that important now?

**Comment by tabatkins** [comment] 2017-12-02 01:43
Yeah, sounds reasonable (and avoids some complexities caused by `counter()` no longer being a `<string>`).

**Comment by tabatkins** [comment] 2017-12-04 19:53
(I've gone ahead and marked it as at-risk, but want a WG heads-up on Wednesday.)

**Closed** 2017-12-07 02:39 UTC
Labels: Closed Accepted by CSSWG Resolution, css-counter-styles-3
