### ISSUE TITLE
CSS: element property : device-overflow-inflation-width + device-overflow-inflated-width

### ISSUE THREAD

**Issue by wesleyolis** [w3c/csswg-drafts#10404] opened 2024-06-08 11:50 UTC
Hi,

I would like to propose the following, which would allow developers to easily identify overflow issues, and correctly deal with them,
to ensure their pages render correctly.

With the new render modes as suggested and proposed in https://github.com/w3c/csswg-drafts/issues/10403
The following properties would make mobile development so much better.
The names of the properties could be shortened.

```.css {
.classname[device-overflow-inflated-width]::before {
display:block; // force the item onto a new rendering line.
}
}
```

```.css {
.classname[device-overflow-inflated-width] {
display:clip;
background-color:red
}
}
```

**Comment by Loirooriol** [comment] 2024-06-09 16:29
1. That's not a property, that's an attribute selector that already has a meaning. I suspect you want a new pseudo-class.
2. I don't understand what you are trying to achieve. Are you trying to apply styles depending on whether there are elements overflowing the viewport? That's circular, and a duplicate of #2011

**Comment by wesleyolis** [comment] 2024-07-22 19:17
@Loiroorio Yes, I would want to apply styles to elements that overflow the viewport, to selectively re-align or change the layout, such that they fall into the viewport and in the case of this proposal, prevent the viewport from being blowing up and limit that for mobiles to a factor and zoom, such pages have less issues rendering on mobile and it then just work.. https://github.com/w3c/csswg-drafts/issues/10403

1. I am using an attribute selector to inspect the property, but using a pseudo-class can work as well, anything that can inspect or make logical decisions in all places required based on an internal dom boolean variable.

2. I would say, that depends on how you structure the code and pre-evaluation of a render buffer of line render elements, before flushing them to pixels, which would allow injection of before items, like currently happens.  You can also limit the recursive iteration to a single overflow functional evaluation, which probably would be good for fixing and sorting most website pages out.
I am pretty sure it would be possible.

**Closed** 2024-10-15 01:39 UTC
Labels: Closed as Duplicate
