### ISSUE TITLE
[css-fonts-4] [varfont] Feature queries?

### ISSUE THREAD

**Issue by davelab6** [w3c/csswg-drafts#1274] opened 2017-04-21 19:08 UTC
Should we have a feature query for variable fonts?

(reference https://hacks.mozilla.org/2016/08/using-feature-queries-in-css/)

```css
@supports (font-variation-settings: "opsz" 14) {
   // code that will only run if variable fonts are supported by the browser 
 }
```

Pondering:

```css
@supports (font-variation-settings: "XOPQ" 14) {
   // what happens here? :) 
 }
```

This idea came from a chat with @jensimmons at the www.snd.org conference :)

**Comment by litherum** [comment] 2017-04-22 00:02
https://drafts.csswg.org/css-conditional-3/#at-supports says:

> The @supports rule is a conditional group rule whose condition tests whether the user agent supports CSS property:value pairs.

In this situation, the user agent does support that property:value pair. (It's the font that doesn't.) So, both the cases have the same semantic meaning.

If you're trying to figure out if a font supports a particular feature, `@supports` isn't what you want, since there's no way to match it up with a particular font file. Instead, you want https://github.com/w3c/csswg-drafts/issues/520

**Comment by litherum** [comment] 2018-03-06 10:02
duplicate of https://github.com/w3c/csswg-drafts/issues/520

**Closed by litherum** 2018-03-06 10:02 UTC
Labels: css-fonts-4
