### ISSUE TITLE
[css-overflow] Selective overflow: hidden

### ISSUE THREAD

**Issue by radogado** [w3c/csswg-drafts#3417] opened 2018-12-10 14:18 UTC
Hi, I'd like to have some children not clipped by `overflow: hidden`, like focus outline, tooltips etc. Has this been discussed before? Thanks!

**Comment by fantasai** [comment] 2018-12-10 23:41
Nope! Hasn't been discussed before. Afaict tooltips are not clipped by `overflow: hidden`, but it seems like focus outlines are. [See testcase](http://software.hixie.ch/utilities/js/live-dom-viewer/?<!DOCTYPE%20html>%0A<div%20style%3D"border%3A%20solid%20gray%3B%20width%3A%201em%3B%20height%3A%200.5em%3B%20overflow%3A%20hidden"><a%20href%3D""><abbr%20title%3D"abbreviation">abbr<%2Fabbr><%2Fa><%2Fdiv>).

Afaict the CSS specs explicitly allow focus outlines to be painted over everything else in https://www.w3.org/TR/CSS2/zindex.html#outlines but it probably looks weird to draw an outline around something that's invisible. Do you have some examples of where this is a problem for you?

**Comment by radogado** [comment] 2018-12-11 13:59
Cropped tooltip: https://radogado.github.io/natuive/demos/postbank/#credit (red circle with question mark)
Focus outline: no example, but anytime a focused element is at the edge of a container with overflow: hidden, the default focus outline is cropped. I had to move the outline inside the element, but that's not ideal.
I think at least the outline should always be visible, it makes no sense to be cropped by overflow: hidden.
Thanks!

**Comment by jonjohnjohnson** [comment] 2018-12-11 22:14
@radogado I think @fantasai was talking about native tooltips that show when a user rests their mouse while hovering elements with a title attribute?

**Comment by Loirooriol** [comment] 2018-12-12 03:22
There is the trick of using `position: absolute` in the child and `position: static` in the parent, so that the containing block of the child is an ancestor of the parent. The problem is that usually I want to position or size the child with respect to the parent, which is not easy if the containing block is something else.

**Comment by tabatkins** [comment] 2018-12-14 21:02
Yes, @fantasai was talking about native tooltips, which are rendered atop everything.  That page is just showing some in-page element, which is affected by stacking/clipping contexts.

CSS is bound (for many reasons, mostly good) by the stacking/clipping context tree. "Escaping" that is difficult. The correct way to avoid being clipped by an ancestor is to not have an ancestor that clips you; in-page tooltips should be rendered as children of `<body>` and positioned with JS.

**Comment by radogado** [comment] 2018-12-17 07:58
@tabatkins great advice, I'll rewrite my tooltip as child of body. Clipping the focus outline, though, makes no sense and is an accessibility problem. Thanks!

**Comment by radogado** [comment] 2018-12-17 10:02
Another example would be a carousel where I need the controls to be outside and visible, while the content is hidden. Something like 

> overflow-absolute-children: visible;

 would be very useful. Thanks.

**Comment by jonjohnjohnson** [comment] 2018-12-17 15:54
> Another example would be a carousel where I need the controls to be outside and visible

@radogado Can you show this example of the layout you are talking about and explain why your controls would be structured inside what needs to have hidden/scrollable overflow, but have their box(es) rendered outside? Can't imagine any scenario where I wouldn't just have the controls structured outside in the first place, as I wouldn't want them moving within the carousels hidden overflow?

**Comment by radogado** [comment] 2018-12-18 16:59
Yes, the padded slider here: https://radogado.github.io/natuive/guide/#slider
I had to add an additional wrapper to achieve that effect, which isn't ideal.
Thanks

**Comment by OliverJAsh** [comment] 2019-07-08 18:35
I submitted a use case which could fit into this: https://github.com/w3c/csswg-drafts/issues/4092

**Comment by radogado** [comment] 2020-01-03 09:07
Filed WebKit bug https://bugs.webkit.org/show_bug.cgi?id=205642

> The focus ring (outline) shouldn't be hidden by overflow rules. Currently it is cropped by overflow: hidden. It looks ugly and broken and the efforts for workarounds are too great and unnecessary. It's a pain for people trying to make sites accessible. Please at least add a CSS option to always display the focus ring.

and they redirected me back here.

Previous Chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=462609

Focus ring should also escape masking by **-webkit-mask**. (Optionally)

Thanks

**Comment by radogado** [comment] 2020-01-28 12:41
![The problem on Apple.com](https://s3.amazonaws.com/gado/temp/Screenshot%202020-01-28%20at%2014.15.21.png)

**Comment by tabatkins** [comment] 2020-01-28 18:46
Given the significant impl complexity of allowing some things to draw outside of an overflowing box, versus the quite trivial complexity of an author ensuring there's a little bit of padding on the box, and taking into the account the *relatively* small pain from authors not doing that (one edge of an outline doesn't show),  I believe the right answer is to do nothing here, and evangelize when necessary to get pages to do their layouts slightly better.

**Comment by OliverJAsh** [comment] 2020-01-28 19:06
@tabatkins How about more complicated use cases such as https://github.com/w3c/csswg-drafts/issues/4092?

**Comment by tabatkins** [comment] 2020-01-28 20:47
Same. There are relatively simple layout-based solutions to make those cases usable (such as wrapping the possibly-overflowing content in a wrapper with overflow:auto).

For separate reasons, we're also pursuing specifying the "top layer" positioning mode that things like `dialog` and fullscreen elements in HTML use, so authors can have individual elements totally escape all containing contexts and be displayed on top of everything else in the page; this requires *slightly* more complexity in the JS, but will allow for things like the "custom autocomplete list that doesn't get clipped or overlapped while it's displayed" use-case to be done well.

**Comment by radogado** [comment] 2020-01-29 08:11
The focus ring is a vital part of the global OS interaction and shouldn't be bound to page layout rules.

**Comment by frivoal** [comment] 2021-07-28 20:34
Agenda+ to seek group feedback on this issue.

**Comment by frivoal** [comment] 2021-07-30 00:03
To summarize, the CSSWG discussion roughly concluded that:
* as far as tooltips are concerned, this is likely going to be addressed by https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/CSSAnchoredPositioning/explainer.md
* As far as outlines are concerned, it's complicated:
  * We cannot make it apply to all outlines. Some are used for focus, some are used for decoration. So anything would have to be opt-in
  * We can think of various ways to make the outline visible. But none of them are great: either they are very complex to implement, or provide no so great UX, or both. For example, if you just don't clip the outlines at all, you can end up with visible outlines around scrolled-out-of-view elements, or around partly scrolled-out-of-view elements, and that's not great. Pulling the outline to the top layer would have that problem, compounded by the fact that the element might be obscured by something else on top. We'd probably get a somewhat more pleasant UX by having two different clip-bounds for a scroll container: one for everything, and another one, slightly larger, just for outlines. But given the complexity of stacking contexts, z-index, compositing, various kind of clipping, etc, this is something no implementer would be interested in doing.
  * This problem also exist in native platform's UI toolkits, and they'd don't deal with it either as far as we know.
  * We also considered including `outline-style: auto` outlines in the scrollable overflow instead of the ink overflow. That wouldn't really help with the stated use case of `overflow:hidden`, but it might be better for related situation with `overflow:scroll` or `overflow: auto`. But means that outlines appearing and being removed as people focus things in and out would now have an impact on layout, and that doesn't seem reasonable.
  
  All in all, while the CSS-WG sympathizes with the problem, we didn't think it was practical to address it.

**Comment by frivoal** [comment] 2021-07-30 00:05
@radogado, although this conclusion isn't the one you hoped for, can you confirm that you can live with this conclusion? If not, do you think we overlooked something?

**Closed** 2021-08-05 10:04 UTC
Labels: Closed Rejected as Wontfix by CSSWG Resolution, Commenter Response Pending, css-overflow-3, css-overflow-4, css-ui-4

**Comment by adamschwartz** [comment] 2021-08-05 17:15
@frivoal Thank you so much for that summary. This issue has long been on my mind since working on Tether many years ago.

I’m quite excited about CSSAnchoredPositioning as described in that doc. Based on quick reading, it seems to me that a faux-outline could potentially be implemented using a popup as a mimic:

```html
<button id="myButton" popup="myPopup">Anchor</button>
<popup id="myButtonOutline" anchor="myButton"></popup>
<style>
    #myButtonOutline {
        outline: inherit;
        position: fixed;
        position-set: buttonOutlinePos;
        width: calc(anchor(right) - anchor(left));
        height: calc(anchor(bottom) - anchor(top));
    }

    @position-set buttonOutlinePos {
        1 {
            top: anchor(top);
            left: anchor(left);
        }
    }
</style>
```

A non-semantic use of “popup” by today’s common understanding of the word within UI design, but perhaps reasonable taken literally as the outline is popping up and out of the otherwise trapped overflow context.
