### ISSUE TITLE
[css-fonts] size-adjust: descriptor and baseline placement / line-height

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#6189] opened 2021-04-07 09:55 UTC
A new test for `size-adjust` [size-adjust-01.html](http://wpt.live/css/css-fonts/size-adjust-01.html) made by @jfkthame 
 expects the baseline of the 150% size-adjust case to shift down due to the Ahem glyphs being scaled up. This ref test expresses as the expectation for `size-adjust` being equivalent to <span> elements for each uppercase letter at 150% font size. ([see ref expectation](https://github.com/web-platform-tests/wpt/blob/master/css/css-fonts/size-adjust-01-ref.html))

This test fails in Chromium's implementation, as for the 150% `size-adjust` case it's scaling the glyphs but not shifting the baseline and not changing the inline line height computation, as much as I can tell. 

The current spec wording says:

> "All metrics associated with this font—including glyph advances, baseline tables, and overrides provided by @font-face descriptors—are scaled by the given percentage, as are the rendered glyph images." 

My interpretation is that as a consequence, line height and baseline placement should be computed based on scaled / `size-adjust`ed metrics, not based on unscaled metrics and Firefox' behaviour passing this test is correct.

Posting this here as an issue just to confirm that that is the intended behaviour. Opinions?

**Comment by jfkthame** [comment] 2021-04-09 18:09
Right; as I understand it, all font-derived metrics such as ascent, descent, line-gap, baselines, advances, kerning, `from-font` values of `underline-offset`, `decoration thickness`, superscript/subscript offsets, `ex` and `ch` units, etc., will be affected (unless, of course, they're overridden by other descriptors). So size-adjust does affect inline line height computation and baseline placement, just as if a larger font-size were used.

**Comment by chrishtr** [comment] 2021-04-20 18:00
Closing, I don't think there is more to discuss. The root cause of the test difference had to do with behavior of spaces in unicode. See [this comment](https://bugs.chromium.org/p/chromium/issues/detail?id=1196631#c8) and the resolution in #4796. My understanding is that Blink's implementation is according to spec in that case, and Gecko is not.

**Closed by chrishtr** 2021-04-20 18:00 UTC
