### ISSUE TITLE
[css-pseudo] generated content between elements

### ISSUE THREAD

**Issue by tylersticka** [w3c/csswg-drafts#4709] opened 2020-01-28 18:27 UTC
We currently have and enjoy `::before` and `::after` [tree-abiding generated content pseudo elements](https://drafts.csswg.org/css-pseudo-4/#generated-content).

One use for these is to generate content _between_ elements. For example, you could insert separators between a list of breadcrumb navigation segments:

```css
.breadcrumbs > * + *::before {
  content: "▸";
  margin: 0 2ch;
}
```

Despite this, I still see hard-coded separators in HTML (vertical bars, bullet or dot characters, etc.) for these sorts of patterns quite often. I have a few thoughts about why this might be:

- Simple lack of familiarity with or access to a project's CSS.
- Adjacent element selectors (or other techniques like `:not(:first-child)`) can be intimidating to some developers.
- There can sometimes be complexity involved in styling a child pseudo element to appear visually as if it's between its parent and adjacent aunt or uncle.

This made me wonder if there'd be value in a pseudo element that injects content _between_ adjacent matching elements?

```css
.breadcrumbs > *::between {
  content: "▸";
  margin: 0 2ch;
}
```

![Illustration of a breadcrumb navigation pattern with symbols inserted between adjacent elements](https://user-images.githubusercontent.com/69633/73293385-a9655600-41b8-11ea-9fb3-24dd21fbe2f9.png)

(I was [encouraged to submit this issue](https://twitter.com/fantasai/status/1220851780357148674) after [writing about the idea](https://cloudfour.com/thinks/some-imaginary-css/#pseudo-elements-between-siblings).)

**Comment by Loirooriol** [comment] 2020-01-28 19:33
Closing as dupe of #2960

**Closed by Loirooriol** 2020-01-28 19:33 UTC
