### ISSUE TITLE
[css-boxmodel] Allow the texts in input element to be painted into the top and bottom padding area.

### ISSUE THREAD

**Issue by yachiehwu** [w3c/csswg-drafts#1941] opened 2017-11-06 06:59 UTC
Browser tests: Firefox, Chrome, Safari, Edge  

**Test Summary:** 

(1) In the vertical direction: when the height of the text is larger than the height of the content area.
* Firefox: Texts can only be painted into the content area. Visually, the out of the content texts is clipped.   
* Safari, Edge: Texts can be painted into the vertical padding area(top padding and bottom padding). If the top and bottom padding don’t have enough spaces, the texts are clipped on top and bottom.  
* Chrome: Texts can be painted out of the content area in the vertical direction( including the top padding/border and the bottom padding/border. And texts can even be painted out of the input element's box model in the vertical direction). Visually, the texts are painted without clipping anyway.

(2) In the horizontal direction:
None of these four browsers paints the texts out of the content in the horizontal direction.
  
Things which don't have impacts on these four browsers:
* border thickness
* line-height
* vertical-align
* -(moz|webkit)-appearance: none
* overflow: visible/hidden/auto/scroll 
* box-sizing: No matter how we change the calculation model, it will be the same, as long as the height of the content is the same after the calculation.  

Things which change on these four browsers:
* font-size: Changing the font-size could fit the texts into the content area. 
 
**Proposal:**

Allow the texts in input to be painted into the top and bottom padding area. 
With this change, this is likely to resolve the web-compatible issue as the research we described above. There are some sites with this web-compatible issue have been posted on [Mozilla bug 752790](https://bugzilla.mozilla.org/show_bug.cgi?id=752790).
Furthermore, visually, for users/developers when content's background color is the same as the padding’s background color, it is not clear where the boundaries of the content area are. Ｗithout clipping the texts in the vertical padding, it makes the texts in input look more friendly to users.

**Comment by dbaron** [comment] 2017-11-07 03:04
Actually, this is probably duplicate of #1717.

**Comment by yachiehwu** [comment] 2017-11-07 03:11
Indeed.

**Comment by jetvillegas** [comment] 2017-11-14 03:02
> Allow the texts in input to be painted into the top and bottom padding area.

I don't see a resolution other than your proposal, given the webcompat reality today. 

@fantasai can you suggest the best spot to make this change? We're going to fix the Firefox bug as noted. It would be good to document the de facto standard in the spec. Thx!

**Comment by karlcow** [comment] 2017-11-14 06:07
* text-overflow doesn't seem to be right place. https://drafts.csswg.org/css-ui/#text-overflow
* css-overflow has a notion of ink-overflow , but it doesn't seem to fit what is happening. https://www.w3.org/TR/css-overflow-3/#ink-overflow
https://codepen.io/webcompat/pen/GOEGOo

![capture d ecran 2017-11-14 a 15 05 34](https://user-images.githubusercontent.com/505230/32765342-4a37282e-c94d-11e7-895e-7f0549d0079f.png)

There is form styling in CSS UI but about appearance :/
https://drafts.csswg.org/css-ui/#form-styling

**Comment by boazsender** [comment] 2017-11-17 21:51
issue #1717 took a much more round about way of arriving at the same proposal you have here @yachiehwu. I'm closing that issue in favor of this one.

@jetvillegas it's awesome to hear that you are fixing this in firefox! This will definitely take out a lot of web compat issues \:D/

There are several more compat examples affected by this raised in whatwg/compat/issues/81:

**Comment by boazsender** [comment] 2017-11-17 22:16
Issue #1717 took a much more round about way of arriving at the same proposal you have here. Nice work @yachiehwu! I'm closing #1717 in favor of this one.

@jetvillegas it's awesome to hear that you are fixing this in firefox! This will definitely take out a lot of web compat issues \:D/. There are several more compat examples affected by this raised in whatwg/compat/issues/81 (thanks to @denschub) including:
* www.elster.de - site is not usable webcompat/web-bugs#9547
* www.unigo.com - design is broken webcompat/web-bugs#10879
* www.bankersadda.com - design is broken webcompat/web-bugs#10964
* www.leapviral.com - design is broken webcompat/web-bugs#11002

To echo @jetvillegas' last question, @fantasai, @frivoal, @tabatkins et al, can you provide some guidance where in the spec this should go?

I've also got a ref test for the proposed behavior up at w3c/web-platform-tests/pull/8080. Here is what test looks like (`chrome` on the left, `firefox` on the right, reference on top, test case on the bottom, using the Ahem font for consistent rendering):
![image](https://user-images.githubusercontent.com/122117/32970931-e567de5c-cb9f-11e7-9952-acd629d8f4af.png)

**Comment by frivoal** [comment] 2017-12-14 05:22
css-overflow seems like the least bad fit, but at the same time this is very specific to the `input` element so it would be a decent fit for a spec on replaced elements / form controls, but there is no such spec currently.

So, css-overflow-4 for now, and later moving to a replaced element spec if we ever get one?

Agenda+ to get a resolution on the behavior, and on the spec it should go to.

**Comment by yachiehwu** [comment] 2017-12-14 13:56
Note: Firefox59 has made the change to be able to paint on the padding in the vertical direction.

**Comment by fantasai** [comment] 2018-01-03 06:52
@jetvillegas I would put it into css-overflow-3, given we don't have a form-controls spec yet.

**Comment by MatsPalmgren** [comment] 2018-01-10 13:59
Just to clarify the new layout we [implemented](https://bugzilla.mozilla.org/show_bug.cgi?id=752790) in Firefox 59: we now allow overflow to paint into the padding in the _block axis_ for `<input>`.  I.e. the logical axis, not the physical axis as was suggested above.

**Comment by frivoal** [comment] 2018-01-11 02:21
I'm OK with putting this in UI-4 this, but we're going to need more details about what the behavior is. The spec cannot just be to allow text to be painted in the top and bottom padding, because I don't think there's anything forbidding it in the first place. If you do the same thing with a div instead of the input, the content will overflow into the padding.

I suppose that if we're defining how `<input>` does it's layout, we actually need to say more than just "can paint into (logical) top/bottom paddings but not left/right paddings", and actually define the actual layout model:
- the text is centered vertically despite no css property asking for it to me (and how is it centered, by the way? Is that baseline based, bounding box based, embox based...?)
- The `line-height` property has no effect
- it preserves white space and doesn't wrap regardless of what the when the `white-space` property says otherwise? That `text-overflow:ellipsis` takes effect even when `overflow` is `visible` (which would turn it off on other elements)…

I suppose there's more, but I don't know it off the top of my head, and would greately appreciate input from browsers, so that I don't have to do much reverse engineering.

By the way, is this best explained in terms of a dedicated and simple (given that there's only ever a single line of plain text) layout model, or should this be explained in terms of existing CSS things applied to various anonymous / shadow boxes, with some amount of property hoisting?

**Closed** 2018-03-06 10:06 UTC
Labels: Closed Accepted by CSSWG Resolution, Tracked in DoC, css-overflow-4

**Comment by simevidas** [comment] 2018-03-28 19:49
@frivoal The spec now states:

> The `line-height` property has no effect

Source: https://drafts.csswg.org/css-ui-4/#control-specific-rules

But that’s not what browsers do. When `line-height` is set, the `<input type="text">` element increases in height to account for that.

Demo: https://codepen.io/simevidas/pen/zWRGJd

Shouldn’t the spec match browsers, or did I misunderstand it?

**Comment by frivoal** [comment] 2018-03-28 23:21
You're right. Not totally sure how line-height got added to the list, as it does have an effect. Correcting the spec.

**Comment by karlcow** [comment] 2018-03-29 01:12
It probably refers to https://codepen.io/webcompat/pen/qoxqOm

![capture d ecran 2018-03-29 a 10 09 53](https://user-images.githubusercontent.com/505230/38064525-5d4acaa0-3339-11e8-85ac-977a4e82648a.png)

* Left Chrome Canary Version 67.0.3382.0 (Build officiel) canary (64 bits)
* Center Safari Tech Preview Release 52 (Safari 11.2, WebKit 13606.1.9.3.1)
* Right Firefox Nightly 61.0a1 (2018-03-28) (64-bit)
