### ISSUE TITLE
[css-transforms-1] Transformable Elements Too Restrictive

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#2033] opened 2017-12-03 02:33 UTC
https://www.w3.org/TR/css-transforms-1/#transformable-element

> A transformable element is an element in one of these categories:
>
>    *  an element whose layout is governed by the CSS box model which is either a block-level or atomic inline-level element, or whose display property computes to table-row, table-row-group, table-header-group, table-footer-group, table-cell, or table-caption [CSS2]
>    *  an element in the SVG namespace and not governed by the CSS box model which has the attributes transform, patternTransform or gradientTransform [SVG11].

The first bullet excludes flex and grid items. I think it should be restructured as a blacklist rather than a whitelist so that it remains correct going forward. Afaict the only thing that's intended to be excluded is table columns/colgroups and non-replaced inlines.

**Comment by smfr** [comment] 2018-04-09 11:30
Duplicate of issue #908

**Closed by smfr** 2018-04-09 11:30 UTC
Labels: Needs Edits, css-transforms-1
