### ISSUE TITLE
[cssom] Editorial: “Parsing Selectors” refers to inexistent production in `css-selectors-4`

### ISSUE THREAD

**Issue by danburzo** [w3c/csswg-drafts#10235] opened 2024-04-20 08:03 UTC
Maybe this section can reflect the updated grammar from Selectors 4, ideally cross-linked to the production?

> __§ [5.1. Parsing Selectors](https://drafts.csswg.org/cssom/#parsing-selectors).__ To parse a group of selectors means to parse the value using the `selectors_group` production defined in the Selectors specification and return either a group of selectors if parsing did not fail or null if parsing did fail.

**Comment by cdoublev** [comment] 2024-04-21 08:42
Duplicate of #1511.

**Closed by cdoublev** 2024-04-21 08:42 UTC
