### ISSUE TITLE
[css-sizing-3] overflow setting should affect min-content

### ISSUE THREAD

**Issue by Dan503** [w3c/csswg-drafts#2683] opened 2018-05-19 00:39 UTC
See https://github.com/w3c/csswg-drafts/issues/2270#issuecomment-390053485

https://www.w3.org/TR/css-sizing-3/#valdef-width-min-content

If `overflow` is set to things other than `visible` then that should also affect `min-content`.

If a developer sets `overflow: hidden;` on a div placed in a css-grid column set to 1fr, currently that div will never allow the overflow to take affect.

Any time a developer sets an `overflow` property, it is a clear sign that the developer intends for the content to be able to overflow it's container.

**Comment by fantasai** [comment] 2018-05-21 21:43
Thanks @Dan503.  :) I think I disagree with you specifically on this point: if the author specifically asks the element with `overflow` to size to its `min-content` size, then that's what should happen. Otherwise we can't intelligently combine it with other constraints, e.g. `width: min-content; max-width: 100%` shouldn't be equivalent to `width: 0; max-width: 100%` if `overflow` is set.

However, see https://github.com/w3c/csswg-drafts/issues/1865 for making `overflow` affect the min-content _contribution_, which I think will solve the problem you call out in 2270. I really want to fix this, but I have to first prove Web-compatibility, which is hard. :( If you think it'd be worth doing for Grid and Flex only, even if we can't make it happen for Block, please comment there to that effect...

**Comment by Dan503** [comment] 2018-05-21 22:28
Ahh ok, I agree with the direction that the issue discussion is going in that issue. :)

I'm not sure how this affects block display though :/

**Comment by tabatkins** [comment] 2018-06-13 18:44
Yeah, this is a dupe of #1865. Closing so conversation can happen over there instead. ^_^

**Closed by tabatkins** 2018-06-13 18:44 UTC
Labels: css-sizing-3
