### ISSUE TITLE
[cssom-view-1]  Bikeshed FATAL ERROR: Couldn't find section '#overflow-scroll-position' in spec 'css-align-3'

### ISSUE THREAD

**Issue by bradtriebwasser** [w3c/csswg-drafts#7991] opened 2022-10-31 22:03 UTC
There is currently a fatal bikeshed error at https://drafts.csswg.org/bikeshed/cssom-view. I think this is affecting downstream references to the draft version of `cssom-view-1`.

The `bikeshed refs` command is missing references from the editors draft, for example `#web-exposed-screen-information`.

**Comment by plinss** [comment] 2022-10-31 22:07
Dupe of https://github.com/tabatkins/bikeshed/issues/2379

Should be fixed as soon as the spec parser is able to run through all the specs, give it an hour.

**Closed by plinss** 2022-10-31 22:07 UTC
