### ISSUE TITLE
[css-text-decor-4] Consider adding a third value (skip?) for text-decoration-skip-ink.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#2818] opened 2018-06-25 23:22 UTC
https://drafts.csswg.org/css-text-decor-4/#text-decoration-skip-ink-property right now only defines `auto | none`, where `auto` is meant to skip.

It seems reasonable to be able to do per-platform ink-skipping considering the defaults of a platform or a language (e.g., don't skip by default on Windows), while allowing authors to explicitly skip when they want.

Would it be reasonable to make the property take a third value to explicitly skip, and give more freedom to the UA for the `auto` value?

**Comment by litherum** [comment] 2018-08-22 16:30
I'd like to hear Microsoft's position on enabling ink skipping by default.

**Comment by astearns** [comment] 2018-08-22 17:29
@upsuper could you look at the discussion above and comment?

**Comment by upsuper** [comment] 2018-08-25 01:17
I don't recall my rationale... actually I don't recall whether it's me or emilio wanted that.

Anyway, I think I'm fine with `auto | none`. I'm actually a bit concerned about `all` having unfortunate behavior for scripts which shouldn't have ink-skip applied by default (or, if we still exclude some scripts, why would we call it `all`?).

**Comment by emilio** [comment] 2018-08-27 09:37
I think the rationale was that some platforms' default ink-skipping behavior is not to ink-skip.

Having only `auto` or `none` means that UAs can't differentiate between when the author has explicitly requested ink-skipping or not, so can't be smart about when to ink-skip to match platform conventions. Ideally we'd have an opt-in value, an opt-out value (`none`) and a "do the default thing", which is `auto`.

@jfkthame was the person that initially pointed the per-platform difference to me, I suggested the third value.

**Comment by upsuper** [comment] 2018-09-05 23:47
It just occured to me that browsers may want not to skip ink for certain decoration style as well, for example, Safari doesn't skip ink for wavy lines (and although Chrome does, I think it'd probably be better for them not to do so as well). Would that affect the proposed normative text for `auto`?

**Comment by litherum** [comment] 2020-01-16 21:12
I think this is a duplicate of https://github.com/w3c/csswg-drafts/issues/4277.

**Comment by fantasai** [comment] 2020-01-23 15:08
Fixed in https://github.com/w3c/csswg-drafts/commit/0d4d229d828ca297f3974a4d1820cd28e112f3d2 per issue #4277 by adding `always` keyword. We could bikeshed the name of the keyword, but I guess this issue is closed? @upsuper?

**Comment by upsuper** [comment] 2020-01-25 22:46
I think I'm fine with that.

I'd like to note that the rationale between this issue and #4277 seem to be quite different. This is about overriding per-platform default, and the other is about overriding browser heuristic. If the goal is to override per-platform default of not doing skip ink, a value should still selectively avoid skipping ink on certain characters, while for the other that behavior should be suppressed.

However, given https://github.com/w3c/csswg-drafts/issues/2818#issuecomment-416172220 both ideas were from @jfkthame, and I suspect he's probably concerning more about what he said in #4277 rather than per-platform default thingy. Also it doesn't seem to me that difference on per-platform default is something meaningful anymore given the current landscape that every major browser has shipped that by default on all platforms they support.

So I think three values like what is done in https://github.com/w3c/csswg-drafts/commit/0d4d229d828ca297f3974a4d1820cd28e112f3d2 makes sense.

But similar to @jensimmons in https://github.com/w3c/csswg-drafts/issues/4277#issuecomment-574779188 I personally think `all` is better than `always` as well. The `all` here implies that we apply the skip-ink to all characters touching underline / overline, overriding browser heuristic of conditional applying. And indeed pairing `none` with `always` doesn't feel very sensible.

**Closed** 2020-04-26 01:22 UTC
Labels: Closed Accepted by CSSWG Resolution, Commenter Satisfied, css-text-decor-4
