### ISSUE TITLE
[css-cascade-5]cascading and inheritance level 5

### ISSUE THREAD

**Issue by mahjs** [w3c/csswg-drafts#7889] opened 2022-10-17 09:41 UTC
Hello everyone,
I was wondering that we could use an !important keyword when we are declaring a cascade layer to specify that ALL the declaration in that specific layer are specified as !important.
It would be a nice feature...
Consider it.
Thanks

**Comment by romainmenke** [comment] 2022-10-17 09:57
duplicate of https://github.com/w3c/csswg-drafts/issues/7535

**Comment by dbaron** [comment] 2022-10-17 13:20
closing as duplicate of #7535, which is another request for what I agree is the same feature.

**Closed** 2022-10-17 13:20 UTC
