### ISSUE TITLE
[css-grid] Doubts about specified and computed value of `grid-auto-flow` property

### ISSUE THREAD

**Issue by mrego** [w3c/csswg-drafts#1834] opened 2017-09-26 20:42 UTC
The [spec text](https://drafts.csswg.org/css-grid/#propdef-grid-auto-flow) is the following:
> Computed value: specified value
> Canonical order: per grammar

I'm testing something like this:
```js
  grid.style.gridAutoFlow = "row";
  console.log(".style: " + grid.style.gridAutoFlow);
  console.log("computedStyle: " + window.getComputedStyle(grid).gridAutoFlow);
```

And I'm setting different values than `row`.
The output is:
```
1) Set grid-auto-flow to 'row'
	1.1) .style: row
	1.2) computedStyle: row
----------------------------------------
2) Set grid-auto-flow to 'row dense'
	2.1) .style: row dense
	2.2) computedStyle: row dense
----------------------------------------
3) Set grid-auto-flow to 'dense row'
	3.1) .style: row dense
	3.2) computedStyle: row dense
----------------------------------------
4) Set grid-auto-flow to 'dense'
	4.1) .style: row dense
	4.2) computedStyle: row dense
----------------------------------------
5) Set grid-auto-flow to ''
	5.1) .style: 
	5.2) computedStyle: row
```

The implementations match in all the cases but 4.1) which is:
* Firefox and Edge: `row dense`
* Chrome and WebKit: `dense`

Which one is right (if any)?
And about the rest of the results, are they right? I guess they're right due to the *Canonical order: per grammar* but I'd like to confirm.

I'm asking this because we're upstreaming to WPT the Chromium/Blink tests and I realized that this one has a minor interoperability issue. :smiley:

**Comment by fantasai** [comment] 2017-09-27 05:01
Canonical order refers to the order in which multiple things are serialized. It doesn't say what to serialize. I think the CSSOM generally recommends to use the most backwards-compatible shortest representation, so 'row', 'dense', 'column', and 'column dense' would be valid serializations of `[ row | column ] || dense`. However, I'm not a CSSOM expert. :) Best to check with @tabatkins and/or @zcorpan (or @dbaron who knows pretty much everything).

**Comment by tabatkins** [comment] 2017-09-27 18:02
Yes, those are indeed the four valid serializations for the property; anything else is specifying more information than necessary. So 4.1 should be just `dense`.  2 and 3 should probably also be just `dense`.

Unfortunately, I think CSSOM no longer has the wording specifying this.  And implementations in general disagree a lot in serialization, because we don't specify very much of it. :(

**Comment by fantasai** [comment] 2017-09-27 23:01
Closing as duplicate of #1564.

**Closed by fantasai** 2017-09-27 23:01 UTC
Labels: css-grid-1, cssom-1
