### ISSUE TITLE
[css-contain-3] Rename 'none' to 'normal'

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#7402] opened 2022-06-22 16:43 UTC
Since we decided elements with `container-type: none` still have style containment, should we rename `none` to `normal`?

**Comment by SebastianZ** [comment] 2022-06-22 19:19
I guess that's actually a duplicate of #7202.

I'm for that, since we now actually _have_ some kind containment as initial value.
I want to point out again, though, that we still have the issue with the other keywords not reflecting that they do not overwrite style containment. But that's probably worth it's own issue.

Sebastian

**Comment by SebastianZ** [comment] 2022-06-22 20:03
>  I want to point out again, though, that we still have the issue with the other keywords not reflecting that they do not overwrite style containment. But that's probably worth it's own issue.

I've now created #7403 to discuss that.

Sebastian

**Comment by dbaron** [comment] 2022-06-29 19:31
The new issue mentioned above is #7431.

**Closed** 2022-07-01 18:03 UTC
Labels: css-contain-3
