### ISSUE TITLE
[css-selectors] Support universal selector usage with tagname `*tagname`

### ISSUE THREAD

**Issue by brandonmcconnell** [w3c/csswg-drafts#8392] opened 2023-02-01 22:09 UTC
Currently, all/most selectors support use after the universal selector.

For example…

<table>
  <thead>
    <tr>
      <th>w/ universal selector</th>
      <th>w/o universal selector</th>
      <th>identical targeting</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><code>*.class</code></td>
      <td><code>.class</code></td>
      <td>✅</td>
    </tr>
  </tbody>
  <tbody>
    <tr>
      <td><code>*#id</code></td>
      <td><code>#id</code></td>
      <td>✅</td>
    </tr>
  </tbody>
  <tbody>
    <tr>
      <td><code>*[attribute]</code></td>
      <td><code>[attribute]</code></td>
      <td>✅</td>
    </tr>
  </tbody>
  <tbody>
    <tr>
      <td><code>*:pseudo</code></td>
      <td><code>:pseudo</code></td>
      <td>✅</td>
    </tr>
  </tbody>
  <tbody>
    <tr>
      <td><code>*::pseudo</code></td>
      <td><code>::pseudo</code></td>
      <td>✅</td>
    </tr>
  </tbody>
  <tbody>
    <tr>
      <td><code>*elem</code></td>
      <td><code>elem</code></td>
      <td>❌</td>
    </tr>
  </tbody>
</table>

Some advantages to allowing the universal selector to prepend tagname selectors are:
* better consistency in how all selectors behave with the universal selector
* easier nesting syntax agreed upon nesting syntax
  
  Up until now, the generally accepted and voted upon nesting syntax requires wrapping a selector with something like `:is()` or `:where()` when it begins with an alpha character since that could easily be confused with a CSS property name. That can look something like this:
  
  ```css
  a:hover {
    color: hotpink;
    :is(aside) & {
      color: red;
    }
  }
  ```
  
  With this change to how the universal selector works next to tagnames, this same block could now be rewritten much more concisely using `*` like this:
  
  ```css
  a:hover {
    color: hotpink;
    *aside & {
      color: red;
    }
  }
  ```

---

I put together a pen for this which can be used for demonstrating this proposal and also to test if/when this is implemented:
https://codepen.io/brandonmcconnell/pen/eYjYVrE

<div align="center">
  <a href="https://codepen.io/brandonmcconnell/pen/eYjYVrE" target="_blank">
    <picture>
      <source media="(prefers-color-scheme: dark)" srcset="https://user-images.githubusercontent.com/5913254/216177278-10842410-fc93-4ddd-bf4c-9b3504b522b3.png">
      <img alt="Ambiguous Universal Selector CSS" src="https://user-images.githubusercontent.com/5913254/216177255-d313edf9-5e4c-44b5-ab6d-3cb49a472eb4.png" width="400">
    </picture>
  </a>
</div>

**Comment by Loirooriol** [comment] 2023-02-02 13:54
Duplicate of #8253.

**Closed by Loirooriol** 2023-02-02 13:54 UTC
