### ISSUE TITLE
[css-values] calc()'s divisions should support numeric expressions

### ISSUE THREAD

**Issue by nox** [w3c/csswg-drafts#1241] opened 2017-04-18 13:26 UTC
https://drafts.csswg.org/css-values/#calc-syntax

The spec says `calc()` supports only numbers after `/`, thus excluding things like `(1 + 1)`. Both Firefox and WebKit support the latter, so the spec should be changed.

Cc @dbaron @SimonSapin

**Comment by dbaron** [comment] 2017-04-18 13:28
I believe the spec used to allow for dividing by numerical-only expressions; I'm not sure why that changed.  (We also want to expand to allowing more in the future, so I don't see the harm in allowing the implemented thing now.)

**Comment by FremyCompany** [comment] 2017-04-19 02:31
Works in Edge too. If it works everywhere, I agree we should update the spec.

**Comment by FremyCompany** [comment] 2017-04-19 02:36
The grammar also doesn't allow the calc( calc(...) ) we resolved to accept, so it should be updated to include that option as well. Depending on how we decide to fix this issue, it might depend on previous PR so I'll refrain from making the change now.

**Comment by tabatkins** [comment] 2017-04-19 02:57
The OP's bug is invalid; the grammar in <https://drafts.csswg.org/css-values/#calc-syntax> definitely allows numeric expressions in the denominator, and the type-checking in <https://drafts.csswg.org/css-values/#calc-type-checking> is referring to "resolved types". Expressions like `(1 + 1)` have a "resolved type" of `<number>`.

François's issue is also invalid - a `calc()` will always resolve to either a `<number>`, `<percentage>`, or `<dimension>`, so nested calc()s are definitely allowed per the grammar.

**Comment by FremyCompany** [comment] 2017-04-19 03:02
@tabatkins Oh, yes, you are right about my second issue!

The first issue was valid before the spec changed. The spec seems to have been accidentally changed by my pull request, I don't know why... I made the commit in a branch. Did someone merge it?

**Comment by FremyCompany** [comment] 2017-04-19 03:05
Here is what I see in the spec now:

```
The syntax of a calc() function is:
<calc()> = calc( <calc-sum> )
<calc-sum> = <calc-product> [ [ '+' | '-' ] <calc-product> ]*
<calc-product> = <calc-value> [ '*' <calc-value> | '/' <calc-number-value> ]*
<calc-value> = <number> | <dimension> | <percentage> | ( <calc-sum> )
<calc-number-sum> = <calc-number-product> [ [ '+' | '-' ] <calc-number-product> ]*
<calc-number-product> = <calc-number-value> [ '*' <calc-number-value> | '/' <calc-number-value> *
<calc-number-value> = <number> | ( <calc-number-sum> )
```

which is what my pull request was adding. I am fairly confused I must say.

**Comment by FremyCompany** [comment] 2017-04-19 03:11
I think the bikeshed watcher screwed up. The spec was just updated to include my PR but the last commit in master is still 6 days old. Next time the watcher will regenerate the spec, my PR will disappear.
> https://github.com/w3c/csswg-drafts/blob/master/css-values/Overview.bs

**Comment by tabatkins** [comment] 2017-04-19 03:11
Sigh, yes, this confused me too. According to @plinss this is due to a bug in Mercurial's bridging.  Okay, nm, let's just merge the PR.

(@plinss suggests not doing PRs from the main repo, as it causes this. Do it in your fork like normal.)

**Comment by FremyCompany** [comment] 2017-04-19 03:14
Thanks for investigating! Good to know, too... 

The downside is that it means I can't use the edit button on github to fix the specs. That seems mildly annoying. On my work PC it's a no-brainer but at home I find it easier.

**Comment by plinss** [comment] 2017-04-19 03:17
@FremyCompany you can hit the "Fork" button on GitHub to fork the repo into your own account, then you can use the "Edit" button in that repo

**Comment by fantasai** [comment] 2017-05-17 21:57
Agenda+ to confirm with the WG that this goes in L3. Since L4 is going to have unit algebra in the denominator, it seems to me that this edit was intended for L3).

**Comment by tabatkins** [comment] 2017-05-23 02:41
Yes, this is just a mistake in the L3 spec (my fault, I think).  It matches current impls.

**Comment by FremyCompany** [comment] 2017-05-29 22:58
I think edits were already made, closing the issue.

**Closed by FremyCompany** 2017-05-29 22:58 UTC
Labels: Closed Accepted as Obvious Bugfix, css-values-3
