### ISSUE TITLE
[css-logical] Logical properties should be animatable like the physical ones

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2751] opened 2018-06-09 17:12 UTC
I don't see why this shouldn't be possible:

```css
#element {
  animation: size 1s infinite alternate;
}
@keyframes size {
  from { inline-size: 100px }
  to { inline-size: 200px }
}
```

I expect it to animate just like if I used `width`. But the [spec](https://drafts.csswg.org/css-logical/#dimension-properties) says

> Animation type: discrete

On Chrome it's effectively discrete, on Firefox it doesn't animate at all. https://jsfiddle.net/45e6okrm/

**Comment by birtles** [comment] 2018-06-11 00:18
From memory, we began implementing this in Firefox but never finished it. It's complicated by the fact that you can also animate the `writing-mode` etc. so that part-way through the animation the mapping for the properties changes, e.g.

```css
#element {
  margin: 50px 100px;
  animation: yer 5s;
}
@keyframes yer {
  to { margin-inline-start: 200px; writing-mode: vertical-lr; }
}
```

As a result you can't just do the mapping to physical properties when you set up the animation. Instead you need to re-evaluate the mapping whenever the _animated_ value of the `writing-mode`, `direction` etc. change.

**Comment by upsuper** [comment] 2018-06-11 00:29
> It's complicated by the fact that you can also animate the writing-mode etc. 

If that's where the difficulty is from, maybe we should put `writing-mode` and `direction` into the category of proeprties that is not animatable. I don't see how animating them can be useful, and I guess it makes sense to get rid of the animatability of them if that interferes with other stuff.

**Comment by birtles** [comment] 2018-06-11 00:50
(I should clarify that responding to changes in the _animated_ value is more difficult than responding to other changes in the computed value.

In order to avoid triggering transitions due to animations, UAs need to distinguish between non-animated style updates and animated style updates. In Gecko we do this using a separate style resolution step for animations and I suspect in order to do transitions properly with regards to inheritance, other UAs will need to do something similar, if they don't already. As a result, while non-animation related changes will get picked up naturally during the animation styling, changes due to animation itself need special handling.

We already have a similar situation with `font-size` and custom properties but those only affect the property values where as this affects the property name mappings.)

**Comment by fantasai** [comment] 2018-06-11 20:02
@upsuper Currently `writing-mode`, `text-orientation`, and `direction` are all listed as not animatable. (By contrast, `unicode-bidi` is listed as discretely animatable.)

**Comment by fantasai** [comment] 2018-06-11 20:06
@Loirooriol Bikeshed is auto-filling the Animatable line in the propdef tables. :( It should really stop doing that. If the spec left out the Animatable line, it should either leave it out of the output or post an error.

**Comment by fantasai** [comment] 2018-06-11 20:22
Fixed the Animatable lines to match their corresponding physical properties (as was always intended) in  https://github.com/w3c/csswg-drafts/commit/bfba9a7438c0001a350132f31f1cd8845a2bba73

@birtles Does there need to be any further clarifications anywhere?

**Comment by birtles** [comment] 2018-06-14 04:13
Yes, we should update Writing Modes spec to say "Animation type: none" since "Animatable: no" is often taken to mean "Animation type: discrete" (after we resolved that properties should be animatable by default and only a very small subset of properties should be marked as explicitly not animatable).

**Comment by Loirooriol** [comment] 2018-06-14 04:33
Just as a reminder, `display` should also be updated: https://github.com/w3c/csswg-drafts/issues/72#issuecomment-210236431.

**Comment by majido** [comment] 2018-07-09 14:36
@emilio your FF patch only makes `direction` and `writing-mode` non-animatable. 

But my reading of that csswg thread was that we needed to more properties non-animatable namely:
`direction`, `text-orientation`, `unicode-bidi`, `writing-mode`.

Since the specifications have not been updated yet can someone please clarify the exact change?

PS: I just found our about your patch since [my Chromium patch](https://chromium-review.googlesource.com/c/chromium/src/+/1127062/7/third_party/WebKit/LayoutTests/external/wpt/web-animations/animation-model/animation-types/property-list.js#b1427) conflicted with your wpt test changes.  Yay for wpt despite more conflict :wink:

**Comment by emilio** [comment] 2018-07-09 14:42
Heh, indeed, yay for WPT :-)

I updated those because those are the only properties that affect the logical -> physical property mapping. I did leave a `TODO` re. `text-orientation`, explaining the reasoning here:

  https://github.com/mozilla/gecko-dev/commit/c6c50bd593b212a0b879a81dd124b56ee0e60bcc#diff-2bcfd81b55b37cd491bddf83a0a71842R43

I think those two are the only ones needed for logical properties themselves, though I'm happy to change `text-orientation` and `unicode-bidi` as well. As the minutes say they're not really useful. But they didn't block my work in https://bugzilla.mozilla.org/show_bug.cgi?id=1309752 :)

**Comment by emilio** [comment] 2018-07-09 14:54
To be clear, the resolution says clearly that the four properties shouldn't be animatable, just two of them weren't blocking my immediate work :P 

I'm happy to send a patch of the other two, though I guess I'll have the same problem as soon as your WPT changes land.

@majido I just filed https://bugzilla.mozilla.org/show_bug.cgi?id=1474317 to update the other two properties, I'm happy to change them as soon as your test changes land (or before if you want, I don't particularly mind :P).

**Comment by birtles** [comment] 2018-07-09 22:22
I've been writing the [Web Animations wpt](https://bugzilla.mozilla.org/attachment.cgi?id=8990650&action=diff) and [CSS Animations wpt](https://bugzilla.mozilla.org/attachment.cgi?id=8990651&action=diff) (in progress) for this and I got stuck working out how to test that `text-orientation` affects the mapping.

In a couple of places the spec says,

> The mapping depends on the element’s writing-mode, direction, and text-orientation.

but I can't find where the mapping involving text-orientation is specified.

**Comment by Loirooriol** [comment] 2018-07-09 22:31
> I can't find where the mapping involving text-orientation is specified.

I was also wondering about this. https://drafts.csswg.org/css-writing-modes/#propdef-text-orientation says `text-orientation: upright`
> causes the used value of `direction` to be `ltr`,

but according to CSS Logical the dependency is with the

> element’s computed values of writing-mode, direction, and text-orientation

so the used value shouldn't matter? I tested and neither Firefox nor Chromium considered this to affect the resolution of logical properties when I specified `direction: rtl`.

**Comment by upsuper** [comment] 2018-07-09 23:10
Based on [Abstract-to-Physical Mappings](https://drafts.csswg.org/css-writing-modes/#logical-to-physical) I don't think `text-orientation` affects any property mapping.

**Comment by nigelmegitt** [comment] 2018-07-20 09:28
For information, TTWG discussed yesterday how we change TTML2 to match this resolution and noted that in TTML there are two distinct concepts that we think are not present in CSS, i.e. _discrete_ animation vs _continuous_ animation.

Discrete animation means a step change in a property value at a defined point in time, i.e. analogous to "render this new document with these style properties now, in place of what was there before", with a syntactic construct to make that easier than actually providing a whole new chunk of content, which is the `set` element.

Continuous animation means a continually varying change in a property value along a curve with defined begin and end times and an interpolation calculation mode, defined using the `animate` element.

We [decided](https://github.com/w3c/ttml2/issues/881#issuecomment-406317560) to retain the option for discretely animating direction, writing-mode etc and interpreted the resolution made in this issue as relating only to continuous animation, which we already decided to remove from TTML2 for the relevant style attributes.

**Comment by Loirooriol** [comment] 2018-07-20 12:59
@nigelmegitt CSS differentiates between "Animation type: dicrete" and "Animation type: not animatable". See https://drafts.csswg.org/css-transitions/#animatable-types and https://drafts.csswg.org/css-transitions/#animatable-properties

The problem was that if you animate direction and writing-mode discretely, then you also need to update the logical-to-physical mapping halfway the animation, which adds complexity. So it was resolved that they don't animate at all.

**Comment by nigelmegitt** [comment] 2018-07-20 13:18
Thanks @Loirooriol that's very useful. In the context of TTML, where timed updates to the physical output are the general desired outcome , the incremental increase in complexity caused by discretely animating properties that cause a new logical-to-physical mapping at a predictable time is minimal.

**Comment by ewilligers** [comment] 2018-07-21 00:31
All properties in the spec should clearly describe animation with "Animation type: not animatable" or "Animation type: discrete".

The minutes didn't explicitly mention `text-orientation`. I thought that was intended to also be "not animatable", but should it be "discrete"? Note that `text-orientation` and `glyph-orientation-vertical` should be consistent with each other.

`text-combine-upright` is the other property in the spec whose animation behavior should be described more clearly ("not animatable" or "discrete").

**Comment by birtles** [comment] 2018-07-22 23:52
> The minutes didn't explicitly mention text-orientation. I thought that was intended to also be "not animatable", but should it be "discrete"? Note that text-orientation and glyph-orientation-vertical should be consistent with each other.

See the earlier comments in this thread, but the reason for considering `text-orientation` not animatable is that the Logical Properties spec says, "The mapping depends on the element’s writing-mode, direction, and text-orientation." However, neither Xidorn or I could find how `text-orientation` affects the mapping. If it doesn't affect the mapping, then I think it would probably be ok to make it animatable.

**Comment by fantasai** [comment] 2018-08-17 21:36
@birtles It does affect the mapping: `writing-mode: vertical-rl; direction: rtl; text-orientation: upright` has a used `direction` of `ltr`. Added some clarifying notes in https://github.com/w3c/csswg-drafts/issues/691#issuecomment-413974948

**Closed** 2018-08-17 21:38 UTC
Labels: Closed Accepted as Obvious Bugfix, css-animations-1, css-logical-1, css-transitions-1
