### ISSUE TITLE
[css value and units] Proposal: add floor, round and ceil

### ISSUE THREAD

**Issue by chris70c** [w3c/csswg-drafts#4589] opened 2019-12-12 21:32 UTC
[https://drafts.csswg.org/css-values-4/#calc-notation](url)

Can we please add some rounding methods to the spec?
It's becoming impossible to design accurate layouts when each browser rounds values in a different way, this would make everything much easier.

Thanks

**Comment by Crissov** [comment] 2019-12-12 22:00
Duplicate of #2513. Please add helpful use cases there.

**Comment by tabatkins** [comment] 2019-12-12 23:58
Ah, yes, I was going to go looking for that issue. Thanks, closing as duplicate.

(And I'll rename #2513 to be a little more descriptive.)

**Closed** 2019-12-12 23:58 UTC
