### ISSUE TITLE
[css-anchor-position-1] Last @try to display none?

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#9380] opened 2023-09-20 02:04 UTC
It wasn't clear from the spec, but it would be super nice to try a bunch of layouts to see where the anchored element fits, but if it doesn't fit anywhere, don't show it. Is that possible with the current syntax proposals?

**Comment by kizu** [comment] 2023-10-06 22:59
Agree, maybe not `display: none`, but `visibility: hidden` could be nice to have. Or something like a `hidden` keyword if we'd go the route of `position-area` list of fallbacks or something similar.

Right now, a workaround for this could be to have the last `@try` render the element with 0x0 dimensions, and hide its content via a container query, but ideally it would be nice to have an ability to hide the element via the fallback mechanism.

**Comment by andruud** [comment] 2023-11-15 09:29
We won't be able to support properties that modify the layout tree within `@try`. At the time we're evaluating `@try`, we've already decided that it has a layout box.

**Comment by tabatkins** [comment] 2023-11-20 20:12
Yeah, having the ability to just hide it when nothing fits is a necessity. `visiblity: hidden` would work (except that it can be overridden by its children); we don't have to worry about lingering layout effects of having it stick around, like we would with an in-flow element.

**Comment by fantasai** [comment] 2024-02-08 22:15
@tabatkins and I drafted up a suggestion for a `position-try-final` property in https://github.com/w3c/csswg-drafts/issues/9196#issuecomment-1912788896 , which would give the options `[ always? && [ first | <<try-size>> ] ] | hide`, where `hide` was defined as

> Use the first [=position option=] (as for ''first''), but also hide the box such that it (and all of its contents) are invisible (like ''visibility: hidden'') and do not contribute to [=scrollable overflow=].

This issue is somewhat related also to the discussion in https://github.com/w3c/csswg-drafts/issues/7758

**Comment by tabatkins** [comment] 2024-02-08 22:49
I actually want to push back on this a little, now, and review what the use-case is for "just don't show me if I don't fit". When is that desired? (Assuming we already have some way of clipping you when your anchor is scrolled out of view.)

**Comment by vmpstr** [comment] 2024-02-09 20:54
The example I was thinking of is positioning help text next to a input field which provides some optional information about the text field. Depending on window size, scroller positions, other content, font size, etc, etc, I may want to try a few locations and if none of them work, just don't display the optional information. The problem with simply clipping is that it may be a worse experience if there is no way to expand the displayed area to reveal the full tooltip.

In either case, I'm sure there are other ways to solve this problem in UX land, like having smaller tooltips or not clipping them. I would just find it surprising that, as an author, I don't have a way of hiding the anchored element. I imagine, in the cases where this is desired, my last try block would then be some artificially far away spot to "hide" it.

**Comment by tabatkins** [comment] 2024-02-09 21:17
Hm. I'd think you'd want to display that text some other way, but I suppose if it's optional/decorative/etc, it would be fine to just hide it, and authors do already have a guaranteed way to "hide" it themselves (by positioning in the unscrollable area).

All right, use-case accepted. ^_^

**Comment by tabatkins** [comment] 2024-03-19 21:13
This is a dupe of #7758 now.

**Closed by tabatkins** 2024-03-19 21:13 UTC
Labels: Agenda+, css-anchor-position-1
