### ISSUE TITLE
[resize-observer] add possibility to observe offset changes

### ISSUE THREAD

**Issue by HolgerJeromin** [w3c/csswg-drafts#3877] opened 2019-04-26 12:19 UTC
In the entries of the ResizeObserver we have the contentRect and/or borderBoxSize. 

For our application we need to call code when the offset and size of a Element has changed.
But sadly the ResizeObserver is not called when the position has changed.
For us it would be nice if I could add an option to observe the offset, too.

Observing the attributes with MutationObserver and checking a diff in all boundingRects has the downside of forced reflow in many cases.

ref #3550 where delivering offsets was rejected, as they are not observed.

**Comment by tabatkins** [comment] 2019-04-26 22:51
So this sounds like it's a duplicate of #3550, then? Would you like to describe your use-case in that issue, and I'll go ahead and close this one?

**Closed by tabatkins** 2019-04-26 22:51 UTC
Labels: resize-observer

**Comment by HolgerJeromin** [comment] 2019-04-29 08:04
> So this sounds like it's a duplicate of #3550, then?

Not in my view, [see](https://github.com/w3c/csswg-drafts/issues/3550#issuecomment-467574641):

> ...to not include the offsets of the box that is being observed as the offsets are not actually be observed...

Adding these to the observe list was not discussed.

**Comment by mootari** [comment] 2021-09-02 14:37
Shouldn't this issue be reopened, since it is not a duplicate of #3550 according to https://github.com/w3c/csswg-drafts/issues/3877#issuecomment-487485053?
