### ISSUE TITLE
[css-inline-3] It's impossible to use `text-box-trim` without changing line progression within the paragraph

### ISSUE THREAD

**Issue by litherum** [w3c/csswg-drafts#8829] opened 2023-05-11 20:18 UTC
https://drafts.csswg.org/css-inline-3/#leading-trim

> Name: | text-box-trim
> -- | --
> Value: | `none \| start \| end \| both`
> 
> ...
> start
> For [block containers](https://drafts.csswg.org/css-display-4/#block-container): trim the [block-start](https://drafts.csswg.org/css-writing-modes-4/#block-start) side of the [first formatted line](https://drafts.csswg.org/css-pseudo-4/#first-formatted-line) to the corresponding [text-box-edge](https://drafts.csswg.org/css-inline-3/#propdef-text-box-edge) metric of its [root inline box](https://drafts.csswg.org/css-inline-3/#root-inline-box).

The two properties `text-box-trim` and `text-box-edge` have very different purposes. One changes the spatial relationship of blocks with respect to each other, whereas the other changes the progression of lines within a block. At a fundamental level, these purposes are orthogonal. If an author _just_ wants to change their blocks' positions, they shouldn't have to change the progression of lines _within_ their blocks.

Philosophically, there is no reason to connect `text-box-trim` and `text-box-edge` the way they're linked in the spec now. Instead, we'd like to propose changing the grammar to be something like (cribbed from the `text-box-edge` property):

> Name: | text-box-trim
> -- | --
> Value: | `leading \| [ text \| cap \| ex \| ideographic \| ideographic-ink ] [ text \| alphabetic \| ideographic \| ideographic-ink ]?`

This would allow `text-box-trim` and `text-box-edge`'s behavior to be orthogonal to each other.

**Comment by fantasai** [comment] 2023-06-11 04:44
I think this is related to (possibly a duplicate of) https://github.com/w3c/csswg-drafts/issues/8696 ?

**Comment by litherum** [comment] 2023-06-11 23:40
it is, though I think this issue has a better discussion of the problem, so I'd recommend that issue being marked as a dup of this one.

**Comment by fantasai** [comment] 2023-08-23 06:04
Discussed this with @litherum and [WebKit] Alan. The suggestion is to fix this issue and #8696 by:

- Shifting the line-box-affecting aspects of `text-box-edge` to a new property (e.g. `text-line-edge`).

- Combining `text-box-edge` and `text-box-trim` into a shorthand property (e.g. `text-box`) that sets both, so that an author can get trimming to, for example, the cap height and alphabetic baseline in a single declaration.

Open questions:

- Whether or not the longhands should exist. (Their main benefit is for internationalization, since they allow the edges to cascade independently of whether or not the trimming happens.)

- Whether there should be an `auto` value that maps `text-box-edge` to `text-line-edge`.

**Closed** 2024-08-02 18:43 UTC
Labels: css-inline-3, Closed Accepted by CSSWG Resolution, topic: text edge control
