### ISSUE TITLE
CSSWG specs need usable test suite docs

### ISSUE THREAD

**Issue by tantek** [w3c/csswg-drafts#2438] opened 2018-03-14 23:08 UTC
Problem: while CSSWG drafts link to their test suites, it is far too hard to figure out how to review & report problems with existing tests, and how to contribute new tests. We need usable test suite documentation, and should consider at a minimum having our specs directly link to where to file test suite issues.

The [WG wiki page on tests](https://wiki.csswg.org/test) is horribly out of date, as are nearly all its subpages. And links to the "Web Platform Tests" site land you at pages so opaque that it is unclear if you’ll have to guess correctly and click 3 or 30 nested links to find out where to give feedback or contribute tests. I made some bandaid fixes to that WG wiki test page with a direct link to issues and also to [Rachel Andrew](https://github.com/rachelandrew)'s excellent post [Christmas Gifts for Your Future Self: Testing the Web Platform](https://24ways.org/2017/testing-the-web-platform/), but that wiki page as a whole needs to be completely rethought and rewritten.

Since having valid (reviewed) tests for a feature is required for that feature to exit CR, and missing such tests (or being unsure of them) is often something that blocks CSSWG drafts from progressing, this issue should remain open here (perhaps as a meta issue) until sufficient solutions are found / deployed that demonstrate increased feedback and contributions to test suites for CSSWG specifications. (When people wonder why aren’t more web developers contributing or giving feedback on CSS tests, the poor usability barriers of these docs alone are a likely sufficient explanation, and thus a good place to start fixing.)

This issue directly affects all current CSSWG drafts at CR or earlier stages that are being developed in this repo and which we want to eventually (preferably efficiently) advance to PR. Thus please leave this issue open here in this repo for the CSS Working Group to resolve (rather than say, attempting to lump it or transfer it into some broader "Web Platform Tests" issue). Some more background: [issue 2378](https://github.com/w3c/csswg-drafts/issues/2378)

cc: [@gsnedders](https://github.com/gsnedders) [@liamquin](https://github.com/liamquin) [@atanassov](https://github.com/atanassov) [@astearns](https://github.com/astearns)

Labels: wg-css, PR-blocker

(Originally published at: http://tantek.com/2018/073/b1/csswg-specs-need-usable-test-docs)

**Comment by dbaron** [comment] 2018-03-15 02:24
There's another piece that I think is worth considering:  are there ways we can make the process easier?

For example, a number of browser-developers have messed up issues related to the built test suite by creating tests that worked in the web-platform-tests repo, but not in the post-build directory structure.  Do we still need the built test suites, or can we just point to tests in the web-platform-tests repo?

**Comment by rachelandrew** [comment] 2018-03-15 05:35
I'd love to help fix this, unfortunately I don't have a huge amount of free time to devote to doing so but writing dev-friendly documentation is a big part of what I do so happy to get involved in some discussion or help to map out a good approach for tackling it.

**Comment by gsnedders** [comment] 2018-03-26 22:44
Notwithstanding the web-platform-tests documentation issues (see https://github.com/w3c/web-platform-tests/issues/10177), I think there's a number of CSS WG specific issues:

 * The test build system makes it hard to find what file(s!) you need to modify to fix a test if you're looking at http://test.csswg.org/harness/ or http://test.csswg.org/suites/ (which is a large part of https://github.com/w3c/csswg-drafts/issues/2378 AFAICT)
 * The report issue button on tests at http://test.csswg.org/harness/ points at Shepherd which is read-only (and there's nothing on Shepherd to make that clear).

We could do with decent documentation on the build system (or, as @dbaron says, get rid of it) and how to deal with various things (like the growing list of warnings it produces when being built, and how you should know whether any warnings were caused by you, etc.).

**Comment by mrego** [comment] 2018-04-02 05:36
> For example, a number of browser-developers have messed up issues related to the built test suite by creating tests that worked in the web-platform-tests repo, but not in the post-build directory structure. Do we still need the built test suites, or can we just point to tests in the web-platform-tests repo?

BTW, this is being discussed in w3c/web-platform-tests#10053.

**Comment by fantasai** [comment] 2018-04-12 15:54
For reference, a pile of links I've sent over to various people to Mozilla's QA documentation from a long time ago. It was very effective at creating a community of QA volunteers.

> This is the Mozilla website around when I joined.  It has a lot of personality. ;)
>   https://web.archive.org/web/20000125153750/http://www.mozilla.org:80/
> Important docs besides the home page:
>   https://web.archive.org/web/20000229165445/http://www.mozilla.org:80/mozorg.html
>   https://web.archive.org/web/20000301043132/http://www.mozilla.org:80/get-involved.html
> ******
>   https://web.archive.org/web/20000302035824/http://www.mozilla.org:80/quality/bug-writing-guidelines.html
>   https://web.archive.org/web/20000304015940/http://www.mozilla.org:80/newlayout/bugathon.html
>
> You can also browse the website circa 2009 at
>   http://www-archive.mozilla.org/quality/
> It's a little more polished and informative at this era, but still managed by the Mozilla technical community rather than the marketing team. The overall landing page for getting involved is
>   http://www-archive.mozilla.org/developer/
> which gives a nice overview of the Mozilla development ecosystem. It was linked from the www.mozilla.org home page, which opened up people curious about Mozilla to
the possibilities of getting involved.
> 
> The common themes here are
>   * www.mozilla.org is up-front about being the home page of an open source organization and allows people curious to learn more about Mozilla development
>   * The development pages are written by developers for potential developers to be useful and welcoming
>   * QA for Gecko is encouraged and potential contributors are given the sense that there's a team of real people working on problems we all care about that could really use their help!

**Comment by svgeesus** [comment] 2024-03-05 06:36
So, given that:

- the primary source of CSS WG tests is now WPT not the ancient and un-maintained tests in Shepherd
- CSS WG specs increasingly use the `&lt;wpt>` annotations to link from specs to individual tests
- Bikeshed complains about missing tests (in WPT but not in the bikeshed source) and unfindable tests (in bikeshed but not in WPT

I believe this issue is in practice solved for many years now. Closing.

**Closed by svgeesus** 2024-03-05 06:36 UTC
