### ISSUE TITLE
[css-text][text-spacing] Visual regressions of line-start at portals and news sites

### ISSUE THREAD

**Issue by kojiishi** [w3c/csswg-drafts#9511] opened 2023-10-23 06:10 UTC
The current initial value of the [`text-spacing-trim` property](https://drafts.csswg.org/css-text-4/#propdef-text-spacing-trim) is [`space-first`](https://drafts.csswg.org/css-text-4/#valdef-text-spacing-trim-space-first). This was chosen because the ideal value `trim-auto` turned out to break novel sites at https://github.com/w3c/csswg-drafts/issues/2462.

From dogfooding a prototype, the `space-first` turned out to regresss portal sites and news sites. The regressions were found at MSN Japan and Google News, occuring multiple times a day. Some consider this a minor visual regression, while others consider a critically blocking regression.

To summairze [a long Japanese discussion at JLTF](https://lists.w3.org/Archives/Public/public-i18n-japanese/2023OctDec/0167.html):
* Most think `trim-auto` is the ideal value for body text and headlines. Note, iOS 17/macOS Sonoma applies this style by default to their native controls.
* `trim-auto` still breaks documents using a style used by some novels, as reported at https://github.com/w3c/csswg-drafts/issues/2462, while `space-first` doesn't.
* For other sites, `trim-auto` is ideal. `space-first` is a) less ideal for body text, b) quite strange for headlines, and c) critically regresses headline lists seen in portal top pages, news sites, blog sites, etc. (note the criticalness is controversial, some people consider it's minor in all cases, while others think critically blocking.)

From the feedback so far to the CSS prorotype, Android, and iOS, I think users/authors are particular about:
* Line start >>>> autospace >> adjuscent > line end

At this point, I can't find options other than defining a new value that doesn't trim line-start at all, and make it initial.

/cc @fantasai @frivoal @nt1m @vitorroriz @Clqsin45 @MurakamiShinyu @himorin @kidayasuo

**Comment by frivoal** [comment] 2023-10-23 07:33
@kojiishi Thanks for reporting this. Real world experience here is very useful. In the above post, I think you meant `trim-auto` rather than `trim-all`, but that doesn't change your main point.

> At this point, I can't find options other than defining a new value that doesn't trim line-start at all, and make it initial.

I am not sure I follow, as you also said that most people though that `trim-all` (I think you meant `trim-auto`) was the ideal value. Is it because not trimming at all gives results that are more consistent than `space-first`, even if they're not great?

Maybe we do need a new value, but I wonder how much of this problem we can address using UA stylesheets, for example by setting `text-spacing: trim-auto` on `h1`, `h2`… and maybe also on `dt`, `dd`, `li`… even if the initial value remains `space-first`?

**Comment by kidayasuo** [comment] 2023-10-23 07:34
> This was chosen because the ideal value `trim-all`

Do you mean trim-auto? I thought trim-all trims all trimmable punctuations to halfwidth regardless of where they occur.

**Comment by kojiishi** [comment] 2023-10-23 07:49
@kidayasuo Thank you, you're right. All `trim-all` replaced with `trim-auto`.

**Comment by kojiishi** [comment] 2023-10-23 08:07
@frivoal
> Is it because not trimming at all gives results that are more consistent than space-first, even if they're not great?

Yes, it's acceptable, though not great. It doesn't change the visual of line-start from without the feature implemented, so no improvements on line-start, but it doesn't regress. In these examples screenshot of `space-first` ([1](https://lists.w3.org/Archives/Public/public-i18n-japanese/2023OctDec/att-0167/02-image.png), [2](https://lists.w3.org/Archives/Public/public-i18n-japanese/2023OctDec/att-0216/image.png)), a) trimming both open parenthesis at line 1 and line 2 is ideal, b) not triming both is acceptable, and c) trimming only one of them is quite bad, especially for headlines.

> Maybe we do need a new value, but I wonder how much of this problem we can address using UA stylesheets, for example by setting text-spacing: trim-auto on h1, h2… and maybe also on dt, dd, li… even if the initial value remains space-first?

Good idea. This is not easy though, as the problem is about web-compat of existing sites, and they use `<div>` quite often.
* If we were to make `trim-auto` as the default, [Aozorabunko](https://www.aozora.gr.jp/cards/000148/files/789_14547.html) for example uses `<div>` and `<br>`.
* If we were to make `space-first` as the default, [MSN Japan](https://www.msn.com/ja-jp), [Google News Japan](https://news.google.com/home?hl=ja&gl=JP&ceid=JP:ja) for examples use `<div>`.

**Comment by kojiishi** [comment] 2023-10-23 08:45
I mean, adding UA stylesheet can't help improving the initial value due to web-compat, but adding `trim-auto` to `h1`, `h2`, `li`, etc. is a great idea.

**Comment by kidayasuo** [comment] 2023-10-23 08:49
Thank you @kojiishi for summarizing the discussion on the JLReq TF mailing list.

I agree with @nt1m that @frivoal’s idea is worth pursuing as it can apply the ideal `trim-auto` on headings and lists while maintaining compatibility.

**Comment by kidayasuo** [comment] 2023-10-24 02:15
Thank you @kojiishi for the summary. One comment. I am not sure if the “Novel” row can be generalized as a novel in general. The text data mentioned in #2462 is created in a specific way to workaround missing functionalities in CSS. To achieve half-width space before the opening bracket in the full-width indentation style, it inserts a full-width space except when the first character of the paragraph is an opening bracket. The first row is representing novels formatted in this specific way.

**Comment by kidayasuo** [comment] 2023-10-24 02:24
Related to my previous comment, is there a way to achieve the “one full-width” indentation style? The `text-indent` property in the Text Module Level 4 does not seem to support it but it might be just my misunderstanding.

**Comment by kojiishi** [comment] 2023-10-24 03:18
> I feel the result of "space-first" is much better than "No trimming at line-start".

I personally don't agree, the table in https://github.com/w3c/csswg-drafts/issues/9511#issuecomment-1774991353 is to pick up all voices, so updated. It was "the worst case list" but now updated to "the worst - best range list". I hope this looks better.

**Comment by kojiishi** [comment] 2023-10-24 03:23
> One comment. I am not sure if the “Novel” row can be generalized as a novel in general. 

How about e-Books? Or if you have suggestion, that helps. I agree the style sometimes happens in non-novels or non-e-Books sites, but IIUC it's considered "critical" for e-Books sites, no?

**Comment by MurakamiShinyu** [comment] 2023-10-24 04:41
@kojiishi 
> I personally don't agree, the table in [#9511 (comment)](https://github.com/w3c/csswg-drafts/issues/9511#issuecomment-1774991353) is to pick up all voices, so updated. It was "the worst case list" but now updated to "the worst - best range list". I hope this looks better.

Thanks! Now this table looks very good and interesting. In my feeling, all "Ok"s in the `space-first` column will be "Better", as I commented before ("I feel `space-first` is better than "No trimming at line-start" in this case, but I understand some people may feel this is a regression.").

**Comment by kojiishi** [comment] 2023-10-24 04:57
Done.

**Comment by kidayasuo** [comment] 2023-10-24 05:21
> > One comment. I am not sure if the “Novel” row can be generalized as a novel in general.
> 
> How about e-Books? Or if you have suggestion, that helps. I agree the style sometimes happens in non-novels or non-e-Books sites, but IIUC it's considered "critical" for e-Books sites, no?

Sorry, I will take back my original comment. As [EBPAJ EPUB 3 File Creation Guide](http://ebpaj.jp/counsel/guide) recommends using fullwidth character to indent, and removing it when the first character is a fullwidth bracket, I agree it will represent major part of novels.

**Comment by frivoal** [comment] 2023-10-24 06:22
> is there a way to achieve the “one full-width” indentation style?

The "proper" way (clean separation of content and style) would be:

```css
text-spacing: trim-auto;
text-intent: 1em; /* or 1ic */
hanging-punctuation: first;
```

browser support for `hanging-punctuation` is however incomplete, which is why authors that want to use this style commonly use the trick you mentioned:
> inserts a full-width space except when the first character of the paragraph is an opening bracket. The first row is representing text data prepared in this specific way.

**Comment by frivoal** [comment] 2023-10-24 06:30
> I am not sure if the “Novel” row can be generalized as a novel in general. The text data mentioned in https://github.com/w3c/csswg-drafts/issues/2462 is created in a specific way to workaround missing functionalities in CSS.

My understanding is that the effect achieved by this style is not specific to novels in theory, and could be desired by anyone. However, in practice, many novel EPUBs (and publications of the same content on the web) use this style because they are particular enough to try and work around the historical deficiencies of CSS (so they are prepared according to http://ebpaj.jp/counsel/guide), while other content that use this style is quite rare. But it does happen. Here is an example:

https://www.mofa.go.jp/mofaj/press/kaiken/kaiken6_000123.html

For content prepared in this style, regardless of whether it is a novel or not, applying `trim-auto` can be a fairly serious problem, as we may not reliably see the start of any paragraph starting with an opening bracket.

**Comment by frivoal** [comment] 2023-10-24 06:43
In the table of https://github.com/w3c/csswg-drafts/issues/9511#issuecomment-1774991353, I'd say that for `e-Books (incl. sites)` + `trim-auto`, the answer would be:
* "ideal" for new content *once* `hanging-punctuation` is supported
* "regression" otherwise

**Comment by kojiishi** [comment] 2023-10-24 08:56
@frivoal Thanks for the feedback. In this issue, I think I'd like to focus on how much each value can improve/regress if we change the initial value, so that we can reach a consensus on the initial value. IIUC, your point is about updating the CSS to get the desired results, is that right? It's a great discussion point and I wasn't aware of the need for `hanging-punctuation`, but I hope this issue focuses on the initial value.

Or if I'm mistaken, and it's relevant for changing the initial value behavior and how it improves/breaks existing content, can you clarify?

**Comment by frivoal** [comment] 2023-10-24 09:52
I mentioned this here because @kidayasuo asked, and because I find it relevant to what is / isn't "ideal": once `hanging-punctuation` is widely supported, all "ideal" layouts can be achieved with `auto-trim`, but as long as it is missing, `space-first` used together with U+3000 is needed for some layouts (which are popular in novels). I don't think it changes anything to what we can do with regards to compatibility, but it could be relevant to people's preferences for various options.

**Comment by MurakamiShinyu** [comment] 2023-10-24 15:38
@kojiishi
In the "No trimming at line-start" column in the table, I feel they are "Poor" rather than "Fine". So they should be corrected to "Poor - Fine" or "Poor - Ideal".

About "Existing implementations" of `space-first`, we can take up ebook readers Kindle and Kinoppy. I wrote about these implementation in #2462:

> The text-spacing is not yet implemented in web browsers, but some part of this feature is already seen in ebook readers.
> I put here two example screenshots (Kindle for PC, and Kinoppy for PC): …
> 
> … In the Kindle case, all opening punctuations ("「" and "『") are set half-width at start of lines. On the other hand, in the Kinoppy case, only the opening punctuation ("『") after a soft wrap break is set half-width, and kept full-width at beginning of paragraphs.
> While Kinoppy's behavior is a normal Japanese typesetting style, Kindle's behavior is not so. Setting opening punctuation half-width at beginning of a paragraph with no indent is hard to recognized as beginning of a paragraph. I know Japanese publishing people asking Kindle dev to fix it.

That is, at that time (in 2018), Kinoppy already had implemented `space-first` as the default behavior, and Kindle had implemented `trim-auto`. And after that, Kindle changed the behavior to `space-first`.
So now at least Kindle and Kinoppy are existing implementations of `space-first`.

**Comment by kojiishi** [comment] 2023-10-25 08:16
@frivoal Right, agree. The comparison table for "what each value can achieve" is very important for choosing the initial value. We want to choose the initial value that provides the best results in the widest use cases. Your and @kidayasuo's comments are very helpful for that.

Another table is needed for choosing the initial value, to ensure "which value is safe to ship for existing content." With your comment, I started thinking about creating one table that contains both, but that'll likely be very complex, as we'll want to add comments a lot more to all other cells too. As you might agree, so many people have words to say for their favorite styles.

When comparing "valuable" and "safe", I think we want to choose the one that is "the most valuable value within the safe values." If there's a consensus here, it will be 2 step process; filter by safety, then filter by valuableness.

I created this table for the first step, because currently proposed initial value turned out to break portal sites in Japan, and the risk is beyond what our team can ship.

So, to all, I'd like to suggest us to focus on the safety and web-compat first. If we find multiple safe candidates, we can discuss their values.

**Comment by kojiishi** [comment] 2023-10-26 07:50
A new critical regression case for `space-first` was reported ([source](https://xtech.nikkei.com/atcl/nxt/news/18/16172/).) Updating the [table](https://github.com/w3c/csswg-drafts/issues/9511#issuecomment-1774991353).
![image](https://github.com/w3c/csswg-drafts/assets/1274377/6cf00546-c556-436b-a589-eb3c11d3160b)

**Comment by MurakamiShinyu** [comment] 2023-10-26 08:52
> A new critical regression case for `space-first` was reported ([source](https://xtech.nikkei.com/atcl/nxt/news/18/16172/).) Updating the [table](https://github.com/w3c/csswg-drafts/issues/9511#issuecomment-1774991353).

Here is the html code:

```html
<p>
（1）量販価格帯の新たなEVシリーズを2027年以降、北米を皮切りに投入予定<br>
（2）コンパクトスポーツ多目的車（SUV）を含む、グローバルで人気の高いセグメントに向けたEVシリーズ<br>
（3）両社で世界規模での生産を可能にする設計を検討<br>
（4）次世代バッテリーに関する協業の深化についても検討
</p>
```

In my [`space-first` proposal](https://github.com/w3c/csswg-drafts/issues/2462), each line after `<br>` must be treated as a first line that "space-first" is applied.

Now I found that the definition of `space-first` was changed between 2022-12-31 and 2023-03-01: 

- https://www.w3.org/TR/2022/WD-css-text-4-20221231/#valdef-text-spacing-space-first

  > Behaves as space-start on the first line the block container and each line after a forced line break but as trim-start on all other lines.

- https://www.w3.org/TR/2023/WD-css-text-4-20230301/#valdef-text-spacing-trim-space-first

  > Set fullwidth opening punctuation with full-width glyphs (spaced) on the first line the block container. Otherwise as trim-auto (unless allow-end is also specified).

I believe this is a mistake.

**Comment by MurakamiShinyu** [comment] 2023-10-26 18:42
I made a test file to compare trim-auto, space-first, and space-start (= no trimming at line-start) values of the text-spacing-trim property.

HTML: [text-spacing-trim-space-first-test.html](https://gist.githack.com/MurakamiShinyu/ea7fdd45e655f97fb64545c444db9099/raw/text-spacing-trim-space-first-test.html)  
Source (GitHub Gist): https://gist.github.com/MurakamiShinyu/ea7fdd45e655f97fb64545c444db9099

You can test it with Vivliostyle which fully supports text-spacing-trim current spec.

View with Vivliostyle Viewer: https://vivliostyle.org/viewer/#src=https://gist.github.com/MurakamiShinyu/ea7fdd45e655f97fb64545c444db9099

PDF (created with Vivliostyle CLI): [text-spacing-trim-space-first-test.pdf](https://github.com/w3c/csswg-drafts/files/13181374/text-spacing-trim-space-first-test.pdf)


Screenshots:

![text-spacing-trim-space-first-test-p1](https://github.com/w3c/csswg-drafts/assets/3324737/54fe9c85-adfe-46d2-8f1a-1402499323fb)
![text-spacing-trim-space-first-test-p2](https://github.com/w3c/csswg-drafts/assets/3324737/b54a6695-7b0e-44a8-9b49-f29c4d840eda)
![text-spacing-trim-space-first-test-p3](https://github.com/w3c/csswg-drafts/assets/3324737/7a592c8a-55f5-46be-aa89-0d82500c4184)
![text-spacing-trim-space-first-test-p4](https://github.com/w3c/csswg-drafts/assets/3324737/7b9ef804-74c6-418c-a1c4-0cd97a03fa88)
![text-spacing-trim-space-first-test-p5](https://github.com/w3c/csswg-drafts/assets/3324737/796f911b-ec53-4d97-9609-865c50c86815)
![text-spacing-trim-space-first-test-p6](https://github.com/w3c/csswg-drafts/assets/3324737/9082b8cc-147b-4307-9c6a-200961e02187)
![text-spacing-trim-space-first-test-p7](https://github.com/w3c/csswg-drafts/assets/3324737/3b036170-5c5a-425b-b68b-f25ed799f106)

**Comment by MurakamiShinyu** [comment] 2023-10-28 07:34
I made a twitter poll on preference for default of line-start punctuation handling on CSS text-spacing.
https://twitter.com/MurakamiShinyu/status/1717837335382094127

So far, the most preferred is A (trim at all line-start), the second is C (no trim at line-start), and the least preferred (about 20%) is B (trim at line-start except first line).

Also some people gave comments saying:
> I think the default should be A, not for now, but for the broad impact in the future.
> Or perhaps we could default to C, which is the same as the current situation. If we wanted to make it better, we could set text-spacing.

I understood that it will be difficult to reach consensus on `space-first` (trim at line-start except first line) as default. So changing the default to `space-start` (no trim at line-start) is fine to me.

If we change the line-start default to `space-start`, we should also change the line-end default because the combination `space-start` and `trim-end` would look unbalanced. Just related issue:

- https://github.com/w3c/csswg-drafts/issues/9521

**Comment by chrishtr** [comment] 2023-12-04 18:15
It sounds like we have a possible resolution to this issue, after finding web compat problems with changing the default rendering to `trim-auto` or `space-first`. My proposed resolution is:

* Add a new `space-start` value to `text-spacing-trim`, which would mean "no trimming at line start for any line", and is the same behavior as Chromium currently has
* Set the default value of `text-spacing-trim` to `space-start allow-end`

This will resolve this issue and #9521.

The reason to make this resolution is that:

For `space-start`:
* Setting the default to `trim-auto` would have too much web compat risk for Japanese novel sites (which are quite popular in Japan)
* Setting the default to `space-first` would have too much web compat risk for major Japanese sites like Nikkei and Yahoo Japan
* `space-start` rendering is an established style for not just the web but also some print cases (e.g. it's the default for Microsoft Word)

For `allow-end`:
* `trim-end` would break editing use cases (see #9521) (Note: we could also just remove `trim-end`, that would also be fine.)

**Comment by fantasai** [comment] 2023-12-13 02:37
Maybe we should consider adding `normal` as the initial value, so that it can be adjusted as we work through compat considerations...

**Comment by fantasai** [comment] 2023-12-13 02:54
For reference, here's the completely expanded set of values (that we cut down for the current set): https://www.w3.org/TR/2022/WD-css-text-4-20221231/#text-spacing-property

Organized into a table, where you pick one from each column (or get the default value), the possibilities were:

<table>
<tr><th>Start <th>Between <th>End</thead>
<tr><td>space-start <td>space-adjacent <td>space-end
<tr><td>trim-start <td>trim-adjacent <td>trim-end
<tr><td>space-first <td> <td>allow-end
</table>

**Comment by frivoal** [comment] 2023-12-13 02:55
In https://github.com/w3c/csswg-drafts/issues/9511#issuecomment-1780592569 and https://github.com/w3c/csswg-drafts/issues/9511#issuecomment-1780688084, @kojiishi and @MurakamiShinyu discuss a regression. That has now been fixed in ed5e0b645966bc367cc2cf74c13192bf5d29deb9. Thank you for catching this.

**Comment by frivoal** [comment] 2023-12-13 03:14
I suspect that @chrishtr is right, and that a value that combines the `space-start` and `trim-adjacent` behavior is the best we can get among things that don't break compat. I'm less sure about the end-of-line side of things. One of the things we've been trying to do here is to avoid exposing all the theoretical combinations when there's not use-case nor demand for them, and stick with a more limited set of keywords that only expose those combiantions that are genuinely useful. For this `space-start`+`trim-adjacent` variant, what do we want to do on the end side? Chris suggests that the initial value should combine that with `allow-end`. Do we even need any of the other possibilities?

If not, the name `trim-adjacent` could just imply both the `space-start` and `allow-end` behavior, and all we have to do is add that value and make it the initial one.

**Comment by chrishtr** [comment] 2023-12-14 19:57
>Chris suggests that the initial value should combine that with allow-end. Do we even need any of the other possibilities?

> If not, the name `trim-adjacent` could just imply both the `space-start` and `allow-end` behavior, and all we have to do is add that value and make it the initial one.

As far as @kojiishi and I can tell we don't need behaviors other than `allow-end` right now. So we can just remove those for now and add them later if we find demand for them.

I think `normal` as the initial value, with the meaning being the same what I 'm suggesting, sounds fine since it is easy to remember.

**Comment by MurakamiShinyu** [comment] 2023-12-19 13:45
I agree with the `normal` as the initial value which implies `space-start trim-adjacent allow-end`.

Other necessary text-spacing-trim values will be:

- `trim-start` implies `trim-start trim-adjacent allow-end`
- `space-first` implies `space-first trim-adjacent allow-end`
- `trim-auto` implies `trim-start trim-adjacent trim-end`
- `space-all` implies `space-start space-adjacent space-end`
- `trim-all` (trim anywhere)

So the value syntax will be:

    normal | trim-start | space-first | trim-auto | space-all | trim-all

Other value keywords (space-start, allow-end, etc.) and combinations are probably not necessary.

**Comment by fantasai** [comment] 2023-12-19 19:02
I wonder if `trim-all` should be `force-trim` to make it clearer that it does this unusual thing?

**Comment by frivoal** [comment] 2023-12-20 03:07
Mostly agree with @MurakamiShinyu. 2 questions, one about the abilities we expose, and one syntactical:
* regardless of what we call them, just like we need both `trim-start trim-adjacent allow-end` and `trim-start trim-adjacent trim-end`, maybe we need `space-first trim-adjacent trim-end` in addition to `space-first trim-adjacent allow-end`? Even if we only pick one, I'm actually not sure which of the two matters most.
* For the choice between `trim-end` and `allow-end` together with `trim-start trim-adjacent` (and maybe with `space-first trim-adjacent`, depending on the answer to the previous question), the spec currently proposes to have an optional `allow-end` additional keyword, whose omission means `trim-end`. In the comment above, @MurakamiShinyu proposes a distinct single keyword for each possibility. I am not sure which is preferable:
    *  `normal | space-all | trim-all | trim-start | trim-auto | space-first | space-auto‡`
        ‡ `space-auto` is meant as a stand-in for variant of `space-first` which has the other behavior between `allow-end` and `trim-end`
    * `normal | space-all | trim-all | trim-auto | [ space-first || allow-end ]`
    
    I suspect the later makes it easier to progressively open up to additional arbitrary combinations of `?-start ?-adjacent ?-end` later. Not entirely sure whether that's a good or bad thing.

**Comment by MurakamiShinyu** [comment] 2023-12-20 06:22
> * regardless of what we call them, just like we need both `trim-start trim-adjacent allow-end` and `trim-start trim-adjacent trim-end`, maybe we need `space-first trim-adjacent trim-end` in addition to `space-first trim-adjacent allow-end`? Even if we only pick one, I'm actually not sure which of the two matters most.

I think we don't need `space-first trim-adjacent trim-end`. The `space-first` proposal was made for compatibility with existing contents especially Japanese ebooks. The most popular ebook reader Kindle supports `space-first trim-adjacent allow-end` (with `hanging-punctuation: allow-end`) behavior implicitly. I think this setting is good enough for such Japanese contents.

> * For the choice between `trim-end` and `allow-end` together with `trim-start trim-adjacent` (and maybe with `space-first trim-adjacent`, depending on the answer to the previous question), the spec currently proposes to have an optional `allow-end` additional keyword, whose omission means `trim-end`. In the comment above, @MurakamiShinyu proposes a distinct single keyword for each possibility. I am not sure which is preferable:
>     *  `normal | space-all | trim-all | trim-start | trim-auto | space-first | space-auto‡`
>         ‡ `space-auto` is meant as a stand-in for variant of `space-first` which has the other behavior between `allow-end` and `trim-end`
>     * `normal | space-all | trim-all | trim-auto | [ space-first || allow-end ]`
>     
>     I suspect the later makes it easier to progressively open up to additional arbitrary combinations of `?-start ?-adjacent ?-end` later. Not entirely sure whether that's a good or bad thing.

I believe `normal | space-all | trim-all | trim-start | trim-auto | space-first` is preferable (`space-auto` is not necessary). While the default (normal) behavior includes `allow-end`, it is natural that the `allow-end` behavior is unchanged when only `trim-start` or `space-first` is specified.

We could treat the text-spacing-trim property as like a shorthand for setting the following individual properties:

- Start
  - Value: space-start | space-first | trim-start
  - Initial: space-start
- Between
  - Value: space-adjacent | trim-adjacent
  - Initial: trim-adjacent
- End
  - Value: space-end | allow-end | trim-end
  - Initial: allow-end
- Other
  - Value: space-other | trim-other
  - Initial: space-other

And the text-spacing-trim values would be defined as:

|               |Start      |Between       |End      |Other      |
|---------------|-----------|--------------|---------|-----------|
|**space-all**  |space-start|space-adjacent|space-end|space-other|
|**normal**     |space-start|trim-adjacent |allow-end|space-other|
|**space-first**|space-first|trim-adjacent |allow-end|space-other|
|**trim-start** |trim-start |trim-adjacent |allow-end|space-other|
|**trim-auto**  |trim-start |trim-adjacent |trim-end |space-other|
|**trim-all**   |trim-start |trim-adjacent |trim-end |trim-other |

**Comment by vitorroriz** [comment] 2023-12-20 15:49
> I agree with the `normal` as the initial value which implies `space-start trim-adjacent allow-end`.
> 
> Other necessary text-spacing-trim values will be:
> 
> * `trim-start` implies `trim-start trim-adjacent allow-end`
> * `space-first` implies `space-first trim-adjacent allow-end`
> * `trim-auto` implies `trim-start trim-adjacent trim-end`
> * `space-all` implies `space-start space-adjacent space-end`
> * `trim-all` (trim anywhere)
> 
> So the value syntax will be:
> 
> ```
> normal | trim-start | space-first | trim-auto | space-all | trim-all
> ```
> 
> Other value keywords (space-start, allow-end, etc.) and combinations are probably not necessary.

I believe WebKit would still need 'auto' so we can possibly align spacing within the platform.

**Comment by chrishtr** [comment] 2023-12-20 17:45
We also resolved that `normal` is the default.

**Comment by frivoal** [comment] 2023-12-21 05:00
Applied most of the changes discussed above, including the new syntax, the new `normal` value, and the fact that `normal` is the initial value. See https://github.com/w3c/csswg-drafts/issues/9736 for a follow up question.

**Closed by frivoal** 2023-12-21 05:00 UTC
Labels: css-text-4, Closed Accepted by CSSWG Resolution, Needs Testcase (WPT)
