### ISSUE TITLE
[css-borders-4] Why can't we just make border with gradient ?

### ISSUE THREAD

**Issue by DinoMalin** [w3c/csswg-drafts#10206] opened 2024-04-14 16:15 UTC
When we want to put gradient in borders, the current solution is either :
1 - Use border-image with linear-background, which doesn't works with border-radius.
2 - Create a parent div with the selected gradient as a background color, put a bit of padding then using a child div to fill all the space of the parent div to create the illusion of a border : It works great except when we want to have a base background color with an opacity different than 1.
So if I can't have a div that have a border with gradient, rounded corners, and an opacity of 0.8 at the the same time, for example.
I think it would be great to handle the border-color property the same way that the background-color property is handled.

**Comment by Loirooriol** [comment] 2024-04-14 18:03
Duplicate of #9456.

**Closed by Loirooriol** 2024-04-14 18:03 UTC
