### ISSUE TITLE
[css-highlight-api] invalidation of static ranges

### ISSUE THREAD

**Issue by frivoal** [w3c/csswg-drafts#4597] opened 2019-12-13 06:49 UTC
As far as I am aware, uses of `StaticRange` prior to css-highlight-api were for ranges created by the User Agent and passed to the author.
In css-highlights-api, it's the other way around, which raises (for the first time?) the question of invalidation of static ranges, as they may have become stale by the time the browser needs to use them.

https://drafts.csswg.org/css-highlight-api-1/#range-invalidation defines a way to evaluate that. Is that reasonable? If not, what should we do instead?

**Comment by dandclark** [comment] 2020-12-18 19:33
The invalidation logic at https://drafts.csswg.org/css-highlight-api-1/#range-invalidation seems reasonable.

In addition to checking whether the start and end node are both [in a document tree](https://dom.spec.whatwg.org/#in-a-document-tree), I wonder if this should check if they are in the *same* document tree.  For example if either the start or end container is adopted into a same-domain iframe document we should probably treat the range as invalid.

Checking that the range doesn't cross the boundary of a contained element per #4598 could also be an addition here.

**Comment by sanketj** [comment] 2021-02-11 19:24
I have proposed a set of criteria for validating StaticRange here: https://github.com/whatwg/dom/issues/947. These criteria can be used for _any_ StaticRange, not just static ranges used in the highlight API. I think #4598 should be an additional restriction for the highlight API, but not something that applies generally to StaticRange.

**Comment by annevk** [comment] 2021-02-15 08:23
Why does this not use live ranges internally? Is any implementation actually planning on using static ranges internally?

cc @smaug----

**Comment by sanketj** [comment] 2021-02-15 20:20
There are certainly benefits to the highlight API using live ranges internally:
- The `Highlight` constructor can be modified to only accept `StaticRange`. The way I see it is that highlights would create and maintain their own "highlight ranges" internally, which are live, and the static ranges passed into the constructor are just inputs for creating these internal ranges.
- We wouldn't need to define any invalidation behavior for the highlight API, and #4598 wouldn't be an issue anymore.

However, I don't think we have answers yet regarding the performance tradeoff - live range maintenance cost vs. static range and highlight validation cost. It would be great to know if Safari ran any numbers on this (since they have an experimental implementation already) and what their findings were. cc: @hober, @megangardner

Regardless of which option is ultimately chosen, we will need to document this in the spec, as there are painting behavior differences depending on which way we go.

**Comment by annevk** [comment] 2021-02-16 07:21
Are the painting differences elaborated on somewhere?

**Comment by sanketj** [comment] 2021-02-16 07:44
Consider the example below:

```
<!DOCTYPE html>
<html>
  <head>
    <style>
      div::highlight(test) {
        background-color: red;
      }
    </style>
  </head>
<body>
    <div>abd</div>
    <input type='button' value='click' onclick='onClick()'>
    <script>
      let div = document.querySelector('div');
      let textNode = div.firstChild;
      let range = new StaticRange({startContainer: textNode, startOffset: 1, endContainer: textNode, endOffset: 3});
      let highlight = new HighlightRangeGroup(range); 
      CSS.highlights.set('test', highlight);

      function onClick() {
        textNode.insertData(2, 'c');
      }
    </script>
</body>
</html>
```

After the button is clicked and 'c' is inserted, the div will have text "abcd". If the highlight was represented with a live range internally, the range's end offset will become 4 and "bcd" will be painted with the highlight styles. If we were just painting the static range internally, the range endpoints will not change and only "bc" will be highlighted.

**Comment by annevk** [comment] 2021-02-16 09:27
Another consideration here is what would be better or preferred by web developers, but I realize that might be hard to get data on.

**Comment by smaug----** [comment] 2021-02-16 09:35
https://drafts.csswg.org/css-highlight-api-1/#range-invalidation  is missing things like shadow DOM, and how is that supposed to work if the start point  has been moved in DOM to be after the end point?
All those would need to be validated during paint time, and if there are lots of highlights around, like there could be for example if one implements a spellchecker using the API, the overhead during paint time might be rather significant.

**Comment by sanketj** [comment] 2021-02-17 06:48
That's why I had proposed the StaticRange validation criteria in whatwg/dom#947. That should cover the shadow DOM cases and the overlapped endpoints case. That criteria seems pretty generic, not highlight API specific, hence I proposed adding those to the StaticRange spec. To validate static highlights, we would need to run those checks, as well as an additional check for #4598. Of course, all of the above is only applicable if the highlight API paints static ranges directly, instead of using live ranges internally.

If we used live ranges internally, there are some additional questions we'll need to answer:
- How would authors be able to remove a range from a `Highlight`? If the static ranges passed into the `Highlight` constructor are just inputs that the `Highlight` uses to create its own internal live ranges that are not exposed to JS, then authors don't have access to the actual range objects being painted and can't remove them individually.
- At what point would we create the internal live ranges maintained by the highlight? A highlight is only painted if it is registered (ie. added to `CSS.highlights`). If we create the internal ranges when we construct the `Highlight` object, then we start paying the cost of maintaining them during DOM mutations, even though the highlight isn't being painted yet. Instead, we could create the internal ranges only when the `Highlight` is added to `CSS.highlights`. However, this would require storing the passed-in static ranges internally until that moment.
- At what point do we "drop" the internal live ranges? A `Highlight` can also be deregistered (ie. removed from `CSS.highlights`). Let's say that after the `Highlight` is removed, we just wait for it to go out of scope and get GC'ed, which is when the internal ranges will be released. Until these ranges are garbage collected, we are still paying the cost to maintain them during DOM mutations, even though the highlight is no longer registered. Instead, we could drop the ranges when the `Highlight` is deregistered. However, how would we re-establish the old range positions if the `Highlight` is subsequently re-registered?

With regards to the performance tradeoff, we are starting prototyping in Chromium, so we can run some perf tests to compare the static range painting overhead vs. the added maintenance cost during DOM mutations if we used live ranges internally. Hopefully that can give us a better idea on which way to go. If other implementors could do the same, that would be great too.

**Comment by smaug----** [comment] 2021-02-18 22:51
Highlight API is effectively a form of Selection API, with support for multiple Ranges, that is what Gecko has had basically forever.
It is used for example for spellchecker and IME and find, in addition to normal selection (which also supports multiple ranges - try with ctrl+mouse). So there is some experience on using Ranges. 
Doing boundary point comparisons during paint time does cause some significant performance issues currently (with WebRender because WebRender code paths haven't been optimized yet), but I'd prefer to remove all such checks from paint time.

**Comment by frivoal** [comment] 2021-03-25 07:39
> Why does this not use live ranges internally?

I think if that's the expected implementation, we should probably drop static ranges from this API entirely. The intended use case for using static ranges rather than live ones is when the author intends to run their own range invalidation logic upon DOM changes, and would like to avoid paying the cost of having the UA update the ranges first, just before they trash all these needlessly updated ranges and insert their own new ones.

If the internal implementation uses live ranges anyway, then this is pointless, and we might as well restrict authors to describing their highlights with live ranges in the first place.

**Comment by dandclark** [comment] 2021-08-03 22:15
@ffiori ran some [experiments](https://docs.google.com/document/d/1byMUPIcx2cldNlppyvRP3HX9w1NIryO_F7mgQNytMzs/edit#heading=h.7nki9mck5t64) and confirmed that at least in Chromium, adding a large number of live Ranges to a document increases the cost of DOM node moves due to the cost of keeping the Ranges up-to-date. On the other hand, with an implementation that caches StaticRange validity there is no scenario where StaticRange has significantly worse performance for Highlights.

It would be interesting to know if WebKit has done any similar experiments on their implementation.

There are realistic scenarios where a site might want to use a large number of Highlights, like a site with a lot of text implementing its own find-on-page. Allowing the use of StaticRange, without creating StaticRanges internally, could be helpful for performance in such scenarios.

I also agree with @frivoal's reply above that if we're always going to use live Ranges internally anyway, then I don't see any reason to include StaticRange in the API.

**Comment by smaug----** [comment] 2021-08-30 10:18
It is unclear to me from the resolution how using Static Ranges works if one modifies DOM. If one has 2 sibling nodes, and a StaticRange selecting them both, and then one add a new node between those siblings, StaticRange would select the first two ones, but not the last node, yet it is the last node which the user of the API wanted to be selected. Rather odd API behavior.

**Comment by dandclark** [comment] 2021-08-30 16:59
> It is unclear to me from the resolution how using Static Ranges works if one modifies DOM. If one has 2 sibling nodes, and a StaticRange selecting them both, and then one add a new node between those siblings, StaticRange would select the first two ones, but not the last node, yet it is the last node which the user of the API wanted to be selected. Rather odd API behavior.

For StaticRange, the developer has the responsibility to update the ranges when DOM mutations occur. So if the developer fails to do this, they'll observe odd behavior like in the case you pointed out. There is a deliberate tradeoff here between between ease-of-use and performance for live range vs static range.

**Comment by smaug----** [comment] 2021-08-31 08:42
Then we need to have performance tests which check how much overhead it is to observe mutations and update highlights based on them.

**Closed** 2021-09-08 16:47 UTC
Labels: Closed Accepted by CSSWG Resolution, Tested, css-highlight-api-1
