### ISSUE TITLE
Potential need for a new CSS pseudo-class for role matching

### ISSUE THREAD

**Issue by digilou** [w3c/csswg-drafts#5901] opened 2021-01-27 17:56 UTC
This was submitted as an [issue in the CSS-A11y](https://github.com/w3c/css-a11y/issues/32) repo by @jnurthen. On 27 Jan 2021, APA suggested bringing this to the CSS-WG to discuss as a CSS issue. May need joint collaboration with ARIA and APA.

**Comment by Crissov** [comment] 2021-01-29 08:20
A `:role()` proposal is already tracked in #3596. A semantic role selector is certainly better than something like regex selectors, #1008 vs #1010. An open question is whether it makes more sense to introduce, for instance, `:role(heading)` than `:heading`.

**Comment by digilou** [comment] 2021-01-29 17:20
Thank you @Crissov. I should've done a search! APA didn't want to lose the idea, but clearly it's been discussed and remains open.

**Comment by jnurthen** [comment] 2021-01-29 17:54
Note - this was not my issue. I simply copied the issue from an old aria issue (before we had the ability to move GitHub issues from one repo to another). All of this is noted in the issue.

**Comment by astearns** [comment] 2021-01-29 22:56
Closing as duplicate of #3596

**Closed by astearns** 2021-01-29 22:56 UTC
