### ISSUE TITLE
[css-fonts] Clarify what ligatures are optional

### ISSUE THREAD

**Issue by upsuper** [w3c/csswg-drafts#2644] opened 2018-05-06 10:26 UTC
Recently we got [a bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1458053) that when `text-justify: inter-character` is specified, some characters which should be composed are instead separated.

I did some investigation and found that the reason is when that is specified, or a non-zero `letter-spacing` is specified, Gecko disables features `liga` and `clig` based on the CSS Text spec which states:
> When the effective spacing between two characters is not zero (due to either justification or a non-zero value of letter-spacing), user agents should not apply optional ligatures.

while in this case, the composition is applied via `clig` feature. It sounds like `clig` is probably not an optional ligature.

But according to @jfkthame in [the bug comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1458053#c5), the example in [OpenType feature registry for `clig`](https://docs.microsoft.com/en-us/typography/opentype/spec/features_ae#a-nameclig-idcligatag-clig) clearly indicates it should be optional ligatures as it falls in the same category as ligatures like "fi". On the other hand, he also noticed that in shaping spec of some scripts, `clig` is also mentioned, which makes it less clear whether it is required, so maybe this should be conditionally treated optional.

It would probably be helpful if the spec can provide recommendation on what ligatures should be considered optional. Also any feedback from i18n wg would be great.

**Comment by r12a** [comment] 2018-05-09 12:32
Ok, this is a bit like a ball of spaghetti. Let me try to unravel it a little.

First of all, the word បាទ used for the example is in the Khmer script, not Myanmar (see https://r12a.github.io/uniview/?charlist=%E1%9E%94%E1%9E%B6%E1%9E%91). 

Second, the ligation occurs between a base character and a combining character, and my understanding is that they should not normally be separated by `text-justify:inter-character`, since they constitute a basic grapheme cluster. The units around which spacing occurs, according to https://drafts.csswg.org/css-text-3/#valdef-text-justify-inter-character, are what CSS calls 'typographic character units'. They are defined at https://drafts.csswg.org/css-text-3/#typographic-character-unit, which implies that a grapheme cluster is usually not broken (ie. you wouldn't want to separate បា).

However, third, in Thai (which is a different script again), the particular vowel-sign represented by the second character apparently is separated in certain similar circumstances, though not identical. This is actually described in an example in the spec (note that the example involves an additional combining character, the anusvara):

> In other scripts such as Thai or Lao, even though for line-breaking the typographic character matches Unicode’s default grapheme clusters, for letter-spacing the relevant unit is less than a [UAX29] grapheme cluster, and may require decomposition or other substitutions before spacing can be inserted. 

> For instance, to properly letter-space the Thai word คำ (U+0E04 + U+0E33), the U+0E33 needs to be decomposed into U+0E4D + U+0E32, and then the extra letter-space inserted before the U+0E32: คํ า. 

I'm not sure whether the presence of the anusvara (the small circle) is required to trigger this behaviour. That combination is also possible in Khmer (បាំ) and also has the special joining form of BA, but the example given is the simpler form.

So i guess there are a number of questions to ask here:

1. Is the reporter of the original bug concerned about Myanmar or Khmer text? Note that the equivalent in Myanmar, ပာဒ်, doesn't involve such a ligated form afaik, so i think they mean Khmer.

2. Does Khmer orthography expect U+1794 KHMER LETTER BA and U+17B6 KHMER VOWEL SIGN AA​ to be separated when `text-justify:inter-character` is applied?

3. Do the same rules apply for tracking as for justification? (The example of Thai above is actually in the context of letter-space, rather than justification iirc.)

3. If BA + AA are separated in Khmer, is the expectation that the special joining form of BA be retained or not? (I would assume not.)

We are in the process of putting together a group of experts in SE Asian scripts.  I'll raise an issue asking them what the expected behaviour should be.

**Comment by r12a** [comment] 2018-05-09 12:41
Oh, and btw, on Firefox 59.0.2 on Mac OS X 10.13.4 I don't see the separation reported anyway.  I hope i'm not missing something...

**Comment by upsuper** [comment] 2018-05-09 12:46
Right, this issue doesn't show up on macOS, probably because the font on macOS doesn't use `clig` for this ligature.

**Comment by nerdkid93** [comment] 2018-05-21 20:49
@r12a I am the reporter of the original Firefox bug. I do not know all of the answers to your questions but I will do as best as I can.

1. I am concerned about Khmer. This appeared as an issue when we added `l10n ` support for Khmer to one of our older web applications.
2. I would expect the letters BA + AA to not be separated since our translators told us that it looked like a "corrupted font" and the word was rendered unreadable (note: the following is a longer part of the original translated string from our application: `វើ​ការ​វិនិច្ឆយ​បាន​ល្អ `)
3. No idea
4. I don't think that BA + AA are supposed to be separated.

Let me know if I can answer any other questions about the issue and I'll do my best to get an answer for it!

**Comment by r12a** [comment] 2018-05-22 11:55
Thanks for the clarification, @nerdkid93. I put up a couple of test files for Khmer and Thai at
https://w3c.github.io/i18n-tests/misc/justification/khmer_am.html
https://w3c.github.io/i18n-tests/misc/justification/thai_am.html

Interestingly, when i tried justifying on a Windows machine with Firefox, i didn't see any separation of the BA+AA glyphs for Khmer. (I did, however, for Thai, which i think is expected.)

**Comment by SergeyMalkin** [comment] 2018-07-02 18:54
My few cents about why turning off ligatures automatically is not a good idea:

* Even for "simple scripts" this will be a problem. Switching off ligatures or contextual ligatures may change shaping results to look completely different. I don't want this to happen with even tiny spacing added.

* Situation is much worse when rule is applied to highly contextual complex scripts like Arabic. Section 8.2.1 of the spec even shows that Arabic requires special treatment where kashida should be used to increase inter-character space, and this will be

* My understanding of intent of turning off features is to prevent uneven spacing, when some glyphs are ligated and some not. But other shaping features can also be degraded sufficiently by spacing, for example cursive attachment or contextual shaping. Which means we don't actually know what features to disable. Ligature is obvious if font is "regular Latin font", but contextual alternates or stylistic sets will degrade significantly. Some stylistic sets are innocent and some are not, there is no way to know which ones. 

* There may be threshold after which features can be turned on or off. IIRC, apps tried to apply heuristics to disable ligatures. InDesign turned them off when spacing was set to at least either 1/4em or 1/10em (I don't remember exactly). But this was very long time ago, when InDesign didn't support complex scripts or contextual alternates. They essentially knew what types of fonts they are dealing with, this is not true anymore.

* There are only few ways for how spacing can be introduced.
  * Inter-character justification, which is mostly applied to East Asian scripts. Ligatures or contextual shaping are rare between ideographs, so turning features on or off doesn't have much effect on shaping results anyway.
  * Arabic justification. This case doesn't require turning features off, it will insert kashidas or use justification alternates into already shaped text.
  * Another is explicit letter-spacing, but in this case I would expect web designer to know how much spacing is added, what font is used, what features are applied (and which ones are safer to use with spacing), and what scripts will be present. This means this is very likely that decision can be made based by designers and there is no much need for layout engine to make this decision for them.

* Finally, there are problems with how this rule is defined in the spec. First, I would expect rule to be not applied when spacing is applied to space character. Second, should ligatures be turned off only for two glyphs around additional space or whole text run? Should features be switched off for all text runs on the line, including ones using different font? How about inline blocks?

**Comment by fantasai** [comment] 2018-07-03 01:00
@SergeyMalkin Explicit letter-spacing is an important case here, and no, actually, we cannot rely on the designer to know what's going on and definitely can't assume that a particular font will be used.

**Comment by SergeyMalkin** [comment] 2018-07-03 18:15
I understand that it can't be guaranteed that particular font will be used. However, designers will know font with high enough confidence and if fallback still happens it is likely to be non-descript system font that will no break with or without features applied. For me, harm from automatically disabling features is much more than occasional rendering that is not ideal (given that spacing works correctly for complex scripts).

**Comment by litherum** [comment] 2018-09-17 05:07
I'm pretty sure in Bringhurst's Elements of Typographic Style, he explicitly instructs people to turn off ligatures if applying justification / tracking. (But I can't check because I'm traveling and apparently it never got turned into an ebook.)

**Comment by litherum** [comment] 2018-09-17 16:07
I just discussed this with our type team. There are a few takeaways:

- rlig is the only feature used for required ligatures. All other features are optional.
- As such, a font that puts required ligatures in clig is a broken font.
- Text engines have workarounds and heuristics for broken fonts. Web engines shouldn’t be disabling these workarounds, as they’re needed for some fonts to work correctly (and for platform consistency). Instead, the CSS spec should be flexible enough to allow for these types of workarounds.

**Comment by bungeman** [comment] 2018-10-23 18:28
I am also interested in which ligatures are "optional". I recently added a test for font feature precedence for the 'liga' feature at https://github.com/web-platform-tests/wpt/pull/13605 . I started writing one for 'dlig' as well (see https://chromium-review.googlesource.com/c/chromium/src/+/1294874 ) but the result is somewhat surprising when based on the current wording.

As per css-fonts-3 at https://www.w3.org/TR/css-fonts-3/#feature-precedence, "setting a non-default value for the ‘letter-spacing’ property disables common ligatures." Common ligatures are specified in css-fonts-3 as 'liga' and 'clig'.

As per css-text-3 at https://www.w3.org/TR/css-text-3/#letter-spacing-property, "when the effective spacing between two characters is not zero (due to either justification or a non-zero value of letter-spacing), user agents should not apply optional ligatures." However, optional ligatures are not defined.

Since css-font-3 is more specific than css-text-3, browsers tend towards the behavior that letter-spacing only effects 'liga' and 'clig'. This leads to the somewhat surprising behavior that common ligatures may be disabled by letter-spacing, but discretionary and historical (and possibly others) are not. It would be greatly beneficial to implementors for

- css-text-3 to specify more precisely which ligatures are "optional ligatures".
- css-fonts-3 to update the precedence rule 4 to explicitly state that only "common ligatures" ('liga' and 'clig') are affected by letter spacing **or** be updated to include more ligatures (perhaps by reference to the newly explicit list of "optional ligatures").
- for css-text-3 and css-fonts-3 to unambiguously agree and be appropriately specific around letter-spacing and ligatures.

**Comment by andjc** [comment] 2018-10-24 06:05
@bungeman if I read the orifinal bug correctly it would affect mymr style fonts and not mym2 . I Myanmar fonts that were developed using a minimal set of opentype feature mainly ligatures and mark positioning. These types of fonts were developed before explicit Myanmar shapers were developed. 

There are two different issues here:
1) whether spacing should be inserted within grapheme clusters
2) what to do about fonts that misuse ligatures based on old opentype logic that was developed before explicit opentype shaping for those scripts became available.

Modern Myanmar fonts are unlikely to use liga or clig and glyphs in fonts using these features aren't really ligatures so in that sense there are not any optional nor obligatory ligatures in Myanmar.

**Comment by bungeman** [comment] 2018-10-25 15:32
As to the original issue with Noto Khmer, at https://github.com/harfbuzz/harfbuzz/issues/1310#issuecomment-432796833 it is confirmed that this is just an oddity of the specification and HarfBuzz. The 'clig' feature is normally an optional feature which should be turned off when letter spacing, but the OpenType shaping spec states that it is required for the Khmer 'khmr' script. HarfBuzz was written around the idea that the user can always force off any feature, even if that results in broken shaping. These two concepts conflict when trying to disable 'clig' just for letter spacing, so either users of HarfBuzz or HarfBuzz itself will need to take this into account. It seems rather unreasonable for every user of HarfBuzz to need to know about this, so HarfBuzz will probably need to be updated to handle this case somehow. This also explains why this particular issue may not be seen with other shapers (CoreText and DirectWrite) since they may already not allow disabling 'required' features. So a possible resolution to the Firefox issue may just be to point at this HarfBuzz issue.

As to Fraktur, there is actually a very good test for that at http://unifraktur.sourceforge.net/testcases/ligature_quirks/ which should probably be adapted in some way into the wpt project. As far as I know, OpenType does not assign a language or script tag for Fraktur for shaping purposes (there is 'PDC ' but it doesn't seem to have separate rules) and Unicode treats it as a Latin script, so it is up to the font to do any required shaping. Since there are no special rules around 'clig' for Fraktur, fonts which support it generally use 'ccmp' for required shaping of 'tz', 'ch', 'ck' and 'liga' for optional ligatures like 'tt'. If a Fraktur font used a feature other than 'ccmp' for these it's just buggy, even 'rlig' is noted as only applying to horizontal text, and Fraktur wants this applied even when laid out vertically.

I would still like some explicit resolution on whether letter-spacing (or just letter spacing) should affect 'dlig' and 'hlig' in the context of resolving features in css.

**Comment by fantasai** [comment] 2018-12-04 23:01
> I am also interested in which ligatures are "optional".

From CSS3 Text's perspective, that would be any ligatures which are not required. Per @litherum's https://github.com/w3c/csswg-drafts/issues/2644#issuecomment-422075536 that means anything except `rlig` in OpenType. And maybe there needs to be some special handling for Khmer because of its broken relationship with OpenType ligature tags. It's technically out-of-scope for CSS to define what OpenType considers required, though. I tried to add some clarifications on this point in https://github.com/w3c/csswg-drafts/commit/caf1e4747f2bd906bb9f671af8c463b28b97deda though.

Wrt Fraktur, it seems that using Fraktur changes the definition of “typographic grapheme cluster”, and pages tagged with `de-Latf` should have their segmentation adjusted accordingly. There's hundreds of examples of this type of thing, and it might be nice to have a registry where we collect info on “what's a typographic grapheme cluster” in all the various writing systems and variants thereof, but that's definitely too detailed for the CSS Specification. However the i18nWG is collecting such info in its *REQ reports, and it would be a good idea to have it noted in LatinReq and add corresponding WPT tests. https://www.w3.org/International/layout I can add this one as an example of how segmentation can vary by lang tag, though, since I think I don't have such an example yet in the spec.

Wrt updating the font feature precedence rules to be clearer about the various types of ligatures, your wording changes for rule 4 seem clearly correct to me; I'm not convinced about the others though. Deferring to @litherum and @svgeesus on that.

**Comment by bungeman** [comment] 2018-12-04 23:43
Note that HarfBuzz has since fixed the Khmer specific issue with 'clig' with https://github.com/harfbuzz/harfbuzz/commit/a95d9d8c8465ebc927bc2194dffe4ea95542e54c and https://github.com/harfbuzz/harfbuzz/commit/000d4b128eba58677acdc3b361829ff2f9a257b1 . This is sort of thing is why I explicitly added the step 6 above ("Font features of the given script which are required.") This explicitly calls out that the shaper may do whatever it thinks necessary, which I believe agrees with litherum above at https://github.com/w3c/csswg-drafts/issues/2644#issuecomment-422075536 in mentioning that "Text engines have workarounds and heuristics for broken fonts." In this case, even if the user wants 'clig' off the shaper may see that 'khmr' script is set and turn it back on anyway. In other cases this may mean that a font is detected to be broken in some way and the shaper ignores some of the requested features. Or the font may have TrueType instead of OpenType shaping and the shaper will do its best to translate the feature tags.

An alternate formulation may just be to have a step 6 (or maybe just wording in the paragraph after this list which starts "For situations where") which states something like "The user agent will take the feature requests created in previous steps into consideration when shaping." to make it obvious that the user agent should use them, but is free to override the requests if it has some special knowledge.

At tip of tree, blink now has this HarfBuzz change (so Khmer doesn't shape poorly) and is disabling common, discretionary, historical, and contextual ligatures when letter-spacing is non-zero (since everyone I asks thinks it strange to just disable common).

**Comment by bungeman** [comment] 2018-12-06 15:13
Thank you for clarifying the term 'optional ligatures' in css-text-3, this is better wording than I would have been able to come up with.

However, I would still like to request that css-fonts-3>feature-precedence>4 and css-fonts-4>feature-precedence>11 replace the term 'common ligatures' with 'optional ligatures' (as proposed above at https://github.com/w3c/csswg-drafts/issues/2644#issuecomment-437085666). This just makes css-fonts agree with css-text while mentioning the effect of a property (letter-spacing) where css-text is now more authoritative.

The other edits suggested at https://github.com/w3c/csswg-drafts/issues/2644#issuecomment-437085666 (to 1 and add 6) are of somewhat less importance now with the edits to css-text-3 and the fact that these edits only document what implementors are already going to do anyway.

**Comment by fantasai** [comment] 2018-12-07 00:14
@bungeman Agreed 100% that those changes you requested to feature-precedence #4 are necessary.

**Comment by svgeesus** [comment] 2018-12-12 17:08
@bungeman thanks for your PR on CSS Fonts 4 and associated test; I just merged it so hopefully Fonts 4 is aligned with Text 3 on optional ligatures.

**Closed** 2018-12-12 22:37 UTC
Labels: Tracked in DoC, css-fonts-3, css-fonts-4, css-text-3, i18n-sealreq, i18n-tracking
