### ISSUE TITLE
[css-scroll-snap] A way to select the currently snapped element.

### ISSUE THREAD

**Issue by jespertheend** [w3c/csswg-drafts#7430] opened 2022-06-29 15:31 UTC
https://drafts.csswg.org/css-scroll-snap-1/

I would like to style the currently differently. Currently the only way to do this is using JavaScript. And any existing solutions I could find don't seem very robust:
- https://stackoverflow.com/questions/61761439/how-can-i-get-css-scroll-snap-to-work-with-js-scroll-event-listener
- https://stackoverflow.com/questions/54797620/css-scroll-snap-api

Something like `:scroll-snapped` could be nice. Although maybe that is too specific to my personal use case.

I'd also like to get access to the currently snapped element via JavaScript, as I plan on performing an action on the snapped element when the user clicks a button. But I don't think this is the correct repository for that request?

**Comment by tabatkins** [comment] 2022-07-01 17:56
(Dupe of #5979)

**Closed by tabatkins** 2022-07-01 17:56 UTC
