### ISSUE TITLE
[css-grid] minmax(auto,min-content) under a max-content constraint

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#3565] opened 2019-01-29 14:13 UTC
Consider this grid: https://jsfiddle.net/xnvrk7h8/

```css
.grid {
  display: grid;
  grid: auto / minmax(auto, min-content);
  float: left;
  border: 3px solid;
}
.item {
  background: blue;
}
.float {
  float: left;
  width: 50px;
  height: 50px;
}
```
```html
<div class="grid">
  <div class="item">
    <div class="float"></div>
    <div class="float"></div>
  </div>
</div>
```

`float: left` sizes the grid under a max-content constraint (assuming the window is wide enough).

The grid item has a max-content width of of 100px when the floats are in the same line, and a min-content of 50px when they are in different lines.

According to https://drafts.csswg.org/css-grid/#algo-single-span-items,

> If the track has an `auto` min track sizing function and the grid container is being sized under a min/max-content constraint, set the track’s base size to the maximum of its items’ min/max-content contributions, respectively, each limited by the max track sizing function if that is fixed and ultimately floored by its minimum contribution.

The track does have an `auto` min track sizing function and the grid container is being sized under a max-content constraint. So the track’s base size should be set to 100px. This is not limited by `min-content` because it's not fixed, and the minimum contribution is less than 100px:

> The minimum contribution of an item is the outer size that would result from assuming the item’s used minimum size (min-width or min-height, whichever matches the relevant axis) as its preferred size (width or height, whichever matches the relevant axis) if its computed preferred size behaves as auto, or else the item’s min-content contribution.

Here the computed `width` is `auto`, and the used value of `min-width: auto` is the [content size suggestion](https://drafts.csswg.org/css-grid/#content-size-suggestion), 50px.

> If the track has a `min-content` max track sizing function, set its growth limit to the maximum of the items’ min-content contributions.

So the growth limit is initially set to 50px, but

> if a track’s growth limit is now less than its base size, increase the growth limit to match the base size.

So both the base size and the growth limit should be 100px, the track is frozen, and the rest of the algorithm doesn't seem relevant.

However, this is not what implementations do:

![results](https://user-images.githubusercontent.com/7477678/51913679-615df880-23d7-11e9-8f98-49d2349763d0.gif)

Note that in Firefox the column is 50px wide but the grid container is 100px wide, so strange, @MatsPalmgren. This is solved by using `min-width: 0` in the grid item, which alters the minimum contribution but shouldn't affect the result.

Is my understanding of the spec correct? Should it be changed to match implementations?

**Comment by fantasai** [comment] 2019-01-29 20:57
I think you're right, something's not right here. Probably the automatic minimum should be limited by min-content here.

**Comment by fantasai** [comment] 2019-01-29 21:21
OK, I think the correct edit here is to remove “if that is fixed” from the spec text you quote:
> If the track has an auto min track sizing function and the grid container is being sized under a min/max-content constraint, set the track’s base size to the maximum of its items’ min/max-content contributions, respectively, each limited by the max track sizing function if that is fixed and ultimately floored by its minimum contribution.

What do you think?

**Comment by fantasai** [comment] 2019-01-29 21:22
CC @MatsPalmgren

**Comment by Loirooriol** [comment] 2019-01-29 21:43
> I think the correct edit here is to remove “if that is fixed”

I don't think the sentence makes sense without “if that is fixed”, because it's not clear how a length should be limited by something which is not a length or a resolveable percentage.

For example, if the max track sizing function is the keyword `max-content`, it needs to be defined that in this case the limit is the item’s max-content contribution.

It can also be a `<flex>` value, and these are not obvious because at that point `fr` is not known yet.

**Comment by fantasai** [comment] 2019-01-29 22:01
So “if that is fixed, else it's own min-content/max-content size if the max track sizing function is min-content/max-content” ?

**Comment by Loirooriol** [comment] 2019-01-29 22:32
Basically yes, but IMO the sentence would bee too long and a bit confusing, there is already a min/max-content dichotomy for the size constraint, one could think that the this min/max-content is refers to that.

I would prefer a refactoring like

> If the track has an `auto` min track sizing function, set the track’s base size to the maximum of its items’ foobars.
> The ***foobar*** of an item is calculated as follows:
> 1. Let *max* be the max track sizing function if that is fixed, else the min/max-content contribution if the max track sizing function is `min/max-content`, respectively, else infinity.
> 2. If the grid container is being sized under a min/max-content constraint, return the item’s min/max-content contribution, respectively, limited by *max* and floored by the item’s minimum contribution.
> 3. Return the item’s minimum contribution, floored at zero.

**Comment by fantasai** [comment] 2019-01-29 23:45
OK, I split the sentence. Didn't refactor the whole thing, but did some editorial tweaking to try to make it clearer.  Let me know if the edits look OK and we'll ask for WG review. :)

**Comment by Loirooriol** [comment] 2019-01-30 00:22
Your refactoring with "limited min-/max-content contribution" looks good too.

I'm just not sure about the use of "min-content/max-content size" instead of the preceding "min-/max-content contribution". Not much sure about the difference, I believe one is an inner size and the other an outer size, here you probably want the outer?

And when it says "else by it’s own min-content/max-content size if that is min-content/max-content", "that" seems to refer to the own size instead of to the max track sizing function. Consider repeating "max track sizing function" to make it clear.

**Comment by fantasai** [comment] 2019-01-30 01:36
Agenda+ to review the proposal:

When sizing auto-minimum tracks under a min-/max-content constraint, we use the item's min-/max-content contribution. But we limit that contribution by the track's max size if it's fixed (length/resolved %). This change makes it so that we also limit the contribution in the case of a min-content/max-content max track size, which fixes Oriol's example above to yield more intuitive behavior.

The value we're using to represent such an intrinsic max track size is the item's own contribution to such a size, which is I *think* a sufficient proxy for the actual max track size.

CC @MatsPalmgren @mrego @javifernandez

**Comment by fantasai** [comment] 2019-01-30 01:37
@Loirooriol I think actually we can simplify to only do this for min-content max track sizes, limiting by max-content seems like it'd be a no-op?

**Comment by Loirooriol** [comment] 2019-01-30 02:12
Sure, the non-fixed limit is only useful when the max track sizing function is `min-content` and the grid container is being sized under a max-content constraint.

**Comment by Loirooriol** [comment] 2019-01-30 10:59
Another case: `fit-content(0)` under a min-/max-content constraint.

Its max track sizing function is `max-content`, so the base size is not limited and is 50px/100px, respectively. Only the growth limit is handled especially to be 0, but this is useless because later it's floored by the base size.

However, Chromium, Firefox and Edge produce a 50px column with `min-width: auto` and a 0px column with `min-width: 0`. So I say that the "limited min-/max-content contribution" should be limited by the `fit-content` argument.

**Comment by fantasai** [comment] 2019-02-01 00:12
@Loirooriol If the limited min-/max-content contribution were limited by the fit-content argument, fit-content(0) would never yield anything greater than a zero-width column. But that's not what happens. I think there is something to fix here, but it's not the same issue, exactly...

**Comment by Loirooriol** [comment] 2019-02-01 00:19
> fit-content(0) would never yield anything greater than a zero-width column

Not true, thanks to the [minimum contribution](https://drafts.csswg.org/css-grid/#min-size-contribution).

**Comment by fantasai** [comment] 2019-02-01 00:47
Right. Forgot that. Fixed, I think?

**Comment by fantasai** [comment] 2019-02-01 00:49
Wondering now whether to simplify out that no-op or leave it as-is because it more accurately reflects the principle of the thing...

**Comment by Loirooriol** [comment] 2019-02-01 01:03
Yes, that's good. Well, the "could" sounds a bit strange to me, like implying uncertainty.

Maybe slightly in favor of simplifying the no-op in order to shorten a bit the long sentence, but I don't care.

**Comment by SelenIT** [comment] 2019-02-05 15:57
I guess the problem is more float-related than Grid-related. It seems to be technically not defined yet how should the preferred width be calculated in presence of floats. My understanding is also that preferred width should account for all the floats and the content that flows around them when they are placed in the single line, but Gecko and WebKit/Blink [seem to disagree](https://bugzilla.mozilla.org/show_bug.cgi?id=396821).

**Comment by Loirooriol** [comment] 2019-02-05 16:20
@MatsPalmgren You are right, I missed that layout is done again "for real" once the container size is known. Firefox follows the spec before fantasai's edits, but the result just seems weird to me.

@SelenIT I floated the grid container in order to size it under a max-content constraint (assuming enough available space) instead of `width: max-content` which is not supported in Edge. And I floated the contents of the grid item instead of using inline-blocks so that the whitespace between them would have no effect. But the example would be the same without floats. The grid spec defines what to do when sizing under min/max-content constraints, which is what floats do (by default, and among other things). The bug you linked seems unrelated, that's about the max-content contribution of a non-BFC-root block container whose line boxes are shortened by a float participating in the same BFC.

**Comment by MatsPalmgren** [comment] 2019-02-05 16:24
@SelenIT I don't think this grid issue has anything to do with that bug, which is about the intrinsic size of box with _child_ floats. It's also worth noting that Chrome and Firefox still agree on the rendering of the testcases in that bug, so I think that bug is WONTFIX since the web-compat risk of changing that now is insanely high. This is a case where the specs should simply specify what browsers are currently implementing.

**Comment by MatsPalmgren** [comment] 2019-02-05 17:56
BTW, if you add `width:100px` on the grid container, then Chrome renders it the same as Firefox (the column size is 50px). So it appears Chrome doesn't calculate the max-content size correctly, or it discards/trumps the intrinsic size when flowing it. ¯\_(ツ)_/¯

**Comment by Loirooriol** [comment] 2019-02-05 18:15
@MatsPalmgren But with `width:100px`, the grid container is no longer sized under a max-content constraint, right? So the "Otherwise" part applies.

On the other hand, while Firefox followed the spec (before fantasai's edits) for my example, if you add `min-width: 0` to the grid item, then the grid container becomes 50px wide. But I think it shouldn't have changed.

**Comment by frivoal** [comment] 2019-02-07 00:21
Quick summary of the current state of affairs: planning to resolve in favor on the changes proposed by @fantasai, pending a 1 week delay to give @fantasai a chance to double check the follow comment from @MatsPalmgren:
> Whatever you decide, please make sure it makes sense also when span > 1 and when there's a mix of fixed and `min-content` max-sizing tracks.

**Comment by fantasai** [comment] 2019-02-07 09:34
@MatsPalmgren 

>  If the result in Firefox isn't what the author wants they should just use `min-content` track sizing (to get the result in Chrome) or `auto` track sizing (to get the result in "Expected").

I think it's reasonable for an author to expect that “shrinkwrap” sizing (like floats) doesn't create more space in the container than its internal layout is later able to use. The point of content-based auto sizing is to just fit the content, and an item sized at max-content shouldn't be larger than its contents. Here we have a grid container sized at max-content (which is intended to size an element to fit its contents at their most stretched-out size), but the result we're getting right now is that the grid container is twice as large as its content.

> Whatever you decide, please make sure it makes sense also when span > 1 and when there's a mix of fixed and `min-content` max-sizing tracks.

Yes. I hadn't yet worked out the edits for correctly clamping the minimum contribution for spanning items in https://github.com/w3c/csswg-drafts/issues/2303 but this issue does make that more complex. I outlined some proposed changes there to handle spanning items, let me know if it seems to work. (Fwiw, edits for that without accepting the change proposed in this issue would just fold min-content under the “infinity” bullet.)

**Comment by Loirooriol** [comment] 2019-02-20 12:50
Some of my points from #2303:

 - The limited min-/max-content contribution should be fully defined in its own subsection (together with the minimum contribution, I guess). Providing a simpler definition in the place where it's defined, and then adding amendments in references to it is less clear. Because not all references will be next to the amendments, and following the link won't provide the full definition.

 - The limited min-/max-content contribution should take `fit-content()` into consideration in the spanning case.

 - Clamping by the min-content contribution may not ensure that spanning items won't contribute more space than what they will end up using.

    Imagine you have a single grid item with a minimum contribution of 20px, a min-content contribution of 25px, and a max-content contribution of 100px. It spans two columns sized with `minmax(auto,min-content) minmax(auto,50px)`.

    When sizing the container under a max-content constraint, the limited max-content contribution will be 50px (100px clamped between 20px and 50px). This will be distributed equally, so both columns will end up with a base size of 25px. Then the minimum contribution, 20px, is distributed for growth limits. The 2nd column already has a growth limit of 50px, so it will remain that way, but the first column will change its growth limit from infinity to the base size, 25px. Then the 2nd column will be maximized and the grid container will be 75px wide.

    The you do layout for real. This time the `auto` minimums only distribute the minimum contribution, 20px. So the base size of each column becomes 10px. 20px are distributed again for the growth limits, the first one becomes 10px and the 2nd one remains 50px. So this time the columns will sum 60px. This is smaller than the grid container.

    IMO the sizing algorithm seems too aggressive reducing the growth limit when it was infinity and becomes finite. If there is free space, the 1st column should probably be allowed to grow until it reaches 25px (the min-content contribution, as dictated by the max track sizing function). This can be an unrelated issue, though.

**Comment by tabatkins** [comment] 2023-07-17 21:22
A narrow fix here: The use of "limited min-/max-content contribution" in the non-spanning auto minimums step was wrong, it should have been only min all along. Unsure why we wrote it that way, but it came from <https://github.com/w3c/csswg-drafts/commit/7cacfbf53ca7dc41d952763897d95bd7e63b5349> back in 2016, so probably we were still just trying to figure out how this works. In the OP's case this'll give us the Chrome behavior (a width of 25px).

**Closed** 2023-10-30 22:14 UTC
Labels: css-grid-1, Closed Accepted by CSSWG Resolution, Needs Testcase (WPT), Tracked in DoC

**Comment by yisibl** [comment] 2024-01-23 07:09
Does this have a wpt test yet?
