### ISSUE TITLE
Apply transitions to media/container queries [css-contain][css-transitions]

### ISSUE THREAD

**Issue by scottkellum** [w3c/csswg-drafts#6581] opened 2021-09-07 16:48 UTC
Add the ability of transitioning between `@media` and `@contain` states. This would enable fine-tune control over how things change as viewport and container sizes change with easing.

This would enable at least two things that is not possible in CSS:
- Interpolation of multiple properties across screen/container sizes.
- Interpolation of text on an easing curve, as opposed to linear with viewport/container unit interpolation.

Some examples to show the need for this feature. These demos are acting as if text in page modules can be interpolated based on container width units in the first column, and transitioned + eased queried properties in the second column.

<table>
<tr>
  <th>Possible with container unit interpolation</th><th>Possible with state transitions and easing</th>
</tr>
<tr>
  <td><img width="1455" alt="A demo showing The Atlantic’s home page with various entry modules scaled as if with linear interpolation. This results in text not having a good size range and the typography  is a little flat." src="https://user-images.githubusercontent.com/377189/132379276-f8271bb0-86cd-4c29-90c0-017c85e2b00d.png"></td>
  <td><img width="1483" alt="A demo showing The Atlantic’s home page with various entry modules scaled as if with easing. The result is more rich and dynamic typography." src="https://user-images.githubusercontent.com/377189/132379274-6e448eb2-0565-4f4f-82d8-7e184dcdd6fe.png"></td>
</tr>
<tr>
<td>
<img width="1460" alt="A Nike product demo showing product names linearly interpolated resulting on the text being too big at smaller sizes." src="https://user-images.githubusercontent.com/377189/132380769-7ef97994-330d-428d-b8dc-84a1b5855d70.png">
</td>
<td>
<img width="1409" alt="A Nike product demo with an interpolation curve showing smaller product names that ramp up to large sizes more gradually." src="https://user-images.githubusercontent.com/377189/132380768-2588be5d-06b3-4b43-b0af-aeeb047b067e.png">
</td>
</table>

**Comment by mirisuzanne** [comment] 2021-09-09 16:09
I like this idea, and have a few notes from previous conversation with Scott. I think most relevant:

- The most common use-case is that each property has a start-value and end-value aligned to particular container sizes, and an easing curve to interpolate. It’s rare (but not impossible) for a single property to have additional/intermediate “stops” defined. In that way, it can be thought of more like a transition than a keyframe animation. 
- However, it is useful to define multiple related properties in the same place, even if they have different start/end points. A keyframe animation with multiple stops makes that possible in [Typetura](https://docs.typetura.com/).

I could imagine an approach similar to `@scroll-timeline`, or a way to use media/container breakpoint values directly in the keyframes rule (or some variant of it), though I haven't started digging into the details of either approach. Unlike scroll-timeline, I don't think it works for the "source" element to be hard-coded (unless it is the viewport). For a container-relative approach, authors should be able to describe the animation/timeline once, and have it respond to individual container contexts.

**Comment by mirisuzanne** [comment] 2021-09-09 17:16
@scottkellum Is this a duplicate of #6245 ?

**Comment by scottkellum** [comment] 2021-09-10 01:58
@mirisuzanne its a little more specific as to the interpolation being from transitions instead of animations after a chat with @una . But yes, very similar.

**Comment by mirisuzanne** [comment] 2021-09-23 03:51
Closing as a duplicate of #6245

**Closed** 2021-09-24 05:00 UTC
Labels: Closed as Duplicate
