### ISSUE TITLE
[css-grid] Ability to have grid items cause cells to be marked as occupied for flow purposes

### ISSUE THREAD

**Issue by meyerweb** [w3c/csswg-drafts#1394] opened 2017-05-19 15:59 UTC
Consider flowing a bunch of sized elements into a grid with inflexible tracks.  For example, a number of random images with differing heights and widths into the following grid:

```
grid-template-columns: repeat(10,100px);
   grid-template-rows: repeat(10,100px);
```

Assume each image has its height and width extriniscally set, whether through inline styles or HTML attributes or whatever, but do not have classes characterizing their heights and widths.  If the images have no `grid-column` or `grid-row` values set by the author, they’ll flow into the grid, cell by cell.  This can easily lead to grid items overlapping each other—for example, if an image 100px tall by 250px tall is placed into a cell, it will overlap the next cell and a half to the right of its own cell.

This is not what authors will expect.  (I already expect a recurring theme of people discovering this, finding out it’s by design, and writing outraged anti-Grid thinkpieces.)  It could be useful in some circumstances, so it’s not a behavior I think should be eradicated, but allowing grid items to act a little more like floats (which avoid each other) and a little less like absolute positioning would be useful.

So I’d like to see the ability for grid items to mark all the cells they impinge upon as ‘occupied’, so that other grid items don’t try to place themselves into those cells.  To return to the previous example, a 100px-by-250px image would mark three cells as occupied: the cell to which it is assigned, and the two to its right.  The next grid item would be placed in the next available unoccupied cell.

Initial proposal for handling it: extend `grid-auto-flow` to allow this as an option.  Something like `grid-auto-flow: dense avoid-overlap`.  This would make masonry-style layouts a lot easier to accomplish with Grid, whether using images or text or both.

My expectation would be that the grid item would (by default) stretch to fill all the cells it initially marks as occupied.  That would allow for centering using the alignment properties, for example.  The basic steps of that process would be:

1. Size the grid item as normal.
2. Determine the number of cells on which it impinges.
3. Place the start/end edges of the item along the edges of the grid area defined by the impinged-upon cells.

At least, so far as I’ve thought about it.  That bit might need to be reworked.  But the base idea, of letting grid items avoid overlapping each other as part of the auto-flow process as opposed to forcing authors to class-label elements and specify track spanning explicitly, is definitely worth pursuing.

**Comment by tabatkins** [comment] 2017-05-25 08:18
Unfortunately, this is still circular - before we can do "figure out my placement from my size", we need to size the tracks (meaning, run Grid's layout algorithm), and before we can do that, we need to figure out the placement of everything.

This falls, again, into the set of "things we can do if we have a guaranteed fixed-size grid", but it doesn't work with the grid we have today.

**Comment by FremyCompany** [comment] 2017-05-29 22:50
Well, you can technically make it work for "width" if you consider the tracks sized with "auto", "fr" and "percentages" (if widthis content-dependent) to be infinite and therefore content will never need any other cell on their right.

This doesn't work for height though, because the height of the items depends on their width and their width depend on the track sizes which themselves depend on content placement. Making it work in one direction and not the other seems meh and confusing to me, probably not worth pursuing. 

As Tab mentioned however, if the grid is fully fixed in both directions, then you can do the item layout as you are placing them, but that is fundamentally different from how grid works today. A completely different algorithm.

**Comment by MatsPalmgren** [comment] 2017-05-30 11:42
> for example, if an image 100px tall by 250px tall is placed into a cell, it will overlap the next cell and a half to the right of its own cell.

Are you sure you're not just seeing a bug in Chrome? In the case you describe, the max-sizing function is fixed and if the image has a default `min-width:auto` then the clamping rule in §6.6 applies and the image should be 100px wide and its height scaled according to its intrinsic ratio.  This works correctly in Firefox Nightly, but not Chrome Canary.

**Comment by mrego** [comment] 2017-05-30 12:13
>> for example, if an image 100px tall by 250px tall is placed into a cell, it will overlap the next cell and a half to the right of its own cell.
>
> Are you sure you're not just seeing a bug in Chrome? In the case you describe, the max-sizing function is fixed and if the image has a default min-width:auto then the clamping rule in §6.6 applies and the image should be 100px wide and its height scaled according to its intrinsic ratio. This works correctly in Firefox Nightly, but not Chrome Canary.

Indeed it seems we've a bug in Chrome as we only apply the clamping to regular items but not images.

@MatsPalmgren one question, what should be the expected height for the first row in [the following example](http://jsbin.com/diqaxay/1/edit?html,css,output)?
```html
<div style="display: inline-grid; border: solid thick;
            grid-template-columns: 100px;">
  <img src="https://placehold.it/200x100" />
  <div style="background: lime; font-size: 2em;">itemmmmmmm</div>
</div>
```

I see that in Firefox it's 100px, despite the image final height is 50px. Is that the expected behavior? Thanks.

**Comment by MatsPalmgren** [comment] 2017-05-30 13:23
I believe the image min-content size in the block-axis is 50px, but §6.6 only affects the item's min-content size, not its max-content size, so its max-content size is still 200x100. So, hum, it seems there was a spec change that we haven't adjusted for yet: §12.5.1 [in the last version](https://www.w3.org/TR/2016/WD-css-grid-1-20160519/#algo-track-sizing) said "For max-content and **auto maximums**", whereas the latest spec has dropped the "auto maximums" there. 

So per the previous spec our layout is correct and the row size should be 100px since the growth limit would be set to the items max-content contribution, but per the latest spec it should be 50px since nothing in [§11.5.1](https://drafts.csswg.org/css-grid/#algo-content) changes the growth limit it's still infinite and thus it falls into the "set its growth limit to its base size" in §11.5.3 and the base size is 50px in this case.

It seems a bit odd that the items' max-content size doesn't affect an `auto` track size anymore, but I haven't tracked down why this spec change was made...

**Comment by mrego** [comment] 2017-05-30 13:29
>>> for example, if an image 100px tall by 250px tall is placed into a cell, it will overlap the next cell and a half to the right of its own cell.
>>
>> Are you sure you're not just seeing a bug in Chrome? In the case you describe, the max-sizing function is fixed and if the image has a default min-width:auto then the clamping rule in §6.6 applies and the image should be 100px wide and its height scaled according to its intrinsic ratio. This works correctly in Firefox Nightly, but not Chrome Canary.
>
>Indeed it seems we've a bug in Chrome as we only apply the clamping to regular items but not images.

And now I'm not sure if this is an issue anymore.
By default the image has `normal` alignment, which for replaced elements mean `start`.
In Chrome we only clamp the size of the items if we've `stretch` alignment. That's what I understood after the whole discussion in #283.

For example the following tests don't pass on Firefox, but pass on Chrome:
* http://w3c-test.org/css/css-grid-1/grid-items/grid-minimum-size-grid-items-013.html
* http://w3c-test.org/css/css-grid-1/grid-items/grid-minimum-size-grid-items-013.html

It would be nice if @fantasai and/or @tabatkins could clarify what's the expected behavior in those cases.

**Comment by MatsPalmgren** [comment] 2017-05-30 13:37
There's nothing in §6.6 that says the clamping should only be applied for some align-self values.
It's independent of align-self as far as I understand.

**Comment by meyerweb** [comment] 2017-05-30 13:42
> Are you sure you're not just seeing a bug in Chrome?

Pretty sure.  I get consistent behavior in Firefox Nightly, Chrome, and Safari when loading up http://meyerweb.com/eric/css/examples/grid/overlaps.html.

The first grid shows images auto-filling into a grid of all fixed-size tracks.  Each image goes into the next “open” cell, even though that may overlap previous images.  I enforced heights and widths through classes for ease of authoring, but imagine images being spit out of a CMS with their exact height and width baked into HTML attributes or inline style.

The second grid shows what I would expect, as an author, where images don’t overlap.  (I had to explicitly assign a grid cell to each image in order to prevent said overlap.)

I’d be fine with adding this capability, but have it only apply to grids with fixed, non-content-dependent track sizes.

**Comment by FremyCompany** [comment] 2017-05-30 17:55
```grid-layout: fixed``` 😂

**Comment by mrego** [comment] 2017-05-31 09:40
> There's nothing in §6.6 that says the clamping should only be applied for some alignment values.
> It's independent of justify/align-self as far as I understand.

But check [§6.2](https://drafts.csswg.org/css-grid/#grid-item-sizing), the table says that for non-replaced elements with alignment other than `normal` or `stretch`, the item should be size like `fit-content` (instead of *fill grid area*).
[I've a jsbin with an example](http://jsbin.com/dufocad/1/edit?html,css,output) about this.

Note that I've realized that Firefox is doing something different than Chrome if the item has `min|fit|max-content` size.
Let's use [a different example for this](http://jsbin.com/gugenok/1/edit?html,css,output), for this jsbin in Chrome the size of the item is 20x20 in the first grid and 120x100 in the other 3. In Firefox it's 20x20 in the first 3 grids and 120x20 in the last one.

**Comment by tabatkins** [comment] 2017-07-28 22:32
(This is a dupe of #1373.)

**Comment by tabatkins** [comment] 2018-04-30 22:43
Closing as dupe.

**Closed by tabatkins** 2018-04-30 22:43 UTC
Labels: css-grid-2
