### ISSUE TITLE
[css-syntax-3] Do not always parse a numeric expressed with scientific notation to a number

### ISSUE THREAD

**Issue by cdoublev** [w3c/csswg-drafts#7289] opened 2022-05-20 07:53 UTC
I do not believe there are meaningfull cases that warrant a fix for the following, if it is an actual bug. My motivation for creating this issue is also to use it for code documentation. I have searched for existing issues with "scientific notation integer", with no success. I also searched for a [WPT](https://github.com/web-platform-tests/wpt/blob/master/css/CSS2/syntax/scientific-notation-001.xht).

`order: 1e0` is parsed as invalid in browsers because `order` should be an `<integer>`.

I do not have a high education in maths: perhaps a number representing an integer but expressed with the scientific notation must not be considered as an integer. 

Otherwise, step 5.3 of [*consume a number*](https://drafts.csswg.org/css-syntax-3/#consume-a-number) could be replaced after step 6 by evaluating if `repr` is a number. I do not know how this evaluation can be translated into spec/WebIDL terms.

Perhaps it can not be fixed because it would break parsing eg. [`<signless-integer>` and `<signed-integer>`](https://drafts.csswg.org/css-syntax-3/#typedef-signless-integer).

Or it may simply be decided that it is not worth to be fixed.

**Comment by dbaron** [comment] 2022-05-20 13:01
[5.2. Integers: the &lt;integer> type](https://www.w3.org/TR/css-values-4/#integers) and [5.3. Real Numbers: the &lt;number> type](https://www.w3.org/TR/css-values-4/#numbers) in css-values are reasonably clear (when read together, at least) that scientific notation is allowed for `<number>` but not for `<integer>`.

**Comment by cdoublev** [comment] 2022-05-22 02:46
Oh, that is right, thanks. Even just 5.3 is enough for me:

> When written literally, a number is either an integer, or zero or more decimal digits followed by a dot (.) followed by one or more decimal digits and optionally an exponent composed of "e" or "E" and an integer.

As noted, I can not say if it is mathematically correct but it is defined that numbers using the scientific notation are not integers in CSS.

Do you think mathematical correctness does not matter and I can close this issue?

**Comment by Loirooriol** [comment] 2022-05-23 12:45
See https://github.com/w3c/csswg-drafts/issues/6471#issuecomment-885945731

**Comment by tabatkins** [comment] 2022-05-23 18:51
Yeah, closing this as essentially a dupe of #6471. I'm still open to amending Syntax to let `<integer>e0` return an integer token, but we can continue that discussion over there; likely we just need to do some instrumentation to figure out the chance for breakage.

**Closed by tabatkins** 2022-05-23 18:51 UTC
