### ISSUE TITLE
[css-backgrounds] feature proposal: background-rotate 

### ISSUE THREAD

**Issue by leandroruel** [w3c/csswg-drafts#5182] opened 2020-06-08 00:19 UTC
in cases where we have backgrounds that we desire to rotate, we have to rotate the whole element through css transforms, but if we want add it to a `<body>` element, would be great if we could add a property: `background-rotate` so we can rotate the whole bg image easily like:

```html
<style>
   body {
     background-image: url(pattern.png);
     background-repeat: repeat-y;
     background-rotate: 180deg;
  }
</style>
```

this will avoid have to rotate the element and instead we only rotate the background.

**Comment by myakura** [comment] 2020-06-08 01:05
@leandroruel hi~. I thought it'd be so great having such transform capability in backgrounds a few weeks ago.

one thing i'm afraid is it looks like a duplicate of https://github.com/w3c/csswg-drafts/issues/3183 . could you perhaps moving your comment over there?

**Comment by leandroruel** [comment] 2020-06-08 16:02
oh @myakura thanks, i tried search for any issue already opened for this but i was unable to find it, i will make my comment there!

**Closed** 2020-06-08 16:36 UTC
Labels: Closed as Duplicate
