### ISSUE TITLE
[css-transform] the used value for border-box

### ISSUE THREAD

**Issue by CJKu** [w3c/csswg-drafts#999] opened 2017-02-02 07:24 UTC
The css-transforms spec[1] said:
> For SVG elements without an associated CSS layout box, the used value for border-box is view-box

Compare to clip-path geometry box[2], the used value for border-box is fill-box. Is there any special reason that we want them fallback to different value?

[1] transform box
https://drafts.csswg.org/css-transforms/#transform-box
> For SVG elements without an associated CSS layout box, the used value for border-box is view-box.
For elements with an associated CSS layout box, the used value for fill-box and view-box is border-box.

[2] clip-path geometry box
https://drafts.fxtf.org/css-masking-1/#the-clip-path
> For SVG elements without associated CSS layout box, the used value for content-box, padding-box, border-box and margin-box is fill-box.
For elements with associated CSS layout box, the used value for fill-box, stroke-box and view-box is border-box.

**Comment by AmeliaBR** [comment] 2017-02-02 17:29
I've been frustrated with these mis-matches myself, but after looking at it thoroughly myself, I ended up agreeing with the approach: in both cases, it works out as "if the specified value doesn't apply to the element, use the default behavior", where CSS and SVG rendering modes have different defaults.  

Trying to logically match CSS boxes to SVG boxes is always going to cause problems, because they just don't match up. And also, not all boxes are available in each property.

**Comment by dbaron** [comment] 2017-04-21 02:12
This should maybe be a duplicate of #857.

**Comment by fantasai** [comment] 2017-04-21 04:29
Series of resolutions from Tokyo F2F:

- border-box is treated as stroke-box in SVG
- padding-box and content-box are treated as fill-box in SVG
- fill-box and stroke-box are treated as defined in fill-stroke module in CSS
- view-box is treated as border-box in CSS
- initial value is view-box

**Comment by AmeliaBR** [comment] 2017-04-21 05:12
`view-box is treated as border-box in CSS`

Well that's one way around the problem of different defaults for `transform-box`, although it closes off the potential to allow transforms relative to the containing box in CSS.  (But we have the extended motion/offset-path options for that.)

So will all boxes now be valid?  The current spec only allows border-, fill- and view-box.

**Comment by fantasai** [comment] 2017-04-21 07:18
I think we're staying with the set that's in the spec. :) The correspondances are as above.

**Comment by smfr** [comment] 2017-11-06 04:43
Not sure if I should say that border-box maps to "stroke-box" for SVG elements, since we don't want to introduce a new value with that name in this spec and fill-and-stroke is still a draft. Should transforms-1 say that it border-box behaves like https://www.w3.org/TR/SVG2/coords.html#TermStrokeBoundingBox for SVG elements?

**Comment by smfr** [comment] 2017-11-09 19:40
https://lists.w3.org/Archives/Public/www-style/2017May/0053.html

**Comment by dirkschulze** [comment] 2018-01-06 18:22
CSS Masking 1 has the same definition as SVG2 in case CSS Masking develops faster: https://drafts.fxtf.org/css-masking-1/#compute-stroke-bounding-box

**Comment by dirkschulze** [comment] 2018-01-06 18:49
@fantasai The definition for `stroke-box` and `fill-box` in CSS Fill and Stroke is incomplete in the sense it needs to be used in CSS Transforms.  It only defines the boxes for SVG shapes and text in the SVG namespace but misses the other elements. That is why filter effects and masking use

> For SVG elements without an associated CSS layout box

(An SVG element with an associated layout box is an <svg> element.)

Are those mappings supposed to be universal? CSS Masking uses different mappings dependent on the property. I need to check if those mappings defined in https://github.com/w3c/csswg-drafts/issues/999#issuecomment-296057314 would cause compatibility issues with existing content.

**Comment by dirkschulze** [comment] 2018-05-01 19:31
The Working Group just discussed `the used value for border-box #999`.

<details><summary>The full IRC log of that discussion</summary>
topic: [css-transform] the used value for border-box #999<br>
8:57 PM K<krit> Dirk Schulze krit: Just an update from my side. I had the task to check the mapping of content-box, border-box, margin-box, padding-box to SVG compatible boxes in the Masking spec.<br>
8:57 PM krit: all the CSS boxes map to the SVG fill-box in the masking spec.<br>
8:57 PM krit: question was if we can align them to the box mapping from fill and stroke<br>
8:58 PM krit: krit I did some test for clip-path: https://codepen.io/krit/pen/qYrqKy<br>
8:59 PM krit: Currently none of the boxes are implemented, not even fill, stroke, view-box.<br>
8:59 PM krit: properties that use those boxes are: clip-path, mask-origin, mask-clip.<br>
9:00 PM krit: none of that existed in SVG 1.1. So there is no compatibility risk if we change the behavior.<br>
9:00 PM krit: I do not resist to follow fill and stroke for box mapping.<br>
9:01 PM krit: mask-origin, mask-clip might map to CSS boxes in Gecko (needs further checjing) but even those would not create compatibility risk to SVG 1.1<br>
9:02 PM RESOLUTION: : Follow CSS box mapping from Fill and Stroke spec  for all specs as decided by the CSS WG already.<br>
9:02 PM RESOLUTION: Follow CSS box mapping from Fill and Stroke spec  for all specs as decided by the CSS WG already.
</details>

**Comment by dirkschulze** [comment] 2018-05-23 17:27
To follow the resolution we need to add the keywords `stroke-box` and `content-box` to the `transform-box` property. Otherwise the mapping is not interoperable between specs.

I checked Firefox, Chrome and Safari. None of the UA implementations allow these keywords but do support the current keywords. All of the checked browsers are fully interoperable:
https://codepen.io/krit/pen/KRLPbg?editors=1100

Do we want to add the missing keywords to make all specs interoperable? This may result in a further delay of getting the spec to REC. If we don't do it now though we won't be able to do it in the future.

**Comment by fantasai** [comment] 2018-05-29 18:40
@dirkschulze Not that I'm objecting, but, can you clarify why you think the additional keywords need to be added? The mapping is at used-value time, not computed-value time, so it will be invisible to the OM.

**Comment by dirkschulze** [comment] 2018-05-29 19:07
@fantasai That is right, we would not need to introduce the keywords for `transform-box` to define the mapping to `stroke-box` or `content-box`.

Though it seems odd that one needs to define `fill-box` for HTML elements to get `content-box` and `border-box` to get `stroke-box` on SVG elements. Without a way to set the intended reference box directly.

None of the UAs actually do support the mapping that the WG resolved on as described in https://github.com/w3c/csswg-drafts/issues/999#issuecomment-296057314. Currently implementations do map `view-box` to `border-box` for HTML elements and `border-box` to `fill-box` for SVG elements.

Regardless of current UA support, I support the mapping that the WG resolved on but feel like it would be more logical to also add the keywords we map to for used values.

**Comment by AmeliaBR** [comment] 2018-05-29 19:18
I think it would be very confusing if we were to require UAs need to add rendering support for values that exist only through used-value conversions, and cannot be specified directly.

So we either need to go back to defining property-specific mappings, or make sure that all "pairs" of boxes are either both included or both excluded.

**Closed** 2018-06-20 18:50 UTC
Labels: Closed Accepted by CSSWG Resolution, SVG, css-transforms-1
