### ISSUE TITLE
[css-logical-1] [css-cascade-3] The all longhand probably shouldn't set logical properties.

### ISSUE THREAD

**Issue by emilio** [w3c/csswg-drafts#1898] opened 2017-10-23 05:42 UTC
Or if it should, order of the expansion of `all` should be specified.

From https://drafts.csswg.org/css-cascade-3/#all-shorthand:

> The all property is a shorthand that resets all CSS properties except direction and unicode-bidi. It only accepts the CSS-wide keywords.

This includes logical properties, and this is a problem because that means that it produces unexpected results when used from CSSOM (where the position a property declaration appears on matters).

In particular, we came across https://bugzilla.mozilla.org/show_bug.cgi?id=1410028, which happens because of the internal order the properties are reset.

In particular, it's not the same if `all` expands to:

```
padding-inline-start: initial;
padding-left: initial;
```

that if it expands the other way around.

i.e., this two pieces of code should be equivalent:

```html
<!doctype html>
<script>
let setStyle = (el, props) => {
  for (prop in props)
    el.style.setProperty(prop, props[prop]);
};

let logical = document.createElement('div');
let physical = document.createElement('div');

setStyle(physical, {
  all: 'initial',
  'background-color': 'blue',
  display: 'block',
  width: '100px',
  height: '100px',
  padding: '10px'
});

setStyle(logical, {
  all: 'initial',
  'background-color': 'blue',
  display: 'block',
  width: '100px',
  height: '100px',
  'padding-inline-start': '10px',
  'padding-inline-end': '10px',
  'padding-block-start': '10px',
  'padding-block-end': '10px'
});

document.documentElement.appendChild(physical);
document.documentElement.appendChild(logical);
</script>
```

But they aren't in current browsers.

**Comment by upsuper** [comment] 2017-10-23 05:53
The problem of making `all` not expand to logical properties is that it in some case it would fail to reset all properties in some cases. For example, if someone has
```javascript
elem.style.paddingLeft = '10px';
elem.style.paddingInlineStart = '10px';
elem.style.all = 'initial';
```
people should be expecting that there is no padding anymore. However, if `all` doesn't reset logical properties, we would still have `padding-inline-start` left there.

I guess the solution should be having the order defined in the way that, logical properties go before physical ones. This doesn't fix the issue that the two pieces of code having different behavior, but it at least provides a behavior compatible with pre-logical world, and can consistently reset all properties with `all`.

**Comment by emilio** [comment] 2017-10-23 05:56
> I guess the solution should be having the order defined in the way that, logical properties go before physical ones. This doesn't fix the issue that the two pieces of code having different behavior, but it at least provides a behavior compatible with pre-logical world, and can consistently reset all properties with all.

Well, the problem you described is a non-issue in a pre-logical world too, fwiw, but I agree that whatever path we take here is going to make some behavior inconsistent (whether it's my example, or yours).

**Comment by heycam** [comment] 2017-10-23 06:54
I guess this is not just an issue with `all`, but for any shorthand that sets logical properties.  For example:

```js
elem.style.writingMode = "horizontal-tb";
elem.style.marginTop = "1px";
elem.style.marginBlockStart = "2px";
elem.style.margin = "0px";  // top margin is still 2px :(
```

**Comment by emilio** [comment] 2017-10-23 07:07
You mean for any shorthand that sets physical properties with logical counterparts, right?

And yeah, not even that, but just something like:

```js
elem.style.writingMode = "horizontal-tb";
elem.style.marginTop = "1px";
elem.style.marginBlockStart = "2px";
elem.style.marginTop = "0px";  // top margin is still 2px :(
```

Given that (which is basically the problem Xidorn described before) is a more general problem with logical props themselves, I think we should make `all` not reset them, and keep the order unspecified. But not sure what other people think.

It may be worth trying to come up with a solution for that problem in a more general way, but it seems hard / impossible to me, because you don't know what physical property is actually represented by that property until computed value time.

**Comment by Loirooriol** [comment] 2017-10-23 18:11
Note that, if you need to rely on the order of an iteration, you should not use [for-in loops](http://www.ecma-international.org/ecma-262/8.0/#sec-enumerate-object-properties):

> The mechanics and order of enumerating the properties is not specified

Instead, you should use something like `for (prop of Reflect.ownKeys(props))`, because the order of [OrdinaryOwnPropertyKeys](http://www.ecma-international.org/ecma-262/8.0/#sec-ordinaryownpropertykeys) is explicitly defined.

Other than this, I think the result would always be as expected if you used `removeProperty` just before `setProperty`. Would it be backwards-compatible if CSSOM  automatically did this?

**Comment by adomasven** [comment] 2017-10-24 06:36
Food for thought: what happens in this scenario?

```js
elem.style.marginTop = "1px";
elem.style.marginBlockStart = "2px";
elem.style.writingMode = "horizontal-tb"; // is top margin 1px or 2px now?
```

**Comment by upsuper** [comment] 2017-10-24 06:43
> Food for thought: what happens in this scenario?

If it starts with an empty style declaration block, then it is deterministic from the spec that, the top margin should be 2px, because `margin-top` comes before `margin-block-start` and thus it's overridden by the latter. It is just like
```css
elem {
  margin-top: 1px;
  margin-block-start: 2px;
  writing-mode: horizontal-tb;
}
```

I think this is clear in the spec, and it is not the problem here.

**Comment by upsuper** [comment] 2017-10-24 06:52
> Other than this, I think the result would always be as expected if you used `removeProperty` just before `setProperty`. Would it be backwards-compatible if CSSOM automatically did this?

Maybe... I somehow think the current behavior makes more sense than always appending the changed declaration... except when it interacts with shorthands and logical properties...

Probably what we can do is:
* define the expand order for shorthands
* have CSSOM remove all longhands including their corresponding logical properties from the declaration block when it is setting a shorthand

With the first, we would have interoperable deterministic result, and with the second, the result should be less surprising when people try to set shorthand when some longhands have been there.

**Comment by Loirooriol** [comment] 2017-10-24 19:32
> Probably what we can do is:
> - define the expand order for shorthands
> - have CSSOM remove all longhands including their corresponding logical properties from the declaration block when it is setting a shorthand

But this wouldn't fix the following, would it?

```js
elem.style.marginTop = "1px";
elem.style.marginBlockStart = "2px";
elem.style.marginTop = "0px";
getComputedStyle(elem).marginTop; // "2px" :(
```

A basic cascading rule is that the last declaration wins when there is a tie. So I really think that by default CSSOM should move the declaration to the end when you assign a value (but a method that preserves the order could be added). If this is not backwards-compatible, please add a note in the spec warning about this misbehavior, and recommend to use `removeProperty` before setting a property.

**Comment by tabatkins** [comment] 2017-10-27 18:42
I've retagged this as just a CSSOM issue, and marked it as a f2f issue, because it's kinda complicated. Retag the other specs if you disagree and think that there is something they should do.

-----

As far as I can tell, the problem is:

* when you set `el.style`, it just manipulates some data structure, that tracks whether a value is set for each property and what it's set to
* this is then serialized to the style attribute in a *predefined* order (the order you set the properties in doesn't matter)
* thus, if the logicals appear after the physicals, then setting `el.style.fooBlockStart="one"; el.style.fooTop="two";` will serialize to `style="foo-top: two; foo-block-start: one;", and the logical value will end up winning, per the Cascade rules for how to resolve coinciding logical/physical declarations.  (Same applies in reverse if logicals appear before the physicals.)
* so this appears to be a CSSOM issue with it not respecting the same rules as the cascade does.

Right?

So Xidorn and Oriol have suggestions:

1. Xidorn suggests that when you set a property with phys/log counterparts, unset the corresponding other property from the el.style data structure.
2. Oriol suggests preserving the order the properties are set in when serializing to the style attribute.

(1) seems hard to do - you need to know the final computed value of writing-mode, direction, and maybe text-orientation to figure out the corresponding property, and those might be set by a completely different stylesheet.

(2) seems to cleanly fit in with the Cascade machinery, tho it would require tracking more information in the element.

**Comment by Loirooriol** [comment] 2017-10-27 19:37
> this is then serialized to the style attribute in a predefined order (the order you set the properties in doesn't matter)

The order does matter. That's because [set a CSS declaration value](https://drafts.csswg.org/cssom/#set-a-css-declaration-value) uses a "list of declarations", and lists are ordered. The algorithm also says "append", which implies there is an order. (Firefox and Chrome are compliant, but it seems Edge does not respect this insertion order).

The problem is that the algorithm only appends the new declaration if there was no previous declaration of the same property. Otherwise, it only updates the value of the old one, without moving it to the end.

Therefore, if you first set properties using `all` and then set a property to another value, you don't know whether the new value will win the cascade or not, because the order in which `all` inserted declarations into the list does not seem to be defined anywhere.

Additionally, the resulting declarations of the following steps will be

```js
elem.style.marginTop = "1px";        // { margin-top: 1px }
elem.style.marginBlockStart = "2px"; // { margin-top: 1px; margin-block-start: 2px }
elem.style.marginTop = "0px";        // { margin-top: 0px; margin-block-start: 2px }
```
so (assuming `writing-mode: horizontal-tb`) the top margin will end up being `2px` instead of `0px`. Instead, I think it should be


```js
elem.style.marginTop = "1px";        // { margin-top: 1px }
elem.style.marginBlockStart = "2px"; // { margin-top: 1px; margin-block-start: 2px }
elem.style.marginTop = "0px";        // { margin-block-start: 2px; margin-top: 0px }
```

**Comment by tabatkins** [comment] 2017-10-27 20:48
Ah, thanks for the clarification! Doesn't change the conclusion much, but tweaks the details a bit.

**Comment by tabatkins** [comment] 2017-10-27 21:01
Vaguely in the same space, [back in 2013 we resolved that .setProperty() needs to act like it's appending, for the purpose of handling importance](https://lists.w3.org/Archives/Public/www-style/2013Sep/0469.html).

**Comment by Loirooriol** [comment] 2017-11-07 18:08
> the suggestion to append or remove and then append

If old declarations are not removed and the element continuously receives new styles (e.g. simulating an animation using JS instead of CSS Animations), then the list of declarations may become huge. This will waste memory for no reason, won't it?

**Comment by emilio** [comment] 2017-11-07 22:22
I'm assuming that you'd remove other entries in the declaration block for the same property, which behavior-wise is identical to what happens during parsing (and remove + append).

At least Firefox and Servo rely on this invariant for a single declaration block.

Browser bugs:

 * https://bugzilla.mozilla.org/show_bug.cgi?id=1415330
 * https://bugs.chromium.org/p/chromium/issues/detail?id=782407
 * https://bugs.webkit.org/show_bug.cgi?id=179391
 * https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/14565977/

**Comment by emilio** [comment] 2017-11-09 12:35
I just realized that there's a gotcha, and it's that you can't optimize out redundant setters anymore, unless it's the last position on the declaration block.

For example, all browsers I know of implement an optimization to avoid doing stuff in the case the property set had the same value. This is no longer applicable unless the property is at the end of the block, which isn't great... :(

**Comment by zcorpan** [comment] 2018-02-11 21:01
For the record: From https://github.com/w3c/csswg-drafts/pull/2269#issuecomment-362869138 which I think is basically the same issue as @emilio's comment above

> WebKit and Blink don't agree with the part of setProperty. They don't update the attribute when the setting doesn't change value. It seems tricky to me in the sense that I don't think we have a formal definition anywhere about how to compare two values of a property, do we?

**Closed** 2018-04-11 13:12 UTC
Labels: cssom-1
