### ISSUE TITLE
[css-position][css-sticky] Position: sticky doesn't work when it has several HTMLElements with margin before it

### ISSUE THREAD

**Issue by Konrud** [w3c/csswg-drafts#3923] opened 2019-05-11 07:17 UTC
Steps to reproduce the problem:
1. Add `<p>` element with text and optionally with `margin` and some other elements before the element you want to set as a sticky
2. Set position: `sticky; top: 0;` on the element, you want to be sticky
3. Scroll down to see that element is actually stays in its place and doesn't behave as a sticky.

What is the expected behavior?
The element should behave as a sticky element.

What went wrong?
The element stays in its place and doesn't behave as a sticky.

Code example: [http://bit.ly/2HeL6Si](http://bit.ly/2HeL6Si)

NOTE:
Position sticky won't work until there are HTMLElements before it in the DOM e.g. `<p>` element with margin. If you, however, delete all the elements before it in the DOM position sticky will work as expected.

Chrome version: 74
OS Version: Windows 7

**Comment by jonjohnjohnson** [comment] 2019-05-11 12:09
@Konrud Your example has less to do with margins and more to do with the fact that the ancestor within which your sticky element is attempting to stick[[1](https://drafts.csswg.org/css-position-3/#sticky-pos)] has a height set too short to be in view when scrolling down to view/reach the sticky element. In other words, remove the `height:720px;` declaration on your `body` element and everything should behave as expected.

[[1] Creation of Sticky-Constraint Rectangles](https://drafts.csswg.org/css-position-3/#sticky-pos)

**Comment by Konrud** [comment] 2019-05-11 12:44
@jonjohnjohnson thank you for your response.
 But don't you think that is a bug or I should say an omission in spec?
 I mean I think I should be able to declare `width` on the parent element and `sticky` element should still work as expected, especially since `width: 720px;` it's not a small value at all and should be enough for the `sticky` element. 
Regarding the reference to the spec that you provided. I've read this one and I know that if you define `overflow: auto;` on both `<body>` and `<html>` elements, `sticky` element will work as expected. This has to do with so-called `scrolling-box` ([https://drafts.csswg.org/cssom-view-1/#scrolling-box](https://drafts.csswg.org/cssom-view-1/#scrolling-box)).
 But I haven't found anything to do with the `height` restriction.

**Comment by jonjohnjohnson** [comment] 2019-05-11 13:22
> But don't you think that is a bug or I should say an omission in spec?

No, the sticky position scheme is not simply a "fixed-like" position scheme for any scrollport. It is something that allows an element to effectively stay in flow, retaining its geometry unless the "intersection" of its containing block and its scroll container allow it to stick to an edge/offset at a certain length. Key here being that it needs room to move within its containing block. And your example doesn't allow any space for it to move within the `body` that is scrolled thousands of pixels out of view by the time any of your sticky elements move into the scrollport. So`720px` is quite definitely a small value here, when your first sticky element is multiple thousands of pixels passed where it would become "unstuck", never actually allowing it to be in a "stuck" state.

This is a feature of sticky. Not a bug or omission.

Please read all the language about boxes and sticky-constraint rectangles in that section, because sticky is not just about vertical scrolling, it doesn't mention `height` specifically, mentions boxes, which encapsulates height and width.

See this demo to understand why it's important for a sticky element to be constrained within the box (height) of it's nearest block level ancestor. Without which, every sticky element could never become "unstuck" at any point, each staying in view and covering each other. Think about how the alphabetical headers are treated in the contacts/phonebook apps like on iOS? https://jsfiddle.net/pbLqjstg/

**Comment by Loirooriol** [comment] 2019-05-18 01:06
@Konrud If you want the `height: 720px`, then you can make the `body` be the scroll container, e.g. `html, body {overflow: auto}` (`html` is needed to avoid [propagation](https://drafts.csswg.org/css-overflow-3/#overflow-propagation))

**Comment by jonjohnjohnson** [comment] 2019-05-18 02:06
> @Konrud If you want the height: 720px, then you can make the body be the scroll container, e.g. html, body {overflow: auto} (html is needed to avoid propagation)

This is if you are ok with your scrollport not matching the size of the window, leaving extra unused space in the viewport or worse cutting off parts of this body scrollport when the viewport is shorter than 720px. You also lose browser viewport/root scroller "conveniences", such as operas and iOS Safaris ability to click on the browsers chrome to scroll to the top of the document or chromes overscrolling rubber banding.

**Comment by tabatkins** [comment] 2020-05-12 19:27
Ah, yeah, this is an odd intersection of some features.

The stickypos's parent (and containing block) is `body`, which is fixed to 720px; its content then overflows (and is caught by the `html` element being scrollable by default). As @jonjohnjohnson said, stickypos won't "stick" an element past the bounds of its containing block; since the CB is a 720px-tall rectangle at the top of the document, and the fixpos element is far below that, already outside the bounds, it won't move any further due to stickiness.

That's why you're seeing it stick if there's nothing preceding it - if the stickypos element starts out within the 720px-tall `body`'s bounds, then it'll be allowed to stick *a little bit* (moving about 400px down, until it hits the bottom of the `body` element). But if you scroll further than that, it gets caught and scrolls up, trapped by the `body` element's bounds.

If you remove the `height:720px` from `body`, allowing it to grow to contain all its contents, it'll work as you expect, and the sticky bits will stick all the way down. Alternately, as @Loirooriol said, you can force the `body` to be a scroll container, by explicitly setting both `html` and `body` to `overflow: scroll;`; that has some unfortunate additional effects, however.

Since I don't understand why the `height: 720px` is there in the first place (it doesn't seem to have any visual effect on the page), I'm closing this issue as Working As Intended.

**Closed by tabatkins** 2020-05-12 19:27 UTC
Labels: Closed Rejected as Wontfix by Editor Discretion, Commenter Response Pending, css-position-3

**Comment by Milo-intent** [comment] 2025-01-30 06:08
@jonjohnjohnson https://stylesheets.space/questions/issue-with-htmlcss-rectangle-doesnt-scroll-as-expected

**Comment by bloodykheeng** [comment] 2025-05-26 10:54
just make the parent div abosolute and height full screen

```
 <div className="grid place-items-center p-2">
            {/* Timer and Instructions Banner */}
            <div className="absolute h-full">
                <div className="flex gap-1 justify-between items-center sticky top-2 z-10">
                    <ProgressBar
                        value={(60 - timeRemaining) * (100 / 60)}
                        showValue={false}
                        style={{ height: '8px', width: "70%" }}
                    />

                    <span className="font-bold flex items-center gap-2">
                        <i className="pi pi-clock text-orange-500"></i>
                        ⏳ {formatTime(timeRemaining)}
                    </span>
                </div>
            </div>
</div>

```
