### ISSUE TITLE
[css-logical] Add some logical version for CSS gradients 

### ISSUE THREAD

**Issue by nico3333fr** [w3c/csswg-drafts#6478] opened 2021-07-28 13:17 UTC
Spec: https://drafts.csswg.org/css-logical/

We need a logical version for CSS gradients.

# Use case

In ProtonMail, we are using a gradient to manage upload progress for attachments, here an example in Farsi (RTL)

![image](https://user-images.githubusercontent.com/2578321/127326679-a9fd9ffb-bc3a-466d-ab71-9d7a572282e3.png)

Actually, we have to detect if user is using a RTL language, and adapt the 

![image](https://user-images.githubusercontent.com/2578321/127296329-08f1b00d-e917-4959-8e54-5c8c9d58db6d.png)

# Solution

Either `logical` keyword or something like:

```css
linear-gradient(to inline-end,...
linear-gradient(to inline-start,...
linear-gradient(to block-start,...
linear-gradient(to block-end,... 
```

Thanks :)

**Comment by Loirooriol** [comment] 2021-07-29 03:33
Duplicate of #1724

**Closed by Loirooriol** 2021-07-29 03:33 UTC
