### ISSUE TITLE
[css-anchor-1] position-fallback fails to cascade

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#9331] opened 2023-09-09 18:11 UTC
Reading through the issues, apparently rules in the `@try` blocks apply “at used value time”, which means they don't fit into the cascade _at all_&mdash;even `!important` rules won't apply.

This is problematic to begin with, and it becomes more problematic the more properties you allow in `@try`.

**Comment by xiaochengh** [comment] 2023-09-13 00:35
In general, making `@try` rules cascadable (which I assume is equivant to applying them at computed value time) is very hard because we need to run layout to decide which fallback style to apply. Maybe we can postpone this to level 2.

But preventing them from overriding `!important` style should be implementable, and I agree that should be probably be done now for sanity.

**Comment by xiaochengh** [comment] 2023-09-13 00:38
Btw is this a duplicate of #9149?

**Comment by tabatkins** [comment] 2023-09-13 12:20
Yes, this is a #9149 dupe. (If I'm wrong, feel free to shout, @fantasai )

**Closed by tabatkins** 2023-09-13 12:20 UTC
Labels: Agenda+ TPAC, css-anchor-position-1
