### ISSUE TITLE
[css-animations-1] Reverse the timer when we reverse the animation during playtime

### ISSUE THREAD

**Issue by hunboy** [w3c/csswg-drafts#979] opened 2017-01-24 13:58 UTC
https://www.w3.org/TR/css3-animations/

Currently when we reverse an animation during populationtime, the timer is not reversed. I say timer is X. But should be 1-X

For the issure I prepared a testcase: https://jsfiddle.net/utasir/sup4hh90/

Press (and keep pressed) the **<** and the **>** icons for moving the animation, whilst this is paused currently.
For the **forward** it works as expected, but for the **backward** - when we reverse the animation - the timer is still X instead of 1-X

Same testcase with 1 image only for a more visible issue: https://jsfiddle.net/utasir/sup4hh90/1/
The image jumps, when we press the backward icon. The reason is: the timer is not reversed.

Issues:
 - animation-delay also could be "reversed"

mozbugzilla link: https://bugzilla.mozilla.org/show_bug.cgi?id=1247604

**Comment by birtles** [comment] 2018-07-03 00:22
I think this would be solved by the `animation-playback-rate` property with a playback rate of -1. `animation-direction` really just determines how the keyframes are interpreted and doesn't provide playback control.

Closing this as a dupe of #980.

**Closed by birtles** 2018-07-03 00:22 UTC
Labels: css-animations-1
