### ISSUE TITLE
[css-fonts-4] What does "italic values less than or equal to 0" mean in "Matching font styles"?

### ISSUE THREAD

**Issue by vlevantovsky** [w3c/csswg-drafts#2217] opened 2018-01-23 14:34 UTC
In "[Matching font styles](https://drafts.csswg.org/css-fonts-4/#font-style-matching)", in the section describing font style matching, step 4 is described as "If no match is found, italic values less than or equal to 0 are checked in descending order until a match is found".
According to the [OpenType spec](https://www.microsoft.com/typography/otspec/dvaraxistag_ital.htm), valid numeric range for 'ital' variation axis is defined as "Values must be in the range 0 to 1."

What does it mean when the CSS spec recommends searching for italic values less than or equal to zero, and what it is we expect to accomplish in this step?

**Comment by litherum** [comment] 2018-03-06 10:32
Duplicate of https://github.com/w3c/csswg-drafts/issues/1531

**Closed by litherum** 2018-03-06 10:32 UTC
Labels: css-fonts-4

**Comment by vlevantovsky** [comment] 2018-03-06 17:48
I don't think the issue I highlighted here has been discussed as part of [#1531](https://github.com/w3c/csswg-drafts/issues/1531). The issue here is that the css-font-4 spec explicitly talks about italic values being "less than or equal to 0" while, according to the font format spec, the negative values are clearly outside of the valid value range for 'italic'.

**Comment by litherum** [comment] 2018-04-10 08:16
You mention “the font format spec” but there are multiple font format specs which are relevant. OpenType disallows these values, but TrueType doesn’t. CSS should work with all (popular) font file formats, not just OpenType.

**Comment by vlevantovsky** [comment] 2018-04-10 09:09
TrueType doesn't have 'italic' defined as a registered variation axis. Slant is defined (with 'slnt' tag), but this is very different from 'italic', even though in some cases the results (the way glyphs are rendered) can be similar. So, while slant angle can be defined as a negative value, it's not the same as 'italic', where [0..1] is a valid range, and where, in most of the actual implementations the variation axis is used as an on/off switch for regular / italic transition.

**Comment by litherum** [comment] 2018-04-10 12:34
Yeah, I’m currently in the middle of some research to learn more about the `ital` axis. I’ll need some more time before I can answer about this axis specifically.
