### ISSUE TITLE
[css-syntax-3] Is two hyphens a valid identifier?

### ISSUE THREAD

**Issue by Masa-Shin** [w3c/csswg-drafts#5764] opened 2020-12-06 06:10 UTC
[This diagram](https://www.w3.org/TR/css-syntax-3/#ident-token-diagram) and the [Class selectors section](https://www.w3.org/TR/selectors/#class-html) implies `.--` is valid for class selector. While in the [Description of CSS’s Syntax section](https://www.w3.org/TR/css-syntax-3/#syntax-description) it says the contrary:
> Property names and at-rule names are always identifiers, which have to start with a letter or a hyphen followed by a letter, and then can contain letters, numbers, hyphens, or underscores.

Is just two hyphens `--` a valid class name?

**Comment by Loirooriol** [comment] 2020-12-06 20:49
https://drafts.csswg.org/css-syntax/#would-start-an-identifier says

> Look at the first code point:
> - U+002D HYPHEN-MINUS
>   If the second code point is [...] a U+002D HYPHEN-MINUS, [...] return true.

So `--` starts an identifier.

Then, in https://drafts.csswg.org/css-syntax/#consume-token

> - U+002D HYPHEN-MINUS (-)
>   [...] if the input stream starts with an identifier, reconsume the current input code point, consume an ident-like token, and return it.

So I would say yes. And a single underscore `_` is also an identifier (and this was the case even in [CSS2](https://www.w3.org/TR/CSS21/syndata.html#value-def-identifier)). The non-normative description seems wrong.

**Comment by Masa-Shin** [comment] 2020-12-08 12:20
@Loirooriol 
Thanks! Although it is non-normative, I think it should be more accurate or have a link to precise definition so probably I will make a PR.

> And a single underscore _ is also an identifier (and this was the case even in CSS2).

I wonder why then `_` does not work in most browsers.

**Comment by Loirooriol** [comment] 2020-12-08 14:07
> I wonder why then `._` does not work in most browsers.

But it does work...
```js
document.documentElement.className = "_";
document.querySelector("._"); // <html>
```

**Comment by Masa-Shin** [comment] 2020-12-08 14:42
> But it does work...

You are right. Somehow it didn't work in my workspace but now it surely works. Thanks again!

**Comment by tabatkins** [comment] 2020-12-09 00:20
Yes, it's a valid ident. ^_^

**Comment by Loirooriol** [comment] 2020-12-09 00:22
@tabatkins The problem is that the non-normative description in https://www.w3.org/TR/css-syntax-3/#syntax-description seems to imply otherwise

**Comment by Masa-Shin** [comment] 2021-02-14 02:24
What do you guys think about the following change?

```
Property names and <a>at-rule</a> names are always <a>identifiers</a>,
- which have to start with a letter or a hyphen followed by a letter,
- and then can contain letters, numbers, hyphens, or underscores.

+ which have to start with a <a>name-start code point</a>, two hyphens, or a hyphen followed by a name-start,
+ and then can contain name-start code points, hyphens, or numbers.
```

**Comment by SebastianZ** [comment] 2021-02-17 19:35
@Loirooriol wrote: 
> @tabatkins The problem is that the non-normative description in https://www.w3.org/TR/css-syntax-3/#syntax-description seems to imply otherwise

@Masa-Shin wrote:
> [This diagram](https://www.w3.org/TR/css-syntax-3/#ident-token-diagram) and the [Class selectors section](https://www.w3.org/TR/selectors/#class-html) implies `.--` is valid for class selector. While in the [Description of CSS’s Syntax section](https://www.w3.org/TR/css-syntax-3/#syntax-description) it says the contrary:
> 
> > Property names and at-rule names are always identifiers, which have to start with a letter or a hyphen followed by a letter, and then can contain letters, numbers, hyphens, or underscores.

The syntax description only refers to *property names* and *at-rule names*, it doesn't say anything about class names.

The paragraph below that refers to the Selectors specification for the syntax of selectors.

The non-normative paragraph is still wrong, though, because it doesn't account for custom property names which *do* start with two hyphens. (And custom at-rule names will probably also use the two-hyphens prefix when they are introduced.)

Sebastian

**Comment by SebastianZ** [comment] 2021-02-17 19:49
@Masa-Shin wrote:
> ```
> Property names and <a>at-rule</a> names are always <a>identifiers</a>,
> which have to start with a <a>name-start code point</a>, two hyphens, or a hyphen followed by a name-start,
> and then can contain name-start code points, hyphens, or numbers.
> ```

I think it should rather be
```
Property names and <a>at-rule</a> names are always <a>identifiers</a>,
which have to start with an <a>identifier-start code point</a>, two hyphens, or a hyphen followed by an identifier-start code point, and then can contain zero or more identifier code points.
```

Sebastian

**Comment by Masa-Shin** [comment] 2021-03-20 09:19
I think [SebastianZ's description](https://github.com/w3c/csswg-drafts/issues/5764#issuecomment-780808633) is correct and better than mine. It seems there is no more opinions so I will make a PR.

**Comment by MrBirb** [comment] 2022-12-21 10:47
@tabatkins I believe this was addressed?

**Comment by SebastianZ** [comment] 2023-02-21 21:12
As Tab merged the agreed on changes, I close this issue now. @MrBirb Thanks for the ping!

Sebastian

**Closed by SebastianZ** 2023-02-21 21:12 UTC
Labels: css-syntax-3
