### ISSUE TITLE
[css-anchor-1] Transitioning when the anchor element with a given name changes

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#8181] opened 2022-12-02 21:56 UTC
It's pretty obvious that if an element changes from `top: anchor(--foo top);` to `top: anchor(--foo bottom)`, that's a computed-value change that will trigger a transition on 'top'.

But what happens when the value is `top: anchor(--foo top);` the whole time, but you change which element has `anchor-name: --foo;`? @jh3y has an example of this using the popover API, where they change the popover attribute, altering which element is used as the "implicit anchor element" without actually touching the CSS. They'd like the abspos to smoothly transition to its new position.

I think this gets solved appropriately with the exact same solution as #8180 - if the tree-scoped reference is resolved as part of the computed value, then having it change underneath you counts as a computed-value change, thus triggering a transition, *and* the start and end values are (non-textually) distinct, referring to the old and new anchor, so you can meaningfully transition between them.

**Comment by jh3y** [comment] 2022-12-05 14:25
Yep – Transitioning the inset properties or being able to use those values in calc to generate `transform` values would be super useful. The demo in question is this one 👇 

https://user-images.githubusercontent.com/842246/205658978-489b6590-bbbf-44ee-a1d2-cd369c32db88.mp4

It shows a use case where you might want an element to follow user interaction. Not one I'd throw into production anytime soon 😅 

But it works using `:has()` to update and `--active-anchor` custom property (this did work in ~108).

```css
:root {
  --active-anchor: --email;
  --active-left: anchor(var(--active-anchor) right);
  --active-top: anchor(var(--active-anchor) center);
}

:root:has(.form-group:focus-within) {
  --anchor-scale: 1;
  --anchor-transition: top 0.2s, left 0.2s, transform 0.2s;
}

#password {
  anchor-name: --password;
}

:root:has(#password) {
  --active-anchor: --password;
}
```

A combination of implicit anchor and transition could also be useful in a variety of tooltip/overlay scenarios too. Even those type trigger UI where like on here when you type `#` to get the dropdown (What is the technical name for that pattern? 😅 )

**Comment by kizu** [comment] 2023-03-15 12:23
<details>
<summary>Disclaimer and additional links</summary>

I'm submitting my feedback following my experiments with the current implementation of anchor positioning in Chrome Canary.

I wrote an article about my experiments, but decided to fill most of my feedback as separate issues here.

A quick summary of related links:

- [anchor positioning specs](https://drafts.csswg.org/css-anchor-position-1/)
- [my article with the experiments](https://kizu.dev/anchor-positioning-experiments/)
</details>

I'm using this issue instead of creating a new one in order not to duplicate things. The issue topic that I wanted to give — “[css-anchor-1] Transitions when moving the anchor-name”.

I did experiment a bit with transitions, and found the same case that works — having multiple elements with different `anchor-name`s, then using a CSS variable for the `anchor()` and dynamically adjusting the value of this variable.

The experiment in question: https://kizu.dev/anchor-positioning-experiments/#transitions

In my case, initially I wanted to instead change to which element the static `anchor-name` is applied — so the `anchor()` would not (necessarily) be a CSS variable, but at any given moment different elements could become the target via moving the “anchor-name” itself from element to an element.

This way the case for my transition would've been significantly simplified.

Here is a CodePen with just the reproducible cases which work and which does not: https://codepen.io/kizu/pen/RwYMmmp

**Comment by kizu** [comment] 2023-03-26 10:44
I would want to provide another use-case — quite an old experiment by @NV, where it could be possible to have a transition for the focus-ring between elements — https://n12v.com/focus-transition/

If the position change that correspond to the change in focus for the `:focus-visible { anchor-name: --focused-element; }` could be animated, then this would be trivial to implement.

**Comment by andruud** [comment] 2023-11-14 13:18
> I think this gets solved appropriately with the exact same solution as https://github.com/w3c/csswg-drafts/issues/8180 - if the tree-scoped reference is resolved as part of the computed value, then having it change underneath you counts as a computed-value change, thus triggering a transition, and the start and end values are (non-textually) distinct, referring to the old and new anchor, so you can meaningfully transition between them.

In other words, something _like_ a tree-scoped name, but instead of only capturing the tree-scope, it now also captures the _element_ it's referencing? This means intermediate states would appear to interpolate to and from the same value, when serialized, right?

@tabatkins Have we considered resolving `anchor()` computed-value time instead? (Similar to how `cq*` units have layout dependencies, but also resolve computed-value time and can trigger transitions).

**Comment by andruud** [comment] 2023-11-15 10:21
Since my previous post raised some questions yesterday (elsewhere), I'll add a more detailed explanation, and some more thoughts on this. 

---

Container relative units (`cq*`) resolve at computed-value time, even though they require layout information to resolve. Example:


```
<style>
  #container {
    container: --c / size;
    width: 100px;
    height: 80px;
  }
  #target {
    width: 50cqw;
  }
</style>
<body>
  <div id=container>
    <div id=mid>
      <div id=target>
      </div>
    </div>
  </div>
</body>
```

During the regular style recalc process, after computing the style for `#container` and figuring out that it's a size container, we _skip_ computing the style for `#container`'s descendants. So during this process, "computed-value time" has happened for `#container`, but not for `#mid` nor for `#target`.

Then, when _layout_ reaches `#container`, we immediately _resume_ style recalc for `#container`'s descendants. Now armed with the knowledge of `#container`'s actual size, we're able to resolve (compute) `cq*` units into what they're supposed to be. So for `#container`'s descendants, "computed-value time" happens _during_ layout. (Hence the term "interleaved style and layout" which you may or may not have encountered).

---

The above works, because at the time we finally end up resolving `cq*`, we know the size of the container. (And thanks to containment, we also know that it's not going to move around).

The same _appears_ to be true for `anchor()`, since we have the requirement that the layout of the anchor must be understood _first_. However, the mental model doesn't quite work out for `anchor()`, because there's no ancestral "container" which marks the interleaving point. In order to detect that `anchor()` is used on some element, "computed-value time" would need to already have happened, and then we'd need to have a second round of "computed-value time"? It's (even) less "clean" than container queries.

The new path we're on for @position-fallback also requires the same uncleanliness: we must know the computed value of `position-fallback` before attempting the associated `@try` styles to eventually figure out the _real_ computed style.

Doing multiple rounds isn't a problem for the implemenation, but figuring out a decent mental model (spec) for this might require some thought ...

**Comment by kizu** [comment] 2023-11-15 10:55
Would having something like an `anchor-scope` (which we'd have, see https://github.com/w3c/csswg-drafts/issues/9045#issuecomment-1721297734) help in some way? I can imagine that we could make it a requirement that an explicitly scoped anchor's name change could be transitioned, and with the element with that explicit scope we get this “ancestral container”?

**Comment by andruud** [comment] 2023-11-15 13:00
@kizu I don't _think_ so, because in that case the "ancestral container" (i.e. element holding `anchor-scope`) wouldn't be the thing we're actually querying. When reaching layout of the anchor-scope-element, we still know nothing about the layout of the actual anchor.

**Comment by mfreed7** [comment] 2024-02-26 18:30
Should be addressed by the current draft spec.

**Comment by xiaochengh** [comment] 2024-02-27 10:57
@mfreed7 Is it really addressed? I see it's still an [open issue](https://drafts.csswg.org/css-anchor-position/#issue-02b9489e) in the spec.

**Comment by mfreed7** [comment] 2024-02-27 21:01
> @mfreed7 Is it really addressed? I see it's still an [open issue](https://drafts.csswg.org/css-anchor-position/#issue-02b9489e) in the spec.

Thanks for raising this! You're right that this still needs work.

**Closed** 2024-04-08 23:53 UTC
Labels: Closed Accepted by CSSWG Resolution, css-anchor-position-1
