### ISSUE TITLE
[css-logical]Flow-relative syntax for transform

### ISSUE THREAD

**Issue by TxHawks** [w3c/csswg-drafts#1788] opened 2017-09-07 14:48 UTC
There is no mention of handling the values of `transform` in a flow-relative manner in the [css-logical-1 spec](https://www.w3.org/TR/css-logical-1), which would certainly be very helpful when authoring multi-directional styles

**Comment by nico3333fr** [comment] 2021-05-26 13:51
Yes, there are some cases where we would really need this, I'm facing one right now for a custom toggle:

LTR:
![image](https://user-images.githubusercontent.com/2578321/119670633-572e5680-be39-11eb-9ffe-340bcb90963e.png)

I'm doing: 
```
transform: translateX(<value>);
```
for active state.

But it will give this in RTL:
![image](https://user-images.githubusercontent.com/2578321/119670725-6a412680-be39-11eb-8fb6-ba0b8fad618f.png)

I have to do:
```
transform: translateX(-<value>);
```
To get the proper display:

![image](https://user-images.githubusercontent.com/2578321/119670509-3c5be200-be39-11eb-89a8-5a4c6d28d05e.png)

Something like: `translate-inline-start` would replace something like: 
```
[dir="rtl] .selector {
transform: translateX(-<value>);
}
```

And same for translateY, we would go for `translate-block-start`. 

For translateZ, I guess i18n does not encounter negative 3D written stuff... so it's okay :D

**Comment by Malvoz** [comment] 2021-12-10 08:43
Duplicate of https://github.com/w3c/csswg-drafts/issues/1544.

**Comment by dbaron** [comment] 2022-08-24 00:07
Closing as duplicate of #1544.

**Closed by dbaron** 2022-08-24 00:07 UTC
Labels: css-logical-2
