### ISSUE TITLE
[css-transforms-2] Explicitly specify that a transform is a containing block for all descendants

### ISSUE THREAD

**Issue by chrishtr** [w3c/csswg-drafts#1945] opened 2017-11-06 19:34 UTC
Currently, it's either unspecified or unclear whether a transform induces a containing block
for all children, including fixed-position. css-transforms-1 has this text, and it needs to be
added to css-transforms-2. Discussed with @smfr and there is agreement on this point.

https://www.w3.org/TR/css-transforms-1/#transform-property

**Comment by RByers** [comment] 2017-11-15 15:23
Dupe of #913

**Closed by RByers** 2017-11-15 15:23 UTC
