### ISSUE TITLE
[css-indexes] “Suggest an edit” link 404s

### ISSUE THREAD

**Issue by meyerweb** [w3c/csswg-drafts#3159] opened 2018-09-26 15:28 UTC
In the header links of https://drafts.csswg.org/indexes/, the link under “Suggest an Edit for this Spec” points to https://github.com/w3c/csswg-drafts/blob/master/indexes-1/Overview.bs.  This yields a 404, at least for me, whether or not I’m logged into GitHub.

**Comment by svgeesus** [comment] 2018-09-26 18:53
Aha, this is a bug caused by appending a document level (-1) where it doesn't belong.

https://github.com/w3c/csswg-drafts/blob/master/indexes/Overview.bs works

@tabatkins would this be fixed by removing the `Level: 1` from the .bs?

**Closed** 2018-09-28 22:18 UTC
