### ISSUE TITLE
[css-lists] generating ::marker boxes should define value of content property

### ISSUE THREAD

**Issue by gsnedders** [w3c/csswg-drafts#2001] opened 2017-11-21 11:26 UTC
Currently https://drafts.csswg.org/css-lists/#content-property just says things like "The contents of the ::marker…", rather than something more precise like "The initial value of the content property of the ::marker…".

It's implied in the above examples that you can set the content property and have that override the default (and hence presumably the initial)?

**Comment by Loirooriol** [comment] 2017-11-21 16:32
The problem is that the examples assume that various properties apply to ::marker, but CSS Pseudo says otherwise. See #1807

**Comment by frivoal** [comment] 2017-12-14 05:37
@gsnedders Well, rather than "the intial value of the content property in ::marker is FOO", which would be a bit weird since properties are not supposed to have different initial values based on context, we could say something like "The 'normal' value of the content property computes to FOO"

**Comment by MatsPalmgren** [comment] 2019-01-09 18:39
FYI, I've filed #3499 to include `content` as a supported property for `::marker`.

**Comment by fantasai** [comment] 2019-04-05 23:09
I believe this is now fixed. https://drafts.csswg.org/css-lists-3/#markers @gsnedders Would you mind verifying?

**Comment by gsnedders** [comment] 2019-04-10 18:49
Do we really want "The contents of the ::marker" and "The ::marker contains" rather than "The marker box contains", given it isn't really the pseudo element that has the content? Also I'd rather always go with "contains" instead of it containing while talking about the `content` property.

**Comment by fantasai** [comment] 2019-04-10 20:06
@gsnedders Thanks, fixed!

**Comment by fantasai** [comment] 2019-04-10 20:08
@gsnedders Lmk if it looks OK now!

**Closed** 2019-06-28 23:52 UTC
Labels: Commenter Response Pending, css-lists-3
