### ISSUE TITLE
[css-text-4] Propose 'text-spacing: space-first' (trim-start-except-first-line) as a normal behavior

### ISSUE THREAD

**Issue by MurakamiShinyu** [w3c/csswg-drafts#2462] opened 2018-03-21 16:47 UTC
## Ebook reader's default text-spacing behavior

The [text-spacing](https://drafts.csswg.org/css-text-4/#text-spacing-property) is not yet implemented in web browsers, but some part of this feature is already seen in ebook readers.
I put here two example screenshots (Kindle for PC, and Kinoppy for PC):

Kindle for PC screenshot:
<img width="340" alt="kindle-win-sample-1" src="https://user-images.githubusercontent.com/3324737/37723132-fed7863e-2d70-11e8-9c56-0cf464090d59.png">

Kinoppy for PC screenshot:
<img width="318" alt="kinoppy-win-sample-1" src="https://user-images.githubusercontent.com/3324737/37723240-37f69662-2d71-11e8-8553-a42ac9c35506.png">

In these examples, the **trim-adjacent** behavior is seen at "、『" in the middle of a line, and the **trim-start** behavior is seen in the lines starting with "「" or "『".

However, there is a difference between these two examples. In the Kindle case, all opening punctuations ("「" and "『") are set half-width at start of lines. On the other hand, in the Kinoppy case, only the opening punctuation ("『") after a soft wrap break is set half-width, and kept full-width at beginning of paragraphs.

While Kinoppy's behavior is a normal Japanese typesetting style, Kindle's behavior is not so. Setting opening punctuation half-width at beginning of  a paragraph with no indent is hard to recognized as beginning of a paragraph. I know Japanese publishing people asking Kindle dev to fix it.

## The preferable behavior not possible in current text-spacing spec

The problem here is that the Japanese ebook's preferable text-spacing behavior is not possible in the current [text-spacing](https://drafts.csswg.org/css-text-4/#text-spacing-property) spec.

We need **space-start** at the first line (or after forced line breaks) and **trim-start** at the rest lines.

I suggest the new value keyword **space-first** for such behavior, and it would be included in the baseline behavior (**normal**):

**normal**  
Specifies the baseline behavior, equivalent to ‘space-first allow-end trim-adjacent’.

**space-first**  
Set fullwidth opening punctuation with full-width glyphs (spaced) at the start of the first line of each block container and each line after a forced line break, and set fullwidth opening punctuation with half-width glyphs (flush) at the start of other lines.

**Value**:	normal | none | [ trim-start | space-start | space-first ] || [ trim-end | space-end | allow-end ] || [ trim-adjacent | space-adjacent ] || no-compress || ideograph-alpha || ideograph-numeric || punctuation

## Rethinking “Japanese Paragraph-start Conventions in CSS”

There may be an opinion that the current text-spacing spec is sufficient because [Japanese Paragraph-start Conventions in CSS](https://drafts.csswg.org/css-text-4/#japanese-start-edges) shows the example that enables the preferable behavior:

- Brackets hang in indent, flush with other lines (third scheme):
```css
p { /* Hanging alignment */
  margin: 0;
  text-indent: 1em;
  text-spacing: trim-start;
  hanging-punctuation: first;
}
```

Yes, it would be great if we can use this. But unfortunately, there is no way to apply this to the current Japanese ebooks (EPUB and Kindle formats).

Most Japanese publishers adopt the Japanese EPUB guideline, [EBPAJ EPUB 3 File Creation Guide](http://ebpaj.jp/counsel/guide), that includes XHTML templates and CSS stylesheets, such as:

```html
<p>　この文章はサンプルです。</p>
<p>「この文章はサンプルです」</p>
```

```css
p {
    margin: 0;
    text-indent: 0;
}
```

That is, paragraphs start with an ideographic space (U+3000) unless starting with an opening punctuation such as "「".
Almost all Japanese EPUB (and Kindle) books are made with this way, and we must accept this reality even if using ideographic space instead of text-indent considered not very good.

The bigger concern with current spec is that the ebook reader implementation and the spec becoming inconsistent. The **space-first** (trim-start-except-first-line) behavior is implemented as default behavior in ebook readers, ignoring the CSS spec. So I believe the text-spacing **normal** should include the **space-first** behavior.

Also I believe the **space-first** behavior is good for general Web content, it improves readability and beauty of CJK text.

**Comment by frivoal** [comment] 2018-03-22 06:47
First, thank you a lot for writing this, `text-space` and related behavior is an important piece for good Japanese typography, and  we need to work more on it.

As for this specific example, I am a bit conflicted. I think we should have an easy way of authoring content that looks good, and we should take compatibility with existing content into account.

At the same time, the authoring practice of using a full width space instead of an intent is bad. The fact that they have no choice because hanging punctuation is not implemented is unfortunate, but when the root cause of an issue is "a feature is not implemented", specifying another feature-that-is-not-yet-implemented is rarely a good answer.

That said, if we do end up with a significant ecosystem of content and readers that rely on this, this may force our hand.

I do wonder though. You said:

> Also, I believe the space-first behavior is good for general Web content, it improves readability and beauty of CJK text.

If both this `space-first` behavior AND the approach currently proposed by the spec (`text-indent: 1em; text-spacing: trim-start;  hanging-punctuation: first;`) were supported, would there still be cases were using `space-first` is a good idea (other than compatibility with existing EPUB content)?

We may still want to do it for compat reasons if the answer is no (maybe), but if the answer is yes, that makes it much more compelling.

**Comment by MurakamiShinyu** [comment] 2018-03-22 11:02
> If both this `space-first` behavior AND the approach currently proposed by the spec (`text-indent: 1em; text-spacing: trim-start; hanging-punctuation: first;`) were supported, would there still be cases were using `space-first` is a good idea (other than compatibility with existing EPUB content)?

Yes, I think the `space-first` is the best default among `[ trim-start | space-start | space-first ]`.

The current default `space-start` is not very good, the half blank of fullwidth opening punctuation after a soft wrap break is visually not good and may be mistaken for the beginning of a paragraph. 

On the other hand, if we change the default to `trim-start`, it will change the appearance of a huge amount of existing web content, many will be improved visually, but some will be broken. People will be surprised if the fullwidth opening punctuation changes to half-width at every start of lines. I guess this is the reason why `trim-start` is not the default in current spec. The `space-first` (trim-start-except-first-line) behavior will cause less impact, similar to `trim-adjacent` and `allow-end`, and will make good readability and beauty of text.

In addition, we should recognize that in most Japanese web content the text-indent style is not used and margin between paragraphs style is dominant. I think `space-first` behavior will fit well with such modern Japanese web text style.

**Comment by fantasai** [comment] 2018-09-13 05:39
OK, I've added this to the spec, along with a note describing why we're adding it and how it should (and should not) be used. @MurakamiShinyu would you mind reviewing?

**Comment by MurakamiShinyu** [comment] 2019-08-26 11:14
> ISSUE 24 Whether this value should also be part of the UA defaults for Web content is currently under discussion.

I strongly believe this value should be part of the defaults regardless of Web or ebooks, and the `normal` definition should be `space-first allow-end trim-adjacent`.

I think that the current `normal` definition with `space-start` is the worst choice between `[trim-start | space-start | space-first]` because full-width opening punctuation at start of a line that does not begin the paragraph visually looks like beginning of a paragraph with indent because of the half em space that the full-width opening punctuation glyph has, and it makes bad readability.

The remaining options are `trim-start` and `space-first`. I don't believe we can select `trim-start` as default because of web compatibility; it affects existing web contents that use intentionally full-width opening punctuation glyph at beginning of text blocks. So the only reasonable choice for default is `space-first`.

Also, I strongly oppose changing defaults on the Web and ebooks. The difference between Web and ebooks is not obvious. For example, I am working on [Vivliostyle](https://vivliostyle.org/) that can be used as an ebook viewer and also can display/print Web contents with pagination; not obvious the Web content viewing with Vivliostyle is ebook content or not. This is important issue for us because [Support text-spacing](https://github.com/vivliostyle/vivliostyle.js/issues/182) is on our ToDo list.

**Comment by xfq** [comment] 2020-02-05 00:30
In terms of the typographic conventions in mainland China, the special case of "fullwidth opening punctuation at the beginning of a paragraph" is not needed. Major publishing houses use half-width glyphs for opening punctuation characters at the beginning of a paragraph. (See related discussions in https://github.com/w3c/clreq/issues/236)

Since we added an `auto` value in #4657, can we handle this as a locale-sensitive text-spacing rule using `auto`, even though `auto` is not the default value of `text-spacing`?

**Comment by kojiishi** [comment] 2020-02-06 03:00
@xfq Can you clarify a bit more? If Chinese uses half-width glyphs for opening punctuation, `trim-/space-` does not matter at all. Can you point out what I missed?

**Comment by kojiishi** [comment] 2020-02-06 03:05
^ nvm, I think I misunderstood "glyph" with "code points", I think it says major publishing houses expects half-width "glyphs" when using full-width "code point", so `trim-` behavior.

**Comment by xfq** [comment] 2020-02-06 12:32
> ^ nvm, I think I misunderstood "glyph" with "code points", I think it says major publishing houses expects half-width "glyphs" when using full-width "code point", so `trim-` behavior.

Yes, sorry about the lack of clarity.

**Comment by MurakamiShinyu** [comment] 2022-11-15 03:04
- https://github.com/w3c/csswg-drafts/issues/7055#issuecomment-1314690172

> > RESOLVED: Incorporate trim-end behavior into the normal keyword
>
> It's good. Please also incorporate space-first behavior into the normal keyword:
>
> In justified paragraph, it is very bad if the line end edge is visually aligned by trim-end but the line start edge is not. The combination of space-start and trim-end looks very unbalanced.

**Comment by frivoal** [comment] 2022-12-30 02:36
The value has been added, but the question of which of `[trim-start | space-start | space-first]` should be part of `normal` isn't settled.

Reminder: a typical Japanese paragraph starts with a 1em indent. If it starts with an opening punctuation (whose glyph is 1em wide, but only the later half contains ink), that punctuation can be:

* Hung in the 1em indent. (This is probably the most typical/desired look.)
* Set flush (trimmed by 1/2em) after the 1em indent.
* Set solid (yielding effectively a 1.5em indent) after the 1em indent.
    
In styles 1 & 2, opening punctuation wrapped to the start of a line are ideally trimmed by 1/2em in order to set them flush.

Considerations:
* The ideal behavior for CJK is probably a combination of `trim-start` (for `text-spacing`), `1ic` (for `text-indent`), and `first` (for `hanging-punctuation`). This formats the start of each paragraph as expected, when the paragraph is marked up to contain only its actual text and no indentation characters. This would suggest `trim-start` as the right initial value, but since it has not historically been implemented that would create a compat problem both on the Web and in eBooks:
  * `trim-start` breaks expectations on monospace preformatted content. We could maybe work around this with `pre { text-spacing: none; }`, but also...
  * Content authored with no consideration for typography would be improved by this, but content authored to mimic the effect of the above formatting would break.

  Because the properties needed for this to work properly haven't historically been available, typographically conscious content manages indentation by using ideographic spaces at the start of paragraphs that do not begin with (an essentially hanging) opening puctuation.
* Both `space-start` (current default) and `space-first` (Murakami-proposed default) work well with existing content that achieves the desired paragraph-start formatting by including an ideographic space in the markup for every paragraph that does not begin with an opening punctuation mark. The downside is that both these values encourage that markup practice, which gets in the way of `text-indent` and `hanging-punctuation` being able to control paragraph formatting.
* Between these two, `space-first` is a strict improvement: while it plays equally well with legacy content, and equally encourages problematic markup practices, it does have the advantage of avoiding the appearance of a paragraph start if a wrapped line happens to start with an opening punctuation.

I think my recommendation would be to:
1. Adopt `space-first` as the default behavior for normal, and
2. Modify `hanging-punctuation: first` to hang a paragraph-initial ideographic space as well.

**Comment by MurakamiShinyu** [comment] 2023-01-11 06:59
> I think my recommendation would be to:
> 
> 1. Adopt `space-first` as the default behavior for normal, and
> 2. Modify `hanging-punctuation: first` to hang a paragraph-initial ideographic space as well.

That seems very reasonable. The `space-first` behavior would be the best for `normal` that must respect compatibility with existing content.

On the other hand, the `auto` value, defined as "The user agent chooses a set of typographically high quality spacing values", has no such requirement and it should include the `trim-start` behavior naturally. (I think this should be noted in the spec so that `text-spacing: auto` behavior will not look very different in multiple implementations.)

**Comment by xfq** [comment] 2023-01-16 05:16
As I mentioned in https://github.com/w3c/csswg-drafts/issues/2462#issuecomment-582183999 , `space-first` does not meet the typographic conventions in Mainland China. If it is adopted as the default value, do Chinese authors need to change `text-spacing` to achieve the desired effect? I hope we can avoid this from happening.

**Comment by MurakamiShinyu** [comment] 2023-01-16 08:42
`trim-start` will be the best for the typographic conventions, not only for Mainland Chinese but also for Japanese, but it cannot be the default behavior because of the compatibility problem with existing content. Do you think `space-start` is better than `space-first`? I cannot believe so.

When we want to achive the typographic conventions with CSS, we need to change property values from defaults. For example, the defaults `text-indent: 0` and `text-align: start` do not meet the conventions for Japanese normal paragraphs, and we have to change these values to achive the conventions. The same would be the case for `text-spacing`. To achive the typographic conventions, we will use `text-spacing: trim-start` (or `text-spacing: auto`, and/or `hanging-punctuation: first allow-end` for Japanese book style).

**Comment by fantasai** [comment] 2023-01-26 07:00
@xfq Does @MurakamiShinyu's response address your concerns?

**Comment by xfq** [comment] 2023-02-01 09:19
@fantasai The Chinese Layout TF [discussed](https://www.w3.org/2023/01/18-clreq-minutes.html#t01) this and agreed with @MurakamiShinyu's response. Thanks!

**Comment by fantasai** [comment] 2023-02-28 22:49
Edits for this have been committed in https://github.com/w3c/csswg-drafts/commit/29661048af03edf0c093f339e03afc41803c6238 and should appear on /TR shortly!

**Closed by fantasai** 2023-02-28 22:49 UTC
Labels: css-text-4, Closed Accepted by CSSWG Resolution, Needs Edits, i18n-tracker, Needs Testcase (WPT), i18n-jlreq, i18n-clreq
