### ISSUE TITLE
[css-color-4] Concerns about color() function fallback

### ISSUE THREAD

**Issue by weinig** [w3c/csswg-drafts#5931] opened 2021-02-06 18:01 UTC
In thinking more about about how to implement the color() function fallback mechanism https://drafts.csswg.org/css-color-4/#color-function, I am becoming concerned with the implementation complexity required to implement this mechanism and wondering if that burden is warranted given the existing ability for authors to specify colors based destination gamut using media queries (https://www.w3.org/TR/mediaqueries-5/#color-gamut).

Additionally, I am not quite clear how well destination dependent fallback will work with upcoming features like color-mix(), https://drafts.csswg.org/css-color-5/#color-mix and color-adjust(), https://drafts.csswg.org/css-color-5/#coloradjust. Questions I have include things like would it make sense to apply the same transformations to all colors in the fallback list? Would authors need to be able to specify different transformers for each fallback color?

I know the spec authors are conscientious and wouldn't have included the fallback mechanism without a good reason, so I am curious what uses cases prompted it and whether they outweigh the concerns.

**Comment by carlosame** [comment] 2021-02-07 15:39
> wondering if that burden is warranted given the existing ability for authors to specify colors based destination gamut using media queries

IMHO the `color()` function is more useful than the `color-gamut` media feature, as it operates in-place with a specific color; otherwise one may have to repeat some selectors in different media queries (with the maintenance burden for the CSS author), and cannot really be sure about a specific color belonging to the "approximate" gamut represented by that media feature.

Quoting from the MQ4/5 spec: "In most cases the author does not need to know the exact capabilities of the display, just whether it is better than sRGB, or significantly better than sRGB".

However, I share your concerns about its usage in `color-mix()` and `color-adjust()`: an in-gamut color may become out-of-gamut (or vice-versa) after the mix/adjust.

**Comment by weinig** [comment] 2021-02-07 19:29
> IMHO the color() function is more useful than the color-gamut media feature, as it operates in-place with a specific color; otherwise one may have to repeat some selectors in different media queries (with the maintenance burden for the CSS author), and cannot really be sure about a specific color belonging to the "approximate" gamut represented by that media feature.

I'm interested in this argument, but unsure how likely this situation is. My expectation, which is based on limited experience, is that authors are more likely these days to specify a palette of colors up front using a css variables, in which case, having some colors specialized for gamut's greater than sRGB seems feasible using the color-gamut media query. But it is totally possible that is ill-informed.

**Comment by carlosame** [comment] 2021-02-07 20:55
> it is totally possible that is ill-informed

The 2020 Web Almanac says that color values account "for 52% of all custom property declarations", although I could not find any figure about the percentage of color properties using `var()`:

https://almanac.httparchive.org/en/2020/css#usage-by-type

I have an archive of more-or-less current CSS from around 200 top-traffic & complex-CSS hosts (which I use for integration-regression testing) and a quick grep shows that about 42% of the CSS files do use `var()` to set color properties, not sure what validity that figure really has.

Also, the folks using preprocessor variables may have their preferences as to avoid the MQ mechanism (or perhaps not).

In any case I assume that the idea is to give a more deterministic/granular way to specify wide-gamut colors, but let's see if the spec authors have something to say about that (maybe just pointing to an older thread where they probably discussed this multiple times already...).

**Comment by svgeesus** [comment] 2021-02-25 22:03
> Also, the folks using preprocessor variables may have their preferences as to avoid the MQ mechanism (or perhaps not).

The 2020 HTTP Archive Web Almanac [looked at usage of the `color()` function](https://almanac.httparchive.org/en/2020/css#color), which was vanishingly small (only 29 mobile and 36 desktop pages using it!). Because the numbers were so small, I could individually examine each of the stylesheets that used it. **All** were using some sort of fallback, wither with `@supports` test or a media query. None were using the `color()` fallback itself, likely because Safari was the only implementation at the time and does not support the fallback syntax. But also, likely, because the existing CSS fallback mechanisms of document order, `@supports` and media queries are more familiar and entirely suited to the task.

> Additionally, I am not quite clear how well destination dependent fallback will work with upcoming features like `color-mix()`, https://drafts.csswg.org/css-color-5/#color-mix and `color-adjust()`, https://drafts.csswg.org/css-color-5/#coloradjust. 

That is a valid concern and indeed, requires a lot of extra specification work to handle that case.

@tabatkins  also mentioned that supporting the fallback would make the Typed Object Model more complex for `@color()`.

So why do we have it? Well, ICC and Lab colors were in SVG before they were in CSS; and SVG was able (at the request of the XSL working group, to make generating SVG with XSLT easier) to use presentation attributes as well as CSS stylesheets. And in the case of a presentation attribute, media queries were not available and `@supports` did not exist, and an attribute can only be specified once in XML. 

So there was a need for a fallback; [SVG ICC colors](https://www.w3.org/TR/SVGColor12/#icc-colors) and [SVG Lab color](https://www.w3.org/TR/SVGColor12/#LAB) had a fallback. Note that the syntax there is different, the fallback came first.

Looking again at this, I think the fallback syntax has _no benefit for CSS_, and _adds complexity and cost_ for no good reason, and I would be totally fine dropping it!

**Comment by svgeesus** [comment] 2021-02-25 22:05
> My expectation, which is based on limited experience, is that authors are more likely these days to specify a palette of colors up front using a css variables, in which case, having some colors specialized for gamut's greater than sRGB seems feasible using the color-gamut media query.

That does indeed seem to be the most common pattern.

**Comment by svgeesus** [comment] 2021-02-25 22:06
Agenda+ to ask for objections to dropping this, while we still can.

**Comment by svgeesus** [comment] 2021-02-25 22:13
This was the [SVG 1.x SVGColor interface](https://www.w3.org/TR/2003/REC-SVG11-20030114//types.html#InterfaceSVGColor) which allowed either an sRGB color, an sRGB fallback with an ICC color, or the keyword `currentColor`.

**Comment by tabatkins** [comment] 2021-02-26 01:08
This would indeed make the Typed OM interface for color() *dramatically* simpler, not to mention simplify the grammar and processing of it spec-wise. I'm for dropping it.

**Comment by carlosame** [comment] 2021-02-27 14:45
> the fallback syntax has _no benefit for CSS_, and _adds complexity and cost_ for no good reason

Dropping the fallback looks like something desirable, but I do not see the fallback as something totally useless. Consider the following declaration:
```css
color: rgb(...); color: color(--my-profile, ...);
```
In a browser that supports the `color()` function, the second value is valid at parse time, so the first one (the `rgb()`) is wiped out. If `--my-profile` fails for whatever reason when the value is computed, without the fallback it becomes _iacvt_ and the failure is likely to be important.

If the fallback is dropped from the specification, I expect most `color()` functions with custom profiles to be used behind the protection of a `var()` fallback:
```css
--my-color: color(--my-profile, ...);
color: var(--my-color, rgb(...));
```
I mean that dropping the fallback makes life a bit easier (at least for implementors), but leaves some fallout.

**Comment by tabatkins** [comment] 2021-02-27 16:17
I highly doubt "most" would be; authors implicitly depend on things loading correctly almost all of the time.

> without the fallback it becomes iacvt

As currently specified, it becomes opaque black if it can't represent a valid color, not IACVT.

**Comment by carlosame** [comment] 2021-03-01 13:18
I wonder how authors can check whether iccMAX profiles (or whatever new format is invented in 10 years) are supported, with a `@supports` or `@media` rule.

And one of the reasons for a color to be invalid is that the profile is still in the process of being loaded. From the specification:

> later colors acting as "fallback" if an earlier color can’t be displayed (for example, if the colorspace it specifies hasn’t been loaded yet).

So a small 'color glitch' is perfectly possible even if the profile loads correctly, but finishes after a first rendering attempt is made.

Legitimate-but-invalid colors are a real thing to be considered here, although the _iacvt_ behavior may be all that is needed (for the `var()` trick that I mentioned).

**Comment by svgeesus** [comment] 2021-03-01 21:00
> If the fallback is dropped from the specification, I expect most `color()` functions with custom profiles to be used behind the protection of a `var()` fallback:
```css
--my-color: color(--my-profile, ...);
color: var(--my-color, rgb(...));
```

Yes, I expect so too; and it would be good to put such an example in the specification.

**Comment by tabatkins** [comment] 2021-03-02 01:16
> Yes, I expect so too; and it would be good to put such an example in the specification.

No, see my response at <https://github.com/w3c/csswg-drafts/issues/5931#issuecomment-787096886>. Unless we change the spec to make an invalid color force the property into IACVT, currently `color(--unknown)` is a perfectly valid function that represents opaque black.

**Comment by FremyCompany** [comment] 2021-03-02 12:30
I find that removing the fallback mechanism makes things cumbersome as an author. Using variables as a fallback mechanism is an inconvenient hack, and I don't think features should rely on that as their solution for potentially-invalid values.

What is the implementation complexity of the fallback? Would that complexity drop if the fallback was a single item rather than a list? Or is the difficulty determining if a color is in gamut or not? Would it help to just implement a fallback for unsupported color spaces, but not validate if the colors are in gamut? I think it would help us if you could describe what is the complexity you perceive, so that we can make a cost/benefit analysis on our side as well :)

**Comment by carlosame** [comment] 2021-03-02 13:09
> Unless we change the spec

We are discussing about changing the spec. In the current spec, the fallback is not a single value but a chain of them: first, a comma-separated list of colors with a specific syntax, then a color with an arbitrary syntax, and finally the opaque black.

If the fallback mechanism is removed, it makes sense to ditch that last component as well.

> Or with multiple `src` descriptors in `@color-profile`

The scenario that I'm considering is a web designer that has/wants to work with an iccMAX profile, and I do not think that he/she is going to 'port' that profile to v4 (which in many cases would be unfeasible) just so people with older/lower-end devices can see the colors. They'd rather go the `lab()` or `lch()` way.

And one of the main reasons why people use iccMAX is to have a profile which is based on a reference white different to D50. Imagine a `color()` value with certain color coordinates from a `@color-profile`, and that custom profile having multiple `src` descriptors pointing to profiles based on different whites...

A fallback (possibly provided by `var()`) is the proper solution. Let's summarize the use cases for a fallback in a custom-profiled `color()`:

1) The custom profile is iccMAX (or something else in the future), and the device does not support it (this in a world where most mobile devices do not receive OS updates after one or two years).
2) A temporary network failure, due to the site not using a CDN or a CDN issue.
3) Security-conscious government/corporate networks that decide to filter ICC profiles with some rule at the proxy, due to IT security considerations (`@color-profile` rules open a new attack surface to remote attackers).
4) Avoid the 'color glitch' that I described in my previous post.

> removing the fallback mechanism makes things cumbersome as an author

Another possibility would be to remove custom-profiled colors (which are the only ones that IMHO require a fallback) and the `@color-profile` rule, but that would make people in certain industries not very happy.

**Comment by svgeesus** [comment] 2021-03-02 13:18
Hi @FremyCompany these are good questions. The complexities that I and others have noted are:

1. There is a recursive fallback, a `<color>` can have either another `<color>` or a legacy sRGB as fallback; that second `<color>` can also have a fallback and so on. It would not seem reasonable to limit the fallback to sRGB only, so this seems difficult to avoid.
2. Thus, the Typed Object Model for `<color>` needs to represent an arbitrarily-long list of fallbacks
3. CSS Color 5 proposes (as one alternative) [relative color syntax](https://drafts.csswg.org/css-color-5/#relative-colors) to extend `rgb()`, `lab()` and so on. Due to the complexity, this extension to `color()` has yet to be proposed as the grammar becomes tricky to write
4. There are questions about [`color-contrast()`](https://drafts.csswg.org/css-color-5/#colorcontrast) and the fallbacks. Does only the first color get tested? Do all of them? If so, how do we express the result, in that case? If not, what is the contrast if one of the fallbacks ends  up being used?
5. Similar questions for [`color-mix()'](https://drafts.csswg.org/css-color-5/#color-mix), is only the first color mixed? if so, what id the first color would not have been used? if not, is the mix result also a list, and how is that expressed?

**Comment by svgeesus** [comment] 2021-03-02 13:31
>> Unless we change the spec

> We are discussing about changing the spec.

Yes :) @tabatkins was pointing out that if that change were made, another change would also need to be made to have the intended result.

> If the fallback mechanism is removed, it makes sense to ditch that last component as well.

That would make the result undefined, which seems worse than "defined, but not what you want" i.e. opaque black.

> The scenario that I'm considering is a web designer that has/wants to work with an iccMAX profile, and I do not think that he/she is going to 'port' that profile to v4 (which in many cases would be unfeasible) just so people with older/lower-end devices can see the colors. They'd rather go the lab() or lch() way.

Fair point, although many of the things that you can do in iccMax you can't do with just a single `lab()` value, for example:

- spectral processing
- BDRF
- material appearance modelling
- custom observer functions
- most things using the calc element

> one of the main reasons why people use iccMAX is to have a profile which is based on a reference white different to D50.

In my (admittedly limited, but certainly non-zero) experience of what people use iccMAX for, that is a nice-to-have but also the easiest to get an ICC v.4 fallback ad certainly not the main reason iccMAX is being used today.

> Another possibility would be to remove custom-profiled colors (which are the only ones that IMHO require a fallback) and the @color-profile rule, but that would make people in certain industries not very happy.

Yes, that would basically make it useless for any use case where an enumerated list of predefined colorspace is insufficient. It would be like removing images, videos and webfonts from the platform, because sometimes they don't load.

**Comment by carlosame** [comment] 2021-03-02 13:45
> That would make the result undefined

That would make the result invalid (at computed-value time) which is what we want :)

But yes it needs to be specified.

**Comment by FremyCompany** [comment] 2021-03-02 21:32
I still don't understand the proposed fallback strategy. 

```
--my-color: color(--my-profile, ...);
color: var(--my-color, rgb(...));
```
means that I have to duplicate the rgb value every time I use the --my-color variable, which defeats the purpose of using variables in the first place.

Plus, this doesn't work. Variables by default are token streams, so it does not matter that the color() does not yield something valid, as long as it is valid css, it will not cause an error until after it has been replaced in the color property, which means that instead you get `color` that errors at computed time, which makes the color property inherit, which is not what the author want. A solution to this would be to type the custom property such that its value must be converted to a color first, but this requires yet another declaration.

One last point is that we also planned to use the fallback in forced-colors mode so that you could do `color(..., ButtonText)` and all color spaces are deactivated in forced color mode. Now, I guess we can do this another way, but this was a convenient system.

**Comment by svgeesus** [comment] 2021-03-02 21:41
> means that I have to duplicate the rgb value 

Ah, the perils of truncated examples.

```css
--my-color: color(--my-profile 0.4842 0.7107 0.2492);
color: var(--my-color, rgb(40% 80% 10%));
```

(In this example I am using [a prophoto-rgb space to represent --my-profile](https://colorjs.io/apps/convert/?color=color(prophoto-rgb%200.4842%200.7107%200.2492)&precision=4))

There is no duplication, the `var` fallback is using sRGB while the `--my-profile` is using whatever parameters it taks (in this case three, I'm using ProPhoto RGB for the example)

The only way there would be a duplication of rgb values if if I was loading a custom profile which is identical to sRGB. Which I can see happening in WPT but no-where else.

**Comment by carlosame** [comment] 2021-03-02 22:10
> Plus, this doesn't work. [...] it will not cause an error until after it has been replaced in the color property [...] this requires yet another declaration

Well, it works in my implementation (if the value contains a _single_ `var()` substitution that does not yield a valid value, then the fallback is directly used), but yes you are right that in browsers it does require another declaration.

It isn't that cumbersome though, and does the job. The alternative of a 'native' fallback is problematic, as explained by @svgeesus.

**Comment by FremyCompany** [comment] 2021-03-03 11:23
> There is no duplication, the var fallback is using sRGB while the --my-profile is using whatever parameters it taks (in this case three, I'm using ProPhoto RGB for the example)

This is not the duplication I was talking about :) What I was saying is that the rgb() values are now in the fallback of the var() and thus each time you want to use that color you have to repeat them, which defeats the purpose of using a variable in the first place. The advantage of variables is that if you need to change the color to match a new palette, you should be able to it from one place, not each time you use the color.

Putting the fallback in the var() does not work, because you could have a dark theme and a light theme, and thus the fallback you want would be different in those two cases.

> > Plus, this doesn't work. [...] it will not cause an error until after it has been replaced in the color property [...] this requires yet another declaration
> 
> Well, it works in my implementation (if the value contains a _single_ `var()` substitution that does not yield a valid value, then the fallback is directly used), but yes you are right that in browsers it does require another declaration.

What user agent are you talking about? I don't think your user agent should decided not to follow the normal behavior of CSS specs, this might seem convenient right now but this is bound to cause issues down the line. Regardless, I think it would be best if we stuck to discussing user agents that follow the specs in this working group, otherwise we are not going to make progress. 

In the real world, the proposed fallback through variables requires at three declarations for each color for which you need a fallback, I don't think this is reasonable.

**Comment by FremyCompany** [comment] 2021-03-03 11:29
To answer another question, I don't think `color()` should keep multiple values as potentially-active at the same time. This is not what the spec says, and this is not desirable. If you put a `color()` in a `color-mix()` and that because of that one of the value that the color had which was out of gamut is now in gamut after the mix, you still do not want to use that color anyway. Indeed, the whole point of the color mix is to mix two colors, each of which might be used on the page. Switching to another item of the color fallback list in the middle of a color mix would cause a discontinuity, which is not what an author would want. The behavior described in the spec is that `color()` decides which color to use, then sticks to it. For the purpose of anything using `color()` the fallback list is not considered, there is only one value, which is the one that `color()` resolved to.

**Comment by carlosame** [comment] 2021-03-03 12:49
> I don't think this is reasonable.

You are right, considering your use case this is not a proper solution. The explicit fallback in `color()` seems ideal for `forced-colors`.

> What user agent are you talking about?

Carte/Css4j, and [Css4j](https://css4j.github.io/) (which has the described behavior) is being used by other projects to do conversions to PDF. There, if you have the following:
```css
--my-color: invalid;
...
border: 1px var(--my-color, #00f);
color: var(--my-color, #00f);
```
the declaration for `border` would be invalid, but the one for `color` would work as being a single, outermost `var()`. Back when I implemented that, it seemed like a solution closer to author's intent, and assumed that browsers would do the same or that (an older version of) the spec allowed that.

**Comment by FremyCompany** [comment] 2021-03-03 17:58
In all fairness, it isn't all that unlikely that the confusion about the fallback behavior was probably even caused by me because I supported the model you implemented back when this was being discussed, and maintained a fork of the custom properties spec for a while; mea culpa ^_^ The reason this wasn't retained in the end is that you have to potentially retry N^2 times if you have nested variables each having fallbacks, and user agents were not keen on supporting this.

**Comment by carlosame** [comment] 2021-03-03 19:47
> you have to potentially retry N^2 times if you have nested variables each having fallbacks, and user agents were not keen on supporting this.

Well I only do that at the outermost (final) `var()`, and it is computationally very cheap.

It is natural to believe that, if the author put a single `var()` with a fallback in the declaration for the final property (not in the intermediate custom properties where one expects purely lexical-level behavior), he/she expects to see that fallback if the custom property's value becomes _iacvt_. And BTW the origin of my interpretation could be either that, or the fact that during most of the development my computer almost always hanged when I attempted to have the IDE and a browser (with e.g. the spec) opened simultaneously...

I won't miss that computer :)

**Comment by svgeesus** [comment] 2021-03-12 17:41
Yesterday I took Safari Preview 121 through the CSS Color 4 testsuite. The [results](https://test.csswg.org/harness/results/css-color-4_dev/grouped/) now show two implementations, BFO Publisher and Safari, passing almost all tests (Spec test coverage is not complete though). BFO skips the tests that require scripting. Relevant to this issue, Safari fails on two tests which exercise `color()` fallback.

predefined-015.htm has a valid first color and a red fallback, the pass is "green no red"

```css
    .test { background-color: red; width: 12em; height: 6em; margin-top:0}
    .ref { background-color: #009900; width: 12em; height: 6em; margin-bottom: 0}
    .test {background-color: color(display-p3 0.26374 0.59085 0.16434, red)}
```
predefined-014.htm has an invalid first color and a green fallback, again the pass is "green no red"

```css
    .test { background-color: red; width: 12em; height: 6em; margin-top:0}
    .ref { background-color: #009900; width: 12em; height: 6em; margin-bottom: 0}
    .test {background-color: color(banana 0.1 0.2 0.3, #009900)}
```

I deduce therefore that Safari does not currently implement the falback _at all_, (which is a reasonable decision at this point) so -15 fails just because the parser hits a comma instead of a closing paren.

BFO Publisher passes both those tests.

So again I think removing the fallback syntax from `color()` and using the existing CSS facilities of stylesheet order, conditionally set custom properties, `@media` queries, and `@supports` gives better fallback without cluttering the syntax and implementation complexity.

**Comment by carlosame** [comment] 2021-03-12 19:06
> So again I think removing the fallback syntax from `color()` and using the existing CSS facilities

Incidentally, it seems that browsers do what I suggested with my "var() trick", and that's not exactly what one would conclude from the specification (which led me to wrongly believe that it was not going to work). Consider the following:
```html
<body style="font-size:16pt">
  <div style="--bar:calc(3em*var(--foo))">
    <p style="font-size:var(--bar,5em)">Hi</p>
  </div>
</body>
```
The `calc()` value becomes inconsistent after substitution (becomes _iacvt_), but then the `5em` fallback is applied (instead of falling back to the `16pt`). For comparison, the fallback is **not** being applied in the following case, and the text is displayed with a size of `16pt`:
```html
<body style="font-size:16pt">
  <div style="--bar:blue">
    <p style="font-size:var(--bar,5em)">Hi</p>
  </div>
</body>
```
because `blue` is a perfectly valid value, but not for `font-size`.

In the first example, `calc()` is internally inconsistent as a value, the same that would/should happen with `color(--invalid, 0.1 0.2 0.3)`.

So the `var()` example that I posted should work, if the browsers handle invalid `color()` values in the same way that they handle invalid `calc()`. Verified with both Chrome and Firefox.

On the other hand, the `forced-colors` use case could benefit from the [switch function that I proposed](https://github.com/w3c/csswg-drafts/issues/5009#issuecomment-620766100) elsewhere, if it is ever implemented.

**Comment by FremyCompany** [comment] 2021-03-12 21:15
Hi @carlosame, your test case is valid but your analysis of what happens is not.

> The calc() value becomes inconsistent after substitution (becomes iacvt), but then the 5em fallback is applied.

No, the calc() is never evaluated. What happens is that the "--foo" declaration is invalid, and ignored. Then the declaration of "--bar" is invalid at specified time, and becomes invalid, due to using an invalid reference to --foo which has not been defined. Since --bar is not defined, the fallback is then used.

You can verify this using this altered code (where the declaration of --foo is valid because it contains at least one token, a white space, but any value would do really):
```html
<body style="font-size:16pt;--foo: ;">
  <div style="--bar:calc(3em*var(--foo))">
    <p style="font-size:var(--bar,5em)">Hi</p>
  </div>
</body>
```

Variables fallback does work as is written in the spec, and making color invalid at computation time would not trigger variable fallback, it isn't supposed to work that way.

**Comment by tabatkins** [comment] 2021-03-12 22:50
Aw dang I had a draft comment saying the same thing but I went to eat lunch and you scooped me, @FremyCompany ^_^

Note that the "`--foo;` is invalid" is a bug that we fixed in the spec a while ago, tho. Empty custom properties are valid per spec.

**Comment by carlosame** [comment] 2021-03-13 13:10
> the "--foo" declaration is invalid

As @tabatkins mentions the `--foo:;` is valid. Seems a bug in both Chrome and Firefox.

A regular property set to the empty value is valid as well, but in practice almost always caused by a buggy template (either a CSS preprocessor or a generic server-side template like Apache Velocity).

**Comment by carlosame** [comment] 2021-03-13 20:24
I just created a gist describing the switch-like function that I mentioned above:

https://gist.github.com/carlosame/dcadf67b33d8a8b25eece17668fa057f

Not exactly the same as having the `color()` fallback value, but potentially useful.

**Comment by svgeesus** [comment] 2021-03-17 16:25
So I see assorted discussion about which other mechanism to use for CSS fallback.

But I am seeing consensus on removing the specific, SVG-influenced, `color()` fallback which nicely simplifies the spec.

**Comment by LeaVerou** [comment] 2021-03-17 16:41
The issue mentioned about an `in-gamut` media query: https://github.com/w3c/csswg-drafts/issues/5045

Do we also need a way for authors to provide fallbacks for nonexistent color spaces, which was another function of the fallback parameter?

**Comment by carlosame** [comment] 2021-03-17 16:51
> I see assorted discussion about which other mechanism to use for CSS fallback.

Yet another proposed mechanism:

[Compact CSS media rules: the `@assign` mechanism](https://gist.github.com/carlosame/d71832c68a4b446b397738f5cdb222b5)

That's the other "flavour" that I mentioned in #5009 but did not write down until now.

**Comment by carlosame** [comment] 2021-03-17 17:46
> I would urge you to fork the other discussion into a different issue

To decouple this issue from the fallback discussion, an important detail is pending: what is the outcome of an invalid custom profile. If it is "opaque black", that leaves little to be done at computed-value time. But if it is IACVT, then something like this may work:
```
varf(<custom-property-name>, <declaration-value>);
```
where `varf` is like `var` but with the fallback being applied if value is IACVT.

**Comment by weinig** [comment] 2021-03-17 19:21
Sorry if this clear to everyone else, but is this "IACVT" term defined somewhere? I am not familiar with it.

**Comment by tabatkins** [comment] 2021-03-17 19:25
[Invalid at computed-value time](https://drafts.csswg.org/css-variables/#invalid-at-computed-value-time)

**Comment by LeaVerou** [comment] 2021-03-17 22:32
> > I see assorted discussion about which other mechanism to use for CSS fallback.
> 
> Yet another proposed mechanism:
> 
> [Compact CSS media rules: the `@assign` mechanism](https://gist.github.com/carlosame/d71832c68a4b446b397738f5cdb222b5)_ (too large to embed)_
> 
> That's the other "flavour" that I mentioned in #5009 but did not write down until now.

Shortened syntaxes for terse media queries are an orthogonal issue to which media queries should exist.

**Comment by carlosame** [comment] 2021-03-17 22:57
> Shortened syntaxes for terse media queries are an orthogonal issue to which media queries should exist.

Yes, and both issues were relevant to the "should we have a fallback or use media queries". For example, a shortened syntax with several values seemed to be useful for `forced-colors` (I mean they already have the media feature but still asked for the fallback), and that's why I'm pointing to potential alternatives.

BTW perhaps I misunderstood the motivation for wanting the `color()` fallback mechanism.

**Closed** 2021-03-18 02:03 UTC
Labels: Needs Edits, Needs Example or Figure, css-color-4

**Comment by svgeesus** [comment] 2021-03-19 17:06
> Do we also need a way for authors to provide fallbacks for nonexistent color spaces, which was another function of the fallback parameter?

Nonexistent colorspaces result in `invalid color` which produces `opaque black`.

**Comment by LeaVerou** [comment] 2021-03-19 23:45
> > Do we also need a way for authors to provide fallbacks for nonexistent color spaces, which was another function of the fallback parameter?
> 
> Nonexistent colorspaces result in `invalid color` which produces `opaque black`.

How would authors be able to handle failure here? Especially since custom color spaces depend on separate HTTP requests, which could always fail for whatever reason. We don't want websites to suddenly turn all black because an HTTP request failed, do we? That would be terrible, both for accessibility and usability.

Some thoughts:

- What if instead of opaque black, the property becomes invalid at computed value time, which would set it to `unset`. That is a far more reasonable fallback for most cases.
- I wonder if instead of having a _color fallback_, we should really have _color space fallbacks_. What do I mean by that? A `@color-profile` descriptor that basically says "if my ICC profile doesn't load, treat my coordinates as this color space". E.g. if we link to a profile for OKLab and it doesn't load, treat coords as Lab. Or if we link to an RGB profile, we can say, as a fallback, treat params as sRGB or P3 or whatever built-in RGB color space is closest to the one we linked to.

**Comment by tabatkins** [comment] 2021-03-20 00:52
I'm not *strongly* opposed to doing more IACVT, but I'd like to avoid adding it to more things if we can; it's an awkward compromise that still doesn't give any guarantee that the result is readable.

I *do* quite like the "color space fallback" idea, designating which of the predefined colorspaces treats its first three arguments "close enough" to your desired colorspace to work as a last-ditch substitution. That seems to solve the problem quite well. Should we choose a default for this, or require it to be explicitly specified on each `@color-profile` rule?

**Comment by faceless2** [comment] 2021-03-20 11:20
I also really like the "color space fallback" solution. Assuming the author hasn't just messed up, the way this is going to come into play is if the profile is unavailable. Lea's suggestion would almost certainly be the least visually jarring result.

Obviously if we have `@color-profile foo { src: url(missing.icc) }` we don't really know enough about the missing profile to determine which space to choose as a fallback. A presumption based on the number of components is what I'd suggest - one component is grayscale, three is `sRGB`, four uses `device-cmyk`.

This will fail for lab profiles, and  for "exotics" with two or more than four components - which can just fall back to black as they do now. And three color spaces that are not RGB are super rare in the real world. Given we're falling back to black  now, falling back to an equally incorrect color isn't a step backwards. While testing I frequently turned whole pages black, as my missing profile meant both text _and_ background were black. Frankly anything is an improvement over that.

**Comment by LeaVerou** [comment] 2021-03-21 03:00
> While testing I frequently turned whole pages black, as my missing profile meant both text _and_ background were black. Frankly anything is an improvement over that.

Yup, that is exactly what I was trying to avoid, so I think failing to opaque black is unacceptable in *any* case.

Probably the best possible fallback will come from the fallback color space. Note that this could also provide a good fallback while the profile is loading, preventing huge color shifts, which would otherwise deter many authors from using ICC profiles. People could even use it as progressive enhancement. I have also heard there were concerns from the Blink team about having colors that depend on an HTTP request, hopefully this should help alleviate them.

However, there is not always a built-in color space that is reasonable, so I don't think we can make this descriptor mandatory. While most ICC profiles are RGB and CMYK, they are not the only ones. This is where IACVT comes in, which, as a last resort, produces far more accessible results than just opaque black everywhere. If we don't want to use IACVT, another option might be to use the property's initial value **if** that is a color, otherwise `transparent`. This prevents the "black text on black background" problem, and doesn't make the entire declaration invalid like IACVT would.

**Comment by carlosame** [comment] 2021-03-23 14:13
Although I'm reluctant to post in closed issues, I want to add that "opaque black" is probably not the most adequate choice because it is not printer-friendly. As was mentioned, it is possible that large chunks (or entire pages) of a document become black, and for printing use cases a likely outcome is the toner cartridge being wasted. `white` or `transparent` seem more sensible choices, toner-wise.

**Comment by LeaVerou** [comment] 2021-03-23 18:18
> Although I'm reluctant to post in closed issues,

Yup, this needs a new issue. I just created one, let's please move discussion there: https://github.com/w3c/csswg-drafts/issues/6129
