### ISSUE TITLE
[css-ui] Reorder value arguments to the `outline` property

### ISSUE THREAD

**Issue by imageck** [w3c/csswg-drafts#8281] opened 2023-01-05 15:38 UTC
To make it in line with `border`. Currently, it's in an alphabetical order, which is in reverse to `border`. Unifying both to some common pattern will improve consistency, code readability and maintainability.

https://www.w3.org/TR/css-ui-3/#outline

**Comment by Loirooriol** [comment] 2023-01-05 18:47
Duplicate of #7700

**Closed by Loirooriol** 2023-01-05 18:47 UTC
