### ISSUE TITLE
View Transitions MPA click miss

### ISSUE THREAD

**Issue by adambernath** [w3c/csswg-drafts#10117] opened 2024-03-21 23:25 UTC
I'm testing out the MPA version, I don't really know how close it is to release, but what I've experienced so far is that it does not register click events (havent tried it with tap) around 20-30% of the time, sometimes even twice on the same element.

Is this something you are aware of and working on? 
Thanks

**Comment by vmpstr** [comment] 2024-03-22 20:59
If you're testing this out in Chromium, do you mind filing a bug at crbug.com/new with the steps to reproduce?

**Comment by vmpstr** [comment] 2024-03-22 21:00
Closing this, since it's unrelated to the view transitions spec work (iiuc). Please reopen if you disagree.

**Closed by vmpstr** 2024-03-22 21:00 UTC
Labels: css-view-transitions-2
