### ISSUE TITLE
[css-color-4] Is color-mod() = color(…) a typo?

### ISSUE THREAD

**Issue by simevidas** [w3c/csswg-drafts#868] opened 2017-01-08 20:04 UTC
```
color-mod() = color( [ <color> | <hue> ] <color-adjuster>* )
```

Source: https://drafts.csswg.org/css-color/#modifying-colors

Why is `color-mod` on the left and `color` on the right? Shouldn’t the same identifier be on both sides?

---

Note to self: Notify https://cloudfour.com/thinks/building-themes-with-css4-color-features/

**Comment by Crissov** [comment] 2017-01-09 16:09
Duplicate of #813.

**Closed** 2018-01-18 16:21 UTC
Labels: css-color-4
