### ISSUE TITLE
[css-display] make invisible content available to AT

### ISSUE THREAD

**Issue by dauwhe** [w3c/csswg-drafts#427] opened 2016-08-25 19:06 UTC
There seem to be [lots](http://a11yproject.com/posts/how-to-hide-content/) of [hacky](http://webaim.org/techniques/css/invisiblecontent/) ways to make web content visually hidden but available to assistive technologies. 

Would `box-suppress: hide` be a solution for that issue? I've seen little discussion on how it would impact the accessibility tree. 

EPUB is struggling with the lack of support for MathML. One thought was to include MathML, but by default display an image equivalent. Reading systems that support MathML could display the MathML through a user agent stylesheet. AT would always need to be able to use the MathML.

**Comment by aaaxx** [comment] 2016-09-08 00:16
I can't upvote this highly enough. It would be really useful for designers to have a standard way to visually hide content, be it `box-suppress` or some other property.

**Comment by fantasai** [comment] 2017-01-03 11:00
This is covered in the Speech module's `speak` property: https://www.w3.org/TR/css-speech/#speaking-props-speak

Perhaps it would be helpful to move it into the Display module to generate more interest? Alternately I've suggested trimming down the Speech module to consist solely of `speak` and `speak-as`.

**Comment by fantasai** [comment] 2017-01-03 11:15
Closing as a duplicate of #560.

**Closed by fantasai** 2017-01-03 11:15 UTC
Labels: css-display-3, css-speech-1
