### ISSUE TITLE
[css-grid-1] Spec doesn't seem to discuss baseline-alignment + auto-margins.

### ISSUE THREAD

**Issue by bfgeek** [w3c/csswg-drafts#5923] opened 2021-02-03 19:19 UTC
Implementations disable baseline alignment for an item (and are lowered in precedence for baseline propagation)  if it has auto margins on either side in the relevant axis: e.g.
https://www.software.hixie.ch/utilities/js/live-dom-viewer/?saved=8886

However we couldn't find this in the spec. E.g.
https://drafts.csswg.org/css-grid-1/#auto-margins only discusses general alignment etc. not normative.
https://drafts.csswg.org/css-align-3/#baseline-alignment doesn't seem to mention it.
https://drafts.csswg.org/css-grid-1/#grid-baselines 

It might be implied(? - unsure) but at least a note discussing this interaction would be good.

**Comment by Loirooriol** [comment] 2021-02-03 19:50
```html
abc <div style="display: inline-grid; border: solid; grid-template-columns: auto auto">
  <small style="align-self: baseline;">baseline</small>
  <big style="font-size: 20px; align-self: baseline; margin-top: auto">baseline</big>
</div>
```
has baseline alignment in Firefox but not in Chromium.

**Comment by bfgeek** [comment] 2021-02-03 20:28
> has baseline alignment in Firefox but not in Chromium.

This behaviour seems potentially like a bug in FF - e.g. https://www.software.hixie.ch/utilities/js/live-dom-viewer/?saved=8887 leaves some space above the first item when there shouldn't be any.

**Comment by Loirooriol** [comment] 2021-02-04 00:00
CC @MatsPalmgren

**Comment by tabatkins** [comment] 2021-06-16 22:20
@bfgeek

You're right that this was unspecified - quite a bit of margin interactions were, as we found out while digging into this! We committed the following fixes:

* Made the definition of auto margins for grid items normative, and tightened it up in https://github.com/w3c/csswg-drafts/commit/16ed028af7c0d0a59a6b723ac15f5c817bcd6353.
* Defined that overflowing items with auto margins safe-align, just as they do in Flexbox, in https://github.com/w3c/csswg-drafts/commit/7b78f0dd7648fc258be1ecdb20ebdf9b6be089e1.
* Defined more completely how baseline self-alignment and content alignment work in https://github.com/w3c/csswg-drafts/commit/965a5af1e8fb03f3706592e416bb7a01169c665b  (filed separately as https://github.com/w3c/csswg-drafts/issues/6389).
* Committed a proposed fix for this issue in https://github.com/w3c/csswg-drafts/commit/c78e58b5ccd893de6811d7b083f57809c102a102).

That final proposed fix (https://github.com/w3c/csswg-drafts/commit/c78e58b5ccd893de6811d7b083f57809c102a102) specifies that auto margins only disable baseline content-alignment if they conflict with its baseline preference, identically to how self-alignment was already specified to work. (I.e. start-aligning a box, whether with margins or alignment properties, is compatible with first-baseline alignment; and end-aligning the box is compatible with last-baseline alignment.)

This doesn't quite match current implementations, but we think it makes the most sense, since auto margins and self-alignment are, in practice, identical for authors. However, we're okay with just fully disabling baseline content-alignment in the presence of auto margins if necessary. What do people think? (Agenda+ to ask more broadly.)

**Comment by javifernandez** [comment] 2021-06-23 09:47
Hi, sorry for the late reply. I'm not sure I understand what's the final proposal for this issue, since there are a lot of changes in the spec and not all of them are related to auto-margin alignment. In the last comment from @tabatkins it was mentioned:

>  that auto margins only disable baseline content-alignment if they conflict with its baseline preference, identically to how self-alignment was already specified to work.

In the last draft ([16ed028](https://github.com/w3c/csswg-drafts/commit/16ed028af7c0d0a59a6b723ac15f5c817bcd6353)) it's stated clearly that the use of auto-margins in on axis disables the the self-alignment properties in such axis. Hence, it's clear that such item can't participate in baseline alignment, since it's align-self/justify-self values must be ignored. I think it's a bit confusing or redundant  that in [c78e58b](https://github.com/w3c/csswg-drafts/commit/c78e58b5ccd893de6811d7b083f57809c102a102) we use auto-margins as a limit for the grid item's participation in baseline (the root cause is that aligng-self/justify-self are ignored) and even there seems to be scenarios (if I've understood it correctly) where even with auto-margins the grid item may participate in baseline alignment (it's impossible since align-self/justify-seld must be ignored).

I've always assumed that the use of auto-margins in one axis would imply ignoring at all the value of the self-alignment properties operating on such axis. In the last published spec this was specified as:

https://www.w3.org/TR/css-grid-1/#auto-margins
> auto margins absorb positive free space prior to alignment via the box alignment properties. 

That's what motivated the initial implementation of the Alignment logic in both, Chrome and Safari.

**Comment by javifernandez** [comment] 2021-06-23 13:31
Now that I read it again, the spec states "disabling the effects", not "disabling the properties"; given this subtle difference, I guess it makes sense to clarify explicitly in the Self Baseline Alignment section that items with auto-margins won't participate in baseline-alignment, despite either justify-self or align-self may have 'baseline' as value.

My only doubt so far is whether these changes introduce any behavior change regarding how auto-margins affects to the Self Alignment features. My understanding is that there is no effect of these properties, independently of their value (including baseline), when items use 'auto' margins.

**Comment by fantasai** [comment] 2021-06-29 22:01
@javifernandez I think you're mixing up self-alignment and content-alignment. Self-alignment is definitely disabled in the presence of auto margins, but our question was about baseline content-alignment.

**Comment by javifernandez** [comment] 2021-06-30 07:59
Yeah, I've read the log of the CSS WG meeting Sorry about the confusion. I'm satisfied with the resolution.

**Closed** 2021-07-02 15:52 UTC
Labels: Closed Accepted by CSSWG Resolution, Commenter Satisfied, Needs Testcase (WPT), css-align-3, css-grid-1
