### ISSUE TITLE
css-color-adjust-1 "forced colours mode" re-introduces a privacy concern

### ISSUE THREAD

**Issue by mallory** [w3c/csswg-drafts#5548] opened 2020-09-24 16:36 UTC
I reviewed [css-color-4] and found that the deprecated systemcolors are necessarily back because of the use of forced colors mode. Even as per the current privacy and security considerations section of [css-color-adjust-1]:

{{
Applying user color preferences via color schemes or forced colors mode expose the user’s color preferences to the page, which can increase fingerprinting surface.
}}

It would be better if these were only available to the user-agent in order to do the color mapping.

[css-color-4] https://drafts.csswg.org/css-color-4/#deprecated-system-colors
[css-color-adjust-1] https://drafts.csswg.org/css-color-adjust-1/#privsec

**Comment by fantasai** [comment] 2021-01-07 18:20
@mallory We've made some technical changes that make this more possible, however see https://github.com/w3c/csswg-drafts/issues/5710 for current discussion.

**Comment by fantasai** [comment] 2021-05-13 19:13
Closing as duplicate of #5710 (since the discussion is there).

**Closed** 2021-05-13 19:13 UTC
Labels: Closed as Duplicate, css-color-4, css-color-adjust-1
