### ISSUE TITLE
[selectors][Editorial] Are things like :is(.foo *) still a <compound-selector>?

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#6737] opened 2021-10-17 17:54 UTC
Currently there are various specs that restrict selector arguments to `<compound-selector>` for performance reasons. E.g. [`:host` and `:host-context()`](https://www.w3.org/TR/css-scoping/#host-selector). 

However, given [how `<compound-selector>` is defined](https://www.w3.org/TR/selectors-4/#typedef-compound-selector), things like `:is(.foo .bar *)` or `:not(.foo .bar *)` still match its grammar:

```
<compound-selector> = [ <type-selector>? <subclass-selector>*
                        [ <pseudo-element-selector> <pseudo-class-selector>* ]* ]!
[...]
<pseudo-class-selector> = ':' <ident-token> |
                          ':' <function-token> <any-value> ')'
```

So technically, things like `:host-context(:is(.foo .bar *))` should be allowed, even though they currently are not in implementations and I guess should not be. Am I missing something or do these grammars need fixing? Perhaps we need a `<restricted-compound-selector>` or something?

cc @tabatkins

**Comment by tabatkins** [comment] 2022-10-25 20:36
Fixing up some of the tags, since this is definitely not editorial.

(I'm not sure what the right answer is, but I've brought this up independently in another issue now, too.)

**Comment by tabatkins** [comment] 2022-10-25 20:44
But I will say, if the perf requirements are still valid, then we should switch to a production that explicitly prohibits pseudo-classes from containing complex selectors. If they're not, then we should stop pretending there's a restriction, and just relax it to `<selector>`.

**Comment by tabatkins** [comment] 2022-12-09 22:47
(Closing as a dupe of #5093)

**Closed by tabatkins** 2022-12-09 22:47 UTC
Labels: selectors-4, css-scoping-1, Agenda+, selectors-5, css-scoping-2
