### ISSUE TITLE
[css-flex] Nobody follows the spec regarding intrinsic size of flex container

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#10779] opened 2024-08-26 13:33 UTC
```html
<!DOCTYPE html>
<style>
.flexbox {
  display: flex;
  flex-direction: column;
  border: solid;
}
.flexbox > div {
  flex: 1 1 100px;
  line-height: 200px;
  min-width: 0;
  min-height: 0;
}
</style>
<div class="flexbox">
  <div>Flex item</div>
</div>
```

According to https://drafts.csswg.org/css-flexbox-1/#intrinsic-main-sizes

> if a [flex container](https://drafts.csswg.org/css-flexbox-1/#flex-container) has a single [flex item](https://drafts.csswg.org/css-flexbox-1/#flex-item) with [flex-basis: 100px;](https://drafts.csswg.org/css-flexbox-1/#propdef-flex-basis) but a max-content size of 200px, then when the item is [flex-grow: 0](https://drafts.csswg.org/css-flexbox-1/#propdef-flex-grow), the flex container (and flex item) is 100px wide, but when the item is flex-grow: 1 or higher, the flex container (and flex item) is 200px wide.

So here the flex container should be 200px tall, but all Gecko/Blink/WebKit  produce 100px instead.

In Servo we are now following the spec so we modified this WPT: https://github.com/web-platform-tests/wpt/commit/6185316759deea9b747bb642d29fd74e6ce98119

But I wonder if the spec should change if the main implementations aren't planning to align with it.

**Comment by cbiesinger** [comment] 2024-08-27 15:05
duplicate of issue #5742 probably?

**Comment by Loirooriol** [comment] 2024-08-27 15:26
That's about the default flex-basis being `0px` or `0%`. Here I'm setting and explicit value for the flex-basis so it seems unrelated.

**Comment by cbiesinger** [comment] 2024-08-27 15:30
oh sorry, I read too quickly

**Comment by bfgeek** [comment] 2024-08-27 18:30
See: https://github.com/w3c/csswg-drafts/issues/8884

**Closed** 2024-08-28 10:00 UTC
Labels: css-flexbox-1, Agenda+
