### ISSUE TITLE
[css-content] doesn't include C.2.86 from CSS2.1

### ISSUE THREAD

**Issue by Loirooriol** [w3c/csswg-drafts#2507] opened 2018-04-05 20:23 UTC
CSS2.1 added this text ([C.2.86](https://www.w3.org/TR/CSS21/changes.html#q21.93)):

> A 'close-quote' that would make the depth negative is in error and is
ignored (at rendering time): the depth stays at 0 and no quote mark is
rendered (although the rest of the 'content' property's value is still
inserted).

You can see it in https://www.w3.org/TR/CSS21/generate.html#quotes-insert

But this is not in https://drafts.csswg.org/css-content/#quote-values

**Comment by fantasai** [comment] 2024-02-05 22:18
Fixed in 95a6e4010ca7f52e1bcb318d3dbd52055b3fe9ff , closing as duplicate of #2038

**Closed by fantasai** 2024-02-05 22:18 UTC
Labels: css-content-3, Closed Accepted as Obvious Bugfix, Closed as Duplicate
