### ISSUE TITLE
[cssom-view] Define term “client window”

### ISSUE THREAD

**Issue by bramus** [w3c/csswg-drafts#8239] opened 2022-12-16 13:36 UTC
As a follow-up to Interop2022’s [Viewport Investigation Effort](https://github.com/web-platform-tests/interop-2022-viewport/), I’m filing this issue that came up.

In issue https://github.com/web-platform-tests/interop-2022-viewport/issues/17 it was noted that the term “client window” is used, but not specified.

We suggest to define this term in the spec.

**Comment by cvrebert** [comment] 2023-02-01 07:10
Duplicate of #430

**Closed** 2023-02-01 09:57 UTC
Labels: cssom-view-1
