### ISSUE TITLE
[css-fonts-4] Deduplication of computed style & inheritance for duplicate axis tags

### ISSUE THREAD

**Issue by drott** [w3c/csswg-drafts#2288] opened 2018-02-08 09:17 UTC
The review of @FremyCompany 's contributed set of test OpenType Variations test cases uncovered an issue with deduplication / resolving overspecified axis tag-value combinations.

The test case is [`css/css-fonts/variations/font-variation-settings-inherit.html`](https://github.com/w3c/web-platform-tests/pull/9373/files#diff-d5ac874d1a25c33c4b5d5c23cf89fb49).

The initial assertions in this test cases assumed that if a parent element has redundant axis tag value combinations, then after inheritance the computed style for the child element should return the result after applying the rule "last appearance supersedes any previous value" (from [8.2. Low-level font variation settings control: the font-variation-settings property](https://drafts.csswg.org/css-fonts-4/#font-variation-settings-def)).

The way I read it, the spec does not explicitly clarify at which point the resolution of duplicate axis tags should be performed. 

- Should it be performed only internally before performing OpenType layout and resolving duplicated tags just at the time of layout and rasterization _(a)_?
- Or should it be performed as soon as the values are set and then stored internally as a deduplicated / validated list _(b)_? 

Blink's implementation (and I believe WebKit, too, @litherum ?) does mostly (a), whereas Edge seems to do (b).

I believe it's cheaper not to do any validation / deduplication during CSS style resolution and inheritance and only apply the "last value supersedes any previous ones" rule when it's needed, in layout and rasterization.

We should specify the behavior for what comes back from computed style and how font-variation-settings should be inherited in order to improve interop and sharpen this test case.

**Comment by upsuper** [comment] 2018-02-15 02:43
I have a different sense. I kind of think it is cheaper to do simplification as early as possible when there is no other constraints. Restyle can happen far more times than parsing, and repaint is usually more frequent than restyle. Also, dropping earlier means the behavior is also easier to verify with tests (without needing to create special test font in this case).

Thus, I believe that it is cheaper on memory, computation, and testability to dedup them as early as possible, ideally during parsing.

**Comment by upsuper** [comment] 2018-02-15 02:49
@jfkthame may know how gecko implements this.

**Comment by jfkthame** [comment] 2018-02-15 10:18
Currently, I believe Gecko passes the specified list of axis-value settings through as-is, and the "last value wins" behavior occurs at rendering time. However, I agree with @upsuper that there's a good case for earlier simplification.

(Note, though, that early simplification of `font-variation-settings` -- e.g. removing duplicates at parsing time -- does not eliminate the need for further processing of the variation list at rendering time, because of how variations specified in a `@font-face` descriptor combine with those specified in an element's style.)

BTW, according to [Fonts 3](https://drafts.csswg.org/css-fonts-3/#propdef-font-feature-settings),

> The computed value of font-feature-settings is a map, so any duplicates in the specified value must not be preserved.

and IMO we should have the equivalent behavior for `font-variation-settings` and `font-feature-settings`; it will be unnecessarily confusing for authors if these two properties behave differently with respect to inheritance, computation, etc.

(I don't have Edge on hand just now to check, but a brief test indicates that neither Gecko nor Blink currently follow the spec here for `font-feature-settings`; duplicates are preserved in the computed value. However, I think we should consider that a bug, and get it fixed accordingly -- for both features and variations.)

**Comment by csnardi** [comment] 2018-02-15 18:19
I believe this should be #1959, correct? The resolution there was:

> RESOLVED: For both font-variation-settings and font-feature-settings, the computed value is a map (and thus specified dupes are removed)

Which has only made it into the spec for font-feature-settings so far, as @jfkthame notes.

**Comment by svgeesus** [comment] 2018-02-15 21:22
Yes, that is the correct resolution.

**Comment by litherum** [comment] 2018-03-06 07:29
Duplicate of https://github.com/w3c/csswg-drafts/issues/1959

**Closed by litherum** 2018-03-06 07:29 UTC
Labels: Needs Edits, css-fonts-4
