### ISSUE TITLE
[css-text] Clarify how letter-spacing and word-spacing should affect tab-size.

### ISSUE THREAD

**Issue by wisniewskit** [w3c/csswg-drafts#643] opened 2016-10-25 04:52 UTC
Recently it was [resolved](https://lists.w3.org/Archives/Public/www-style/2016Oct/0068.html) that letter-spacing and word-spacing should affect tab-size, as per this [proposal](https://lists.w3.org/Archives/Public/www-style/2015Jan/0548.html):

> tab stops are calculated as
>   n*( width of U+0020 plus letter-spacing plus word-spacing)

But this seems strange to me, as tab characters are already affected by letter-spacing, aren't they? (That's what I'm seeing while playing around in devtools in Firefox and Chrome). Why count letter-spacing twice for tabs?

In addition, tabs [aren't word-separators in the spec](https://drafts.csswg.org/css-text-3/#word-spacing-property), which also states:

> If there are no word-separator characters, or if a word-separating character has a zero advance width (such as the zero width space U+200B) then the user agent must not create an additional spacing between words.

How is this meant to be reconciled? Should the word-spacing be applied regardless of whether there are word-separator characters in the run?

**Comment by dbaron** [comment] 2016-12-22 23:41
A few thoughts here (basically crossposting from the [Gecko bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1308113)):

* Tabs currently get one <code>letter-spacing</code> already.  So I think integer values of <code>tab-size</code> should account for letter-spacing by using the formula: <blockquote>N*(width of U+0020) + (N-1)*letter-spacing</blockquote>
* I don't understand the motivation for accounting for <code>word-spacing</code>, so it's hard for me to tell what was intended.  What is accounting for <code>word-spacing</code> supposed to make things line up with?

**Comment by fantasai** [comment] 2017-01-03 11:24
Tabs are defined to be rendered as a shift in position, not as a grapheme affected by `letter-spacing` or `word-spacing`. https://drafts.csswg.org/css-text/#white-space-phase-2

>Each tab is rendered as a horizontal shift that lines up the start edge of the next glyph with the next tab stop. Tab stops occur at points that are multiples of the tab size from the block’s starting content edge.

I can clarify in `letter-spacing` that tabs are not affected, if that is a point of confusion.

dbaron wrote:
> I don't understand the motivation for accounting for word-spacing, so it's hard for me to tell what was intended. What is accounting for word-spacing supposed to make things line up with?

Spaces. Spaces are increased by `word-spacing`, so for tab stops to line up with multiples of spaces, they must account for the width of the space, plus `letter-spacing`, plus `word-spacing`.

**Comment by dbaron** [comment] 2017-01-03 18:15
Are there implementations that implement tabs in preformatted text in terms of that tab stop mechanism?

It's not clear to me how it's supposed to interact with changes of font, <code>tab-size</code>, <code>letter-spacing</code>, or <code>word-spacing</code> within a block.  Are tab stops just always recomputed using the local properties, but then measured relative to the nearest block's content edge?

**Comment by fantasai** [comment] 2017-01-04 16:47
`tab-size` is a property of the containing block. If this is a compat problem, that's a separate issue then.

**Comment by fantasai** [comment] 2017-01-10 00:03
Closing the issue, please feel free to re-open if the spec remains unclear

(Wrt tab-size being applied to the containing block, if that's a problem, please file a separate issue on it.)

**Closed by fantasai** 2017-01-10 00:03 UTC
Labels: css-text-3
