### ISSUE TITLE
[css-text-decor] Characters to skip for emphasis marks (text-emphasis)

### ISSUE THREAD

**Issue by fantasai** [w3c/csswg-drafts#839] opened 2016-12-27 15:41 UTC
Opening a placeholder issue to continue any discussion from https://lists.w3.org/Archives/Public/www-style/2015Dec/0184.html and https://lists.w3.org/Archives/Public/www-style/2016Dec/0083.html 

>>> presumably these marks should not be displayed for combining characters either?
>>
>> Actually there was a related discussion raised recently in HTML5 Chinese IG as well. That discussion is about whether emphasis marks should also be skipped for punctuations. JLReq explicitly says emphasis marks are not used for several punctuations (see 3.3.9 note 2), but the spec doesn't have anything around this.
> 
> It was considered [1], but IIRC JLTF wanted us to include all punctuation and make the author do the skipping because "what if the author wants to emphasize that punctuation mark for some reason". Imho this is an uncomfortable default for the Web because it means most publications need to do a lot of markup mangling to get this to work right... but we ended up deferring to that opinion. Maybe Koji remembers more, I can't seem to find records of the discussion.
> 
> See http://drafts.csswg.org/css-text-decor-4/#text-emphasis-skip for what was our last set of thoughts on the issue.
> 
> I'm happy to re-open the discussion if there's more input to consider.

For background, see https://lists.w3.org/Archives/Public/www-style/2016Dec/0083.html https://drafts.csswg.org/css-text-decor-4/#text-emphasis-skip and view-source:https://drafts.csswg.org/css-text-decor-4/Overview.bs

**Comment by fantasai** [comment] 2018-02-08 17:20
Discussed with i18n, conclusion is that skipping punctuation by default would be better. Question to CSSWG: can we make that happen.

**Comment by aphillips** [comment] 2018-02-09 16:21
(on behalf of I18N WG)

As @fantasai mentions, we discussed this yesterday in [teleconference](https://www.w3.org/2018/02/08-i18n-minutes.html). I drew an action to respond to this issue.

According to JLREQ (and other information that we have gathered, such as information about Chinese and Korean), the normal behavior for emphasis marks would be to skip punctuation marks. Ideally, the default mode for emphasis marks would correspond to their normal usage. 

@fantasai reports that text-decoration Level 4 is expected to include tailoring for emphasis marks to add (or remove) emphasis from punctuation.

She also reports that you discussed this with JLTF and they requested the current behavior (not skipping punctuation) because "what if you wanted to emphasize those characters for some reason". That is a rational point of view, but means that, to get the normally expected behavior, one must modify the markup and/or styling and it's a little inconvenient (imagine having to put closing and opening `em` tags around a comma in the middle of a sentence).

The members present in the call felt that skipping the punctuation would be better, since it gives casual users the expected behavior, provided that exceptional behavior is provided for in Level 4 fairly soon.

If the current behavior were kept, then Level 4 should add the punctuation skipping override fairly soon and the default stylesheet should adopt that. Either approach is equivalent, but it would be better, in our opinion, to adopt the "normal" styling now.

**Comment by xfq** [comment] 2018-03-08 11:55
The initial value of [text-emphasis-skip](https://drafts.csswg.org/css-text-decor-4/#text-emphasis-skip) needs adjusting too.

**Comment by fantasai** [comment] 2018-03-09 06:49
Yes, you are right. Updated L4 spec as well.

**Comment by xfq** [comment] 2018-03-12 15:04
I just submitted a PR to update the L4 spec: https://github.com/w3c/csswg-drafts/pull/2433

(Personally I would like to reduce the duplication of the same info in the description of two different properties in the future.)

**Comment by fantasai** [comment] 2018-05-21 01:36
OK, I think this is settled now. r=@frivoal with high-level advice from Kobayashi-sensei
Agenda+ to confirm closing this issue.

**Comment by frivoal** [comment] 2018-05-21 02:33
@fantasai and I have been through Kobayashi-sensei's essay on this topic, so I think we're covered, but for archival purposes, here's the original:

> 圏点と句読点の関係です．これは，あまり明確でないことが問題かもしれません．
> 
> まず，句点類（cl-06），読点類（cl-07），始め括弧類（cl-01）及び終わり括弧類（cl-02）には，日本語の書籍などでは，付けた例は少ないでしょう．ただし，DTPなどでは，読点類（cl-07）をまたいだ文字列では，つい読点類（cl-07）を含めて文字列を選択し，指定するので，誤って付けてしまったと考えられる例はあります．
> 
> 中点類（cl-05）は，付けた例が少ないが，付けた例もあります．
> 
> アラビア数字や欧字にも，一般に付けないのですが，最近は簡単に付けられることから，何度か目にしています．（活字組版では，こうしたものに圏点を付けることは困難であった．）
> 
> それでは，なぜ句読点などには付けないか？という問題です．これは慣習としかいえません（私自身，その理由は聞いたことがありません）．しかし，次のようにいくつかの理由は想定できます．
> 
> 圏点は，漢文（かんぶん，kanbun composition，JLReqの定義に説明あり）から始まったようで，漢文には，そもそも句読点がなかったということもあり，句読点などに圏点を付ける必要がなかった．
> 
> 圏点は，文章に付けるというよりは，文章の一部である語句に付けるケースが多かった．
> 
> 句読点などは，行の調整処理でアキが詰められることも予想され，字幅が全角でないものには，活字組版では圏点は付けにくかった．圏点は，ルビと異なり，一般に字詰め方向の字幅は，親文字と同じサイズの全角のものが使用されていた．
> 
> 上とも関係するが，行の調整処理でアキが詰められて句読点などに圏点が付くと，その漢字や仮名に付く圏点と，詰められた句読点に付く圏点の字間が乱れるということで，これは，あまり見た目がよくないという面もあります．
> 
> もう1点，句読点や括弧類は，文字の外枠の中央に文字面が配置されていないので，その後ろ，又は前に空白を持っています．こうしたものに圏点を付けると，句読点や括弧類と圏点の位置関係のバランスが悪いというのも，これらに圏点を付けないとことにつながったように思います．
> 
> 次に著者と圏点の関係です．一般論でいえば，著者は圏点を句読点に付けるかどうかは意識していないと思います．強調したい範囲を著者が指定した場合，編集者が句読点には付けないようにしているということが多いと思います．
> 
> 最後に，文章を読む面から句読点に圏点を付けるかどうかを考えてみると，著者が意識していないように，句読点に圏点を付けるかどうかで，意味が変わる，あるいは誤解させるということは，あまり考えられないと思います．
> 
> 最後に，やや細かい話です．
> 
> ルビが付いた語句に圏点を付けたいケースはあります．こうした場合，経験のある編集者は，強調の方法はいくつかあるので，別の強調の方法を考え，そのように処理したものです．例えば，〈（U+3008）と〉（U+3009）でくくるという方法を選びます．
> 
> でも，最近は，こうしたことを考慮する，あるいは句読点に圏点を付けないという認識も，すこしずつ少なくなってきているのではとも思っています．
> 
> つまり，この問題は，あまり厳密には考えようがない問題でもあるかと思います．
> 
> 以上，ご参考まで．

**Closed** 2018-05-29 20:16 UTC
Labels: Closed Accepted by CSSWG Resolution, css-text-decor-3, css-text-decor-4, i18n-clreq, i18n-comment, i18n-jlreq
