### ISSUE TITLE
[css-sizing-3]: `calc-size` links to itself

### ISSUE THREAD

**Issue by keithamus** [w3c/csswg-drafts#11101] opened 2024-10-28 17:44 UTC
The definition for `calc-size()` says "See <calc-size()>". Clicking on this appears to do nothing because it is a link to the same definition. 

I think this should resolve to css-values-5. Removing the `<dfn>` and adding `spec:css-values-5; type:function; text:calc-size()` to `link-defaults` seems to fix this but I don't think that's the right change to make. Guidance appreciated here.

**Comment by cdoublev** [comment] 2024-10-29 07:31
Global CSS types are often defined for a property, a function, a parent CSS type, etc... using `<dfn for=context>`. Here the author probably wanted a definition *for* the context of sizing properties, as indicated by the parent `<dl>`:

  > `<dl dfn-type=value dfn-for="width, min-width, max-width, height, min-height, max-height">`

So this `<dfn>` probably cannot be removed. I do not know how to fix this circularity though.

Duplicate of #10938.

**Closed by cdoublev** 2024-10-29 07:31 UTC
Labels: css-sizing-3, editorial
