### ISSUE TITLE
[cssom-view] draft html is not published

### ISSUE THREAD

**Issue by michaelwasserman** [w3c/csswg-drafts#7011] opened 2022-02-03 19:04 UTC
I would expect https://drafts.csswg.org/cssom-view/ to contain an html file for https://drafts.csswg.org/cssom-view/Overview.bs but none exists. It seems to be available sometimes, but more often not.

This yields broken links in the [TR](https://www.w3.org/TR/cssom-view-1/)'s [link to the editor's draft](https://drafts.csswg.org/cssom-view/) and from other bikeshed drafts referencing e.g. {{Screen}}.

This might help diagnose html generation errors: https://drafts.csswg.org/bikeshed/cssom-view-1/

**Comment by michaelwasserman** [comment] 2022-02-03 19:05
FYI: @smfr @emilio

**Comment by tabatkins** [comment] 2022-02-03 19:07
dupe of #6528

**Closed by tabatkins** 2022-02-03 19:07 UTC
