### ISSUE TITLE
[selectors] Restrict :is/:where/etc based on context

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#5581] opened 2020-10-04 17:41 UTC
By default, :is() (and friends) accept complex selectors. However, we likely want to narrow what is allowed inside :is() based on the context where it's used. For example, for :host(:is(...)), only compound selectors should be allowed, and for ::before:is(...), only user action pseudo-classes.

**Comment by Loirooriol** [comment] 2020-10-04 18:13
Seems a duplicate of #5093

**Closed by Loirooriol** 2020-10-04 18:13 UTC

**Comment by andruud** [comment] 2020-10-04 18:16
Ah, thank you @Loirooriol
