### ISSUE TITLE
[css-fonts] incorrect links (to descriptor instead of property descriptions)

### ISSUE THREAD

**Issue by jfkthame** [w3c/csswg-drafts#2279] opened 2018-02-06 17:49 UTC
In §7.2. Feature and variation precedence,[1] a number of instances of font *properties* in steps 7 through 10 are linked to the corresponding *descriptor* definitions instead. (This affects mentions of font-variant, font-feature-settings, and font-variation-settings.)

Also, references in step 2 to the font-weight, font-stretch, and font-style properties are not linkified, although they are colored blue.

Actually, I think the problem is wider than just this section: a small sampling elsewhere in the spec looks like many (all?) occurrences of these *properties* (font-feature-settings, font-variation-settings, font-variant) are linked to the *descriptor* definitions instead. I guess having descriptors and properties with the same name may be confusing a process somewhere.

[1] https://drafts.csswg.org/css-fonts-4/#feature-variation-precedence

**Comment by litherum** [comment] 2018-02-06 18:53
Oh, if I understand you correctly, this is a problem with Bikeshed that @tabatkins says he will fix. AFAIK there is no way to tell Bikeshed that "this should be a link to the descriptor" vs "this should be be a link to the property of the same name."

**Comment by svgeesus** [comment] 2018-02-06 21:20
I thought that was fixed, and uses `for`.
https://tabatkins.github.io/bikeshed/#ambi-for
https://tabatkins.github.io/bikeshed/#dfn-for

**Comment by svgeesus** [comment] 2018-02-06 22:30
> Any of the above shorthands (besides the biblio varieties) that encompass multiple types can have their type specified explicitly, by appending the type and separating it with a !!, like the following to indicate that you want the IDL attribute named "bar", rather than the dictionary member of the same name:
> {{bar!!attribute}}
> https://tabatkins.github.io/bikeshed/#autolinking

So instead of 'font-family' we can use 'font-family!!property' or 'font-family!!descriptor', it seems. Testing some more locally.

**Comment by svgeesus** [comment] 2018-02-06 22:50
OK, somewhat better now. Properties are now links and point to the right property definition; except font-variant points to Fonts 3. 

Still a bunch of Bikeshed errors on the console though. It doesn't like giving a type inside &lt;&lt; >>

**Comment by litherum** [comment] 2018-03-06 10:24
So can I close this?

**Comment by litherum** [comment] 2018-03-06 10:27
duplicate of https://github.com/w3c/csswg-drafts/issues/1585

**Closed by litherum** 2018-03-06 10:27 UTC
Labels: css-fonts-4
