### ISSUE TITLE
[css-overflow] Ability to ignore specific descendants when generating scrollbars

### ISSUE THREAD

**Issue by LeaVerou** [w3c/csswg-drafts#8400] opened 2023-02-05 00:36 UTC
Problem: Positioned box "decorations": ribbons, complex shadows (that require pseudo-elements) and other ornamental elements or pseudo-elements. causing scrollbars to be generated when they should be ignored when scrollbars are calculated.

E.g. for the ribbon [here](https://designftw.mit.edu/) I had to use `position: fixed` and JS to hide it when the page is scrolled.

<img width="167" alt="image" src="https://user-images.githubusercontent.com/175836/216785662-1bfa04f4-20ed-4456-b983-96ce3445e5de.png">

And in other cases even `position: fixed` doesn't help, and the decoration still generates scrollbars, with no straightforward workaround (complex workarounds include wrappers with `overflow: hidden` and fragile sizing).

Perhaps a property that basically says "ignore this element when calculating scrollbars", which would only apply to positioned elements only, syntax TBB. @fantasai @frivoal thoughts?

**Comment by ydaniv** [comment] 2023-02-05 15:22
Another common use case is for content that's animated into view when it's fold enters the viewport. So if that element would naturally be expected not to generate scrollbars, it may generate them on the beginning of the animation, and avoiding it in a generic way is a hassle, and requires fixing the problem outside the element's scope. 
So another interesting point is if it could be animatable discrete.

**Comment by LeaVerou** [comment] 2023-02-05 18:00
> Another common use case is for content that's animated into view when it's fold enters the viewport. So if that element would naturally be expected not to generate scrollbars, it may generate them on the beginning of the animation, and avoiding it in a generic way is a hassle, and requires fixing the problem outside the element's scope. So another interesting point is if it could be animatable discrete.

Thank you, I have come across this quite a lot as well!

**Comment by tabatkins** [comment] 2023-02-28 18:36
Yeah, this appears to be a dupe of #8361, which came in slightly earlier. @LeaVerou, mind closing this in favor of the other issue?

**Closed** 2023-02-28 18:40 UTC
Labels: css-overflow-4, Agenda+
