### ISSUE TITLE
[css-positioning-3] Sticky positioning for table elements

### ISSUE THREAD

**Issue by Nadya678** [w3c/csswg-drafts#2155] opened 2018-01-01 08:51 UTC
https://www.w3.org/TR/css-position-3/#sticky-pos

The sticky will not work with `<thead/>`, `<tr/>` (table-rows), `<th/>` etc. **I need it here!** For always visible header if i scroll table right or down. Without any script. This will very helpful a big tables.

> The effect of position: sticky on table elements is the same as for position: relative

In my opinion this sentence should be removed and the behaviour for all elements (and display values) should be the same.

**Comment by SelenIT** [comment] 2018-01-02 17:19
Please refer to the [current Editor's draft of the spec](https://drafts.csswg.org/css-position-3/#sticky-pos) since the published version you referred to may be rather outdated.

AFAIK, the spec doesn't say that either relative or sticky position _should_ not work for table internal elements. On the contrary, it [specifies their behavior for relative positioning](https://drafts.csswg.org/css-position-3/#valdef-position-relative), and implies that sticky positioning for them should behave similarly (i.e. only for table columns and column groups the positioning should be ignored, other table parts should be offset relatively to their normal position in the table, and cells spanning several rows/columns should be shifted as a whole).

So non-supporting either [relative](https://github.com/w3c/csswg-drafts/issues/1899) or sticky positioning for table parts is just a bug of the browsers. It is already marked as fixed for [Chrome 65](https://bugs.chromium.org/p/chromium/issues/detail?id=702927) and [Firefox 59](https://bugzilla.mozilla.org/show_bug.cgi?id=975644).

**Comment by Nadya678** [comment] 2018-01-04 02:51
Thank you for clearing the problem. Also MDN refers to old specification. 
The table cannot be containing block (ir cannot be a scrollbox but 
```
table{display:block; overflow:hidden}
tbody{display:table} 
th
{
   position:sticky;
   left:0; 
   top:0; 
   right:0; 
   bottom:0
}
```
will work for me after implementation?

**Comment by SelenIT** [comment] 2018-01-04 10:01
Yes, it should work. I just tested [this Codepen](https://codepen.io/anon/pen/VyzOoW) in Chrome Canary 65, and it worked for me (with both `thead` and `tr` elements).

**Comment by Nadya678** [comment] 2018-01-05 12:37
I think the problem is resolved. I have big problems with script version of table headers. The tables are loaded dynamically (XMLHttpRequest) and if the scrollbar appers the header is broken without possibility of use sticky. 

But it is sad, the sticky NEVER will be work in IE11 (Windows 7 and Windows 8.1) users cannot upgrade itt to EDGE. They pay for their system but big "no" from M$ to allow them use EDGE. Disguisting policy of M$...

**Comment by SebastianZ** [comment] 2018-01-06 01:07
> Also MDN refers to old specification.

I've updated the description of `sticky` on MDN to reflect that it also applies to table-related elements.

> But it is sad, the sticky NEVER will be work in IE11 (Windows 7 and Windows 8.1) users cannot upgrade itt to EDGE.

Microsoft offered a free upgrade to Windows 10 for several years (which just ended a few days ago). So people had enough time to make the switch. Anyway, that's off-topic.

Sebastian

**Comment by Nadya678** [comment] 2018-01-07 15:08
>Microsoft offered a free upgrade to Windows 10 for several years.

The Windows 10 is the greatest evil due to privacy policy of this version of system. Please read the Policy prvacy of the M$ with "More" sections.  Better solution is to change IE11 to Moz.

**Comment by jonjohnjohnson** [comment] 2018-08-06 17:15
Guessing this issue can be closed now? As far as implementor direction, it seems table elements can use sticky positioning.

**Comment by SelenIT** [comment] 2018-08-07 08:31
It seems that for some reason Chrome [reverted](
https://bugs.chromium.org/p/chromium/issues/detail?id=702927#c23) their changes for fixing `position:sticky` behavior on `thead` element.

**Comment by tobiu** [comment] 2018-08-09 21:09
I can confirm that position: sticky is broken for Chrome right now.

A quick question if I may: Should position: sticky enable a html table to support sticky column headers (sticked to the top) as well as locked columns (sticked to the left)?

It would be really nice in case there was a way to not use 2 tables and sync their scroll states.

For this use case, the scrollers have 2 issues: 
1) there is a gap of around 10px to the bottom and right (this works in FF)
2) it would be nice if the scrollers would honor the "scrollable" area in a better way for tables with sticky items

I just tested it here:
https://codepen.io/anon/pen/XBojGp

**Comment by jonjohnjohnson** [comment] 2018-08-09 21:43
@tobiu Here is a screencast of your demo in chrome canary 70.0.3516.0 on my macOS 10.12.6 where it shows an implementor allowing sticky positioned elements nested to share the outermost containing block, enabling an "html table to support sticky column headers (sticked to the top) as well as locked columns (sticked to the left)". This shows that you shouldn't need two synced scrollers I believe?

http://cl.ly/0i1w2P0J3x0Q

**Comment by tobiu** [comment] 2018-08-09 21:55
@jonjohnjohnson the demo looks exactly the same to me. If you look close at your video, you will see the scrollbar offset to the bottom and right edge (10-20px i guess), there is no offset for top and left. you do see the full content when you scroll though. This gap is not present in FF.

from an UX perspective it would be nice, if the scrollers would exclude the sticky elements inside tables completely (e.g. the x-scrollbar would start after the last locked column).

Best regards and thx for looking into it!

**Comment by tabatkins** [comment] 2020-04-29 00:09
Closing since stickypos does work on internal table elements.

**Closed by tabatkins** 2020-04-29 00:09 UTC
Labels: Closed Rejected as Invalid, css-position-3

**Comment by fantasai** [comment] 2020-04-29 00:13
Follow-up issue in https://github.com/w3c/csswg-drafts/issues/5020
