### ISSUE TITLE
[css-align] fully specify the "Overflow and Scroll Positions" section

### ISSUE THREAD

**Issue by dbaron** [w3c/csswg-drafts#1425] opened 2017-05-20 20:48 UTC
I think the current [Overflow and Scroll Positions section](https://drafts.csswg.org/css-align/#overflow-scroll-position), whose entire normative contents are currently:

> The content distribution properties also affect the initial scroll position, setting it to display the appropriate portion of the scrollable area. In other words, the scrollable overflow region is aligned relative to the viewport as specified by the content distribution properties. Additionally, so that the content remains in the scrollable overflow region in order to be scrollable, the scroll and auto values of overflow trigger safe content alignment always.

is insufficient for what it's trying to specify.

I think there are a number of issues here:
* In the first sentence, "also affect" doesn't say *how* it affects the initial scroll position.  For example, what does baseline do?  What does center do?  Do `safe` and `unsafe` influence the decision?
  * I'd note that I think it's a bad idea for the initial scroll position not to be at the edge of the scrollport, since existing scrolling user interfaces can make it hard to get back to a position that's not at the edge.
* The second sentence appears to confuse [viewport](https://drafts.csswg.org/css2/visuren.html#viewport) and [scrollport](https://drafts.csswg.org/css-overflow-3/#scrollport).
* The third sentence appears to completely contradict the first two, at least as I understand them.  In other words, there only exists an initial scroll position when the content overflows, so this forces content-alignment on anything that is scrollable with more than one possible scroll position to be content-aligned to `start`.  That, in turn, seems to imply that the initial scroll position would always be at the start edge like it's always been.

**Comment by tabatkins** [comment] 2017-06-21 22:01
1. It has the effect stated - it aligns the scrollable overflow region within the scrollport, for the purpose of finding the initial scroll position.  You appear to be reading this as talking about, more or less, where the `scrollOffset=0` position is - it's not.  What we're trying to describe is what, for example, Chrome does for an overflowing column-reverse flexbox - it starts the element scrolled down to the bottom.

There's def some cleanup we need to do here, tho - fantasai and I are discussing this now.

2. Yeah, it does. Will fix.

3. I think this is also caused by your confusion regarding our use of "initial scroll position" vs "0 scroll offset".  But also: we've some cleanup to do here.

**Comment by fantasai** [comment] 2017-06-21 22:41
Okay, we've edited the section to hopefully be more precise. Let us know if you have any further concerns! https://drafts.csswg.org/css-align/#overflow-scroll-position

**Comment by dbaron** [comment] 2018-07-05 01:14
The section appears to be unchanged from what I originally quoted.

**Comment by fantasai** [comment] 2018-07-05 03:53
:(

**Comment by tabatkins** [comment] 2018-08-09 23:34
> I think this requires somewhat careful review to see if this definition influences the way scrollTop etc. are reported.

On further review, yeah, our text was somewhat wrong.  In particular, it was setting the origin incorrectly if the content *wasn't* big enough to actually trigger overflow.

All in all, the previous text's attempt to align and then hack scroll coordinates back to being correct was weird and hard to understand.  So we rewrote it again!

This time the text is more straightforwardly stating what's intended: that aligning an overflowing scroll container should show the same content as it would if it weren't scrollable, but that it should allow scrolling to see all the content it should normally be able to show.  We also added a note capturing an important detail: that this *isn't* guaranteed to be identical to just aligning the scroll thumb in the scroll bar (tho it will *often* be identical).

Finally, we realized that doing this alignment (particularly for end-alignment) might be impossible with the current definition of scrollable overflow region, due to end-side padding being excluded in confusing circumstances. So, we defined that the container's end-edge padding is included as needed for end-alignment, and specified that this occurs for all non-normal alignment values for consistency. This also allows us to address the repeated requests for such padding behavior from the web author community without fear of Web-compat issues.

**Comment by fantasai** [comment] 2018-08-09 23:35
Agenda+ to discuss https://github.com/w3c/csswg-drafts/issues/1425#issuecomment-411930443

**Comment by dbaron** [comment] 2018-08-15 23:51
I think the first paragraph of the new text is mostly reasonable.

However, it contains the text:

> initially-visible content of the scroll container is the same as it would be if it were not a scroll container

which seems problematic since scrollbars can remove some of the available space for the content, which means that the initially-visible content actually *can't* be the same in some cases.  I think, for example, that if you're doing

```css
align-content: end;
justify-content: end;
overflow: scroll;
```

then you want the scroll-position all the way at the end, not one scrollbar width short of all the way to the end as the spec currently (maybe) defines (at least if you assume that you want the *position* of the content to match where it would be if it were not a scroll container).

I suspect this means you should define things in terms of alignments -- particularly for center.

-----

I don't think I actually understand what the second normative paragraph is trying to say.

**Comment by fantasai** [comment] 2018-08-24 20:48
@dbaron OK, adjusted the wording a bit. https://drafts.csswg.org/css-align-3/#overflow-scroll-position Does it make sense now?

**Comment by tabatkins** [comment] 2018-08-24 21:30
And adjusted it a bit more.

**Comment by fantasai** [comment] 2018-10-08 21:57
Closing out this issue. (We still need to make some improvements on the illustrations aka whiteboard drawings which should be SVG with nice captions, but that's a follow-up issue.)

**Closed by fantasai** 2018-10-08 21:57 UTC
Labels: Closed Accepted by CSSWG Resolution, Commenter Response Pending, css-align-3
