### ISSUE TITLE
[css-flexbox] should a definite flex-basis always make the main size be definite?

### ISSUE THREAD

**Issue by cbiesinger** [w3c/csswg-drafts#4311] opened 2019-09-16 02:28 UTC
https://drafts.csswg.org/css-flexbox/#definite-sizes

Currently, a main size is only made definite if the flex container has a definite height.

However, browsers do not quite implement that. See https://crbug.com/1003506 for some discussion, but basically:

```html
<div style="display: flex; flex-direction: column; width: 100px; background: yellow;">
  <div style="height: 100px; flex: 1 1 auto; background: green; min-height: 0;">
    <div style="height: 100%; background: red;"></div>
  </div>
</div>
```

An element that would have a definite height outside of flex now suddenly has an indefinite height when put in a flexbox, because it's flexible (at least according to the spec, not in impls).

- Should that change?
- Would implementing this spec-compliant be web-compatible?

Also note that Chrome currently resolves percentages only if the main size property is definite; a definite flex-basis is not enough. That should probably be changed.

@dholbert @fantasai @tabatkins

**Comment by fantasai** [comment] 2021-07-15 22:50
The main reason we restrict percentages from resolving in various indefinite circumstance is that, at least historically, it was hard to do. Afaict, generally authors prefer if percentages resolve. So if implementations are resolving in more cases than specced here... seems like we should just update the spec to match implementations?

Agenda+

**Comment by dholbert** [comment] 2021-07-21 16:49
I had misremembered that we implemented the "fully inflexible" requirement here, but it seems that in fact we weren't able to do so because it's not web-compatible, as noted in these code-comments:
https://searchfox.org/mozilla-central/rev/699174544b058f13f02e7586b3c8fdbf438f084b/layout/generic/nsFlexContainerFrame.cpp#2167-2173
https://searchfox.org/mozilla-central/rev/699174544b058f13f02e7586b3c8fdbf438f084b/layout/generic/nsFlexContainerFrame.cpp#2130,2133-2135
and this chromium issue:
https://bugs.chromium.org/p/chromium/issues/detail?id=1003506#c7

So I agree that we should just remove the "fully inflexible" restriction here, to match implementations & webcompat requirements (which are what caused this implementation behavior).

**Comment by dholbert** [comment] 2021-07-21 16:54
In the meeting, I think we were pretty much ready to resolve here, except for my pushback.

I'm now withdrawing my pushback & am happy to resolve on removing the fully-inflexible requirement.

One observation, though - when we update the spec text for this, we probably want to write the amended "fully inflexible" condition as actual authoritative spec-text rather than in a Note. (The spec-text under discussion here is currently a "Note.")

**Comment by davidsgrogan** [comment] 2021-07-24 23:20
This change is good.

Compat will probably be ok, especially if Blink and Gecko sync up shipping this change.

To be clear, this **will** be a change for Blink. Blink's existing behavior is intentional that the red block's percent height resolves in the original test case [above](https://github.com/w3c/csswg-drafts/issues/4311#issue-493820930), but that giving the item `height:auto` and `flex-basis:100px` would make it not resolve. This is intentional because my understanding of https://drafts.csswg.org/css-flexbox/#definite-sizes and the prose in https://drafts.csswg.org/css2/#the-height-property indicates this behavior complies with the current specifications.

> One observation, though - when we update the spec text for this, we probably need to write the amended condition as actual authoritative spec-text rather than in a Note.

+1.
I further [contend](https://github.com/w3c/csswg-drafts/issues/4305#issuecomment-859122600) that the Note even as written today is inaccurate. Removing the Note and specifying this new behavior as normative would be **wonderful**. I think it would also let us close [issue 4305](https://github.com/w3c/csswg-drafts/issues/4305).

Last thing. I'm a *little* worried about performance. The original testcase has `min-height: 0`. But most flex items on the web will have to rely on automatic minimum sizing like the case below. So in the below case Blink will lay out the item with an indefinite height to get its [content size suggestion](https://drafts.csswg.org/css-flexbox/#content-size-suggestion), which will be 0. Then Blink will lay out the item post-flexing with a definite height which will cause the subtree to need a second layout, doubling layout time. If this pattern is nested the slowdown gets exponential. Would this cause any potential perf regressions for Gecko?

```html
<div style="display: flex; flex-direction: column; width: 100px; background: yellow;">
  <div style="flex: 1 1 100px; background: green;">
    <div style="height: 100%; background: red;"></div>
  </div>
</div>
```
Anyway, I haven't dug deeper on this potential performance issue, so if no one else is worried about performance, we shouldn't block this change just because of that.

**Comment by dholbert** [comment] 2021-07-29 20:49
> Compat will probably be ok, especially if Blink and Gecko sync up shipping this change.
> [...]
> Would this cause any potential perf regressions for Gecko?

I believe Gecko is already shipping the proposed behavior -- if there's a definite flex-basis, then we treat that as making the resolved main size definite.

>  To be clear, this **will** be a change for Blink. Blink's existing behavior is intentional that the red block's percent height resolves in the original test case [above](https://github.com/w3c/csswg-drafts/issues/4311#issue-493820930), but that giving the item `height:auto` and `flex-basis:100px` would make it not resolve.

Interesting! That seems like an odd inconsistency which is nice that we can resolve here. :)  (It seems quite weird to condition on the definiteness of the specified `height` in that example, since the specified `height` is otherwise ignored for the purpose of computing the actual height [aside from indirectly influencing the resolved automatic minimum height].)

FWIW, Gecko treats the two scenarios the same (`flex-basis:100px;height:auto` and `flex-basis:auto;height:100px`), from the perspective of this issue -- we treat the flex item as having a definite height since the flex basis is definite in both cases.

**Closed** 2021-08-10 21:58 UTC
Labels: css-flexbox-1

**Comment by tabatkins** [comment] 2021-08-10 23:13
All right, we've made a handful of edits here.

First, we rephrased the definition of "main size" a little, mostly for clarity, but added a line that makes it clear that the post-flexing main size is used when any layout algo is asking for the "used width" or "used height" (as appropriate). Small detail, but tied into this topic:

> The main size of a flex container or flex item refers to its width or height, whichever is in the main dimension. Its main size property is either its width or height property, whichever is in the main dimension. Likewise, its min and max main size properties are its min-width/max-width or min-height/max-height properties, whichever are in the main dimension, and determine its min/max main size.
> In flex layout, the main size is controlled by the flex property rather than directly by the main size property.
> 
> Note: This means any references to a flex item’s used size in the main dimension (width, height, inline size, block size) refers to its post-flexing main size.

Then we addressed the main topic, ensuring that a definite flex basis is *always* treated as definite:

> * If the flex container has a definite main size, then the post-flexing main sizes of its flex items are treated as definite.
> 
> * If a flex-item’s flex basis is definite, then its post-flexing main size is also definite.

----

One side-issue that showed up in this thread was some minor confusion about applying CSS2 layout definitions, which explicitly reference the 'width' or 'height' properties' computed values for certain things, when for a flex item it's intended that you pay attention to the flex-basis instead. We're not sure how to actually fix this without going in and editting CSS2 in an invasive way and making it reference flexbox. :/ Hopefully it's okay without that clarification?  (We can't just say "whenever another spec referenced the main size property, use the flex-basis instead", because things like inheritance do need to actually get the value of the 'width' or 'height' property...)

**Comment by tabatkins** [comment] 2021-09-10 23:16
As far as I can tell, this is already tested by <https://github.com/web-platform-tests/wpt/blob/master/css/css-flexbox/percentage-heights-003.html>
