### ISSUE TITLE
[css-color-4] The given channel is multiplied by the given value. What does it mean?

### ISSUE THREAD

**Issue by Semigradsky** [w3c/csswg-drafts#1930] opened 2017-11-03 14:43 UTC
https://drafts.csswg.org/css-color/#hsl-hwb-adjusters
> If the operator is *, the given channel is multiplied by the given value.

There is example of usage in spec: `lightness(*150%)`.

When I write
```css
color(hsl(0, 25%, 50%) lightness(*150%))
```
it should be the same as
```css
hsl(0, 31.25%, 50%)
```
?

**Comment by tabatkins** [comment] 2019-10-25 20:07
Yes, that was indeed the intended behavior.

(This section has since been dropped from Color 4 tho, so I'm closing this issue.)

**Closed by tabatkins** 2019-10-25 20:07 UTC
Labels: css-color-4

**Comment by tabatkins** [comment] 2019-10-25 20:08
(Sorry, I misread the number: `37.5%` would be the correct value, as that is 25% * 150%.)
