### ISSUE TITLE
[css-color-4] Serialization of named colors

### ISSUE THREAD

**Issue by GPHemsley** [w3c/csswg-drafts#7870] opened 2022-10-12 04:50 UTC
The spec says that [named colors](https://w3c.github.io/csswg-drafts/css-color-4/#serializing-sRGB-values) (including [`transparent`](https://w3c.github.io/csswg-drafts/css-color-4/#serializing-other-colors)) resolve to their `rgb()`/`rgba()` values. However, it appears that Firefox, Chrome, and Edge, at least, serialize to their literal (lowercase) names.

Should the spec be changed?

**Comment by cdoublev** [comment] 2022-10-12 10:06
You might be interested by the comments starting from this https://github.com/w3c/csswg-drafts/issues/1004#issuecomment-1061910466.

**Comment by GPHemsley** [comment] 2022-10-13 00:41
> You might be interested by the comments starting from this [#1004 (comment)](https://github.com/w3c/csswg-drafts/issues/1004#issuecomment-1061910466).

@cdoublev I am indeed. You're always a step ahead of me. :)

Can't say I understand anything any better, though. :/

**Comment by cdoublev** [comment] 2022-10-13 04:12
Yeah, it gives me a headache each time I try to understand how color serialization is defined. The simple answer is that browsers do not always serialize in a conforming way and I think serialization does not have a high priority, be it for browser interoperability or spec authors. I understand it since it is not a feature for end users.

With that said, two people asking the same question may be a sign that the spec can be improved. The part you are linking to defines that a named color is derived from a computed value, but `style.color` (specified value) is not. Why would it be required to serialize a named color as part of a specified value, to `rgb()`? I have learned (this should be defined somewhere, imo) that a specified value is meant to represent the value as specified by its author + simplifications from tokenization (lowercase keywords, etc).

Good luck with your WPTs! =)

**Comment by svgeesus** [comment] 2022-10-13 16:35
I discussed a similar issue with @emilio at TPAC and the problem is that most, but not all, of [to serialize a CSS value](http://w3c.github.io/csswg-drafts/cssom-1/#serializing-css-values) for colors moved to CSS Color 4. The part that remains, and thus makes reading CSS Color 4 about serialization, is:

> If [<color>](https://w3c.github.io/csswg-drafts/css-color-4/#typedef-color) is a component of a **specified** value, then return the color as follows:
>
> - If the color was **explicitly specified** by the author, then return the original, author specified color value.
> - Otherwise, return the value that would be returned if the color were a component of a computed value.

That needs to be moved over; in addition, the rule in CSSOM does not reflect what browsers do and needs to be amended to 

> - If the color was **explicitly specified** by the author _as a named color_, then return the original, author specified color value folded to ASCII-lowercase.

**Comment by GPHemsley** [comment] 2022-10-13 22:35
Ah, I was suspecting that the **keyword** rule may also have been coming into play:

> **keyword**
> &rarr; The keyword [converted to ASCII lowercase](https://infra.spec.whatwg.org/#ascii-lowercase).

**Comment by svgeesus** [comment] 2022-10-18 16:21
@emilio can you confirm that I remembered correctly? If so I can copy-and-edit the remaining portion of color serialization from CSSOM to CSS Color 4.

**Comment by svgeesus** [comment] 2022-10-18 16:27
Related:

 - https://github.com/w3c/csswg-drafts/issues/7728

**Comment by GPHemsley** [comment] 2022-11-01 05:52
So, if I'm understanding correctly, serialization (of sRGB, anyway) uses the computed value except when it was specified as a keyword, then it uses the (normalized) specified value?

Any update on the decisions about spec edits? I'm not seeing anything in the minutes beyond publishing a new draft.

**Comment by emilio** [comment] 2022-11-09 17:14
Yeah, Chris's comment is right. The only explicitly preserved thing for srgb colors is the keyword.

But it needs to be recursive (e.g., `color-mix(red, blue, ..)` should use `red` / `blue`. It's not necessarily the computed value for all colors, depending on how / when some of the new functions compute.

**Comment by emilio** [comment] 2022-11-09 17:51
That's what I'm saying right? Everything except the keyword is _not_ preserved :)

**Comment by svgeesus** [comment] 2023-01-14 15:05
@GPHemsley how is the spec looking now? In particular [14.1. Resolving sRGB values](https://drafts.csswg.org/css-color-4/#resolving-sRGB-values) and [15.2. Serializing sRGB values](https://drafts.csswg.org/css-color-4/#serializing-sRGB-values)

In general I am going through the spec to ensure that each syntactic form of `<color>` defines a specified value, as well as computed; and in general changing serialization to cover both specified and computed value serialization.

**Comment by svgeesus** [comment] 2023-01-14 15:17
This was also discussed in 

 - https://github.com/w3c/csswg-drafts/issues/7728

**Comment by cdoublev** [comment] 2023-01-15 13:26
> **15.2. Serializing sRGB values**
>
> [...]
>  
> When serializing the value of a property which was set by the author to a **CSS named color**, therefore, for the specified value, the (all lowercase) named value is retained.

`<system-color>`, `<deprecated-color>`, `currentColor`, `transparent`, as components of a speficied value, also serialize to the (all lowercase) named value in Chrome/FF.

I do not understand whether `transparent` should serialize to the color name or rgb() from the following:

  > **15.6. Serializing other colors**
  >
  > This applies to `transparent` and `currentcolor`.
  >
  > The serialized form of these values is derived from the computed value and uses ASCII lowercase letters for the color name.
  >
  > The serialized form of `transparent` is the string `rgba(0, 0, 0, 0)`.
  >
  > The serialized form of `currentColor` is the string `currentcolor`.

The following:

  > During serialization, any missing values are converted to 0.

contradicts this:

  > If a color with a missing component is serialized or otherwise presented directly to an author, then for legacy color syntax it represents that component as a zero value

**Comment by svgeesus** [comment] 2023-01-17 13:07
The spec [already covers the specified value of `transparent`](https://drafts.csswg.org/css-color-4/#resolving-other-colors) (but as it is an sRGB color it should be moved to that section):

> The specified value of [transparent](https://drafts.csswg.org/css-color-4/#valdef-color-transparent) is "transparent" while the computed and used value is [transparent black](https://drafts.csswg.org/css-color-4/#transparent-black).

**Comment by cdoublev** [comment] 2023-01-19 20:07
Dealing with specified values in *14. Resolving `<color>` Values* confuses me. 

I would not expect a specified value to resolve. I would expect it to remain (close) to the (tokenized) value as specified by its author. I would only expect *14. Resolve `<color>` Values* to define any transformation on the specified value to resolve the computed value, and any transformation on the computed value to resolve the used value.

In my opinion, for specified value:

  1. `<system-color>` or `<deprecated-color>` should also serialize to the lowercase color name, however I think lowercase color keywords (`<named-color>`, `<system-color>`, `<deprecated-color>`, `transparent`, `currentcolor`) already stems from *serializing a keyword* (CSSOM), therefore it is not strictly required to be defined in CSS Color
  2. mapping `<percentage>` to `<number>` should be defined in *15. Serializing `<color>` Values*

2 is not required for specified values, but this is what browsers are currently doing. Obviously, if `<percentage>` should be mapped to `<number>` for resolved values and when serializing a specified value, it can be done at parse-time for specified values, instead of at serialization time. 

Nevertheless it would be less confusing to define it in *15. Serializing `<color>` Values*. I think there are precedents for this in other specs.

**Comment by cdoublev** [comment] 2023-01-20 09:29
I assume this issue is about all color keywords instead of creating a specific issue or adding noise to #8312.

Chrome/FF serialize specified `<deprecated-color>` to lowercase but:

  > User agents must support these keywords, and to mitigate fingerprinting **must map them** to the (undeprecated) system colors as listed below.

ie. mapping is not applied.

  > **14.1. Resolving sRGB values**
  >
  > This applies to: [...] deprecated-colors
  >
  > If the sRGB color was explicitly specified by the author as a named color, or as a system color, the specified value is that named or system color, converted to ASCII lowercase. [...] Otherwise, the specified, computed and used value is the corresponding sRGB color, paired with the specified alpha channel

This section seems to define that `<deprecated-color>` must serialize to `rgb()`.

  > **14.5. Resolving other colors**
  >
  > This applies to system colors (including the `<deprecated-color>`s), [...]
  >
  > The specified value for each `<system-color>` keyword is the corresponding color in its color space.

This section seems to define that `<deprecated-color>` must serialize to lowercase.

  > **15.2. Serializing sRGB values**
  >
  > The serialized form of the following sRGB values: [...] deprecated-colors, is derived from the specified value. 
  >
  > When serializing the value of a property which was set by the author to a CSS named color, therefore, for the specified value, the (all lowercase) named value is retained. [...] 
  >
  > For all other sRGB values, the specified, computed and used value is the corresponding sRGB value.

This section seems to define that `<deprecated-color>` must serialize to `rgb()`.

**Comment by svgeesus** [comment] 2023-01-20 14:56
The intent is that the specified value is the ASCII-lowercased keyword and the computed value is `rgb()`. But thanks for noticing that

> set by the author to a CSS named color, 

should be expanded to

> set by the author to a CSS named color, system color, deprecated system color or `transparent`

See also
 - https://github.com/w3c/csswg-drafts/issues/8312

**Comment by svgeesus** [comment] 2023-01-31 15:30
@GPHemsley does [Serializing sRGB values](https://drafts.csswg.org/css-color-4/#serializing-sRGB-values) look okay to you now, in terms of your original question? Specifically:

> When serializing the value of a property which was set by the author to a CSS [named color](https://drafts.csswg.org/css-color-4/#named-color), a [system color](https://drafts.csswg.org/css-color-4/#css-system-colors), a [deprecated-color](https://drafts.csswg.org/css-color-4/#deprecated-system-colors), or [transparent](https://drafts.csswg.org/css-color-4/#valdef-color-transparent) therefore, for the [specified value](https://drafts.csswg.org/css-cascade-5/#specified-value), the [ASCII lowercase](https://infra.spec.whatwg.org/#ascii-lowercase) keyword value is retained. For the computed and used value, the corresponding sRGB value is used.

**Closed** 2023-02-08 17:53 UTC
Labels: css-color-4, Closed Accepted by CSSWG Resolution
