### ISSUE TITLE
Feature Request: Collapsing Gaps for Grid Columns with auto or minmax(auto, 1fr)

### ISSUE THREAD

**Issue by enbee81** [w3c/csswg-drafts#10442] opened 2024-06-13 14:06 UTC
When dealing with grid columns that have a width of `auto` or a min-auto width defined within `minmax()`, such as `minmax(auto, 1fr)`, it would be beneficial to have an option for collapsing gaps.

**Proposed Feature:**
Collapsing gaps should function similarly to collapsing margins, where adjacent gaps with an empty column in between would collapse into a single gap.

**Example Scenario:**
Consider the following example: [CodePen Example](https://codepen.io/enbee81/pen/KKLyXwv?editors=1100)

In this example, an image is optional. When the image is missing, the current behavior results in a 4rem gap instead of the desired 2rem gap. Collapsing gaps would address this issue, ensuring the layout remains consistent and visually appealing even when certain elements are not present.

**Comment by Loirooriol** [comment] 2024-06-15 06:49
Duplicate of #5813

**Closed by Loirooriol** 2024-06-15 06:49 UTC
