### ISSUE TITLE
[css-view-transition-2] Should :active-view-transition() without parameter be a valid syntax

### ISSUE THREAD

**Issue by vmpstr** [w3c/csswg-drafts#9627] opened 2023-11-22 17:39 UTC
This came up in discussion of #9546

We currently only allow `*` or a list as valid parameters. Should we also allow no parameter to mean the same thing as the asterisk?

I don't have a strong preference. My weak preference is to keep requiring a parameter. This seems more consistent with things like `:is()` and `:has()` which, AFAIK, do require a parameter. Although, my sense that this is not really a valid precedence.

@fantasai @atanassov

**Comment by noamr** [comment] 2023-11-23 11:56
Duplicate of #9626

**Closed by noamr** 2023-11-23 11:56 UTC
Labels: css-view-transitions-2
