### ISSUE TITLE
[css-flexbox][css-overflow] sub flex with text-overflow, what the best result is?

### ISSUE THREAD

**Issue by Zefling** [w3c/csswg-drafts#6302] opened 2021-05-21 16:36 UTC
Since I never got a response to this bug, lets ask me here.
https://bugzilla.mozilla.org/show_bug.cgi?id=1424201
I was wondering if this was the spec that wanted it, because Firefox and Chrome made the same rendering.

Test: https://bug1424201.bmoattachments.org/attachment.cgi?id=8935710
Actual result in Firefox and Chrome:
![image](https://user-images.githubusercontent.com/3032555/119170208-3940aa80-ba63-11eb-9fb5-d78e13e70eca.png)

In some cases, the inability to nest flexible elements makes the task more complex and forces pruning to be less responsive.

**Comment by Loirooriol** [comment] 2021-05-21 17:29
Seems you want `width: auto; min-width: 0`? https://drafts.csswg.org/css-flexbox-1/#min-size-auto

**Comment by Zefling** [comment] 2021-05-21 17:58
Indeed, it works, but without reading the spec it's impossible to guess this.
Who can find it logical to put `min-width: 0` to force a max size of element?

**Comment by Loirooriol** [comment] 2021-05-21 18:24
Yes, I understand the confusion. I guess this is basically a duplicate of #1865

**Closed by Loirooriol** 2021-05-21 18:24 UTC
