### ISSUE TITLE
[css-images][css-masking][paint] Ambiguities in handling url()

### ISSUE THREAD

**Issue by tabatkins** [w3c/csswg-drafts#383] opened 2016-08-04 23:17 UTC
Back in 2012, roc raised this issue about an ambiguity in handling url()s that might refer to an image or an SVG element reference: https://lists.w3.org/Archives/Public/www-svg/2012Oct/0019.html In particular, giving a url like "mask-image: url(foo.svg#bar)", do we load that as an SVG image with a fragment of #bar, or do we load it as an SVG document and retrieve the `id=bar` element (which might be a `<mask>` element)? This also infects _all_ CSS-`<image>`-taking properties, if we let CSS refer to SVG paint servers.

There was a lot of discussion and seemingly consensus, but nothing ever got formally decided, and several of the affected specs (Images, Masking, etc) weren't edited to take this into account.  Let's fix that!  The conclusion seemed to be:
1. url()s without a fragment are always interpreted as images.
2. url()s with a fragment vary slightly based on property: CSS-defined properties default to interpreting it as an image, while SVG-defined properties default to interpreting it as an element reference.  You can force the image interpretation by instead loading it with `image()`, and the element interpretation by loading it as `element()`.

This means that `background-image` can only refer to a paint server by using `element("foo.svg#bar")`, while `mask-image` can only use an [SVG Stack](https://hofmannsven.com/2013/laboratory/svg-stacking/) by using `image("foo.svg#bar")`.

It also means that in our new attempt to define `fill` and `stroke` for CSS, it'll default fragment urls to being element references, as that's their current behavior in SVG.

Let's please put this 4-year-old issue to rest - I can do the edits to the necessary specs.

**Comment by AmeliaBR** [comment] 2016-08-10 04:21
FYI:

I wrote up [detailed URL-handling rules for SVG 2](https://svgwg.org/svg2-draft/linking.html#processingURL) as part of the overhaul of use-element handling.  I tried to be consistent with CSS/FX specs (particularly Masking) to the extent that they had any guidance, but if you're adding new guidance you may want to review that section and make sure we're still consistent.

Key parts that are relevant to CSS:

- If a property can only accept an image file reference, treat the URL as an image file. Any target fragment is used when rendering that image, but doesn't define a relevant target.

- If a property can accept either an image file or an element reference, and the referenced document can be parsed as a DOM, identify the targetted element to determine if it is a valid reference. If it is not, re-interpret the URL as an image file reference.

- If a property _can_ accept an element reference, and the URL does not have a target fragment, treat it as a reference to the root element when determining if it is a valid reference.  This was based on a long-standing SVG feature request for `<use>` element references (to be able to use a separate SVG without editing it to add an `id` on the root element).  If it is going to be a problem with CSS image properties, we may want to restrict that behavior.

- External resources specified in style properties are fetched with CORS anonymous mode, so there shouldn't be security restrictions on whether the file is parsed as an SVG asset document or an SVG image.

 I was only focusing on `url()` references, not on `image()` vs `element()`, and I was of course only focusing on SVG-defined properties.  

I like the idea of using functions to clarify which way you want to interpret the reference.  I'm slightly concerned about confusion with the other use of `element()`, to the rendered image data from an element in the current DOM.  That's conceptually quite different from referencing an element that describes a graphical effect to apply.

I'm not too keen on having different rules for CSS-defined properties vs SVG-defined properties.  That just seems like grounds for confusion.  I realize there is a theoretical backwards-compatibility issue when allowing SVG paint servers as a CSS image type (a URL that would formerly be interpretted as an SVG image with :target styles now being interpretted as a paint server reference), but I think it is exceedingly rare in practice that :target styles are tied to a paint server element.  The bigger concern would be whether there are substantial performance impacts from parsing the document to identify the element before deciding to treat it as an image: i.e., can implementations switch from "effects" mode to "image" mode without repeating the basic parsing & DOM construction?

**Comment by tabatkins** [comment] 2016-08-17 15:56
Hmm, so yeah, that's rather inconsistent with our earlier plans for CSS. :/ This is gonna need some discussion.

**Comment by astearns** [comment] 2016-08-24 17:09
(removing label because this is already on the TPAC agenda)

**Comment by AmeliaBR** [comment] 2016-08-24 17:18
This is a big, long-term-strategy issue, so I appreciate that you're giving it extra thought.  But FYI, we're aiming to get SVG 2 published as CR before TPAC, so requests to change anything normative will be a bit of a pain after that.

(Oh, and I won't be at TPAC myself, but do ping me if you have any questions about the SVG side.)

**Comment by tabatkins** [comment] 2016-09-19 14:42
After TPAC discussion:
* I'm going to figure out *precisely* what properties are web-compat required to deal with this ambiguous syntax (where a url() can potentially be an image or a resource). I think it's just 'mask' and the 'marker-*' properties. (At least, that's the Chrome ones.)
* For those required-ambiguous properties, we seem to want to go with the "fragment means resource, no-fragment means image" behavior; in particular, implementations do *not* want to load things twice.
* We'll bind ourselves to not introduce ambiguity in the future; properties will be defined to have url() always be an image or ref, and you will have to switch behavior with image() or element(), as appropriate.


Extra detail: it looks like Chrome and Firefox do the split based on "local fragment" vs "otherwise". This means that external links, frag or no, are treated as image. Need more detail. /cc @birtles

**Comment by AmeliaBR** [comment] 2016-09-19 16:35
By the way, one other detail I clarified in the SVG linking spec is that element references can be in any document that can be parsed as a DOM.  I.e., you can link to an element in an HTML doc, not only an SVG doc.  This is of course already supported in all the browsers for same-document references, but it was not defined for external references.

That shouldn't add too much confusion on this issue, but it means that in some cases there won't be a valid image interpretation of a file if the element reference interpretation fails.

**Comment by tabatkins** [comment] 2017-04-19 09:03
We're also gonna go ahead and use local/external as the determiner for the now-ambiguous fill/stroke properties.

And we might be able to do it globally:

* 'background-image' refs that have "url(#foo)" are broken today, I think, and so will continue to be broken even if we treat them as (local) element references.  (Today they refer to the stylesheet's URL, with the hash setting the :target pseudo if it's HTML. The result is then loaded as an image, so it only does something useful in the silly polyglot-html-and-png tricks.)
* `<use>` doesn't currently, in many (all?) browsers, allow external references (despite SVG defining them as allowed), so it should be okay for them to interpreted as an image ref, and thus being invalid and ignored.

**Comment by fantasai** [comment] 2017-04-19 16:00
We didn't actually resolve on anything except mask-image.

**Comment by AmeliaBR** [comment] 2017-04-19 18:05
Wait, does this mean that you won't be able to use SVG mask elements in an external file?  That is tragic.  I'm pretty sure it's supported in at least Firefox, maybe Edge.

`<use>` in external files is supported in all modern browser, provided it is same-origin.  (Cross-origin references aren't supported anywhere, including in the spec.)

**Comment by AmeliaBR** [comment] 2017-04-19 18:08
And for fill & stroke, again references to another file are currently only supported in Firefox, old Presto, and Edge under certain possibly accidental conditions.  But I was *really* hoping that a consistent model with CSS URL references would lead to browsers fixing that.  It seriously limits the ability to create re-usable assets for inline SVG icons if you need to copy & paste (or PHP include, or whatever) your gradients into every page of the website.

**Comment by astearns** [comment] 2017-04-21 00:40
The last resolution is the actual one

**Comment by AmeliaBR** [comment] 2017-04-21 05:52
>The last resolution is the actual one

That would be "RESOLVED: Let's stop resolving" ?

______________________

> For ambiguous cases, UAs SHOULD first see if there's an appropriate reference, otherwise go back and reload as an image

So, does this mean that [my URL-resolution algorithm from SVG 2](https://www.w3.org/TR/SVG2/linking.html#processingURL-validity) is still valid?

Although, now I read it again I realize that I should have been more clear that there are two cases for what to do if a target element can't be located, depending on whether it is a same-file vs different file references.  
- Same file: if the target element doesn't exist or is the wrong type, listen for DOM mutations in case the problem is fixed later. 
- Different file: if the target element doesn't exist or is the wrong type, and property can also accept an image, then re-process the referenced file as an image resource.

**Comment by rocallahan** [comment] 2018-03-28 11:10
I thought I mentioned this on www-style a few years ago but I can't find it now: I had come to the conclusion that the way to resolve this issue was to unify the image-loading path with the element-reference path, basically by eliminating the latter. You would use the image-loading path, and if you happened to load an SVG image and the fragment reference points to the right kind of element, you would use that instead of rendering the image. Document self-references would of course be special-cased. This depends on the browser being able to "punch through" the image-loading-and-rendering abstraction to access the underlying DOM, but I guess that's not a problem in practice.

**Comment by fantasai** [comment] 2019-07-19 23:48
@krit You'll need to update css-masking with something like the following:

```
This property sets the mask layer image of an element. Where:

<mask-reference> = none | <image> | <url>

<image>
	(define image handling here)

<url>
	An [=ambiguous image URL=],
	possibly referencing a <{mask}> element.
	If it references a <{mask}>,
	(mask handling here);
	otherwise,
	it's treated as <<image>>, above.
```

**Comment by fantasai** [comment] 2019-07-20 00:12
OK, Agenda+ to confirm a few things

- Generally-speaking, do we like the new text that was added or are there concerns?
- Were fragment-only URLs specially treated as unambiguous? Or do they also get reloaded as an image somehow? This isn't quite clear from the minutes.
- We resolved on “should”. It's not clear what the UA is supposed to do if it disagrees with the “should”.

**Comment by dirkschulze** [comment] 2019-07-23 04:24
@fantasai I clearly should register @krit :P The change to masking looks fine to me.
@tabatkins I do wonder if there are security implications that were no taken into account in CSS Images. There must have been a reason why the original resolutions suggested to _reload_ the referenced resource as image if there isn't a matching reference element with the ID specified by the fragment. However, I do not remember. **If** at all, a reference would be more problematic than an `<image>`. Right now, the text seems to suggest to "reinterpret" the resource as `<image>`.

**Comment by tabatkins** [comment] 2019-07-23 22:37
The reasoning was because browsers might not be able to "back out" of the resource-loading path to treat it as an image, and vice versa.

**Comment by dirkschulze** [comment] 2019-07-24 06:41
@tabatkins So now it is up to the UA to reload or reuse/reinterpret the resource depending on the UAs own requirements?

Also, agree with @rocallahan that we should load an element reference document with the same restrictions as an <image> and special case self referencing documents (only fragment identifier or URL that points to the same document) in general. That might be part of fetching and using an ambitious URL as <image> might imply it but IMO should be mentioned explicitly.

**Comment by tabatkins** [comment] 2019-07-25 22:03
> So now it is up to the UA to reload or reuse/reinterpret the resource depending on the UAs own requirements?

Yeah.

> but IMO should be mentioned explicitly.

That's now tracked by #4152.

**Closed** 2019-08-13 22:35 UTC
Labels: Closed Accepted by CSSWG Resolution, css-images-3, topic: urls
