### ISSUE TITLE
[css-backgrounds] 'border' shorthand resets 'border-image' but can't set it

### ISSUE THREAD

**Issue by therealglazou** [w3c/csswg-drafts#2108] opened 2017-12-13 17:09 UTC
'border' shorthand resets 'border-image' but can't set it and this is a big problem because this is NOT web authors' expectation. I am getting a lot of user feedback about it, and pretty aggressive I must say. Please see https://lists.w3.org/Archives/Public/www-style/2017Nov/0018.html and thread for more details.

**Comment by ewilligers** [comment] 2017-12-20 17:51
Could we serialize border as  ... / <border-image>  iff <border-image> if not its initial value?

**Comment by therealglazou** [comment] 2017-12-20 17:59
Best use case : a web page (inside an app or a standalone browser) offers to set the borders for an element. The four of them. User sets the four, one by one, to same style color and thickness because that's hyper-common. Expects then a 'border' shorthand to appear. Won't happen because of 'border-image'... Will happen only if 'border-image' is reset too. Most web designers don't use border-image and seen from stats, most ignore it since no-initial/none/inherit/unset values for border-image-source are < 0.1%.

**Comment by fantasai** [comment] 2017-12-20 18:36
Why wouldn't it happen because of 'border-image'? It's the app that makes a decision of when to coalesce the user's instructions into a single shorthand. It can certainly make that call if it wants to.

I would also expect that if the user takes an element with a border image on it, and tells the app to make the border a solid red line instead, that it disables the border image so that you can see that solid red line. This logic is exactly why the `border` shorthand sets `border-image`.

**Comment by lespacedunmatin** [comment] 2017-12-20 22:12
So border would reset border-image and not border-radius ? Note that it leads to misunderstandings in [French documentation of border on MDN](https://developer.mozilla.org/fr/docs/Web/CSS/border) (loosy translation by myself): “border can be used to reset any property link to the border defined before in the cascade. W3C intends to keep that reset mecanism.”

**Comment by bradkemper** [comment] 2017-12-20 22:33
Border-radius is not a border property; it’s just badly named. It’s main reason for being called that is because it’s measured on the border box, and ends up being a smaller radius for the padding box and content box.

**Comment by lespacedunmatin** [comment] 2017-12-20 22:37
Yep, realized that it should have been named box-corner-radius.

**Comment by bradkemper** [comment] 2017-12-20 22:48
Anyway, I’m an author who is not confused by the resetting. Of course, I’m biased, being a co-author, but this resetting happens in other shorthands too, right? It seems pretty simple to me. But I don’t see why you have to write everything out in longhand because of it. That seems like an odd choice. Why not just ignore border-image in the UI and in the CSS you write, when it is not changing anything (changing all border-image-* properties from `initial` to `initial`)?

**Comment by bradkemper** [comment] 2017-12-20 22:51
Co-editor, I meant to say.

**Comment by AmeliaBR** [comment] 2017-12-20 23:07
Here's a use case for the other side of the equation:

In my design system, I have a class `big-warning-button`. It applies a very large red border:

```css
button.big-warning-button {
  color: dakrRed;
  background: lightSalmon;
  border: solid 5px;
}
```

But then, someone down the line changes the theme styles for default buttons to use a `border-image` instead of a regular border:

```css
button {
  border-image: url(/assets/fancy-border.png) 10 10 stretch;
}
```

If the `border` shorthand worked as proposed in this issue:

My big warning buttons are now broken. I check dev tools. The border width and border color are still there.  So is the `border-image` property, but it's assigned with a simple tag selector. Why is it overriding the border I set with a _class_ selector? I thought I understood CSS! This isn't how it's supposed to work! Why must everything be so darn complicated!!!  Stupid `border-image` keeps breaking everything. No wonder we never use it.

**Comment by AmeliaBR** [comment] 2017-12-20 23:24
PS, pulling out a comment I made on IRC earlier:

Has anyone made a list of other shorthands that have similar behavior?

> [`font`](https://drafts.csswg.org/css-fonts-4/#font-prop) is one (with respect to new font-variant properties), but I think it should be possible to allow the full font-variant options to be specified without breaking anything.

Another: The [`mask-border` property and its longhands](https://drafts.fxtf.org/css-masking-1/#the-mask-border) are currently spec'd to be reset by the `mask` property. But last I checked, no one had implemented `mask-border`, so there's no compat issue to changing it.

Although really, I don't think _any_ shorthand is as confusing as the `border` shorthand: even separate from `border-image`, there's the way it can be decomposed into two different sets of middlehands (`border-style`/`-width`/`-color` vs `border-top`/`-right`/`-bottom`/`-left`).  So authoring tools are going to need special logic for handling it, regardless.

**Comment by bradkemper** [comment] 2017-12-21 03:13
I’m actually surprised that `text-decoration` doesn’t reset `text-decoration-skip`. I would expect it to, given its name and the fact that it isn’t in the shorthand.

**Comment by bradkemper** [comment] 2017-12-21 03:15
Same for `text-emphasis` and `text-emphasis-position`.

**Comment by frivoal** [comment] 2017-12-21 03:41
@bradkemper I think this was discussed quite extensively, and the decision to not link them was due to the fact that they are typically independent decisions: you set `text-decoration` / `text-emphasis` on a per element basis, but you're fairly likely to set `text-decoration-skip` or `text-emphasis-position` on a broader basis, possibly for the whole page. Linking the two in the same shorthand would turn normal usage in an ugly specificity fight, and that's no fun.

**Comment by therealglazou** [comment] 2017-12-21 06:27
> So authoring tools are going to need special logic for handling it, regardless.

My goodness, no they are not! You are missing the point here: authoring tools do not reinvent the wheel and rely on the serialization rules ALREADY implemented in the CSS OM of the rendering engine they use. AFAICT from my tests and implementations, this works very well for both specified (in stylesheets or inline styles) and computed style in all engines available today on the market. That's why setting the four borders never outputs 'border' any more, breaking 20+ years of common practice. If editing tools are expected to be able to deal with this, it means:

1. they're working around the spec
2. it's clearly a hack
3. they're re-implementing serialization - and they should not do that

For your test case above, we should not have changed 'border'. We should have added an extra shorthand for both the line border and the image border. The way we changed the spec was a hack. CSS 2.1 said shorthands "allow authors to specify the values of several properties with a single property". We changed that.

**Comment by bradkemper** [comment] 2017-12-21 14:15
@frivoal I thought there must be a reason that I didn’t remember or didn’t pay close attention to at the time. I just meant that it seemed like an exception, rather than the rule. In general, aside from unfortunate naming mistakes like border-radius, I would expect a `foo` shorthand to reset all `foo-*` properties. 

I suppose if `text-decoration-skip` could be an exception, then so could `border-image`, but I think changing it now would likely break too much, as @dbaron indicated. And as @ameliaBR indicates, people intuitively expect border images to be reset by `border`. I think they just don’t expect extra rules written out in their editor (or browser developer tools) when it happens.

**Comment by bradkemper** [comment] 2017-12-21 15:53
@therealglazou It seems to me that the issue is really with the serialization, and practically it boils down to two choices: change how the serialization works (which might break some sites, but probably fewer than if we changed a significant detail of how the shorthand itself works), or change how you deal with the serialization (which you would consider a hack). 

I don’t really see why the serialization has to work the way it does. Why can’t `thin black solid` be returned and just imply all the border image resets? Is that somehow worse? Is that harder to deal with for people that read the serializations?

**Comment by fantasai** [comment] 2020-03-06 22:24
Agenda+ to mark as WONTFIX, since I don't really see any way to fix this.

**Comment by TalbotG** [comment] 2020-03-11 19:40
Suggestion: rename 'border-image' . 
If the [default border image area is the border-box](https://www.w3.org/TR/css-backgrounds-3/#border-image-area), then how about renaming 'border-image' to 'border-box-image' ? 
If the [border image area can even extend beyond the border box](https://www.w3.org/TR/css-backgrounds-3/#propdef-border-image-outset), then how about renaming 'border-image' to 'box-image' or some other better descriptive property name? 
By renaming the property, we would elegantly avoid this 'border' shorthand reset problem. 2 problems with 1 fix.
Right now -  just a hunch - , 'border-image' is not widely  used on the web.

**Comment by tabatkins** [comment] 2020-03-11 20:19
I haven't checked yet, but given the length of time it's been around, I would be *extremely surprised* if it was web-compatible to rename border-image. Without evidence to the contrary I'm prepared to reject that out-of-hand.

**Closed** 2020-03-18 16:45 UTC
Labels: Closed Rejected as Wontfix by CSSWG Resolution, css-backgrounds-3
