### ISSUE TITLE
[css-grid] Applying 'justify-content' content distribution is in the wrong place in the overall grid sizing algo

### ISSUE THREAD

**Issue by MatsPalmgren** [w3c/csswg-drafts#2557] opened 2018-04-12 20:50 UTC
The Grid spec currently says that "the tracks are aligned within the grid container according to the `align-content` and `justify-content` properties." in [step 4](https://drafts.csswg.org/css-grid/#algo-overview), after the sizes of both columns and rows have been determined. This leads to the wrong layout because intrinsic row sizes are then determined using the wrong Containing Block inline-size for spanning items. Here's [a testcase](https://bug1453627.bmoattachments.org/attachment.cgi?id=8967327) demonstrating the wrong layout in Chrome (the row size is too large for the text). The layout in Firefox is IMHO the correct one - it sizes the row based on the height of the text when the CB inline-size is 500px, which is what the `grid-column: span 2` grid area is sized to after `justify-content` is applied.

The correct place to apply `justify-content` in the overall algo is between step 1 and 2, i.e. first you determine the column sizes, then you apply `justify-content`.  This allows you to calculate the correct CB inline-size (and padding/margin percentage basis) for the items. Now you can calculate the correct row sizes, and after that apply `align-content`.

**Comment by mrego** [comment] 2018-04-12 21:35
I knew this would end up in a issue here. I discussed the case with @tabatkins today, and he was pretty sure Chromium was right.
The spec even has a note about this, so it seems intentional:
> Note: This can introduce extra space between tracks, potentially enlarging the grid area
> of any grid items spanning the gaps beyond the space allotted to during track sizing.

Anyway let's see what other people think about this (CC @fantasai & @atanassov).
Or if someone recalls the reason why this is done this way.

BTW, Firefox and Edge behave the same for this case, and different from Chromium and WebKit.
Note that for the same example with an orthgonal item neither of Edge, Chromium or WebKit recompute the size of the column. Firefox just don't take orthogonal into accounts so the result is different.

**Comment by fantasai** [comment] 2018-04-20 23:26
IIRC we considered the effect of alignment on same-axis sizing, e.g. it would add some slack to a spanning element which was spanning only max-content sized tracks. However, we didn't consider the effect of alignment on sizing in the other axis, and it does seem to me that doing so would be an improvement in most cases. (If orthogonal cases don't get quite the same benefits that's probably OK, as long as we don't break them.)

**Comment by mrego** [comment] 2018-04-23 07:45
If we do this as part of the track sizing algorithm, this will conflict with what was discussed at #2409.

For example you have 2 rows of 100px each, and then you've a orthogonal item spanning both rows.
In #2409 we said that the item should consider it has 200px height, for the purpose of computing the proper intrinsic size with baseline.
But, if there's `align-content: space-between` the final height of the item could be 300px or 500px (it'd depend on the grid container's height). We couldn't compute that in advance to know the estimated height to do the intrinsic size computation.

**Comment by fantasai** [comment] 2018-05-01 00:47
@mrego I'm not following. We use 200px height to calculate the intrinsic width of the orthogonal item, sure. And then we start the track sizing algorithm, sizing the columns based on that information. Whether we perform alignment of the tracks after that set of tracks is sized or at the end of the algorithm, the final size of the orthogonal item will still be 300px or 500px. If we apply alignment within the grid algorithm, it seems to me we get a better result regardless, no?

The proposal, if I understand correctly (just so we're all clear) is to change from:

1. Size the columns, making some estimates about row sizes (if needed for orthogonal flows)
2. Size the rows, using the column sizes we just calculated (if needed for orthogonal flows)
3. Size the column, using the row sizes we just calculated (skip if not needed)
4. Size the rows, using the column sizes we just calculated (skip if not needed)
5. Align the tracks

to:

1. Size the columns, making some estimates about row sizes (if needed for orthogonal flows). Align the columns (so colspans in the next step are more accurate).
2. Size the rows, using the column sizes we just calculated (if needed for orthogonal flows). Align the rows (so rowspans in the next step are more accurate).
3. Size the column, using the row sizes we just calculated (skip if not needed). Align the rows (so colspans in the next step are more accurate).
4. Size the rows, using the column sizes we just calculated (skip if not needed). Align the rows.

**Comment by javifernandez** [comment] 2018-05-01 22:41
> Whether we perform alignment of the tracks after that set of tracks is sized or at the end of the algorithm, the final size of the orthogonal item will still be 300px or 500px. If we apply alignment within the grid algorithm, it seems to me we get a better result regardless, no?

The issue is that baseline alignment in the row-axis (justify-self) may depend on the final size of the row, as explained in #2409.

**Comment by fantasai** [comment] 2018-05-04 00:09
@javifernandez I'm not understanding why this is a problem. :(

**Comment by javifernandez** [comment] 2018-05-04 20:32
This issue is about the place to run the Content Alignment logic; with the new baseline alignment integrated in the track sizing algorithm, the place where we finally run the Content Alignment logic will have an impact in the result of the Baseline Alignment, generating different results.

**Comment by tabatkins** [comment] 2018-05-17 17:18
Hmm, indeed. Case in point:

```html
<style>
.grid { 
 display: grid; 
 grid: 100px 100px auto / auto; 
 align-content: space-between; 
 height: 300px;
}
.ortho {
 grid-row: 1 / span 2;
 font: 50px Ahem;
 writing-mode: vertical-rl;
 background: purple;
}
.content {
 grid-row: 3;
}
</style>
<div class=grid>
  <div class=ortho>É É ÉÉ</div>
  <div class=content>foo</div>
</div>
```

Today, the spec says that the orthogonal item can tell how large its containing block is (200px high, as it spans only rows with fixed max track sizing functions).  The *actual* height of the block might not be 200px, as it depends on how much space is left over in the grid after the content-sized track is sized.

If we move the distribution up in the algorithm, then we have to weaken the condition we're using - the amount of gap, and thus the size of the grid area, is content-sized *if any track in the entire grid is content-sized*. Per the spec, this means we have to assume the grid area is infinite, and we'll get the original bad layout from #2409.

(On that note, we should probably make it clearer that gaps are considered in the calculation of the grid-area size, even if we leave distribution at the end.)

**Comment by fantasai** [comment] 2018-05-17 17:28
No, we don't change the rules for estimating the height of the rows/gaps in step 1. It still starts out assuming the fixed heights and no content distribution gaps -- but at the end of step 2, we take that into account when performing the check in step 3.

**Comment by tabatkins** [comment] 2018-05-17 17:30
@fantasai points out that I'm wrong - I'm talking about Step 1 in my previous comment, but row-distribution would happen in a new Step 2.5. So for the purpose of Step 1, the gap is still 0, and the item would still lay out into a fixed size of 400px.

The distribution would then likely change the min-content contribution of the item, when we hit step 3, but that will just make us cycle once, and hopefully with a closer-to-correct min/max-content contribution.

**Comment by javifernandez** [comment] 2018-05-21 13:46
> @javifernandez Given the above, do you agree that it's okay to move content distribution up into new steps 1.5 and 2.5 (and eliminate step 4)?

@tabatkins are you talking about the original 6 steps fantasai described ? 

1. Size the columns, making some estimates about row sizes (if needed for orthogonal flows)
2. Size the rows, using the column sizes we just calculated (if needed for orthogonal flows)
3. Size the column, using the row sizes we just calculated (skip if not needed)
4. Size the rows, using the column sizes we just calculated (skip if not needed)
5. Align the tracks
6. Lay out items into the resulting grid areas

Wouldn't be the step 5 the one that should be removed ? I don't follow why we should remove step 4, neither in the 6 original steps or in the new ones (reduced to 5 steps)

In any case, and with some caution until I had the time to implement a prototype for this change, I think those new steps 1.5 and 2.5 will produce better results and I'm for it. I'd like to know the @MatsPalmgren 's opinion about this, since he was the one creating the issue; besides, I'm curious about how and why he implemented it in the first place, because this is the Firefox's  current behavior, right ?

**Comment by tabatkins** [comment] 2018-05-22 02:35
I was talking about the actual spec, where Step 4 is the "align tracks" step. (Well, it's "size the grid container and align tracks", but obviously we'll keep "size the grid container" around.)

**Comment by javifernandez** [comment] 2018-05-22 10:41
> I was talking about the actual spec, where Step 4 is the "align tracks" step. (Well, it's "size the grid container and align tracks", but obviously we'll keep "size the grid container" around.)

I'd be fine with that change, at least give it a try. I think I'll have some time in the coming days to implement some prototypes, just in case we want to wait to see if there are problems with the proposed changes. In any case, I'd like know  what @MatsPalmgren thinks before committing the changes.

**Comment by MatsPalmgren** [comment] 2018-05-23 00:43
Doing the distribution step immediately after the track sizes are known always leads to better results as far as I can tell.  You need both the _position_ and size of the columns to calculate the correct CB inline-size for column-spanning items, and the CB inline-size is required to determine any content-based block-axis contributions for the items. I don't think the proposed change makes any difference to how row sizes are estimated for orthogonal items, since that happens during (or before) step 1.

(I tend to think that the row estimation is suboptimal/wrong in both Chrome and Firefox currently though and that we can improve the heuristic there, but that seems like a separate issue.)

>Perhaps this is an implementation detail, but we only run step 1 of the algorithm in order to determine the preferred width. Once set, we use this preferred width during the layout, so we can't then change it if Step 3 gives a different result for the columns.

That's basically what Gecko does too.  The proposed change doesn't affect that in any way though, since distribution of space only happens when the grid container has a definite size in that axis (so it doesn't occur during intrinsic sizing).

**Comment by javifernandez** [comment] 2018-05-23 08:58
Ok, I think we have an agreement on the proposed changes, so that  these new steps 1.5 and 2.5 will produce better results. I also agree that it shouldn't interfere with row estimation in case of orthogonal items, which will be addressed in the extra cycle, as tab mentioned. 

> That's basically what Gecko does too. The proposed change doesn't affect that in any way though, since distribution of space only happens when the grid container has a definite size in that axis (so it doesn't occur during intrinsic sizing).

Well, I was talking about a case where an orthogonal item spans several rows in a grid with a definite height. For example:

```
<div style="display: inline-grid; grid-template-rows: 50px 50px; height: 200px;  font: 20px/1 Ahem; justify-content: start; align-content: space-between;">
   <div style="grid-row: span 2; background: cyan; writing-mode: vertical-lr">XXX XX X XX X XXX</div>
</div>
```

While in Firefox the example above is not rendered correctly because it doesn't perform a estimation of the row size, in Chrome it renders correctly, but column tracks are not computed correctly (at least not as good as we intend with the new steps we added now). The reason is that, as you said, row estimation happens during step 1, hence, it doesn't take Content Alignment into account. Once the preferred width is set, we can't change it, even if the actual rows's size is bigger during layout. 

Anyway, I don't think this is a blocker to land the changes in the spec to add the new steps in the sizing algorithm.

**Comment by MatsPalmgren** [comment] 2018-05-23 14:45
Right, that's what I meant with the current row estimation being suboptimal since it leads to surprising results for simple cases.  I filed issue #2697 to improve it.

**Comment by fantasai** [comment] 2018-06-12 02:59
OK, I edited in a first pass at incorporating this change in https://github.com/w3c/csswg-drafts/commit/277817b114e3bee1abb9d720bb559dc557928ff5 and https://github.com/w3c/csswg-drafts/commit/c9e9f7f440a8456d241da9639e36115683a5b102

@MatsPalmgren @javifernandez @mrego  Would you mind looking this over to make sure it adequately captures what we've discussed?

**Comment by javifernandez** [comment] 2018-06-14 21:40
> @MatsPalmgren @javifernandez @mrego Would you mind looking this over to make sure it adequately captures what we've discussed?

The changes look good to me.

**Comment by mrego** [comment] 2018-08-03 05:56
One question about the final text in the spec, we still need the last step (now number 5):
> 5. Finally, the grid container is sized using the resulting size of the grid as its content size, and the tracks are aligned within the grid container according to the align-content and justify-content properties.

If content alignment was already done as part of the previous steps, why we still need it?

**Comment by fantasai** [comment] 2018-08-24 23:33
@mrego The previous steps calculate the effective column/row gaps taking content alignment into account, but they don't actually apply alignment e.g. centering to the tracks.

(Of course if in your implementation you've worked this into your algorithm earlier, you don't need to do it at this point, but it's generally true that CSS implementations don't need to follow the steps in the spec so long as they return the expected output.)

**Closed** 2018-08-24 23:35 UTC
Labels: Closed Accepted by CSSWG Resolution, Commenter Response Pending, css-grid-1
