### ISSUE TITLE
[css-color-adjust-1] User origin !important vs. forced colors mode

### ISSUE THREAD

**Issue by andruud** [w3c/csswg-drafts#4020] opened 2019-06-07 18:54 UTC
So let's say I have a user stylesheet:
```
color: red !important;
```
In forced colors mode, what applies? The spec says `revert !important` is added to the cascade at the user level (when?), which may or may not win over my `red !important`.

I don't think it's enough to state that the value is added at the user level. Clearly we need `revert !very important`.

cc @fantasai, @lilles

**Comment by lilles** [comment] 2019-06-11 14:47
I don't know what the intention was here. I would guess applied after other user stylesheets.

**Comment by AmeliaBR** [comment] 2019-06-11 15:11
The intention is to revert author styles. I don't think we're why to revert user !Important styles. So maybe it should say "user level important styles, before why used style sheets".

**Comment by andruud** [comment] 2019-07-29 08:25
If the intent is to revert author styles, then we must `revert` at the author origin, in which case we get the same problem for an author-level declaration `color: red !important`.

**Comment by fantasai** [comment] 2020-03-06 03:51
Yeah, you're right, this isn't specified quite correctly. It reverts everything in the author origin as intended, but also reverts everything in the user origin as well. For it to work as intended (preserving user styles), we'd need to have an origin between user and author.

We kindof already have this, in the form of the "non-CSS presentation hints" layer. If we turn that into a real origin and give it a corresponding !important level, then we can inject these rules into that origin and they should work as intended.

Agenda+ to discuss.

**Comment by andruud** [comment] 2020-03-09 10:17
@fantasai That makes sense. But let's definitely not make the new origin something that can be `revert`-ed _to_ (only from). `revert` is already complicated and expensive enough, so `revert` in the author origin should still revert to the user origin IMO.

**Comment by emilio** [comment] 2020-03-09 15:16
FWIW the way Firefox implements this is just treating author-level declarations for those properties as `revert`: https://searchfox.org/mozilla-central/rev/557a0e222dd104c5d805ba344c45d6abc27d3db0/servo/components/style/properties/cascade.rs#406

**Comment by emilio** [comment] 2020-03-09 15:18
I think the spec mostly wants to say that any declaration for those properties in the author origin is treated as `revert`, or something of that sort.

**Comment by fantasai** [comment] 2020-04-02 22:09
Committed changes. @emilio Would you mind reviewing to make sure it matches your understanding? Also what about animations, should I be including those? (They're in their own origin.)

**Closed** 2020-05-19 22:31 UTC
Labels: Closed Accepted by CSSWG Resolution, css-cascade-4, css-cascade-5, css-color-adjust-1
